ARF-SS13/coyote-bayou

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

It's green. It's a house. It has glass. Oh and flies. Beware the flies.

Greenhouse

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Ça c'est bon, mon cher.  Welcome to the swamps, mother trucker.
Massive overhaul of the main maps lower level with multiple grass, trees, vines, water, mobs placed down to properly swing the vibe to the kind of place that holds the planet together.  We still need better dirt tho.
Dip your toes in, baby.

Massive Bayou-ification.

---

config/config.txt

:cl:
config: updated the config
/:cl:

Update the config

---

code/__HELPERS/shell.dm

:cl:
fix: fix issuing shell commands
/:cl:

Fix Shelleo

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Pushing what I have cause I  can't be assed.

Mapping stuff

---

code/modules/power/lighting.dm

stops lights from flickering

---

code/game/vault_door.dm

I forgot to do this originally, its in a branch but not PR'd, oops!

prevents 1 in 4th chance for a severity 2 explosion to destroy the vault door

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/controllers/subsystem/monster_wave.dm

-Adds real Defibs, clothing machines, more prosthetic limbs and proper access restricted front doors.

Followers Clinic Update

---

code/_onclick/hud/screen_objects.dm
code/modules/mob/dead/new_player/new_player.dm
code/modules/research/designs/autolathe_desings/autolathe_designs_tcomms_and_misc.dm

Removes craftable headsets + Fixes Lobby screen..?

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm
code/modules/jobs/job_types/wasteland.dm

-Adds Redwater Outlaw jobs
-Small touching ups to Redwater town

Redwater Outlaws & Some touchups to Redwater

---

code/__DEFINES/dcs/signals/signals_mob_main.dm
code/datums/datum.dm
code/modules/mob/dead/dead.dm
code/modules/mob/dead/new_player/login.dm
code/modules/mob/dead/observer/login.dm
code/modules/mob/dead/observer/observer.dm
code/modules/mob/living/carbon/human/login.dm
code/modules/mob/living/login.dm
code/modules/mob/login.dm
fortune13.dme

oops.
I think the Login() function for new clients didn't fully commit to allowing you to exist on the server. The funny thing is, you can't recognise this on test servers because they put you in and if you close the game, it boots you out.
I only recognised this issue with dreamdaemon. Damn.

you can login again :o

---

_maps/map_files/Pahrump-Sunset/RockSprings.dmm
code/modules/jobs/job_types/wasteland.dm
code/modules/jobs/jobs.dm

It's a rough start for them, but Redwater should be totally playable now.  All the outlaws are condensed into their faction and it includes party time necklaces for some of the folks in town that may, or may not, pop their heads off.

Redwater Ready To Rock

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

-dorty dirt darts n a few more moob spooners

mmm dirt cromchy gud

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

Dungeon and rocksprings, small little tweeks.

Small map changes

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Reworks the hospital to be a little gentler to the FoA right at roundstart.
The area mostly just needed some tweaking/work, as before it was lacking some very basic functionality for the Followers of the Apocalypse
:cl:
balance: FoA hospital change
/:cl:

Tweaks FoA hospital to be a little less painful at roundstart.

---

code/modules/jobs/job_types/wasteland.dm
code/modules/jobs/jobs.dm

yay bad people good make shoot shoot pow pow

Added outlaws to Redwater late join

---

code/modules/jobs/job_types/tribals.dm
code/modules/jobs/job_types/wasteland.dm
code/modules/jobs/jobs.dm

Adds the tribal jobs back in without map conflicts, leaving the mapping to Jess.

I'm dumb as a box of hair!

---

code/modules/jobs/job_types/tribals.dm
code/modules/jobs/job_types/wasteland.dm
fortune13.dme

LAUNCH EVERY ZIG
I'll begin overhauling the 'foreign tribals' next.  Jess needs to add map spawn points for these PROPER tribals to their camp.

TRIBAL FACTION TURN ON

---

code/modules/jobs/job_types/tribals.dm
code/modules/jobs/job_types/wasteland.dm
code/modules/jobs/jobs.dm

Pulls the tribals apart, allowing for the Sulphur Bottom Tribe to exist along side Tribals who have traveled to the area from far off lands.

Sulphur Bottom Tribe & Far-Lands Tribals Separation

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/modules/jobs/job_types/tribals.dm
code/modules/jobs/jobs.dm

Slowly unfucking Pahrumps areas
Fixes tribal objectives, since the chief is now on hand.
Gets Oasis jobs working again entirely!  Mind you, they're still called Oasis.  I need to figure out how to call them Nash.  But for now, they work!

Map, Tribal Objectives, and Nash (Oasis) turned on.

---

code/modules/jobs/job_types/oasis.dm
code/modules/jobs/job_types/wasteland.dm

Make your handheld radio, dorks.

Headset removal - Peanut Gallery Obliteration & Good Karma BOS Exile

---

code/modules/projectiles/projectile/beams.dm

buffed damage on most hitscan lasers [TEST]

---

code/modules/jobs/job_types/tribals.dm

tribal hunters turned on

---

code/datums/components/crafting/recipes/recipes_primal.dm

Making more things for tribals to be craftable

---

code/datums/looping_sounds/weather.dm
modular_coyote/code/modules/say/soundbubbles.dm

Quieter sandstorms & burbles

---

code/__DEFINES/sound.dm

Remove sound from list

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

Nash is now ready, fully ready, to be played.
Technically so is Redwater, the Tribal Camp, and the Followers Clinic.
We are very nearly at the point of being ready to begin working on rules.  Thank you everyone for all the help you've given so far.  <3

Nash 1.0 - Ready to G'nash

---

_maps/map_files/Pahrump-Old/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Dungeons.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm

-Saved the GOOD Enclave Bunker from the old files
-Overhauling the lower Z for Nash.  I literally can't tell you what all was done.  But it is considerably more... uh... Happening.
-Fire Ant Lower Level
-Removed NCR Ghouls description and remade them as US Army Ghouls
-Gave Deathclaws reach = 2 to counter spear meta against them.  Big arms, big reach, big scrotty tickles.

Mapping Stuff & Scattered Crap

---

code/game/objects/items/stacks/cash.dm

-Merged to unspacemanify spacecash into Dollars.

Credits to pre-war dollars

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

The map has a real lack of these two items, this should add in a good amount of them.

More Cell Chargers and Rechargers

---

code/modules/mob/living/simple_animal/hostile/giant_spider.dm

Spiders to rad spiders

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/modules/fallout/turf/ground.dm

Running water now slows down and splashes like normal water.
Updated the running water in the tribal camp to use it.

Running water update

---

code/datums/traits/good.dm
code/datums/traits/negative.dm
code/datums/traits/neutral.dm

Quirk Unlockening due to books being much harder to acquire

Unlocks Quirks

---

code/controllers/subsystem/monster_wave.dm
code/modules/mob/living/simple_animal/friendly/farm_animals.dm

Changed firings up to 30, Jess will be fixing areas so they don't spawn in towns shortly.
Removed Deathclaw from the nest spawner, as they will be being made much more dangerous in the near future.

Monster wave refactor

---

code/modules/mob/living/simple_animal/friendly/farm_animals.dm

Health on Brahmin Upped to 200, sot hey can be sneezed at and not die.

Big Brahmin Beef Bours

---

code/datums/components/crafting/guncrafting.dm
code/game/objects/items/storage/_storage.dm
code/modules/crafting/items.dm

Salvage has its salvage-to-loot functionality on the salvage itself, not the workbench of all places.
Salvage bags shouldnt be able to be spammed into making thousands of lootthings
If a workbench tries to pick something that isnt salvage to salvage, it just skips it.
You need to actually be in range of the workbench now.
Dekludge~
:cl:
fix: Salvage should only be salvageable once, as intended.
refactor: Salvage looting is now a function of the salvage itself
refactor: Now 100000% less repeated salvage loot code!
/:cl:

Salvage (bag) fixes and refucktors

---

code/game/objects/items/granters.dm

Skillgranter text now has the right grammar.
You ditch the useless book, and everyone around you ditched the book too, as far as the chat output is concerned. Not anymore!
:cl:
fix: Fixed skill granter grammar.
/:cl:

Fixes skillgranter grammar

---

code/game/objects/items/tanks/watertank.dm

:cl:
tweak: Backpack water tanks dont slow you down anymore!
/:cl:

Backpack water tanks no longer have slowdown

---

code/modules/language/wayfarer.dm

Makes the language icon for tribals be something that isnt popcorn.
No longer makes me hungry
:cl:
fix: Tribal language is no longer popcorn.
/:cl:

Depopcorns tribal language

---

code/modules/projectiles/guns/ballistic/automatic.dm

whitelegs tommygun accepts drum mags
:cl:
add: Whitelegs tommygun accepts drum mags.
/:cl:

whitelegs tommygun accepts drum mags

---

code/modules/research/designs/ammolathe_designs.dm

renames grease gun mag in the ammobench to 9mm, cus it listed it as .45, which it wasnt.
:cl:
fix: Ammolathe now lists greasegun mags as 9mm.
/:cl:

renames grease gun mag in the ammobench to 9mm

---

code/modules/mob/living/simple_animal/friendly/farm_animals.dm

Adds saddles and brands.
Adds more description to the stuff added to the beast.
Makes brahmin equipment cheaper to make.
Apparently you can ride them now? sick

Changes a lot of stuff with brahmin

---

code/datums/dog_fashion.dm
code/modules/clothing/masks/gasmask.dm

Re-adds clown and mime masks. Even if they arent used for anything, it aint SS13 without clown stuff, I will die on this hill, fight me.
it aint ss13 without clown gear.

re-adds clown and mime masks

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

-Added some more flora onto the main two maps
-Added our mappers template to Redwaters Z
-General Touching Ups

Various map changes

---

code/modules/mob/dead/new_player/sprite_accessories/body_markings.dm
code/modules/mob/living/carbon/human/species_types/ghoul.dm

Ghouls can now choose ears, tails, wings, etc. Just turn on mismatched markings and enjoy.

Now you can make even more cursed ghouls

---

_maps/map_files/Pahrump-Old/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Temp Map Storage/Dungeons -outdated.dmm
_maps/map_files/Temp Map Storage/Pahrump-Sunset - Outdated.dmm
code/_globalvars/lists/maintenance_loot.dm
code/datums/components/crafting/recipes/recipes_medicine.dm
code/datums/wounds/burns.dm
code/game/objects/effects/spawners/f13lootdrop.dm
code/game/objects/items/storage/f13storage.dm
code/game/objects/items/storage/firstaid.dm
code/game/objects/items/storage/survivalkit.dm
code/game/objects/structures/ghost_role_spawners.dm
code/modules/WVM/wmv_buyer.dm
code/modules/fallout/reagents/medicines.dm
code/modules/food_and_drinks/recipes/tablecraft/recipes_wastefood.dm
code/modules/jobs/job_types/legion.dm
code/modules/jobs/job_types/tribals.dm
code/modules/jobs/job_types/wasteland.dm
code/modules/movespeed/modifiers/mobs.dm
code/modules/reagents/chemistry/machinery/chem_master.dm
code/modules/reagents/chemistry/reagents/medicine_reagents.dm
code/modules/reagents/chemistry/recipes/medicine.dm
code/modules/reagents/reagent_containers/hypospray.dm
code/modules/reagents/reagent_containers/patch.dm
modular_sunset/code/modules/fluff/happyshark_recipe.dm
modular_sunset/code/modules/food_and_drinks/happy_shark/happy_shark.dm

Just about everything is done by the belovely Fuzzy Fuzlet!
First round of the Bottom Med chem overhaul!
Featured changes:
- Stimpaks heal 20 HP instantly, plus 30 HP over 20 seconds
- Superstims heal 50 HP instantly, plus 50 HP over 20 seconds, as well as a mild bleed heal
- Healing powder heals 50 HP over 50 seconds, and is a pill now
- Healing poultice heals 100 HP over 50 seconds, as well as a mild bleed heal
- Bitter drank heals 50 HP ovr 25 seconds, and it a pill now.
- Healing powder takes 1 broc and xander, and can be crafted by anyone anywhere
- Stims, poultice, and bitters require a worktable, most of which needing their recipes granted
- Stimfluid heals 1 brute and burn per unit when injected, and its OD will make you pukestun yourself
- Superstimfluid heals 1 brute and burn …

Bottom Med Changepack Alpha

---

_maps/RandomZLevels/VR/yuma_VR.dmm
code/_globalvars/lists/maintenance_loot.dm
code/datums/components/crafting/recipes/recipes_tailoring.dm
code/game/objects/effects/spawners/f13lootdrop.dm
code/modules/clothing/suits/arfsuits.dm
code/modules/clothing/suits/f13factionarmor.dm
code/modules/jobs/job_types/oasis.dm
code/modules/mob/living/simple_animal/hostile/f13/raider.dm

Changes raider iconoclast armor to be medium armor with increased environmental protection, at the cost of a bit more slowdown.
The suit is supposed to be made from a rad suit, so, yeah.
:cl:
balance: Iconoclast armor is now medium environmental armor.
/:cl:

Tweaks raider iconoclast armor

---

code/_globalvars/lists/flavor_misc.dm
modular_coyote/code/mam_ears_coyote.dm
modular_coyote/code/mam_tails_coyote.dm

Now you can properly select them as both human and anthromoph cause a

Acessories be stupid

---

code/__HELPERS/custom_holoforms.dm
code/game/objects/structures/window.dm
code/modules/jobs/loadout_ingame.dm
tgui/packages/tgui/interfaces/LoadoutSelect.js

ye, it fixes loadout thing
idk what to call this, also fixes window movement.
Only merge when this checkbox is ticked <3

Does the thing:tm:

---

code/modules/mob/living/emote.dm

Special thanks to Fuzzy Fuzlet for everything!
Makes a \*special emote that lets you roll a (stat*10) stat check. For instance,
with 3 strength, doing \*special strength does...
[Strength, 30%] Dan Kelly tests their strength...
then 2 seconds later...
[Success] Dan Kelly was strong!
or
[Success] Dan Kellywas too weak...
There are also multiple keywords for each SPECIAL stat, like agility, agi, a, or dex all correspond to agility.
Everything's easy to change.
Its a cool thing~
:cl:
add: Added *special, to roll against your stats!
/:cl:

SPECIAL stat emote

---

code/modules/mob/living/emote.dm

I forgot to upload a commit, it should actually work now.!

Fixes SPECIAL emote

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

pew pew eat wall too much halth

synth man bad

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

shumtors only u can storp the gecko horde

Fixed nash shutters

---

.gitignore
fortune13.dme
modular_coyote/code/modules/mapping/occupation_removal.dm

Removes jobs from occupation screen

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

various map touching ups for the day

fiddly bits map touchings

---

code/__DEFINES/combat.dm
code/modules/projectiles/guns/energy.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/energy/plasmaf13.dm

Energy weapons didnt have a real firing delay. Now, they do.
Also makes plasma weapons not do 30 times their base damage.
Energy weapons could be turbospammed. Not anymore!

Adds firing delay and other stats to energy weapons

---

code/_onclick/hud/alert.dm
code/game/objects/items/granters.dm
code/game/objects/items/storage/firstaid.dm
code/modules/fallout/reagents/medicines.dm
code/modules/jobs/job_types/wasteland.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/movespeed/modifiers/mobs.dm
code/modules/reagents/chemistry/reagents/impure_reagents.dm
code/modules/reagents/chemistry/recipes/medicine.dm

Fixes meds not metabolizing
lessens superstim, poultice, and fat slowdowns
reflavored fat to just being stuffed
added poultice recipes to tribals
added stim recipes to Big Book of Science
updated pill blacklist for bitters and powder
removes impure stimjuice
removed chem recipes for stimjuiice and superstimjuice
made by bottoms, for bottoms

Bottom Med Fix Pack 1

---

code/modules/mob/living/emote.dm

makes *special usable. Also adds in some help text to show what keywords work.
Features are usually better if they work more than not at all.

Fixes *special being unusable

---

code/__DEFINES/combat.dm

Increased pistol and rifle bullet base damages, cus it was way too low.
- Light pistol 10 -> 20 (9mm, 22,, 3 shot ghouls)
- Medium pistol 15 -> 25 (10mm, .45, etc, also 3 shot ghouls)
- heavy pistol 20 -> 40 (.357 and up, 2 shot ghouls)
- medium rifle 40 -> 45 (.308, 3 shot reavers)
- heavy rifle 50 -> 60 (.50 and up, 2 shot reavers)
- shotgun pellet 10 -> 11
- shotgun slug 40 -> 50
- match ammo damage mult 1.5 -> 1.25
- handload ammo damage mult 0.5 -> 0.75
- global recoil mult 1 -> 0.75
- global spread mult 2 -> 1
- POOR and AWFUL accuracy 50% worse
Guns should be able to kill things.

Boosts bullet damages, reduces recoil and spread a bit

---

code/game/objects/effects/mines.dm
code/modules/fallout/obj/explosives.dm

ye. Some reason they were being passed the turf they were on, not the actual mob being passed. So I improv'd and used usr, as that contains the mob object.

mines have been fixed!

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

-added rad scorp maze on northern nash z
-general map touch ups and fixings

Map touchings

---

code/datums/weather/weather_types/acid_rain.dm
code/datums/weather/weather_types/rain.dm

ye. also makes it so when rain starts, add 80 water to any hydroponics tray under the weather effect. (mainly because it doesnt loop effected turfs, which is fair!

stops cleaning of things from rain/acid rain

---

.github/workflows/ci_suite.yml
.github/workflows/compile_changelogs.yml
.github/workflows/conflicts.yml
.github/workflows/show_screenshot_test_results.yml

:cl:
add: Auto changelog is added!
/:cl:

New workflows testing the autochangelog + map edits

---

.github/workflows/pr_emoji.yml

Strips the CL so changelogs can apply, oops!
:cl:
fix: Workflows!
/:cl:

adds in this workflow

---

code/modules/mob/living/living.dm

Adds update_movespeed() to fully_heal()

maybe fixes slowdowns sticking?

---

config/config.txt

21 by 15 bby and 35 fps bbbbbyyyy
21 by 15 bby and 35 fps bbbbbyyyy
:cl:
config: changed viewport to widescreen
config: changed base fps to 35
/:cl:

switchin to widescreen & 35fps

---

code/modules/mob/living/emote.dm

Adds in support for multiple different phrases for each special outcome, as well as some new phrases as well!
:cl:
add: More *special phrases!
/:cl:

*special additions

---

.github/workflows/docker_publish.yml

fghgfdhjfghjgfh

---

Dockerfile

updates docker to modern TG

---

code/game/objects/items/stacks/cash.dm
code/game/objects/items/stacks/sheets/glass.dm
code/game/objects/items/stacks/stack.dm
code/game/objects/items/stacks/wrap.dm
code/modules/awaymissions/super_secret_room.dm
code/modules/fallout/obj/stack/f13Cash.dm
code/modules/mob/status_procs.dm
tools/ci/show_screenshot_test_results.js

Fixes stackable pickups not merging when dragged, blurry eyes not effecting mobs 'n yea!
:cl:
fix: Fixed tiles not being autoscooped when dragged
fix: Blur layer not effecting mobs.
fix: my depression
/:cl:

Tilepickup fix

---

code/modules/smithing/anvil.dm
tools/ci/run_server.sh

Hrm.. How to word it. ah well.
Oh! you can alt click the anvil to reset it to default completely if something goes wrong.
:cl:
twaek: Anvil code should now more understandable with all the scuffed comments I added.
/:cl:

Refactorises anvil code

---

config/config.txt

Changes view to 17*15

---

code/controllers/subsystem/nightcycle.dm

Made the day night cycle color settings more natural and visually appealing.  Also dialed them in fairly well so they're far FAR less jarring.
:cl:
tweak: Tweaked Day/Night lighting and colors to make the movement of the sun move natural and appealing.*
*to me ofc
/:cl:

Less jarring light changes

---

code/datums/traits/negative.dm

This quirk is the dumbest thing I've ever seen.  Why am I making eye contact with CHAIRS?
:cl: Fenny
tweak: tweaked social anxiety to remove the spammy 'retreat into yourself' text
tweak: tweaked social anxiety to remove the random objects eye contact 'feature.'
tweak: slapped myself in the balls help aaaa-
/:cl:

Adjusting Social Anxiety

---

code/modules/jobs/job_types/oasis.dm

Jump in the cac
I hate goats.
:cl:
tweak: ayyy ayyy I got a gun no goats, goats gotta die
/:cl:

Bighorn references

---

code/game/objects/items/storage/survivalkit.dm

Ah yes, oxygen tanks. Very tribal. Very fallout. Replaces it with another torch.
Also renames them from "legion" to "tribal"

Fixes the stupid fucking bag

---

code/modules/fallout/reagents/medicines.dm

I made it only work if you're dead, accidentally. Now, it works only if you're *not* dead. Whoops!

Fixes stimfluid

---

_maps/map_files/Pahrump-Sunset/RedRiver.dmm

Basically testing the map checker

Red River touchups

---

code/datums/traits/negative.dm

Locking Phobia

---

_maps/map_files/Pahrump-Sunset/RedRiver.dmm
code/datums/traits/negative.dm

Forestsssss

---

code/modules/unit_tests/_unit_tests.dm

disables failing linter for now

---

code/datums/components/crafting/recipes/recipes_primal.dm
code/datums/components/crafting/recipes/recipes_tribal.dm
code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm

Makes a wooden bat craftable at a workbench with 10 wood and 1 leather
Also makes quivers craftable, as well as a bone satchel for collecting bones

Baaaaaaaaaaaaaaaat

---

code/modules/jobs/job_types/tribals.dm

hehe funny warpaint

---

dependencies.sh

ye! Woo!!! Dependencies, our favourite.

aaaaaa dependency update

---

code/game/objects/items/melee/f13onehanded.dm
code/modules/mob/living/simple_animal/animal_defense.dm
code/modules/projectiles/boxes_magazines/internal/_cylinder.dm

By Lyro, downstreamed manually.

Revolver dump fix

---

code/modules/projectiles/projectile/beams.dm

Buffs plasma bolts quite a bit. The pistol was too weak, worse than a wattz.

Buffs plasma bolts

---

code/game/objects/effects/spawners/gibspawner.dm

Some more stuff I forgot ot merge

---

_maps/map_files/Pahrump-Sunset/RedRiver.dmm

Adds hut, some enviromental hazards on concrete bridge, removes NCR dollar in house and removes walls next to sandbag (last 2 request from Fenny)
:cl:
add: i love huts!
add: i hate bridges!
/:cl:

Red River: adds hut, stuff on bridge, 2 fixes south of bridge

---

code/game/objects/items/defib.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/surgery/organs/organ_internal.dm

Organs no longer rot. Dead people's organs will stay just as messed up as they were when they died.

Dead organs no longer rot

---

code/modules/clothing/suits/_suits.dm
modular_sunset/code/modules/clothing/suits/f13suits.dm

Suits that dont have digileg sprites no longer print a bright green SUIT on their mob. We get it, most suits dont have digisprites, dont gotta rub it in!

No more SUIT

---

_maps/map_files/Pahrump-Sunset/RedRiver.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm
code/modules/fallout/turf/ground.dm

Bee murder.

---

config/config.txt

Slightly wider screen

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Ranger Station to Rancher House

---

code/_globalvars/lists/keybindings.dm
code/modules/mob/living/emote.dm

So fun fact, there's code to have emotes be part of the keybind menu, but someone disabled it. Works fine, so I reenabled it.
Also added some keybinds for *special emotes. So you can just bind a key to rolling for strength if you want!

Enables emote keybinds

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Fixed Nash doors to bighorn

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RedRiver.dmm

vendor go bye-bye

---

code/modules/fallout/turf/walls.dm

now everyone gets out of the swamp

shrek reference

---

code/game/objects/items/stacks/medical.dm

Sutures no longer try and fail to report a limb, so no more 'you suture the wounds on your.'

Fixes sutures and such's text

---

code/__DEFINES/span.dm
code/datums/emotes.dm
code/modules/mob/say_vr.dm
interface/stylesheet.dm
tgui/packages/tgui-panel/chat/constants.js
tgui/packages/tgui-panel/styles/goon/chat-dark.scss
tgui/packages/tgui-panel/styles/goon/chat-light.scss

Fixes subtle only being viewable in subtle range while as a ghost.
Adds chat filters for subtles.
Admins can see subtlers while ghosted and spy on steamy ultrakink ERP.
Refactors subtle code a bit, sorta
Subtles are both visible and audible, dont have to pick one anymore!
Admins must see all, even if they dont want to.
:cl:
fix: Ghosts can now see subtles.
refactor: Subtle is a bit tighter.
admin: Admins can see subtlers while ghosted.
/:cl:

Subtle(r) changes

---

code/modules/mob/living/simple_animal/hostile/bosses/boss.dm
code/modules/mob/living/simple_animal/hostile/cat_butcher.dm
code/modules/mob/living/simple_animal/hostile/f13/centaur.dm
code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
code/modules/mob/living/simple_animal/hostile/f13/insects.dm
code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
code/modules/mob/living/simple_animal/hostile/f13/tunnelers.dm
code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
code/modules/mob/living/simple_animal/hostile/faithless.dm
code/modules/mob/living/simple_animal/hostile/gorilla/gorilla.dm
code/modules/mob/living/simple_animal/hostile/jungle/leaper.dm
code/modules/mob/living/simple_animal/hostile/jungle/mook.dm
code/modules/mob/living/simple_animal/hostile/jungle/seedling.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/basilisk.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/elite.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/gutlunch.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/hivelord.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/ice_demon.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/ice_whelp.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/polarbear.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/wolf.dm
code/modules/mob/living/simple_animal/hostile/nanotrasen.dm
code/modules/mob/living/simple_animal/hostile/retaliate/spaceman.dm
code/modules/mob/living/simple_animal/hostile/skeleton.dm
code/modules/mob/living/simple_animal/hostile/stickman.dm
code/modules/mob/living/simple_animal/hostile/syndicate.dm
code/modules/mob/living/simple_animal/hostile/zombie.dm

Took it to the extreme levels though, perhaps.
This makes mobs to not attack unconscious/crit people.
:cl: Anonymous
del: Mobs no longer attack characters that are unconscious.
/:cl:

Mobs no longer attack unconscious people

---

code/datums/components/crafting/recipes/recipes_tailoring.dm

Adds ability to craft arm patches beside the chest ones. Was missed in #293.
:cl: Anonymous
fix: Besides chest patch, you can now craft arm patch as well.
/:cl:

Good ser, you forgot the arm patch crafting

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

workbench smelly

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

imagine typing those words smh

too many nightstalkers

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm

Vault no longer a big book store

---

code/datums/emotes.dm
code/modules/mob/say_vr.dm

Subtles are supposed to show up for ghosts, but they dont. This hopefully fixes that.

Maybe fixes subtles not appearing for ghosts

---

code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm

Changes gutsy HP to be a little less fuck you

Gutsy update || wastebots.dm

---

code/modules/jobs/job_types/oasis.dm

Because a detective spawning with 1k+ caps was just silly

Detective Cash Fix(?)

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RedRiver.dmm

makes vault life a little easier

Vault door access change

---

code/game/objects/items/stacks/medical.dm

Bandages work again! Also rebalances bandages to take a little bit longer to apply, but heal brute and stop bleeding a bit better. Same thing with sutures.

Fixes bandages, rebalances healing items

---

code/game/objects/items/granters.dm
code/modules/hydroponics/grown/misc.dm
code/modules/hydroponics/grown/xander.dm

Xander root now heals burn, and aloe heals toxin. They also have their respective juices in them.
:cl:
tweak: Xander heals burn now.
/:cl:

Xander and aloe changes

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/RedRiver.dmm

silly tf2 medic gun

---

modular_citadel/code/modules/client/loadout/mask.dm
modular_citadel/code/modules/client/loadout/uniform.dm

Adds momento bandana and gear harness into the loadout menu and rebalances the bandanas to one if they dont have pull down.
:cl:
add: momento and gear harness
tweak: bandana points
/:cl:

Momento + Gear Harness + Bandana 

---

code/modules/projectiles/guns/ballistic/rifle.dm

Brush gun description updated
:cl:
tweak: brush gun description
/:cl:

brush gun description

---

code/modules/clothing/glasses/f13.dm
code/modules/hydroponics/grown/apple.dm
code/modules/instruments/instruments/item.dm

Fixes descriptions for a few items
:cl:
fix: Fixed Sandstorm Goggles to not reference Caesar's Legion.
fix: Fixed the Golden Violin to not reference TGery.
fix: Fixed Golden Apples to not reference being in spess.
/:cl:

Description Fixes

---

config/config.txt

Enables border control

---

_maps/map_files/Pahrump-Sunset/RockSprings.dmm

you don't go in redwater sillybutt
:cl:
remove: removed a high level energy spawn from redwater
/:cl:

Silly high tier energy gun

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm

So as to head off possible crashes, probably needs to be refactored or re-combobulated or something idk
:cl:
del: Temporary removal of Circuit Imprinter from Vault, hopefully it can get fixed soon
/:cl:

Circuit Printer Removed

---

code/modules/mob/living/simple_animal/friendly/animalfriendly.dm

Serdy the shepherd!
:cl:
add: Added Serdy!
/:cl:

Adds a good boy

---

tools/tgs4_scripts/DreamDaemonLaunch.sh

:cl:
server: Adds TGS renice script to increase server priority on Linux system
/:cl:

Add renice script

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Smartfridge & Vendor
Smartfridge & Vendor
:cl:
add: Added smart fridge and vendor to the Followers Clinic.
/:cl:

Followers Machinery

---

_maps/map_files/Pahrump-Sunset/RedRiver.dmm

less of an insanely long walk, more to do/esplore. has a workbench for people who would care to go that far for one or who are desperate if the rest have been taken.
:cl:
add: boo-womp
/:cl:

adds a house and garage to the red river road

---

code/datums/components/mood.dm
code/datums/mood_events/needs_events.dm

Rewords the fat moodlet.
Voracious people are happy to be able to eat so well out in the wastes.
:cl:
tweak: Voracious people are happy to be able to eat so well out in the wastes.
/:cl:

Voracious folk dont mind being stuffed

---

code/__DEFINES/radio.dm
code/_onclick/hud/screen_objects.dm
code/datums/components/crafting/recipes/recipes_misc.dm
code/datums/components/crafting/recipes/recipes_tailoring.dm
code/game/objects/items/devices/radio/encryptionkey.dm
code/game/objects/items/devices/radio/headset.dm
code/game/objects/items/storage/fancy.dm
code/modules/fallout/misc/gangs.dm
code/modules/fallout/misc/gangtool.dm
code/modules/fallout/obj/structures/obstacle.dm
code/modules/fallout/turf/walls.dm
code/modules/jobs/job_types/tribals.dm
code/modules/jobs/job_types/wasteland.dm
code/modules/reagents/chemistry/recipes/medicine.dm
modular_citadel/code/modules/reagents/chemistry/reagents/eigentstasium.dm

Guh.
- Renames the Medical channel to Followers
- Renames the Town radio to Nash (currently unused)
- Removes Town radio access from the Followers headsets
- Clicking a hand that isn't empty with the other hand clicks the item being held by that hand instead of swapping hands (rejoice, bow users)
- Puts all the Miscellaneous recipes in the same category
- Moves flower crowns to the Miscellaneous Clothing category
- Adds Rolling Paper and Rolling Paper (Bulk) recipes to Miscellaneous, requiring 1 natural paper / 10 natural paper + 1 cardboard sheet
- Inviting tribals to your tribe probably works now?
- Reworks the gangtool code a little
- Possibly fixes the playtime issue with tribals?
- Fixes the suture chem reaction making 15 sutures instead of just 1
- Comments out the eigenstatium …

Fixes, QoL & Features Galore

---

_maps/map_files/Pahrump-Sunset/RockSprings.dmm
code/game/objects/items/melee/f13powerfist.dm
code/modules/jobs/job_types/wasteland.dm
code/modules/jobs/jobs.dm

adds overboss job. it should spawn. but it doesn't. idk why. lol
:cl:
add: overbaws
/:cl:

[WIP] Overboss

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm

Removing Followers Over Gear.
:cl:
Neuter: Cutting the balls off the gay dog medi-squad.
/:cl:

Silly followers, no you can't have all that crap. 

---

code/modules/jobs/job_types/wasteland.dm

fix fi xci fix if xi
:cl:
fix: overbos
/:cl:

makes overboss spawn in proper location & with itwems now

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Hotfix for map

---

code/controllers/subsystem/garbage.dm
code/controllers/subsystem/idlenpcpool.dm
code/controllers/subsystem/npcpool.dm
code/game/objects/effects/spawners/gibspawner.dm
code/modules/admin/topic.dm
modular_coyote/code/mam_tails_coyote.dm

Fixes a couple things.
Adds deer tails to anphros
me explaining to myself what the GC status entry means
Slightly added some more sanity to the idle NPC manager, I have a feeling nullspaced NPCs are still being calculated. Unsure! Only time will tell, hard to test locally.
Removed the gib timer as we added it in so rain cleans gibs now. Makes it more messier indoors B)
GC hasn't been changed, but I had a look at it and it literally works the same was as usual. Infact, it runs great.
No fucking clue anymore tbh there hasnt been much issues on github to look at.
Changelog isnt working so :I why bother.

Another fix or two

---

_maps/map_files/Pahrump-Sunset/RockSprings.dmm
code/__DEFINES/traits.dm
code/datums/components/crafting/recipes/recipes_tailoring.dm
code/datums/traits/good.dm
code/game/objects/items/granters.dm
code/game/objects/items/stacks/sheets/sheet_types.dm
code/modules/clothing/suits/arfsuits_unused.dm
code/modules/jobs/job_types/followers.dm
code/modules/jobs/job_types/oasis.dm
code/modules/jobs/job_types/wasteland.dm
code/modules/jobs/jobs.dm
modular_citadel/code/modules/client/loadout/head.dm
modular_citadel/code/modules/client/loadout/suit.dm
modular_citadel/code/modules/client/loadout/uniform.dm
modular_sunset/code/modules/client/loadout/suit.dm

Reverts ARF-SS13/coyote-bayou#413

Revert "Revert "Loadout Update""

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Minorly revamps the flow/layout of the followers hospital. Makes the outside safer. _**Does not add any new items, only organizes existing ones. Nothing has been added aside from one ghoul nest outside and a couple of literal trash spawners. THE MOST SACRED RULE OF ALCHEMY: THE LAW OF EQUIVALENT EXCHAN-**_
:cl:
tweak: Changed followers hospital to be less dangerous outside, better flow inside, as in accordance with the #cbt channel
/:cl:

followers hospital minor revamp?

---

.github/workflows/autobuild_tgui.yml

attempts to fix the TGUI autobuild

---

fortune13.dme
modular_coyote/code/modules/mapping/turf_patches.dm

A hotfix for Wren's mapping, their tiles have no air, oof, dangit. thanks planetary atmos..!

patches the lavaland turfs to be made for good ol fallout 13

---

code/datums/components/crafting/recipes/recipes_forge.dm
code/datums/components/crafting/recipes/recipes_primal.dm
code/modules/fallout/turf/ground.dm
code/modules/smithing/smithed_items.dm

1) Animal glue recipe (3 bones, 1 sinew, 3 leather, 50 water) tool campfire = 1 wonderglue
2) Duct tape recipe (4 durathread + 1 wonderglue) tool workbench = 1 wonderglue
3) Wooden floor also create plating, so you dont need to waste preciouse iron sheets to build a shack or simple defence wall
4) Bone ingots (2 bones + 1 wonderglue + 2 iron rods)
- [X ] You tested this on a local server.
:cl:
add: Added wonderglue and duct tape recipes
add: Wooden floor also create plating
add: Bone ingots and their crafting recipes
/:cl:

More tribal features

---

_maps/map_files/Pahrump-Sunset/RedRiver.dmm

:cl:
add: ah goodness new area for people to find and loot north of redriver
/:cl:

adds a store north of redriver.

---

code/modules/fallout/obj/stack/f13Cash.dm
code/modules/fallout/obj/structures/mob_spawners.dm
code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm
code/modules/mob/living/simple_animal/hostile/f13/centaur.dm
code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
code/modules/mob/living/simple_animal/hostile/f13/insects.dm
code/modules/mob/living/simple_animal/hostile/f13/mirelurks.dm
code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
code/modules/mob/living/simple_animal/hostile/f13/wolf.dm

haha money go drippy
:cl:
tweak: More cappies :)
/:cl:

hehe cappies

---

code/__DEFINES/footsteps.dm
code/controllers/subsystem/mob_spawners.dm
code/game/objects/items/prize_loot.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/research/techweb/nodes/engineering_nodes.dm

ree.
Fixes two runtimes on code startup.
That it.
Edit:
Fixes a chicken walking on gravel causing runtimes too.
Edit Edit:
Nests didn't stop processing after being GC'd and I think spawned mobs in nullspace. Fixed!

Fixes some stinky runtimes >:(

---

code/modules/mob/mob.dm

Stop wielding when you attempt to switch hands

---

_maps/map_files/Pahrump-Sunset/RedRiver.dmm

yearp
:cl:
add: new obstacles at gas station redriver
/:cl:

Makes it a bit harder to get in to the place north of red river from the south

---

code/modules/mob/dead/new_player/sprite_accessories/socks.dm
code/modules/mob/dead/new_player/sprite_accessories/underwear.dm

I like socks and underwear. So these were randomly uncommented out before, and now they rebring them.
:cl:
uncomments: out a bunch of underwear and socks. 
/:cl:

uncomments some of the socks and underwear.

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

what it says on the tin cheif.
:cl:
del: misbehaving walls hiding under doors.
/:cl:

No more doors over walls

---

_maps/pahrump.json

since its just eatin up needless resnorses, we're togglin her off.  Revert dis to bring her back
:cl:
del: Removed the Mall Z from the load list, should make things run a little smoother for now.
/:cl:

Turnin off the mall z for now

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Re-adds the OR table and console to the Followers first floor
:cl:
add: FoA has their first floor OR table back.
/:cl:

Re-adding the FoA OR table

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Contains the other half of PR #495
of course this happens the one time I don't use a Draft PR.
:cl:
fix: Actually port the rest of the changes in #495 
/:cl:

the other half of my PR

---

code/modules/mob/emote.dm
code/modules/mob/living/emote.dm
code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
code/modules/mob/say.dm

Reverts ARF-SS13/coyote-bayou#492
Emotes and Says broke to hell and back.

Revert "Adds linebreaks to *me"

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Deletes the cleanbot in the pool.
:cl:
del: Deletes a cleanbot in the pool area.
/:cl:

Delet Clenbutt

---

code/modules/smithing/anvil.dm

:cl:
balance: Now the experience system really makes sense. You will not be able to forge the best items if you do not master your skill to the maximum.
balance:  Anvils quality balance
/:cl:

New leveling system for blacksmithing

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

east wall isn't concrete in the actual thing, sorry for bad screenshot. vendor has a thing looking into the street :) also removes that annoying rad puddle outside the east gate and adds/moves clutter
:cl:
add: vendor (and technically bar) nash updates
/:cl:

minor nash updates

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm

Removes a bunch of mobs from the rooftop and basement due to there not being any loot worth fighting that much shit over.
:cl:
del: a bunch of mobs and nests.
/:cl:

Mapping Edits, Followers V3

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm

Cuts a wire on the rooftop, forcing the followers to actually fix it before power goes out. Adds another research document and a blueprint to the roof guarded by the gutsy. Adds another sheet of uranium to the basement. 
:cl:
tweak: Makes some more changes to the followers.
/:cl:

Mapping Update, Followers V4

---

modular_coyote/code/modules/verbies/whocares.dm

Used `key` instead of `C.key`, such a simple typo! I couldnt notice it while testing cause it shows my name, no one else was on, oooooof.
Also some other fixes to prevent ghosts showing differently in who() and allows admins to see the status of ghosted players.
changelog still doesn't work atm, we need to host 2 php files :I

Who() fix, oops.

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

This just edits a small house near the pharmacy and lake area to have a small bathroom and readjusts the internal layout, that's it.
:cl:
tweak: Changed a small house east of the clinic.
/:cl:

A map change that isn't to the followers for once.

---

_maps/map_files/Pahrump-Sunset/RedRiver.dmm

This PR adds a tad bit of river touch up with the mountains and even more caves to explore, awhile they are less caves with less details but also brings in a ole mirelurk baby named Captain harpe who is an dosmetic little pal to anyone who finds him, especially if it is mirelurks. :) Either way, picture time, what has changed. 
All the mapping changes well for loot is either superlow or hobo tier spawns as someone can easily cheese it and grab them, so no point in putting anything worth of high value down.
------------------
Little dock gotten expanded by a little. 
------------------
In the image above, the barricades gotten a little love by having a bit more there, in number 1. 
in circle two and this is what happened to most bars, they all gotten changed into strong metal bars, so that …

Red River update

---

code/__DEFINES/melee.dm
code/modules/smithing/finished_items.dm
modular_coyote/eris/code/wielding.dm

:cl:
added an extra condition for smithed weapons so that they function with eris code
/:cl:

Smithing fix

---

code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
code/modules/jobs/job_types/wasteland.dm

Yes, I've got heartaches by the number. (fixes a blueprint and what bluepritn someone gets)
:cl:
fix: I've got heartaches by the number. (gives NCR outlaw the proper blueprints)
/:cl:

hotfix for auto stuff. please don't kill me

---

modular_citadel/code/modules/client/loadout/uniform.dm

Cherry pick test of a Sunset PR. Tests cherry-picking to make sure all is well.
https://github.com/sunset-wasteland/sunset-wasteland/pull/306 Original PR.
:cl:
fix: stop referencing rhodesia i beg you
/:cl:

Renames NCR Shorts in loadout

---

code/modules/jobs/job_types/oasis.dm

Reduces town doctor coun t to 1

---

code/game/machinery/water_purifier.dm
code/game/objects/items/melee/misc.dm
code/game/objects/items/storage/belt.dm
code/modules/fallout/misc/gangs.dm
code/modules/fallout/misc/tribes.dm
code/modules/integrated_electronics/subtypes/atmospherics.dm
code/modules/mob/living/carbon/human/species_types/golems.dm
code/modules/mob/living/simple_animal/bot/secbot.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/projectile/bullets/dart_syringe.dm

[Original PR.](https://github.com/sunset-wasteland/sunset-wasteland/pull/316)
:cl:
fix: misc runtime fixes
/:cl:

Cherry-picks runtime fixes from Sunset

---

code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/projectiles/guns/ballistic/revolver.dm
code/modules/projectiles/guns/ballistic/rifle.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/energy/plasmaf13.dm
code/modules/projectiles/guns/hoboguns.dm

Does what it says on the tin, adds the GUN_SCOPE trait to weapons with Can_Scope = True
:cl:
add: Adds GUN_SCOPE trait to weapons with Can_Scope =  True
/:cl:

Adds GUN_SCOPE trait to weapons with Can_Scope =  True

---

code/__DEFINES/mobs.dm

tech nically now just one decisecond.

Ghosts no longer need to wait 20 minutes to respawn

---

code/_onclick/other_mobs.dm
code/datums/hud.dm
code/game/machinery/computer/arcade/orion_trail.dm
code/game/objects/effects/landmarks.dm
code/modules/antagonists/swarmer/swarmer.dm
code/modules/hydroponics/beekeeping/beebox.dm
code/modules/mob/living/simple_animal/bot/bot.dm
code/modules/mob/living/simple_animal/eldritch_demons.dm
code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
code/modules/mob/living/simple_animal/friendly/drone/extra_drone_types.dm
code/modules/mob/living/simple_animal/hostile/bees.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/mob/living/simple_animal/hostile/jungle/leaper.dm
code/modules/mob/living/simple_animal/hostile/mecha_pilot.dm
code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/goldgrub.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/shuttle/special.dm

Original PR:
https://github.com/sunset-wasteland/sunset-wasteland/pull/321
:cl:
fix: Fixed the GC regarding mobs.
/:cl:

Cherry picks GC / hard del fixes from Sunset

---

modular_citadel/code/modules/client/loadout/suit.dm

Readjusts suit prices.
So this is how it works.
If it has zero armor thne its one. 
If it is light armored two points.
If it has more pockets like say seven, then its two points.
If it has more then light armored then 3.
:cl:
Tweak: Prices.
/:cl:

Loadout: Suit prices

---

code/modules/client/verbs/ooc.dm

hotfix admin OOC shit

---

code/datums/brain_damage/severe.dm

What it says on the tin. Triples the stress buffer of Monophobic people.
:cl:
tweak: changes monophobia stress buffer from 10 to 30
/:cl:

Triples the time that Monophobia takes to start making trouble.

---

code/modules/client/verbs/ooc.dm

Ye! Now you can't see people's Ckey via the ignore tab <3

Hides ckeys from the ignore verb

---

code/game/machinery/autolathe.dm
code/modules/farming/farming_structures.dm
code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm

[pooort](https://github.com/sunset-wasteland/sunset-wasteland/pull/333)
:cl:
add: Added bulk fruit fermentation. By clicking a fermenting barrel with a plant bag, all the suitable plants in it will be fermented.
add: Added bulk seed extraction. By clicking a Legion seed extractor with a plant bag, all the suitable plants in it will have their seeds extracted.
tweak: Smartfridges like bottle racks, alchemy racks, etc. can now be loaded from ALL storage items, not just bags.
/:cl:

Removes carpal tunnel syndrome from the game

---

code/modules/jobs/job_types/oasis.dm

Reverts ARF-SS13/coyote-bayou#564 due to silliness and love.

Revert "Reduces town doctor coun t to 1"

---

code/modules/projectiles/guns/mods/mods.dm

Scoop me bby
Hoopsies, dis better name
:cl:
tweak: ACOG Scope to Old Scope
/:cl:

ACOG Scope to Old Scope

---

code/modules/jobs/job_types/wasteland.dm

Hoopsies, dis better name
:cl:
tweak: One of the slave loadouts renamed to Domestic
/:cl:

Domestic Slave rename

---

modular_citadel/code/modules/client/loadout/suit.dm

:cl:
code: unlocks field scribe coat from loadout
/:cl:

Unlocks the fieldscribe coat

---

code/modules/research/designs/autolathe_designs.dm

funni metal in funi mechanical box hehe
:cl:
add: Added titanium sheets to autolathe
/:cl:

Titanium Sheet Into Autolathe

---

code/modules/research/designs/autolathe_designs.dm
code/modules/research/designs/autolathe_desings/autolathe_designs_medical_and_dinnerware.dm
code/modules/research/designs/medical_designs.dm

stimky chemixer
:cl:
tweak: Moved Portable Chem Mixer from proto to autolathe.
/:cl:

Portable Chem Mixer to Autolathe

---

code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm

Touched the handloaded .22 and 10mm recipes to be more consistent.
:cl:
tweak: Touched the handloaded .22 and 10mm recipes to be more consistent.
/:cl:

Improv Ammo Recipe Adjusted (10mm/.22)

---

code/modules/research/designs/autolathe_designs.dm
code/modules/research/designs/autolathe_desings/autolathe_designs_sec_and_hacked.dm

I hate your bluespace boolshid
:cl:
del: Removed RCDs from Autolathes
/:cl:

RCD removed from autolathes

---

code/game/machinery/autolathe.dm

can now interact w/ open reloading benches
:cl:
fix: reloading benches can now be interracted with while open
/:cl:

fixes reloading benches arg

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RedRiver.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

Touched up a few places, made a few spawns a little safer.  Put down some arkansas/texas flags.  Nothing crazy.
:cl:
tweak: tweaked a few things on a few maps
/:cl:

Map Touchups

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Upstairs Nash buildings and a WATCH TOWER!
:cl:
add: Upstairs Nash buildings and a WATCH TOWER!
/:cl:

Nash Upstairs

---

code/__DEFINES/armor.dm
code/modules/clothing/clothing.dm

Nerfs the shit out of armor.
Reduces DR across the board.
Reduces DT across the board.
Somehow they're still more powerful than before. DT's a hellova drug.
:cl:
balance: Reduces DR and DT across tha board. yet they're still more powerful than before DT. Wierd.
/:cl:

Armor buffn'ts

---

code/modules/mob/living/carbon/human/species_types/synthliz.dm

Some various tweaks to Synthetic Lizardpeople. See changelog for details. Given that this effects balance, please Testmerge for a week before merging fully.
:cl:
add: Adds TRAIT_RADIMMUNE to synthetic lizardpeople
add: Adds TRAIT_NOBREATH to synthetic lizardpeople
add: Adds TRAIT_NOHARDCRIT to synthetic lizardpeople
add: Adds TRAIT_NOSOFTCRIT to synthetic lizardpeople
del: Removes HAS_BLOOD flag from Synthetic lizardpeople.
del: Removes HAS_FLESH flag from synthetic lizardpeople.
/:cl:

<Ready for Testmerge> Update synthliz.dm

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

it never ends, this shit
Should fix Redwaters doors, and Nash's bar got a little fiddling
:cl:
tweak: Should fix Redwaters doors, and Nash's bar got a little fiddling
/:cl:

Lil mappy fixes & bar poking

---

code/game/machinery/doors/door.dm
code/modules/fallout/obj/structures/simple_door.dm

We dont need to know in chat when a door is destroyed. Thats what logs are for! also makes the chunderdome just about unusable.

Admemes are no longer spammed when doors die.

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RedRiver.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

Added underground motel & tunnel to Redlick.
Adjusted number of spanwers in Nash Z.
add: Added underground paths to get to Redwater/Redlick.
del: Removed some of the random spawners on the Nash Z.
tweak: Tweaked ur moms nips lmao
/:cl:

Map Touching - Lots of stuff!

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

https://youtu.be/7VMn11uybLQ
:cl:
fix: Fix HN stairs
/:cl:

Fixed HN stairs

---

code/__DEFINES/random_mob_spawner.dm
code/modules/fallout/obj/structures/mob_spawners.dm

Extended the overpopulation search range for nests, and makes it check through walls too.
Added in another safety check for now so that nests that start with 1 mob dont spawn that mob endlessly. fuckin deathclaws.
Made the difficulty list combiners use an actual decent proc.
Smallened the range spawners check for players. Also made it a view check, so you'll have to see the nest for it to fire.

Unfucks mob spawners again again

---

_maps/map_files/Pahrump-Sunset/RedRiver.dmm

made it so the plant building can't kill people right when they spawn lol
:cl:
tweak: tweaked redlicks plant building so its closed
/:cl:

fixed redlick road building

---

code/game/objects/effects/landmarks.dm

heeh
:cl:
fix: fixed Sheriff spawn.
/:cl:

Fix Sheriff spawn

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

I added some more trip oil for the sins of your forefathers, to pay for it I gave the followers a fucking grinder.
Also readded the ammo bench for redwater.  For now.
:cl:
add: Added a grinder to the followers, and an ammo bench back to Redwater.
/:cl:

Followers Grinding hours

---

code/modules/fallout/obj/structures/mob_spawners.dm

Spawners were just not spawning things, so I made them trigger through walls again. Also made them not restart their cooldown if something was on it.

Buffed spawners a bit

---

code/modules/fallout/obj/structures/mob_spawners.dm

Mob spawners no longer care abouut players. They'll ignore players and just count their own kind of mobs. Cus, they were counting players, and just wouldnt work. heck.

Unfucks mob spawners again again again

---

code/modules/fallout/obj/structures/mob_spawners.dm

Thats it, back to just raw mob range checking.
One more stamp and I get a free pizza.

Unfucks mob spawners again again again again

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

haha roof go brr
haha roof go brr
:cl:
add: added vending machine with deans to the museum
tweak: tweaked the nash clnics roof
/:cl:

Fixed Nash Clinic Roof & Deans Vendor

---

code/modules/cargo/exports/misc_export.dm
code/modules/cargo/packs/security.dm

cargo update. no mapping changes.
:cl:
add: grabbags, can sell cells
/:cl:

ec's now able to be exported, more munitions including grabbags. 

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

Mirrors for hair issues
funny reflective surface additions to redwater and the tribal camp
:cl:
add: Added more mirrors to rocksprings.dmi
/:cl:

More mirrors in Redwater/Den

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

Starting the process of fleshing out second floor buildings and roof access ladders.
https://gyazo.com/ae27939c7252ffced4a3d557e5c0bdc8
:cl:
add: Rooftop areas above the plant shop & one building near the clinics second floor w/ enviromental story telling.
/:cl:

Second Floor Add-ons

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Fixes weird mapping glitch when @Tk420634 did a thing. Re merges #650
:cl:
fix: Fixes a mapping merge error.
/:cl:

Re-ReFix Nash Curtains

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Has a guarenteed power armor spawn as well as really high-tier melee weapon loot. If you get to the end, though, you **definitely deserve it.**
:cl:
add: expanded the super mutant vault dungeon :)
/:cl:

expands the super mutant vault dungeon

---

code/controllers/configuration/entries/general.dm
config/config.txt

Changed HUB Tagline, included discord link.
Changed Lobby countdown from 160 seconds to 5.
Changed Round End Counter to 30 seconds.
Changed player ability to vote for restarts.
Changed forum URL to our forums.
Changed banappeals link to our forums.
Changed the auto-train call to 5.5 hours with 15 minutes between call votes, with two calls max before it autocalls.  Meaning rounds can last between 6 and 6.5 hours.
I definitely want someone to look over these number changes for me and make sure this shit is correct.
:cl:
imagedel: …

Config Updates & Round Time Adjustements

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm
code/modules/jobs/job_types/wasteland.dm

Moved some spawns around, mostly moved stuff out of buildings and to matrix tiles, also added redwater watcher spawn.
:cl:
tweak: Moved some spawns around, mostly moved stuff out of buildings and to matrix tiles, also added redwater watcher spawn.
/:cl:

Fixed some spawns

---

code/__DEFINES/armor.dm
code/game/objects/objs.dm

Know how some armors have negative armor values? Most of those are unintended. This fixes them, and also buffs higher end specialist armors.

Armor fixes

---

code/modules/projectiles/boxes_magazines/_box_magazine.dm

Removes the delay from doing steps when reboring guns.

Reboring is no longer on a delay

---

_maps/map_files/Pahrump-Sunset/RedRiver.dmm

Added a few buildings to Red River Z, as well as adjusting a few traps.
:cl:
tweak: Added a few buildings to Red River Z, as well as adjusting a few traps.
/:cl:

Red River Z Update

---

code/modules/projectiles/guns/ballistic/automatic.dm

Uzi is full auto and semi auto, does full damage, and is normal-sized. American 180 fires faster and does full damage too.

Buffs uzi and 180

---

config/config.txt

Disabled player restart votes

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
code/modules/clothing/head/f13head.dm
code/modules/clothing/suits/arfsuits.dm

changes supermutant behmoth hp from 3000 to 1500
turrets now shoot you b/c of weird aggro problems with them and the behemoth, but the behemoth's hp is like...literally cut in half you'll probably be fine on the DPS check
raises armor on excavator from -33 las/boolet to around 0, still has dope DR
:cl:
tweak: supermutant behemoth dungeon fixes/changes
/:cl:

supermutant behemoth changes and exca suit changes

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Expands a specific Cave Cabin on the Cave Z Level.
:cl:
tweak: Expanded a Cabin in a cave.
/:cl:

Makes a Cave cozier

---

code/modules/mob/living/simple_animal/hostile/bear.dm

Replaces shitty sprite of bear with better older sprite for bear. 
:cl:
/:cl:

Bear please

---

config/config.txt

or vote, I guess.  For transfers
:cl:
/:cl:

let them eat their cake

---

code/datums/components/crafting/recipes/recipes_tailoring.dm

Fixes https://github.com/ARF-SS13/coyote-bayou/issues/623  Please remember to close issue when merged.
:cl:
/:cl:

Typo in Reinforced Steel Breastplate

---

code/game/objects/items/storage/boxes.dm

Modified some hugbox loadouts to be more fallout-y
:cl:
tweak: tweaked hugbox loadouts
/:cl:

Hugbox crap update

---

code/modules/library/lib_items.dm

hahaheheaahaaa  dried tatologs
:cl:
tweak: Skill books onto bookshelves
/:cl:

Skill books into bookcases

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Tore it up, shrimple as.  All wood now.
:cl:
del: Removed carpet under stairs in Heavens Night.
/:cl:

Purple carpet under Nash bar

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RedRiver.dmm

Adds a new dungeon above the robot parking lot, removes red river northern spawns (players will still spawn south of the river on the safer side of town)
:cl:
add: Adds new dungeon above robot parking lot
del: Removed overly dangerous northern redlick spawns
/:cl:

S'mapping - Dungeon & Spawners

---

code/modules/cargo/exports/misc_export.dm
code/modules/cargo/packs/goodies.dm
code/modules/cargo/packs/medical.dm
fortune13.dme

misc_export.dm was not enabled. also, lets you order books, OOoOOoOOoOOooOOoooo..
:cl:
add: cargo books
fix: lets you sell stuff via cargo now
/:cl:

actually enables cargo exports, oops.

---

code/modules/surgery/bodyparts/_bodyparts.dm

Clothes shouldnt take damage anymore.

Disables clothing damage

---

code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm

adds a g to the robobrains description.
:cl:
add: Added a letter to robobrains desc
/:cl:

The real G

---

code/game/objects/effects/spawners/f13lootdrop.dm
code/modules/fallout/obj/structures/mob_spawners.dm

filling a burrow now does not guarenteed spawn you the same 4 guns on endless loop. can spawn caps, garbage, armor, etc,.
:cl:
add: new loot table for burrows
/:cl:

changes loot from filled burrows

---

code/modules/pool/pool_drain.dm

all my homies hate pools.
Fixes 100,000+ runtimes lmao
:cl:
del: Removed pool drainage
/:cl:

Fuck pools

---

code/modules/hydroponics/grown/towercap.dm

fuck you, stack.dm runtime.  All my homies hate runtimes.  The commented out code can be revisited later, but for now this solves that nasty little bugger real good.
:cl:
code: Runtime murder, Stack.dm edition
/:cl:

Fixes stack.dm runtime

---

code/modules/detectivework/detective_work.dm
code/modules/mob/mob.dm

Things that leave fingerprints that are made to leave fingerprints by things that arent mobs should no longer runtime.
Examining various parts of your UI should no longer runtime.

Runtime roundup 1

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
code/modules/mob/living/simple_animal/hostile/megafauna/behemoth.dm

someone solo'd the behemoth. THE NUMBERS GO UP AND DOWN AND UP AND DOWN AND UP AND DOWN AND U
:cl:
tweak: behemoth is now a bit harder (more hp, better scaling)
/:cl:

raises HP/scaling of behemoth

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Fiddlediddle
:cl:
tweak: tweaked listening post
/:cl:

Listening Post Fiddling

---

config/config.txt

Updated Server tagline

---

code/game/objects/items/devices/PDA/PDA.dm

perish
Fixes PDAs creating hundreds of runtimes.
:cl:
fix: fixes stinky pda runtimes
/:cl:

PDA Runtime fix

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm
code/modules/fallout/turf/ground.dm
code/modules/mob/living/carbon/human/species_types/anthropomorph.dm

Fever blossom weight lowered from 7 to 3 (less spawn amount)
Followers mall access door changed to an airlock
Did some adjusting on the synthetic anthropomorph disabled species
Two various map fixups (mirror fixed on nash zlevel, stairs to nowhere on redwater zlevel removed)

Various Changes (See description)

---

code/modules/fallout/obj/structures/mob_spawners.dm

Lowers number of molerats in the nest and doubles the time between spawns.  Should make less molerat hellscapes lmfao
:cl:
tweak: Tweaked Molerat Spawner
/:cl:

Molerat Spawner nerf

---

code/datums/traits/good.dm
code/modules/clothing/suits/arfsuits.dm
code/modules/clothing/suits/arfsuits_unused.dm
code/modules/clothing/under/f13.dm
code/modules/vehicles/rubbish.dm
modular_citadel/code/modules/client/loadout/__donator.dm
modular_citadel/code/modules/client/loadout/suit.dm
modular_citadel/code/modules/client/loadout/uniform.dm

Adds the technophreak to the 'good' traits listing for 3 points.
Committed out all the custom boxes except sanderps.
Too much loadout stuff to list off at once lmfao.
Shameless cherry pick: https://github.com/sunset-wasteland/sunset-wasteland/pull/415 (thanks kav!)
Loadout item locked to TK!

New trait and some loadout additions, plus some others

---

code/game/objects/items/cards_ids.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Adds a license for Fuzlet to do whatever it is they do. Also a box of crayons for a quick snack.

Adds a fuzzy license

---

code/datums/traits/good.dm

Lowers the loadout cost of Technophreak

---

code/modules/hydroponics/grown/cotton.dm

cotton eye'd joe.mp3
:cl:
/:cl:

Stop Cotton Runtime

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Oops
:cl:
fix: fixes ladder in what was the old ranger station to go back downstairs
/:cl:

Fixes Ranch House Ladder

---

modular_citadel/code/modules/client/loadout/__donator.dm

Fixes a character setup bug I caused...oops

---

modular_citadel/code/modules/client/loadout/__donator.dm

Kits ckey fix

---

modular_citadel/code/modules/client/loadout/__donator.dm

Comes with a Wattz 1000 and energy cell.

Loadout item for Feris!

---

code/datums/components/spawner.dm

Spawners no longer default to being infinite.

Uninfinitizes spawners

---

modular_citadel/code/modules/client/loadout/__donator.dm

Yep, it's much better than how my rushing brain had it.

Fixed up the loadout ckey locked items!

---

modular_citadel/code/modules/client/loadout/__donator.dm

Loadout item locked to ckey Mathiel

Mathiel ckey locked loadout kit!

---

code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm

Removes the Legion/NCR reference.
ඞ ඞ ඞ
PS: THEY YAP!

Time Paradox Removed! ~~Ian~~ Trading Protectron edition

---

code/__DEFINES/inventory.dm
code/datums/components/storage/concrete/bags.dm
code/game/objects/items/storage/bags.dm

Salvage bag has a larger size and is properly defined for more easy changes to it in the future. It seems to work after a quick check. 
:cl:
/:cl:

Salvage bag is properly defined as it's own thing and has a larger size

---

_maps/map_files/Pahrump-Sunset/RedRiver.dmm

Made it so you can walk up agianst one of the fences in Redlick
:cl:
fix: fixed a fence in redlick
/:cl:

Fixed Redlick Fence

---

modular_citadel/code/modules/client/loadout/__donator.dm

added my loadout! Didn't test it in my server, if I need to scream at me in DMs
:cl:
/:cl:

added my loadout

---

code/_globalvars/lists/maintenance_loot.dm
code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
code/game/objects/items/granters.dm
code/modules/projectiles/guns/mods/mods.dm

You need guns and bullets 3 AND an advanced workbench to make them!
Battery shunt damage increase lowered from 50% increase to 35%.
Removed fire speed increase from the overdrive. It's now a full battery increasing mod!

Moves the four added modkits to the crafting recipe!

---

code/controllers/subsystem/nightcycle.dm

as the title says. increases the power of the midday sun.
going to be going through a whole time of day overhaul at some point, mayhaps including temperature, and including being able to click on urself to tell what time of day it is
:cl:
tweak: daylight brighter
/:cl:

just increases the power of the midday sun.

---

_maps/map_files/Pahrump-Sunset/RedRiver.dmm

Adds trimming to the Red River.
:cl:
add: Adds muddy trim to Red River
/:cl:

Bear you're a coward

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Removes NCR Documents from the old ranger station/ranch house
:cl:
del: Removed NCR Documents from the old Ranger Station
/:cl:

NCR Document Removal

---

code/__DEFINES/inventory.dm
code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/research/designs/ammolathe_designs.dm

Changes *to* .22 stuff.
Fixes descriptions on .22 LR guns.
extended .22 mags dont go on holsters.
Adds extended .22 mags to ammolathe.

22 changed

---

_maps/map_files/generic/CentCom.dmm
code/controllers/subsystem/vis_overlays.dm
code/datums/browser.dm
code/datums/components/storage/concrete/bag_of_holding.dm
code/datums/components/storage/storage.dm
code/datums/outfit.dm
code/datums/spawners_menu.dm
code/game/objects/effects/overlays.dm
code/game/turfs/turf.dm
code/modules/asset_cache/asset_list_items.dm
code/modules/fallout/obj/structures/obstacle.dm
code/modules/fallout/turf/ground.dm
code/modules/hydroponics/biogenerator.dm
code/modules/instruments/songs/editor.dm
code/modules/mining/machine_vending.dm
code/modules/mob/dead/observer/orbit.dm
code/modules/mob/living/carbon/life.dm
code/modules/mob/living/simple_animal/friendly/farm_animals.dm
code/modules/mob/living/simple_animal/friendly/snake.dm
code/modules/mob/living/simple_animal/hostile/bees.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/mob/living/simple_animal/hostile/retaliate/retaliate.dm
code/modules/pits/pits.dm
code/modules/projectiles/projectile.dm
code/modules/smithing/finished_items.dm
code/modules/vending/_vending.dm
tgui/packages/tgui/interfaces/Biogenerator.js
tgui/packages/tgui/interfaces/MiningVendor.js
tgui/packages/tgui/interfaces/Vending.js

Ports, courtesey of out-of-phaze
https://github.com/sunset-wasteland/sunset-wasteland/pull/423
Does not port auxmos updates (Needs someone clever to oversee, like Jon), does not port typecache changes (Ive changed the fuck out of storage stuff, will need more dedicated attention later)

Fixes and upgrades

---

code/__HELPERS/_string_lists.dm
code/__HELPERS/files.dm
code/__HELPERS/roundend.dm
code/__HELPERS/text.dm
code/__HELPERS/type2type.dm
code/controllers/subsystem/persistence.dm
code/controllers/subsystem/profiler.dm
code/game/objects/structures/musician.dm
code/modules/admin/admin_investigate.dm
code/modules/asset_cache/asset_list.dm
code/modules/client/preferences.dm
code/modules/instruments/songs/play_legacy.dm
code/modules/mapping/map_config.dm
code/modules/photography/_pictures.dm

Relative copy of a pr Paradise
Untested, suggest Testmerging to make sure this doesn't fuck anything
Doesn't affect anything player-sided.

 Adds checks so admins can't print files using adv. proccall

---

modular_citadel/code/modules/client/loadout/__donator.dm

Kit locked to ckey aerodynamique.
Kit locked to ckey greed2323.
Now with 100% more swag for you local doguty and rowobot

Bear and Greed's ckey locked loadout!

---

modular_citadel/code/modules/client/loadout/__donator.dm

added one extra ammo clip and a bedsheet for luna to wear as a cape.
:cl:
/:cl:

Lunasloadout2.0

---

code/modules/clothing/suits/arfsuits.dm

It has good melee/laser protection, but garbage gun resistance!
PS: The fix was to actually make it show up in the listing as being medium armor when examined as well as have all the stats appropriate to superlags armor update.

Fixes the Leather Battle Coat!

---

code/_globalvars/lists/maintenance_loot.dm

The good mods shouldnt be common anymore with this pr. SORRY

They're out of the loot pile now! (The parts)

---

modular_citadel/code/modules/client/loadout/__donator.dm

Loadout kit locked to jackson1112. Quite a lot this time around but a few staff approved of it!

Loadout kit for jackson1112

---

modular_citadel/code/modules/client/loadout/__donator.dm

Fixes Jacksons kit. (some items were wrong/one missing)
Adds ckey locked loadout kit for swirlby.

Ckey loadout kit, and a fix to another!

---

modular_citadel/code/modules/client/loadout/__donator.dm

No player-sided changes, just better organization code-wise.
Also renames a few paths to the associated ckey, for consistency.

Alphabetizes custom loadout stuff

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

*skrem
Fixes this.
https://media.discordapp.net/attachments/987874744395239424/1020025638071042078/unknown.png?width=687&height=490
:cl:
/:cl:

Removes a rogue different area tile

---

code/game/objects/structures/beds_chairs/bed.dm
code/modules/mob/living/simple_animal/friendly/dog.dm

Dogs no longer check through every turf in an area for a dogbed when they spawn.

Dogs no longer search through every fucking atom in the wasteland when spawning

---

modular_citadel/code/modules/client/loadout/__donator.dm

Added more to Mathiel's loadout kit upon request.
_Hopefully_ fixes lucine's kit? It looked fine but they couldn't access it. Shared the same kit name as another player though so maaaybe that will fix things.

THAT TIME OF THE DAY AGAIN! (Loadout wild ride)

---

code/modules/clothing/suits/arfsuits.dm
modular_citadel/code/modules/client/loadout/suit.dm

It'll work 100% now. Tested and all. Has armor actually and a sprite!

Fixes the kha- IMEAN Leather Battle Coat for good

---

fortune13.dme
modular_citadel/code/modules/client/loadout/__donator.dm
modular_sunset/code/modules/fluff/slimecookie_granter.dm
modular_sunset/code/modules/fluff/slimescookie_recipe.dm

Ckey loadout kits locked to risingstarslash. Both of which are general to others that requested with an added item similar to sanderp. Comes with a slime cookie recipe book for three of the cookies in the second one!
Fixes up feris' ckey locked kit!

Ckey loadout kit!

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

- Adds a second story to the hotel
- Adds a basement underneath the workshop
- Adds more caps to the trader
- Adds some torches to the gate of Nash
- Adds a yard to the jail
Also some fixes to the tribal camp
- Adds a bedsheet to the surgery room, replaces the matches to seal surgries with a cautrery
- Adds a matrix area 
:cl:
server: …

Nash updates

---

modular_citadel/code/modules/client/loadout/__donator.dm

Loadout kit locked to ckey Esperkin.

Loadout ckey locked kit!

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Fixes nash workshop stairs

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

HE ARRIVES, also some nash shopkeep changes
:cl:
add: Adds Mango Mathew Sprite, and adjusts his lil fort
tweak: tweaks nash shopkeep spawn gear
/:cl:

The MAN-GOING

---

code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
code/modules/mob/living/simple_animal/hostile/f13/raider.dm

Haha, fucked that up didn't I?  We do a little shitting.  Also lowered some damages on rapid_meleeing mobs
:cl:
balance: rebalanced some mobs melee attacks
/:cl:

Slows Knife Raiders, and their buddies attacks a bit.

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Reverts ARF-SS13/coyote-bayou#801

Revert "More Nash updates and fixes."

---

_maps/map_files/Pahrump-Sunset/RockSprings.dmm

Reverts ARF-SS13/coyote-bayou#799

Revert "The MAN-GOING"

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Reverts ARF-SS13/coyote-bayou#798

Revert "Fixes nash workshop stairs"

---

code/game/objects/effects/spawners/f13lootdrop.dm
code/game/objects/items/melee/f13onehanded.dm
code/game/objects/items/melee/f13twohanded.dm

as the above says. way too many changes to changelog.
:cl:
tweak: some melee weapons attack faster or slower
balance: melee weapons are overall better, generally
/:cl:

changes attack speed and damage of melee weapons

---

code/modules/jobs/job_types/followers.dm
code/modules/jobs/job_types/oasis.dm

Maaaaaaybe fixes the loadout options I set up before. Was missing: = 1 on each one.

Take 3 of OHGODIHOPETHISWORKS (Loadout Edition)

---

code/modules/mob/living/simple_animal/hostile/megafauna/behemoth.dm

Behemoths shouldnt gib people anymore. Turns out they were voring your corpse! Gotta LOOC that shit!
Also their normal walk-dust no longer damages people. The big stoooomp still does though!

Behemoth nerfs

---

modular_citadel/code/modules/client/loadout/__donator.dm

Loadou kit locked to ckey fuzlet.

Kit for a cutie!

---

code/modules/research/rdconsole.dm

Let me touch your buttons
:cl:
fix: fixed rd console from being only clickable in funny ways
/:cl:

RD Console stinky

---

code/controllers/subsystem/processing/weather.dm

Seeing if its been crashing everything.

Disables weather

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
code/modules/mob/living/simple_animal/hostile/megafauna/behemoth.dm

makes shutters in the behemoth room stronker, also adds mobs to the fight
:cl:
tweak: behemoth fight changes
/:cl:

behemoth fight changes

---

code/__DEFINES/combat.dm
code/__HELPERS/unsorted.dm
code/modules/projectiles/ammunition/_ammunition.dm
code/modules/projectiles/guns/ballistic.dm

When you shoot a gun, the casing flies out to the right of your character a ways. Turns lines and piles of casings into vast sprays of littered brass.

Spent casings fly out of your gun

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/RedRiver.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

hehe dee dee dee 'i see u'
:cl:
tweak: tweaked some turret spawns
/:cl:

Turret adjustments for Dan

---

code/game/objects/items/plushes.dm
code/modules/admin/admin_verbs.dm
code/modules/projectiles/guns/ballistic/automatic.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Adds a .22 rifle to one of Fuz's loadouts, and gives them a unique fox toy.
Adds in Superlagg (my)'s loadout.

Loadout stuff for Superlagg and Fuzlet

---

code/modules/clothing/neck/mantle.dm
code/modules/clothing/suits/arfsuits.dm
modular_citadel/code/modules/client/loadout/__donator.dm
modular_citadel/code/modules/client/loadout/suit.dm

That kevlar kits literally broken man.
Adds the ranger cape to the loadout selection. (general tab of suits I believe)
Adds armor to the harper coat! The armor itself is light quality.
Nerfs the Leather Battle Coat slightly. Lowering the tier of the DT to two down from three. Oh it even also is far worse than it already is against bullets. The kha-I MEAN-whoever made this didnt think this through, did they?

Some loadout and armor edits!

---

modular_citadel/code/modules/client/loadout/__donator.dm

Edits Nirzak's loadout kit! Adds a reinforced combat helmet. Approved because it only really protects the head body part.

Edit to a ckey loadout kit!

---

code/modules/clothing/suits/arfsuits.dm

We do a bit of adjustments! Improves the melee damage resistance whilst lowering the laser resistance. This is added onto the DT lower.

Edits the Leather Battle Coat!

---

code/game/machinery/porta_turret/portable_turret.dm

Adds in some pre-made robot-friendly turrets for mappers to use.
Turrets will also stop shooting you if you go into stamcrit. Really good if they start shooting rubbers. Which mappers can totally make them do.

Adds robot owned turrets, and stamcrit mercy

---

config/config.txt

changes config servertag message
:cl:
/:cl:

cucks fenny

---

code/modules/reagents/chemistry/recipes/others.dm

I shouldn't have to spend 5 minutes playing musical chairs with the chemicals listing so acidic buffer doesnt get lost or another of the various chems mix with a precursor thus ruining it, and neither should anyone else for a niche chemical that only caters to slimepeople and select drinks. 
Grrr, yes it's a salt pr, hit me with the tag.

Fixes the Celugel Recipe

---

_maps/map_files/Pahrump-Sunset/RedRiver.dmm
code/game/objects/effects/spawners/f13lootdrop.dm

Additionally: adds some documents to computers for people to look at. Also adds an item to the loot drop table.
:cl:
add: police station on redlick z
add: fancee coat to loot drop table
/:cl:

adds a police station to redlick

---

modular_citadel/code/modules/client/loadout/__donator.dm

This should set Nirzak's kit up properly!

Fixes a loadout kit

---

modular_citadel/code/modules/client/loadout/__donator.dm

Fixes up Mathiel's loadout to a requested change!

Quick edit to a sune's loadout

---

modular_citadel/code/modules/client/loadout/__donator.dm
modular_citadel/code/modules/client/loadout/backpack.dm
modular_citadel/code/modules/client/loadout/hands.dm
modular_citadel/code/modules/client/loadout/neck.dm

Adds a selection of cigarettes types and some jewelry to the loadout list! The Cigars are in the backpack tab, the necklaces in the neck, and rings in the hand. (tabs)
Also edits merek's kit on request.

Loadout Additions!

---

code/game/objects/items/melee/f13twohanded.dm

https://youtu.be/6wzULnlHr8w
:cl:
/:cl:

bampr swad shnorp plas

---

code/__DEFINES/armor.dm
code/__DEFINES/combat.dm
code/__DEFINES/mobs.dm
code/modules/mob/living/damage_procs.dm
code/modules/mob/living/simple_animal/animal_defense.dm
code/modules/mob/living/simple_animal/friendly/dog.dm
code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm
code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
code/modules/mob/living/simple_animal/hostile/f13/raider.dm
code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/projectiles/ammunition/energy/laser.dm
code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/projectile/beams.dm
modular_sunset/code/mob/renegade.dm

Mobs have armor now! Most of them just have light armor, but super mutants and sentrybots have medium+ armor. Lemme know how they are!
Adds in a description system to convey *more or less* how much armor the mob has.
There are two kinds of ranged supermutant now: Shotgun and Varmint Rifle ones.
Shotgun mutants shoot two improvised shells that will murder you... unless you're armored or more than like 4 tiles away. Then they'll just hurt a bit.
Varmint rifle mutants shoot a varmint rifle at you. Much weaker than a hunting rifle and less likely to wound you. Also much less likely to kill you.
Rebalanced mob health and armor for those who are armored.
EMP does various things to robots, not just damage them. Its possible to stunlock them like this!
Tidied up some simplemob files.
Also makes …

Mob rebalancing

---

code/__DEFINES/combat.dm
code/game/objects/effects/spawners/f13lootdrop.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/guns/ballistic.dm
code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/projectiles/guns/ballistic/launchers.dm
code/modules/projectiles/guns/ballistic/pistol.dm
code/modules/projectiles/guns/ballistic/revolver.dm
code/modules/projectiles/guns/ballistic/shotgun.dm
code/modules/projectiles/guns/energy.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/hoboguns.dm

Resizes various guns and touches up what slot they should go in.
Reworks misfiring to not be 1000% duplicated code, and also opens up the possibility for other guns to misfire.
Misfiring can do one of three things:
- Hurt you, with various different damages based on what gun it is
- Unload the gun, and maybe toss the ammo across the room
- Fling the gun across the room
Also unfucks detective revolver code to no longer ruin it forever.

Resizes / enslottens various guns, touches up hoboguns

---

modular_citadel/code/modules/client/loadout/__donator.dm

Adds a loadout kit locked to ckey GeneralPantsu.
Adds a loadout kit locked to ckey RoachwithaRoach.

Ckey kits!

---

code/__DEFINES/misc.dm
code/modules/surgery/bodyparts/_bodyparts.dm
code/modules/surgery/bodyparts/parts.dm

Fixes butts looking wierd on certain markings.
Fixes arm markings not showing up.
Fixes more layering on markings regarding their position relating to butts.

WEE OO WEE OO EMERGENCY BUTT FIXES INBOUND

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Removes the poorly mapped tables and adds a railing.
:cl:
tweak: Adjusts Nash's Workshop once more.
/:cl:

Updates Nash's Workshop a little.

---

code/__DEFINES/armor.dm
code/modules/mob/living/simple_animal/animal_defense.dm

They now use the right var when things hit them. Woo,

Fixes mobs runtiming when hit

---

code/game/objects/items/storage/f13storage.dm
code/modules/reagents/chemistry/recipes/others.dm
modular_citadel/code/modules/client/loadout/__donator.dm
modular_citadel/code/modules/client/loadout/backpack.dm

Funny loadout selection go brrr for rations!
Fixes the acidic buffer back.

More loadout stuff and a fix to a bug I caused!

---

code/controllers/subsystem/processing/weather.dm

Reverts ARF-SS13/coyote-bayou#827 due to it not being what was causing crashes

Revert "Disables weather"

---

modular_citadel/code/modules/client/loadout/__donator.dm

Changes up Lucines kit on request.
Loadout kit locked to ckey tk420634. (second one)

More loadout kit shenanigans!

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
code/game/turfs/simulated/floor/f13_floors.dm

abandoend supermutant/spider vault now has miasma in it
gas gas gas 
:cl:
add: abandoend supermutant/spider vault now has miasma in it
/:cl:

makes the vault have the stinky, stinky smell of gas

---

modular_citadel/code/modules/client/loadout/backpack.dm

Removes my changes in favor of @Superlagg 's much better change!
Fixes up a few minor errors on their end!
Makes the xeno filters cost 1 point extra! (4 points now, was 3)

Cleans up the loadout a bit + Fixes up some!

---

modular_citadel/code/modules/client/loadout/hands.dm

Minor typo causing the rings to not show. Forgot the S!

Fixed an oof-y I did in the loadout (Now with 100% more S!)

---

modular_citadel/code/modules/client/loadout/backpack.dm

Added menu 11 to the loadout list! The poor hotdawgs weren't in.

Missing Menu Item (11)

---

code/modules/projectiles/guns/ballistic/rifle.dm

actually just makes it the brush gun sprite, but, whatever.
:cl:
/:cl:

'fixes' ranger lever action not having a full on-person sprite

---

_maps/pahrump.json

I am not very smart.
:cl:
/:cl:

ghost of mallshima

---

code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/projectiles/guns/ballistic/launchers.dm
code/modules/projectiles/guns/ballistic/shotgun.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/hoboguns.dm

I did a wierd with the defines, making guns able to fit in your glove slot. I mean sure its technically in your hand, but cmon man. Fixes that.

Guns dont go in your gloves anymore

---

code/modules/projectiles/ammunition/energy/plasma.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Plasma rifle go brrr
Credit to thatguyfromthatplace for sounds!

Links a soundfile properly

---

code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/projectile/beams.dm

damage lowered by two on all three, and firing speed lowered.

Nerfs the AEP7 and WATTZ pistol/magnetto

---

code/controllers/subsystem/research.dm
code/datums/components/remote_materials.dm
code/datums/materials/basemats.dm
code/game/objects/items/stacks/sheets/mineral.dm
code/game/objects/items/stacks/tiles/tile_mineral.dm
code/game/turfs/simulated/floor/mineral_floor.dm
code/modules/antagonists/abductor/equipment/abduction_gear.dm
code/modules/mining/ores_coins.dm
code/modules/research/designs/medical_designs.dm
code/modules/research/designs/misc_designs.dm
code/modules/research/designs/power_designs.dm
code/modules/research/designs/smelting_designs.dm
code/modules/research/designs/stock_parts_designs.dm
code/modules/research/designs/tool_designs.dm
code/modules/research/designs/weapon_designs.dm
code/modules/research/rdconsole.dm
code/modules/research/techweb/_techweb.dm
code/modules/research/techweb/nodes/alien_nodes.dm

Reverts ARF-SS13/coyote-bayou#609 to attempt to fix mining crashes

Revert "Research fixes and materials/research overhaul Part 1"

---

code/controllers/subsystem/research.dm
code/datums/components/remote_materials.dm
code/datums/materials/basemats.dm
code/game/objects/items/stacks/sheets/mineral.dm
code/game/objects/items/stacks/tiles/tile_mineral.dm
code/game/turfs/simulated/floor/mineral_floor.dm
code/modules/antagonists/abductor/equipment/abduction_gear.dm
code/modules/mining/ores_coins.dm
code/modules/research/designs/medical_designs.dm
code/modules/research/designs/misc_designs.dm
code/modules/research/designs/power_designs.dm
code/modules/research/designs/smelting_designs.dm
code/modules/research/designs/stock_parts_designs.dm
code/modules/research/designs/tool_designs.dm
code/modules/research/designs/weapon_designs.dm
code/modules/research/rdconsole.dm
code/modules/research/techweb/_techweb.dm
code/modules/research/techweb/nodes/alien_nodes.dm

Reverts ARF-SS13/coyote-bayou#909

Revert "Revert "Research fixes and materials/research overhaul Part 1""

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RedRiver.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm
code/modules/clothing/suits/arfsuits.dm

Also changed the circuit boards about in the mall.
Changed up the follower hospitals science are about a little. It's constantly adjusted each round. Eventually these changes will stick one week lmfao.
Fixes a deathclaw coat recipe.

Adds the food items to the map + Others!

---

code/modules/jobs/job_types/bos.dm

job slots from 0 to 1 on scribe
:cl:
fix: scribe
/:cl:

raises scribe job slots. oops

---

code/_globalvars/lists/maintenance_loot.dm
modular_coyote/eris/code/mods/mod_types.dm

Red paint makes bullets move faster? How? Why does it just make it shoot faster to? Guess people use red paint as lube in the fallout universe. 🤷

Removes the red paint

---

_maps/map_files/Pahrump-Sunset/RockSprings.dmm

Adds 2 barbie dreamhouses, a zealot compound, and a hidden church to Rockysprings. Is it mothman? Is it snurch? Who knows.
Also the citizens of Nash felt bad for the smelly people of Redwater and fixed their plumbing for them

Take me to snurch~

---

_maps/map_files/Pahrump-Sunset/RockSprings.dmm

Snurch 1, BoS 0
https://youtu.be/RrDt9a0q3P0
:cl:
/:cl:

BOS v. Snurch

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

fixes some stuff that got undone, poopy mapbot can die
:cl:
/:cl:

Some mappy chongles

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Thinking back on it...toooo unlorefriendly. High tech nanites only really fit in space settings.
Has a brainwashing machine, chair, cuffs, and lethal injection syringes now!

Nanite-B-Gone!

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
code/game/objects/effects/spawners/f13lootdrop.dm
code/game/objects/items/melee/f13onehanded.dm
code/modules/mob/living/simple_animal/friendly/drone/extra_drone_types.dm
code/modules/projectiles/guns/ballistic/automatic.dm

Adds more to BOS bunker in dungeon.dmm
changes loot tables a lil
Adds new drone subtype
Adds/changes stuff to loot-tables
Makes type-93 an AN-94-type beat instead of yet another 5.56 full auto (think that the OG f13 devs were running out of ideas?)
:cl:
add: see PR fopr full
/:cl:

bear package

---

code/game/objects/effects/spawners/f13lootdrop.dm

Blueprint gone from loot pool!

Gauss-B-Gone

---

_maps/templates/shelter_10.dmm
code/modules/mining/equipment/survival_pod.dm
code/modules/mining/shelters.dm

Fixes the capsules and prevents them from deleting upon click.

Vault-Tec Capsule Fixes

---

code/modules/projectiles/projectile/bullets/rifle.dm

Gauss slugs:
- Do 37 damage
- Fly through everything
- Do an extra 97 damage to most hostile mobs
- Knockback mobs
- Has 0.5 AP
Blender slugs:
- Can bounce up to 9 times
- Will kill you
- Only pierce mobs, windows, and doors.

Gauss changes

---

code/game/objects/effects/spawners/f13lootdrop.dm

Reverts ARF-SS13/coyote-bayou#935

Revert "Gauss-B-Gone"

---

code/__DEFINES/mobs.dm
code/__DEFINES/wounds.dm
code/datums/wounds/bleed.dm
code/game/objects/items/stacks/medical.dm
code/modules/mob/living/blood.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/surgery/bodyparts/_bodyparts.dm

Fixes some things:
- Bandages and sutures should apply and heal properly.
- Blood regen and wound healing shouldnt take you below hungry.
- Bandages and sutures will tell the owner when they arent healing brute/burn anymore.
- Bandages and sutures no longer spam you with damage text, only when they're destroyed.
- Disabled doctoring skill checks for bandages and sutures, pending a better implementation that actually works.
- Moved the bandage/suture examine texts out of the wound and to the actual examine proc.
- Bandages/sutures tell if they're covering a bleed wound.
- Fixed some other examine texts.
- Simplified some procs

Hottie fixes to bleeding (cus im a hottie)

---

code/game/objects/items/devices/scanners.dm

Fixes some stuff in the scanner, it'll report the right blood loss now.

Quick bloody hottiefix 2

---

code/modules/mob/living/simple_animal/hostile/f13/tunnelers.dm

no more formaldehyde lol
:cl:
/:cl:

blind one fix

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
code/game/objects/items/granters.dm
code/modules/jobs/job_types/followers.dm

Changes up the recharger pistol (who has it)
Adds the tribeam stun rifle to the map!
Adds a recipe for the tribeam stun rifle

Followers Changes!

---

code/__DEFINES/wounds.dm
code/game/objects/items/stacks/medical.dm
code/modules/surgery/bodyparts/_bodyparts.dm

Fixes limbs falling asleep and not processing bandage healing.
Bandages/sutures now heal over the course of their lifetime, not just a short while.
Bandages/sutures keep trying to apply to limbs that need them.
Nutrition helps with bandage/suture healing, if you're not hungry.

Bandage fixes 2

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

Went thru a bunch of terminals and added lore snippets to them.  Git rekt.  I guess.
:cl:
/:cl:

The terminaling Pt 1

---

code/_globalvars/lists/maintenance_loot.dm
code/modules/jobs/job_types/wasteland.dm

Stealthboys added to the loot pool, as well as one for a redwater resident role!

---

code/_globalvars/lists/maintenance_loot.dm
code/game/objects/effects/spawners/f13lootdrop.dm

The number is set as 1. You have a low chance of getting one from closing up a burrow now, making burrow hunting even more worthwhile!

Moves the Stealth boy to Bears garbagetomid loot pool!

---

_maps/map_files/Pahrump-Sunset/RockSprings.dmm

maps secret well into tribal village

---

_maps/map_files/Pahrump-Sunset/RockSprings.dmm

Reverts ARF-SS13/coyote-bayou#959

Revert "maps secret well into tribal village"

---

code/modules/mob/living/simple_animal/hostile/f13/chinese.dm

baby's first pr

---

code/modules/jobs/job_types/followers.dm

Been meaning to do this for a while but never got around to it, lmfao.
Adds two more slots!

More followers guard slots!

---

_maps/map_files/Pahrump-Sunset/RockSprings.dmm

yeah. adds it back into the same place as last time
:cl:
add: sacred well back in
/:cl:

maps sacred well back into tribal camp

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Same as the first, second the verse!
Also with the 60 min lock: Changes up a turret in a dungeon in the sewers. Now it wont cap the sentrybot roundstart.

60 min lock for chinese dungeon + minor edit to a mini dungeon

---

code/controllers/subsystem/research.dm
code/datums/components/remote_materials.dm
code/datums/materials/basemats.dm
code/game/objects/items/stacks/sheets/mineral.dm
code/game/objects/items/stacks/tiles/tile_mineral.dm
code/game/turfs/simulated/floor/mineral_floor.dm
code/modules/antagonists/abductor/equipment/abduction_gear.dm
code/modules/mining/ores_coins.dm
code/modules/research/designs/medical_designs.dm
code/modules/research/designs/misc_designs.dm
code/modules/research/designs/power_designs.dm
code/modules/research/designs/smelting_designs.dm
code/modules/research/designs/stock_parts_designs.dm
code/modules/research/designs/tool_designs.dm
code/modules/research/designs/weapon_designs.dm
code/modules/research/rdconsole.dm
code/modules/research/techweb/_techweb.dm
code/modules/research/techweb/nodes/alien_nodes.dm

Reverts ARF-SS13/coyote-bayou#910

Revert "Revert "Revert "Research fixes and materials/research overhaul Part 1"""

---

modular_citadel/code/modules/client/loadout/__donator.dm

Changed the admittedly snowflake kit to something fitting for a blue skull wolf.
Comes with a forget-me-not flower, fusion lighter, and trench knife.

Changes up Rising's kit!

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm

removes the mayhem in a bottle from the tunneler dungeon at beevee's request

mayhem begone

---

modular_citadel/code/modules/client/loadout/__donator.dm

Loadout kit locked to ckey Planetary!

Loadout kit for planetary

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm

Makes a few inaccessible areas actually inacessible: the supermutant behemoth dungeon and the upstairs of the military base is now surrounded by inaccessible rock
:cl:
/:cl:

blocks off some inaccessible areas

---

code/datums/components/crafting/recipes/recipes_misc.dm
code/game/objects/items/stacks/rods.dm
code/game/objects/items/stacks/sheets/sheet_types.dm
code/game/objects/items/stacks/stack.dm
code/game/objects/structures/lattice.dm
code/game/turfs/openspace/openspace.dm
code/modules/mob/inventory.dm

Building lattices on open space now require rods made from 5 sheets each of iron and prewar alloy, and 1 sheet each of plastic and bronze. The catwalk on top of that needs normal metal rods tho.
Also fixes the bug where the wrong things would stack with other wrong things, like improvised bandages and other bandages.

Fixes stacking bug and makes fortnighting more expensive

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Just as the tin says 🐺 
Lowered the chinese dungeon enter time to two hours instead of three!
Added advanced workbench back next to the cargo train.

Advanced workbench for the shopkeeper + Chinese dungeon time lowering!

---

code/game/objects/items/miscellaneous.dm
code/modules/jobs/job_types/followers.dm
modular_citadel/code/modules/client/loadout/hands.dm

Changed up the cybernetic delivery box for possible dungeon loot itemry. Added an esword option to it (intend to make the dungeon quite hard, but less so than the chinese dungeon)
Changed up the administrators surgery option. The medbeam gun will now be unremovable from their person once implanted. (you can still cut it out of the arm 😁)
Added two more delivery kit options! One of which you can take multiple times for increasing points cost for more plushie fuuuuun! YAY PLUSHIES!!!

Loadout options + touch-ups! (see description)

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

removes 3/4 hour timelocks from dungeons. adds 2nd floor to library.
:cl:
/:cl:

removes timelocks, adds library

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm

adds the library. actually. finally. aka adds a book binder and scanner cuz i forgot those argh
:cl:
/:cl:

actually adds the library

---

code/datums/looping_sounds/_looping_sound.dm
code/datums/looping_sounds/item_sounds.dm
code/datums/looping_sounds/machinery_sounds.dm
code/datums/looping_sounds/weather.dm
code/game/area/areas.dm

Microwaves should run properly, and wind should end when it should end!

Fixes soundloops

---

code/modules/vending/_vending.dm
code/modules/vending/medical.dm

This PR contains fixes for bugs encountered with item vendors as well as rebalances for items and prices contained in them.
:cl:
fix: Fixed premium items not charging the correct amount of money
tweak: Adds epinephrine back to the followers medical vendor.
tweak: Changes the default price on H&H Tools vendors from 5 caps to 10
/:cl:

Vendor pass, fixes and rebalancing.

---

code/__DEFINES/traits.dm
code/controllers/configuration/entries/game_options.dm
code/datums/components/crafting/recipes/recipes_primal.dm
code/datums/traits/good.dm
code/game/objects/items/granters.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/jobs/job_types/followers.dm
code/modules/jobs/job_types/khan.dm
code/modules/jobs/job_types/oasis.dm
code/modules/jobs/job_types/wasteland.dm
config/game_options.txt

The burned book will be removed, and in its place, you'll be given 3 extra quirk points!
Also, most of the quirks formerly granted by the book will have their price brought up to 3 points.
Also adds a guncrafting quirk that allows you to craft the stuff the tribal Technophilia trait thing did.

Burned book rework

---

code/datums/components/crafting/recipes/recipes_misc.dm

Aerial Support Girder (x10) makes Aerial Support Girder (x10)

Aerial Support Girder (x10) makes 10 Aerial Support Girders

---

code/datums/looping_sounds/machinery_sounds.dm

No more gaps in the VZHZHZHZHZHZH

Makes the microwave loop properly

---

code/datums/components/crafting/recipes/recipes_tailoring.dm
code/modules/clothing/gloves/f13gloves.dm
code/modules/clothing/shoes/f13.dm
code/modules/clothing/suits/arfsuits.dm
modular_citadel/code/modules/client/loadout/gloves.dm
modular_citadel/code/modules/client/loadout/shoes.dm

fixes super eggregious examples of armor being out-of-wack. highlights include raider combat armor actually inheriting values from mk2 combat armor. 
takes away plated gloves and shoes from loadout. makes them have very good armor
:cl:
/:cl:

armor rebalancing sorta

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
code/datums/looping_sounds/ambient_sounds.dm
code/modules/fallout/areas/area.dm

Caves & Tunnel Ambience
:cl:
/:cl:

Sound Overhaul Pt. 2.5

---

code/datums/components/footstep.dm
code/modules/mob/living/carbon/alien/humanoid/humanoid.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/simple_animal/hostile/alien.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/mob/living/simple_animal/slime/slime.dm

Players' footsteps are much quieter, and all footsteps should be audible from further away. Still quieter~

Enquiets foosteps

---

modular_citadel/code/modules/client/loadout/__donator.dm

Adds a loadout kit locked to ckey Sloaff!

Loadout kit - Sloaff

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

I put a gardening tool rack instead of normal rack to make it easier for gardeners to keep track in Nash. I also changed a tile in the clinic so that it will look nicer and match the other floor.
:cl:
add: Added Gardening Rack
del: Deleted Rack
fix: Fixed clinic map.
/:cl:

Update Pahrump-Sunset Cleanup

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Added a unique tier spawner to one locker, and a midhigh tier spawner in the other.
Adjusted one of the Mr. Gutsy's in the room. Minor boss for the goodies!
Fixes a minor mishap in the chinese dungeon. Probably wasn't needed but, hey....

Adjusts the Deathclaw Labs end point

---

interface/interface.dm
interface/skin.dmf

OOC Status Button in the top right of your screen!
:cl:
/:cl:

OOC Status Button

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/shuttles/cargo_pahrump.dmm
code/modules/cargo/exports/misc_export.dm

armalite, schmeisser, ranger, now all available to sell
changed cargo train to be more muh lore friendly
workbench in trader is now replaced with adv workbench. adv workbench in 009 tunnel now gone
:cl:
/:cl:

Misc shopkeep updates

---

code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/projectile/beams.dm

This should make it properly have the sprite it needs. Also gave it the good ol blue laser bolt for realsies.

Badland's Special Fix!

---

code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/research/designs/ammolathe_designs.dm

fifth or sixth 1v4 with an r82 has happened
merge, i am just poking at stuff gently rn
:cl:
/:cl:

auto changes

---

_maps/shuttles/cargo_pahrump.dmm

should... work...to make the shuttle not as wide/tall? look dude idk lmao
:cl:
/:cl:

shopkeeper fix maybe

---

_maps/shuttles/cargo_pahrump.dmm

Don't know why, don't know how- but for some reason, the cargo shuttle map ONLY works when it is in that VERY ULTRA-SPECIFIC configuration.
I'm at a loss. Not worth it.
:cl:
fix: revert cargo shuttle
/:cl:

reverts cargo_pahrump.dmm

---

_maps/map_files/generic/CentCom.dmm
code/modules/clothing/head/helmet.dm
code/modules/clothing/suits/arfsuits.dm
code/modules/clothing/suits/arfsuits_unused.dm
code/modules/food_and_drinks/drinks/drinks.dm
code/modules/jobs/job_types/wasteland.dm
code/modules/projectiles/guns/ballistic/pistol.dm
code/modules/projectiles/guns/energy/laser.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Me and tia were kind of dumbfounded it turned out this fast 😅 
Also fixed a bit of a mishap I did when making the worn pistol variant.
Loadout kit locked to ckey dameonowen.
Loadout kit locked to ckey pixelexip.
Edits to ckey kit for seermankhajiit00.
Edits the Captain's Flask name to Golden Flask. WHAT CAPTAIN?!
Adds armor to the preacher plate suit. It's light armor with an affinity towards melee specifically.

Nerfs and ckey kits...OHMY!

---

_maps/map_files/generic/CentCom.dmm
code/modules/clothing/head/f13head.dm
code/modules/clothing/suits/arfsuits.dm
code/modules/jobs/job_types/wasteland.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Note to self, check for a ***HELMET*** dm file. Don't use arfsuits.dm

Fixes the knight helmet

---

code/modules/projectiles/boxes_magazines/internal/revolver.dm

Fixes the 44 Magnum revolver having 7 shots
:cl:
tweak: Reduced the 44 Magnum to 6 shots instead of 7 and removed some errant code
/:cl:

Fixes 44 magnum to be 6 shots.

---

code/modules/jobs/job_types/followers.dm
code/modules/jobs/job_types/wasteland.dm
code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/projectiles/guns/energy/plasmaf13.dm
code/modules/projectiles/projectile/beams.dm
code/modules/projectiles/projectile/energy/tesla.dm

Big ol armor pen buff, with slight damage increases!

Autolaser stuff + Fuzlet's edit!

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm

Credit goes to sunset wasteland! I just did a few edits here and there.~

Mass fusion overhaul!

---

modular_citadel/code/modules/client/loadout/__donator.dm

Edits fuzlets first ckey kit upon request.

Loadout kit edit: Fuzlet!

---

code/datums/weather/weather.dm
code/datums/weather/weather_types/ash_storm.dm

Removes ash storms!
Sandstorms are fuckin opaque!

No more ash storms, also sandstorms actually reduce visibility

---

code/game/machinery/doors/door.dm
code/game/objects/items/prize_loot.dm

Lets lockpicks open doors, and break, and be tiny!
:cl:
/:cl:

Lockpickin' Games bby

---

code/_globalvars/lists/maintenance_loot.dm
code/game/objects/effects/spawners/f13lootdrop.dm
code/modules/projectiles/guns/ballistic/automatic.dm

Reduces the 22 uzi's rate of fire down to 200rpm, but makes it akimboable.
Trashpiles can drop most forms of improvised ammo.

Various gun and ammo loot changes

---

code/game/objects/effects/spawners/f13lootdrop.dm
code/modules/projectiles/guns/ballistic/automatic.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Adds a loadout box for me! Includes a sidewinder SMG and a few empty mags.
Also make the sidewinder spawn with a 15 round 9mm mag, instead of a 32 round one.

loadout kit for me! also some sidewinder changes

---

code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
code/datums/traits/good.dm
code/game/objects/items/granters.dm

exactly what the title says.
ranger is no longer roundstart, same w/ schmeisser, learned from gun n boolet part 2
:cl:
/:cl:

gunsmith fixes, recipe changes for ranger/schmit

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RedRiver.dmm

Also did some sliiiight buffs to elsewhere. Oh noooooooo.

No longer spooky month, so fixing the haunted mansion up!

---

code/modules/mob/living/emote.dm

P
Prototyping gendered audio emotes
:cl:
/:cl:

More emote noises

---

code/controllers/subsystem/ticker.dm

Fix my stupidity and actually get the timezone right for the round start.
Also, accelerate time back to 6x speed.
:cl:
tweak: Changed time in round again, and restored accelerated time
/:cl:

Do time things!

---

code/modules/jobs/access.dm

IDs (and anything with access... which is basically just IDs, not keys yet. NOT KEYS YET. NO NOT KEYS IM GONNA WORK ON THAT) that are either directly equipped to your mob, or inside an object directly equipped to your mob (in a box in your pocket, inside your suit, inside your hat, inside your backpack, but NOT inside of a box inside your backpack) will open doors they open.

IDs work pretty much anywhere

---

code/game/objects/items/cards_ids.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Loadout kit locked to ckey Darknova92. Comes with a custom choice item that he wanted added!

Loadout kit: Darknova

---

code/game/objects/structures/flora.dm
code/modules/mob/living/emote.dm

https://youtu.be/BXNwtEQHTDE)
:cl:
/:cl:

Watch out, trees suck.

---

code/datums/components/crafting/recipes/recipes_forge.dm

Because I like making Bear angy
:cl:
/:cl:

Sappers to steel in recipe

---

code/__DEFINES/mobs.dm
code/datums/traits/negative.dm

max 4 positive quirks

---

code/datums/traits/negative.dm

Yeah the negative ones are -1.

all negative quirks are -1

---

code/_globalvars/lists/maintenance_loot.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Fixes up the two locked boxed + loadout error fix

---

config/game_options.txt

I'm dumb as fuck lmao
:cl:
/:cl:

lmfao - quirks to 5 points

---

code/modules/client/preferences_savefile.dm

Made max quirks actually go up to 4 and not 3.

One character bugfix

---

code/__DEFINES/loadout.dm
code/modules/client/preferences.dm

Now has three sections you can pick from instead of one long ass fecking list.
:cl:
/:cl:

Ported modern quirk layout

---

code/game/turfs/simulated/minerals.dm

Temporally removes minerals from mining
:cl:
/:cl:

Temp removes minerals

---

code/controllers/subsystem/processing/quirks.dm
code/datums/traits/negative.dm
modular_citadel/code/modules/client/loadout/glasses.dm

Adds two variants of Nearsighted, with and without glasses as well as mega nearsighted.
Also makes sure you can't select all three, of course.
:cl:
/:cl:

Quirks Scaling - Nearsighted

---

code/datums/traits/negative.dm

No Glasses desc

---

code/__DEFINES/traits.dm
code/controllers/subsystem/processing/quirks.dm
code/datums/traits/good.dm
code/datums/traits/negative.dm

Variates the Punching Quirks.
Tweaks one positive quirk and adds another.
Fists of Iron (Iron Fist previously): Unchanged
Fists of Steel: Punching equivalent to Big Leagues
Adds a Negative Quirk
Fists of Noodle: Removes all punching damage
:cl:
/:cl:

Fists of [THING] Quirk Variation

---

code/__DEFINES/traits.dm
code/_onclick/item_attack.dm
code/controllers/subsystem/processing/quirks.dm
code/datums/traits/good.dm

Adds Little Leagues, a lower cost and damage version of Big Leagues.  Soon with negative variation.
:cl:
/:cl:

Little Leagues

---

code/_onclick/item_attack.dm
code/controllers/subsystem/processing/quirks.dm
code/datums/traits/negative.dm

Flipsides of Big and Little Leagues.
Gentle -5 Melee damage, 1pt
Wimpy -10 Melee damage, 3pt
:cl:
/:cl:

Gentle and Wimpy Quirks

---

code/__DEFINES/traits.dm
code/controllers/subsystem/processing/quirks.dm
code/datums/traits/good.dm
code/datums/traits/negative.dm

Renames lifegiver and creates variants.
Lifegiver -> Health -Tough
Health - Tough: +10 Health, 1pt
Health - Tougher: +20 Health, 3pt
Health - Flimsy: -10 Health, -1pt
Health - Very Flimsy: -20 Health, -3pt
:cl:
/:cl:

Lifegiver Rename and Additions

---

code/datums/brain_damage/severe.dm
code/datums/traits/negative.dm

No longer fecking dying from being alone, but boy howdy do you still not have an overall good time of it lol
:cl:
/:cl:

Monophobia Nerf

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/_globalvars/lists/maintenance_loot.dm
code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
code/game/objects/items/granters.dm
code/modules/projectiles/guns/mods/mods.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Loadout kit locked to ckey ZeroNetalpha
Changes to darknova's and sloafs ckey kit.
Lockbox change ups for the medicine lockbox!
Adds some special blueprint potential in the army depot homes/in the administative offices!

Loadout and lockbox stuff!

---

code/datums/brain_damage/severe.dm
code/modules/keybindings/keybind/movement.dm
code/modules/mob/living/living_movement.dm
code/modules/mob/mob.dm
code/modules/mob/mob_defines.dm

Adds Splurts Pixel Tilting & fixes a problem lol
Players will need to bind it tho.
:cl:
/:cl:

Pixel Tilting

---

code/__DEFINES/mobs.dm
code/datums/components/storage/concrete/boxes.dm
code/datums/traits/negative.dm
code/game/objects/items/storage/bags.dm
code/game/objects/items/storage/fancy.dm
code/modules/mob/living/blood.dm

Might fix people getting permafucked by stamina after getting damaged
Casing bags straighten out the inserted bullets so they dont look awful in the inventory
Cigarette packs no longer open the box itself when you altclick it, and will try to pull out an inserted lighter if one's in there
Nutrition can regenerate blood to the max.
Epi prevents you from going into the lowest level of bloodloss, instead of just preventing you from dying
Masked mook also counts all masks, except for cigarettes.

Unatomic change PR thing

---

code/__DEFINES/armor.dm
code/__DEFINES/combat.dm
code/__DEFINES/inventory.dm
code/game/objects/items/stealthboy.dm
code/game/objects/structures/ladders.dm
code/modules/mob/living/living_defense.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/guns/ballistic.dm
code/modules/projectiles/guns/ballistic/revolver.dm
code/modules/projectiles/guns/ballistic/rifle.dm
code/modules/projectiles/guns/ballistic/shotgun.dm
code/modules/projectiles/projectile.dm

Rubbers will do a bit less damage and actually consider armor.
Most revolvers will be a size smaller, cus honestly they could use some love.
Ladders should no longer runtime.
If you don't have the rifleman perk, autorecocking a shotgun/rifle by clicking will make it take longer to fire the next shot. Manually recocking the gun by using it in hand will make it fire faster.
Tactical reloads will try and put the magazine that used to be in the gun into your hand.
neck holsters hold 7 things in them instead of 3.

Another unatomized change pile

---

code/modules/projectiles/projectile/bullets/rifle.dm

Gauss shot should reduce its damage properly per thing hit.

Gauss fixes

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
code/game/objects/items/stacks/sheets/mineral.dm
code/modules/vending/matvend.dm
fortune13.dme

followers can now buy minerals
:cl:
/:cl:

adds vending machine to followers basement + custom cost to mineral sheets

---

code/datums/traits/negative.dm

I guess you can say its bad, idk man industrial society or something
:cl:
/:cl:

Oops, luddite bad

---

code/datums/traits/negative.dm

Me big dumb

---

code/controllers/subsystem/processing/quirks.dm

Sleeping on these quirks

---

modular_citadel/code/modules/client/loadout/__donator.dm

Loadout kit locked to Ckey tk420634 (number three)
Loadout kit locked to CKey ZeroNetAlpha (number two)

Two loadout kit updates!

---

code/__DEFINES/vote.dm

we do a lil shitting
:cl:
/:cl:

hahaheehoohoo

---

code/controllers/subsystem/processing/quirks.dm

Quirk Fixes

---

code/datums/traits/good.dm

Yeah, 14 is way too much.  10 should be good?  Maybe even 8.  We'll see.
:cl:
/:cl:

Deadeye Adjustment

---

code/modules/projectiles/guns/ballistic/rifle.dm
code/modules/projectiles/guns/ballistic/shotgun.dm

Autococking is done only if you have rifleman.

rifleman autocock

---

code/datums/traits/good.dm

Adds Master Rifleman Quirk
:cl:
/:cl:

Rifleman Quirk

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Beefs up the mass fusion underground. You want good loot? Gotta work for it. Have fun! Better bring a buddy.
Adds a few more loot boxes for lockpicking. 
Removes the one strong glowing one in the hospital basement. No thanks, I'm not a masochist!

Let's make this a wee bit harder! (See description)

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
code/game/objects/items/stacks/sheets/mineral.dm
code/modules/vending/matvend.dm

decreases prices in vendor, but **does not** increase maximum avail mats
also adds some more clutter* to bottom floor
*trash piles, blud, more mobs, some stimmies (wow!!)
:cl:
/:cl:

followers hospital bottom floor and mat-vendor changes

---

modular_coyote/code/modules/examine_images.dm

Yea this is a BYOND issue here treating the save data as a file instead of text.
pain.
I'll work on a sound solution later. For now, the classic Grem'Botch'Job

Fixes the character save files not loading the image.

---

code/datums/mood_events/generic_negative_events.dm
code/datums/mood_events/generic_positive_events.dm
code/datums/traits/good.dm

Moods adjusted to be carry more weight and last longer to match our longer round time and desire to add character selfcare.
:cl:
/:cl:

Mood Adjustments

---

code/datums/traits/good.dm

Needs redoing at a base level, lots of unintended effects.
:cl:
/:cl:

Thick Skin Rework

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/modules/fallout/obj/decals.dm
code/modules/power/singularity/collector.dm

Adds actual power to Mass Fusion.
Adjusts the followers starting battery power to encourage using the solar panels.
Changes a few areas to allow for different zones to be powered differently.

Mass Fusion Upgrade

---

code/__DEFINES/combat.dm
code/datums/components/pellet_cloud.dm
code/modules/projectiles/ammunition/_firing.dm
code/modules/projectiles/boxes_magazines/external/rifle.dm
code/modules/projectiles/boxes_magazines/external/shotgun.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/projectile.dm
modular_coyote/eris/code/living_recoil.dm

Makes the accuracy perks work properly.
Reworks accuracy mechanics to be more accurate at low recoil buildup, and less at more recoil.
Shotgun spread is fixed, but offset by your inaccuracy.
Guns and bullets can actually affect the shot's final accuracy, so bad ammo is less accurate, and better is more accurate.

accurady stuff

---

code/modules/surgery/healing.dm

Used to be you needed the mixed tend wound thing to do it. this was a poor decision, so now every tend wounds surgery heals bleeding.
Also rewords the action text a bit, and makes failures a bit more bloody.

Fixes tend wounds not working on bleeds

---

code/modules/mob/living/simple_animal/hostile/f13/insects.dm

tweaks description of ant to make it clearer u can butcher it for stuff
:cl:
/:cl:

giant ant desc tweak

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm

Removes teh bones

---

code/__DEFINES/traits.dm
code/datums/components/crafting/recipes/recipes_medicine.dm
code/modules/fallout/reagents/medicines.dm
code/modules/hydroponics/grown/punga.dm
code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
code/modules/reagents/chemistry/holder.dm
code/modules/reagents/chemistry/reagents.dm
code/modules/reagents/chemistry/reagents/medicine_reagents.dm
code/modules/reagents/reagent_containers/pill.dm

Adds fiery purgative! Intense tox / rad heals, but it makes you violently ill and vomit all over the place. You'll need something to eat afterwards.
Changes punga! Juices into potassium iodide, distills into vodka, and contains punga juice. Punga juice reduces rads and tox, slowly, but surely.
Adds craftable antitoxin! Craft nightstalker and radscorpin meat together, or broc + xander + datura. Heals around 25 tox over time, per dose.

BottoMed additions

---

code/__DEFINES/armor.dm
code/modules/mob/living/simple_animal/hostile/f13/insects.dm

1. ants no longer decompose
2. change desc
3. change armor
:cl:
/:cl:

ant updates

---

code/controllers/subsystem/nightcycle.dm

LATE MORNING and LATE AFTERNOON
to onramp/offramp for daytime
:cl:
/:cl:

[WIP] adds two new times of day

---

tgui/packages/tgui-panel/chat/model.js

Forces LOOC to be visible at all times. You cannot escape LOOC. You will read my local OOC messages. Thank you.

There is no escape from LOOC

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/modules/projectiles/guns/energy/dueling.dm

Adds two boxes in the bar backroom on a new table near the bartender spawn area.

Dueling Guns for bar!

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm
code/game/machinery/doors/unpowered.dm
code/modules/mob/living/simple_animal/hostile/f13/raider.dm

followers matvendor now in garage
ants in nash z north of followers
ants in redwaterz behind booze licker shack 
:cl:
/:cl:

holy FUCK there are ANTS in my PANTS???

---

modular_citadel/code/modules/client/loadout/__donator.dm

Loadout kit edit for ckey Fuzlet! Adds carpet.

Loadout kit edit: Fuzlet

---

code/__DEFINES/combat.dm
code/__DEFINES/mobs.dm
code/__DEFINES/sound.dm
code/_onclick/drag_drop.dm
code/modules/mob/living/living_defense.dm
code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
code/modules/mob/mob_defines.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/projectile.dm

Reduces spam so that hopefully automatic guns wont lag me so fucking much.

Gun message antispam optimizations

---

code/datums/components/pellet_cloud.dm
code/modules/projectiles/ammunition/_firing.dm

Spread-fire guns all fired in a line if you had insane aim. That was a bug. now, insane aim tightens shotgun spead by 50%.

Fixes shotgun lasers

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm

Id's are set up properly for the shutters. I'd be surprised if this didn't work lmfao.
Anyhow, basically changes up the arena a bit. Makes it more deadly, lockdown, whatnot.
Also buffs bubblegums health and damage a bit.

Bubblegum Change up!

---

code/modules/projectiles/guns/ballistic/rifle.dm

bolt actions now do a bit more dmg

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
modular_citadel/code/modules/client/loadout/__donator.dm

Loadout kit locked to ckey Aerodynamique. (3rd one!)
Slightly nerfs the difficulty of the mass fusion basement.

Loadout Kit + Mass fusion basement fix up

---

code/datums/emotes.dm
code/game/say.dm
code/modules/mob/living/emote.dm
code/modules/mob/mob.dm
code/modules/mob/say_vr.dm

Co-authored-by: Tk420634 <Tk420634@users.noreply.github.com>
If you put @ in your *me or *subtle, it'll replace it with your character's name!

Adds player narrate -- with tokens!

---

code/__DEFINES/combat.dm
code/game/objects/effects/spawners/f13lootdrop.dm
code/modules/projectiles/guns/ballistic/automatic.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Adds a worn gun

---

code/game/turfs/simulated/minerals.dm

Reverts ARF-SS13/coyote-bayou#1095

Revert "Temp removes minerals"

---

code/_onclick/item_attack.dm
code/modules/antagonists/devil/true_devil/_true_devil.dm
code/modules/mob/living/carbon/carbon_defense.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/mob/living/silicon/ai/ai_defense.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/curse_blob.dm

Instead of doing funky things with force manipulation, damage modifier traits now just submit a var of how much to modify the attack damage.
Should work a lot better and simpler now.

Fixes damage modifiers

---

code/modules/projectiles/boxes_magazines/external/pistol.dm
code/modules/projectiles/guns/ballistic/pistol.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Give the doctor dragon rubber rounds so she doesn't need to pull them out of people when she's done.
:cl:
tweak: tweaked a loadout
/:cl:

Give Dr. Drgn rubber rounds to make her job easier

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

Restores a building to Nash. Adds the second story building I had made. Adds Big Red machines around Nash

Ody Seeks Redemption

---

.github/workflows/ci_suite.yml
modular_coyote/code/modules/mapping/turf_patches.dm
modular_coyote/code/modules/say/soundbubbles.dm

If it doesn't, literally ban me from the server for being so stupid beyond believe.
Also attempts to make a way to stop lots of outdoor turfs used in the map to not be processed under the wrong section of auxmos, I don't understand functional programming but there's a different state machine for handling atmos code for dirty turfs. :c

So uh yeah this should fix speech bubbles for suresies.

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Patches mistakes from Racoon Sex Dungeon PR

bug patch 1

---

code/game/turfs/turf.dm

If an area is outdoors, its turfs will get sunlight, even if it isnt on the base level!

makes the sun work on upper levels

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
code/__DEFINES/combat.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Adds a request to Lucine's kit!
Fixes a spelling error in seermans kit!
Adds some stuff to Nay's kit!
Edits nirzaks loadout upon request!
Edits the ids myself and darknova start with!
Bob says hi. He thinks your face is tasty.

Loadout kit fix ups! + Extras Teehee

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm

Cleans up the railing in Upper Nash as well as adds some roofing so the guard tower can see south.
:cl:
tweak: tweaked some Nash sightlines
/:cl:

Minor changes to upper Nash

---

modular_citadel/code/modules/client/loadout/__donator.dm

WOOOOOOF (Loadout stuff)

---

code/modules/mob/living/carbon/emote.dm
code/modules/mob/living/emote.dm

Fixes a goofy problem, makes people giggle correctly.

Fixes gendered emotes using the gender of the last person to use it

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Removes the rnd console and lathe that makes circuit boards. I didn't realize the thing could and only now became an issue.

A mistake fixed

---

code/datums/components/waddling.dm
code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm
code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
code/modules/mob/living/simple_animal/hostile/f13/insects.dm
code/modules/mob/living/simple_animal/hostile/f13/mirelurks.dm
code/modules/mob/living/simple_animal/hostile/f13/raider.dm
code/modules/mob/living/simple_animal/hostile/f13/tunnelers.dm
code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
code/modules/mob/living/simple_animal/hostile/f13/wolf.dm
code/modules/mob/mob.dm
code/modules/mob/mob_defines.dm
fortune13.dme

Testing Waddling on mobs
:cl:
/:cl:

Waddle Babby

---

code/modules/projectiles/guns/ballistic/pistol.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Don't make late night prs kids. Fixed my own oof. 
Adds a third sig type, which is worn. Reverts trusty's nerf. Adds the nerf to the new worn type.

Lazyness fix! Now with 100% less lazyness!

---

code/modules/reagents/reagent_containers/pill.dm

Fixes firey purgtive being a red flashing ERROR

---

code/__DEFINES/combat.dm
code/__DEFINES/sound.dm
code/_globalvars/lists/maintenance_loot.dm
code/game/objects/effects/spawners/f13lootdrop.dm
code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/projectiles/guns/ballistic/minigun.dm
code/modules/projectiles/guns/ballistic/pistol.dm
code/modules/projectiles/guns/ballistic/shotgun.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/mods/mods.dm
modular_citadel/code/modules/client/loadout/__donator.dm
modular_coyote/code/game/objects/structures/sacredwell.dm
modular_coyote/eris/code/mods/mod_types.dm

Most automatic guns shoot considerably slower. However, most guns that had their damage reduced cus they were fuckin bullet hoses now do closer to normal damage. Also the lower firing rate allows them to stay on target a bit better.
Also, red paint is back! It just does a flat 20% increase to fire rate and that's it.

Autofire Changes

---

code/game/objects/items/devices/scanners.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/carbon/human/human_defense.dm
code/modules/surgery/bodyparts/_bodyparts.dm

Medical anal-izers show your wound damage even if you're at full health. Also moves around the labels on the individual limbs, cus you cant get tox/oxy on your limbs.
Double-examining someone shows a readout of damage on their limbs, as well as a way to remove their bandages.
You can remove your own bandages and sutures through checking your body.

Scanner fixes and bandge removal stuff

---

code/modules/projectiles/ammunition/energy/plasma.dm

I forgot to change *one thing when copying/editting files*

Fixes the New plasma gun!

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/__DEFINES/armor.dm
code/__DEFINES/combat.dm
code/datums/components/crafting/recipes/recipes_medicine.dm
code/game/objects/items/miscellaneous.dm
code/modules/clothing/suits/arfsuits.dm
code/modules/clothing/suits/utility.dm
code/modules/fallout/obj/structures/mob_spawners.dm
code/modules/fallout/reagents/drinks.dm
code/modules/jobs/job_types/oasis.dm
code/modules/projectiles/boxes_magazines/internal/shotgun.dm
code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/projectiles/guns/ballistic/pistol.dm
code/modules/projectiles/guns/ballistic/revolver.dm
code/modules/projectiles/guns/ballistic/shotgun.dm
code/modules/projectiles/guns/hoboguns.dm
code/modules/reagents/reagent_containers/glass.dm
code/modules/research/designs/autolathe_designs.dm
code/modules/research/designs/autolathe_desings/autolathe_designs_tcomms_and_misc.dm
code/modules/vending/bigredvendor.dm

Fuzzy Fixes

---

modular_citadel/code/modules/client/loadout/__donator.dm

Adds a few requested items to ckey Fuzlet.
Adds the worn sidewinder to ckey Risingstarslash.

Fuzlet and Risingstar's Loadout kit edits!

---

code/modules/projectiles/guns/ballistic/automatic.dm

forgot to make it so it has its own fire modes. Aka none at all.
Hurray for four guns in a trenchcoat!

Worn Multi caliber smg fix

---

code/_globalvars/lists/maintenance_loot.dm

Removes a missed revolver template!

---

code/__DEFINES/armor.dm

these bois way too stromk to be hitting you with hellnibbles
:cl:
/:cl:

Halfing ant armor

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm

No more sneaking into the clinic
https://gyazo.com/b4c9bb66dd769629c35c464152546d37
:cl:
/:cl:

Mall-to-clinic Needs Raid Perms now

---

code/__DEFINES/preferences.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/client/preferences_toggles.dm
modular_coyote/eris/code/dynamic_cursor.dm
modular_coyote/eris/code/living_recoil.dm

Makes the gun cursor able to be toggled in preferences.
Also reduces how frequently recoil tries to update itself. Recoil reduction has been tweaked accordingly.

Toggleable gun cursor pref

---

code/datums/mood_events/generic_positive_events.dm
code/game/objects/items/devices/PDA/PDA.dm
code/game/objects/items/grenades/grenade.dm
code/modules/fallout/obj/decals.dm
code/modules/food_and_drinks/food/snacks/dough.dm
code/modules/mob/living/simple_animal/hostile/f13/centaur.dm
code/modules/mob/living/simple_animal/hostile/f13/chinese.dm
code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
code/modules/mob/living/simple_animal/hostile/f13/insects.dm

PDAs
Grenades
Radpuddles
Some doughs
Centaurs
Chinese Ghouls
Deathclaws
Eyesbots
Ghouls
Insects
Now all have lick flavors.  Why would you lick them?  Fuck me running if I know.
:cl:
/:cl:

More lick flavors

---

code/datums/components/crafting/recipes/recipes_explosives.dm
code/datums/traits/good.dm
code/game/objects/items/grenades/ghettobomb.dm
code/game/objects/items/grenades/grenade.dm

Firebombs, molotovs, and coffeebombs will prime themselves if shot, and explode if caught in an explosion. You can chain explosions together this way.
Molotovs will actually work. They'll spray fire based on how what and how much of what's in there. Currently, only a few blatantly flammable things work in there. If you add blackpowder, it'll also cause a minor explosion.
Firebombs and coffeebombs will be craftable using scrap parts (metal, circuits, etc) in place of their typical components (flasks, coffeepots, etc). Scrap recipes will be a bit more expensive though.
The explosive crafting perk will let you craft more advanced explosives, including pulse grenades.
The coffeepot bomb makes a sound when activated.

Explosives update

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
code/modules/jobs/job_types/followers.dm
code/modules/mining/machine_vending.dm
code/modules/projectiles/guns/ballistic/pistol.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Adds loadout kit locked to ckey Sloaff! (3rd one)
Adds loadout kit locked to ckey Tonyburritos!
Adds some things to an existing kit. Yay nuka cola!

Loadout Things!

---

code/__DEFINES/traits.dm
code/datums/traits/good.dm
code/game/objects/items/granters.dm

Adds recipes to former tribal

---

modular_citadel/code/modules/client/loadout/__donator.dm

Loadout kit locked to ckey tonyburritos (2nd one!)

Loadout kit: Tony

---

modular_coyote/eris/code/living_recoil.dm

Returns recoil to working properly.

recoil fix

---

code/modules/mob/living/carbon/human/species_types/synthliz.dm

it's pronounced an-thropo-morph
:cl:
/:cl:

Synthlizard can have wings

---

modular_citadel/code/modules/client/loadout/__donator.dm

Misreading on my part does this. Drats.

Fixes Nay's kit!

---

code/game/objects/effects/spawners/f13lootdrop.dm
code/game/objects/items/melee/f13powerfist.dm
code/game/objects/structures/crates_lockers/closets/secure/medical.dm
code/modules/research/designs/mining_designs.dm
modular_citadel/code/modules/client/loadout/__donator.dm

The damage should be less than a normal power fist. 15 force as opposed to a regulars 22. Perfect replacement pseudo weak melee weapon/pickaxe!
Buffed the speed of the drill slightly, cause it was like using an iron or silver. Should now be slightly slower than a diamond drill, but still only one tile at a time.
Yeets the followers headset in the small clinic up north. Just ask the followers for their comms if you really want that, not find a magical loot thing lol

Removes Sonic Jackhammer, replaces with Mole Miner

---

code/modules/research/designs/mining_designs.dm
code/modules/research/techweb/nodes/tools_nodes.dm

Fixes the mole miner not showing up in RnD

---

code/modules/projectiles/guns/ballistic/pistol.dm
code/modules/projectiles/guns/ballistic/revolver.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Adds in a fancy gun for Fuzzy.
Also lowers the firing rate on some turbofucked guns.
Also makes the detective 38 randomly misfire if loaded with 357. Still fires them just fine, just it might bite you.

Adds a fuzzy gun, and tweaks some guns

---

code/modules/mob/living/simple_animal/friendly/fox.dm
code/modules/projectiles/guns/ballistic/launchers.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Adds the worlds worst rocket launcher

---

code/modules/projectiles/ammunition/energy/laser.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/projectile/beams.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Worn Badlands special for Four fangs!

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Mappin fixes

---

code/__DEFINES/radio.dm
code/datums/traits/negative.dm
code/game/objects/effects/landmarks.dm
code/game/objects/items/devices/radio/encryptionkey.dm
code/game/objects/items/devices/radio/headset.dm
code/modules/clothing/outfits/vr.dm
code/modules/jobs/job_types/followers.dm
code/modules/jobs/job_types/oasis.dm
code/modules/jobs/jobs.dm
tgui/packages/tgui-panel/styles/goon/chat-dark.scss

Renamed follower jobs to town stuff.
Changed their headsets to be town + medical.
Made nash radio pink.

Changed up follower jobtitles, also their headsets

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Map fixings

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Lots of changes and fixes.
Adds a Graveyard.
Opens the workshop a bit.
Removes the well from the Tribal farm and adds a sink instead. Adds a shower to the tribal bath house.
Adds some pots and seeds to the bar.
Moves a house onto another house temporarily.
Gives Tribals a lot of lanterns.
:cl:
fix: Fixes Nash up some more.
/:cl:

More fixes to Nash

---

code/modules/jobs/job_types/tribals.dm

Gives all tribals their language, crafting bench and recipies back.
Gives Hunter and Head Hunter Trapper.
Gives Surgery to Shaman
:cl:
balance: Tribal starter perks added.
/:cl:

Adds some base traits back to all tribals.

---

code/modules/jobs/job_types/wasteland.dm

Overboss Off Toggle

---

code/game/objects/items/storage/firstaid.dm
code/game/objects/items/storage/survivalkit.dm
code/modules/reagents/reagent_containers/bottle.dm
code/modules/reagents/reagent_containers/hypospray.dm
code/modules/reagents/reagent_containers/syringes.dm
code/modules/research/designs/autolathe_desings/autolathe_designs_medical_and_dinnerware.dm

Adds charcoal to the ancient medkit and baseline survival kit.
Adds one antivenom vial to the tribal survival kit.
Adds a Sanguirite syringe to the town doctors pouch kit! Let's raise more awareness of this wonderdrug!
Changes what's in an ancient medkit, making them more widespread to treat all manner of injuries/ailments!
Hypospray mk.II is now printable from an autolathe!

Medical Supply Edits!

---

code/modules/surgery/healing.dm

>You attempt to patch some of Hope Prevatt's b, r, u, i, s, e and s.
**X**
>You attempt to patch some of Hope Prevatt's bruises.
**O**
:cl:
fix: fixed surgery wound type text output
/:cl:

Fix surgery wound type text output

---

code/modules/jobs/job_types/oasis.dm

1984 1984 1984 1984 1984 1984 1984 1984 1984 1984 1984 1984 1984
:cl:
/:cl:

removes premium gun from trade worker since we're just adding a boss role for em and there's like 5 of em

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Snail Wiggling the Map.
:cl:
/:cl:

Map Sniggling

---

code/modules/projectiles/ammunition/_firing.dm
code/modules/projectiles/boxes_magazines/internal/revolver.dm
code/modules/projectiles/guns/ballistic/pistol.dm
code/modules/projectiles/guns/hoboguns.dm
code/modules/projectiles/projectile.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Replaces the silly launcher with an unbelievably shitty pipegun that shoots anything. Poorly.
Makes fuzzy's guns less cool and not autoeject empty mags.

Fuzzy gun stuff and romckit launcher thing

---

code/datums/components/crafting/recipes/recipes_medicine.dm
code/datums/traits/good.dm
code/game/objects/items/granters.dm
code/modules/jobs/job_types/tribals.dm
code/modules/jobs/job_types/wasteland.dm

Requires high end botany to successfully do, but these are well worth it.
Each bottle has 1 units, thus one usage per making.

Craftable Red, Blue, and Green potions!

---

code/modules/projectiles/guns/ballistic/pistol.dm

i whoopsed on the fuzzy gun

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Check the mapping channel in dev chatter for the various changes. Many pictures. Tl'dr:
Added the ability to walk along the nash wall starting from the north (to get to all the watchtowers).
Fixed up the doors and one room in the tribal upstairs area.
Added a kitchen and kitchen storage to the bar.
Added a senior doctor bedroom and meeting room for the nash doctor union.
Added a spawn point downstairs for all of the nash doctors.

Various nash quality of life improvements!

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
modular_citadel/code/modules/client/loadout/__donator.dm

Should fix that ladder 100%.
Also fixes cylphies uniform for her kit.

Accidently capitalized a letter on the ladder

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Also fixes up the Tribal botanical garden to be more 'clean'.
Here's some images of the changes.
There is also a glass ceiling above this garden.
:cl:
add: Added some soil plots to the front of Nash.
/:cl:

Adds some soil plots near the front entrance to Nash.

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Also watchtower extra ladders
:cl:
/:cl:

Start of underground Nash

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

Move Snuardian Snawn

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

:cl:
add: Adds a Sheriff's Office to the top of the Jailhouse.
/:cl:

Adds a Sheriff's Office

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm

Hard rock wall error and switched out the op ppsh for the balanced one!

Minor fix ups for the chinese dungeon!

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm

Oops.
:cl:
fix: Makes a building actually a building.
/:cl:

Makes the Sheriff's office an actual building.

---

code/modules/projectiles/guns/hoboguns.dm

Tox's gun should actually show up now. For real this time.

fixes the silly launcher, at last

---

code/datums/components/riding.dm
code/game/objects/structures/stairs.dm
code/modules/mob/living/simple_animal/friendly/farm_animals.dm

Dead brahmin can no longer be ridden. They also drop all their stuff when they die.

Dead brahmin arent ridable anymore

---

code/datums/components/crafting/recipes/recipes_medicine.dm

Changes the recipes from tools = list(TOOL_WORKBENCH) to tools = list(TOOL_ALCHEMY_TABLE)
(All except for antivenom with meat, I don't want you to be forced to have an alchemy bench for that.)
:cl:
tweak: tweaked a recipe tools from workbench, to alchemy table.
/:cl:

Changes tribal meds to Alchemy Table

---

code/game/objects/items/storage/firstaid.dm
code/modules/reagents/reagent_containers/pill.dm
modular_citadel/code/modules/client/loadout/__donator.dm

GIves a busty dog her busty meds.
yes i know its a lot

Adds fireclaw787's loadout item

---

modular_coyote/code/game/objects/structures/sacredwell.dm

Removed the silver bow, broken sprite tribal armour and added the light armour and light cloak.
:cl:
add: Added light armour and cloak to the well.
del: Removed silver bow and broken sprite armour.
/:cl:

Fixing a few wonky well items.

---

code/game/objects/items/loadout_beacons.dm
code/modules/projectiles/guns/ballistic/revolver.dm

Makes the 22 revolver actually in 22

Fixes the 22 revolver

---

modular_citadel/code/modules/client/loadout/__donator.dm

Loadout kit locked to ckey ImBubbl101.
Changes both fuzlet and risingstarslash's kit items.

Loadout kit additions

---

modular_citadel/code/modules/client/loadout/__donator.dm

Changes up fuzlet's second kit upon request.

Fuzzy kit edit

---

code/_globalvars/lists/maintenance_loot.dm
code/game/objects/effects/spawners/bundle.dm
code/modules/fallout/obj/trash_stack.dm
code/modules/mob/living/simple_animal/hostile/regalrat.dm

Rats, rats, this is the rats.
:cl:
/:cl:

Setting rats up to be more interesting, and used!

---

code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
code/game/objects/items/granters.dm
code/game/objects/items/loadout_beacons.dm
code/modules/projectiles/boxes_magazines/internal/revolver.dm
code/modules/projectiles/guns/ballistic/revolver.dm

Changes the .223 pistol to .308, so its babies first BEEG PEESTOL
:cl:
/:cl:

.223 Pistol evolving to .308 Pistol

---

code/modules/hydroponics/grown/yucca.dm

Yucca Tweaked

---

code/modules/mob/living/simple_animal/hostile/f13/raider.dm

Makes raiders butcherable for some parts
Makes SMG raider bosses a little more difficult (via randomized movement)
:cl:
/:cl:

Raider Update

---

code/datums/components/crafting/recipes/recipes_medicine.dm
code/modules/jobs/job_types/tribals.dm

Give SB shaman bitters
:cl:
/:cl:

Shaman Bitters

---

code/modules/reagents/reagent_containers/hypospray.dm

Makes Med-x drawable

---

code/modules/projectiles/guns/ballistic/bow.dm
code/modules/projectiles/guns/ballistic/rifle.dm

In theory should add scopes to the AMR and crossbow.
:cl:
/:cl:

Scopes Added to two weapons

---

code/game/objects/items/storage/backpack.dm

why this bitch b u l k y
:cl:
/:cl:

Smuggy Satchel to Normal

---

code/modules/projectiles/boxes_magazines/ammo_boxes.dm
code/modules/research/designs/ammolathe_designs.dm

Stripper clips and speedloaders

---

code/modules/jobs/job_types/followers.dm

I guess we'll pay you people.
:cl:
/:cl:

Clinic Pay

---

code/modules/power/cell.dm

MF and ECP to small

---

code/modules/mob/living/simple_animal/animal_defense.dm

Increases damage to mobs from bombs

---

code/datums/components/crafting/recipes/recipes_tailoring.dm

Culls plates that you couldn't make from the recipe list

---

code/modules/projectiles/guns/ballistic/automatic.dm

Akimbo .22 Sport Carbies

---

code/game/objects/items/loadout_beacons.dm

Bumper Sword spawner fix

---

code/modules/jobs/job_types/oasis.dm

Removed a trekking book and a hunting rifle
:cl:
/:cl:

Cleaning up Citizen Loadouts

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm

Removes the traits from the shelf listing, and adds some condiment shelves about! Yummy!

Removal of Trait Books + Some map edits

---

code/game/objects/items/shields.dm

Buckler buff & shield tworking
:cl:
/:cl:

Shield tweaks

---

code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
code/game/objects/items/granters.dm

Get ur guns n bullets 2 n stuff your pants with sawn offs
:cl:
/:cl:

Caravan't SnotSnun Craftable

---

code/modules/mob/living/simple_animal/hostile/f13/insects.dm

Ant health nerf

---

code/__DEFINES/mobs.dm
code/datums/spawners_menu.dm
code/modules/mob/dead/observer/observer.dm
code/modules/mob/living/living.dm
code/modules/mob/living/simple_animal/hostile/abilities_common.dm
code/modules/mob/living/simple_animal/hostile/f13/raider.dm
code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/mob/living/simple_animal/simple_animal.dm
fortune13.dme
modular_coyote/code/mob.dm
tgui/packages/tgui/interfaces/SpawnersMenu.js

Very early production!
Allows ghosts to click on geckos and play as them!
Also gives two abilities: Summon Backup and Direct Mobs. Summon Backup calls all nearby friendly mobs to your side, and Direct Mobs sends them to a tile you click on.

Playable geckos

---

code/game/objects/effects/spawners/f13lootdrop.dm

Hell of a thing to be left out.

Fixer added to wasteland meds spawner

---

code/game/objects/items/loadout_beacons.dm
code/modules/projectiles/guns/ballistic/automatic.dm

Adds bands of the swamp star to waster melee.
Fixes multicaliber gun loadout selections
Fixes .308 pistol being named .223

Fixes some loadout stuff

---

code/modules/jobs/job_types/oasis.dm

Citizen slots

---

code/game/objects/items/signs.dm

sign max message length to 100 from 30
:cl:
/:cl:

Sign Line Plus

---

code/modules/mob/living/simple_animal/hostile/f13/centaur.dm
code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
code/modules/mob/living/simple_animal/hostile/f13/mirelurks.dm
code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
modular_sunset/code/mob/renegade.dm

Makes them not put you down if in crit.
:cl:
/:cl:

Renegade Tweak

---

code/controllers/subsystem/monster_wave.dm
code/modules/mob/living/simple_animal/hostile/f13/insects.dm

More random monster spawns for the grinder

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RedRiver.dmm

Adjustments to poke holes in some stuff.  Should make Nash a bit harder to seal up tighter than a clam, but still totally doable with some real effort.
:cl:
/:cl:

Map Tweaks

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Well, the player playable ones.
:cl:
/:cl:

Removes Renegadebots

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

I'm very dumb

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

removes the last of a thing from a place, don't worry about it :)
:cl:
/:cl:

Fenny - Really dumb

---

code/datums/components/crafting/recipes/recipes_misc.dm
code/game/machinery/porta_turret/portable_turret.dm

They duped materials, annoyingly. Now they dont.

Fixes port-a-turrets

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Stairs, yes.  Of course.
:cl:
/:cl:

More stairs

---

code/modules/projectiles/ammunition/ballistic/shotgun.dm

Bloatfly ranged attack text fix

---

code/datums/components/waddling.dm
code/game/objects/effects/spawners/bundle.dm
code/game/objects/items.dm
code/game/objects/items/plushes.dm
code/modules/fallout/obj/structures/mob_spawners.dm
code/modules/mob/inventory.dm
code/modules/mob/living/simple_animal/hostile/abilities_common.dm
code/modules/mob/living/simple_animal/hostile/regalrat.dm

Finally, fuz's and my plushies are properly sized, and it stays sized properly when picked up!
Also rats stay big when resized and they wiggle around.
Curious mice are actual mobs now, with no abilities.
Mice dig their own dens, which spawn mice.

Fixes wiggles and size on mobs, also mouse tweaks

---

code/datums/components/crafting/recipes/recipes_explosives.dm
code/game/objects/items/grenades/f13grenade.dm
code/game/objects/items/grenades/ghettobomb.dm
code/game/objects/items/grenades/grenade.dm
code/game/objects/items/loadout_beacons.dm
code/game/turfs/simulated/minerals.dm
code/game/turfs/simulated/wall/reinf_walls.dm
code/game/turfs/simulated/walls.dm
code/modules/fallout/obj/stack/f13Cash.dm
code/modules/fallout/turf/mineral_walls.dm
code/modules/mining/machine_vending.dm

Dynamite makes a light explosion that won't damage r-walls, but destroys the fuck out of rock walls, making it a decent mining explosive!
Also coffeepot bombs should work properly now.

Tweaks dynamite, adds it to mining rewards

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Strip club in the sewers!
:cl:
/:cl:

Sewer club to get dirty iin

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Silly house

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm

removes a rogue hvac

---

modular_citadel/code/modules/client/loadout/__donator.dm

Make sure to tell her to check the loadout special tab.

Jo'anna mayor!

---

code/modules/jobs/job_types/SS13/captain.dm
modular_citadel/code/modules/client/loadout/__donator.dm

This codes so confusing sometimes, I swear.

Possible Mayors spare fix

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Puts a floor under a door, instead of, you know, a fucking wall.
:cl:
/:cl:

House in Nash fix

---

code/datums/traits/good.dm
code/datums/traits/negative.dm

lmao lol, I blame fuzzy for this entirely
:cl:
/:cl:

Quirk typo fixes

---

code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm
code/modules/mob/living/simple_animal/hostile/f13/centaur.dm
code/modules/mob/living/simple_animal/hostile/f13/chinese.dm
code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
code/modules/mob/living/simple_animal/hostile/f13/insects.dm
code/modules/mob/living/simple_animal/hostile/f13/mirelurks.dm
code/modules/mob/living/simple_animal/hostile/f13/raider.dm
code/modules/mob/living/simple_animal/hostile/f13/rattler.dm
code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
code/modules/mob/living/simple_animal/hostile/f13/tunnelers.dm
code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
code/modules/mob/living/simple_animal/hostile/f13/wolf.dm

This is to make way for Dans wait time changes, since mobs will be attacking faster their damage needs to be reeled back some.
Ngl it's very arbitrary, and will need more dialing in, but it eez what eet eez.
:cl:
/:cl:

Preliminary Mob Damage Lowering

---

code/game/objects/items/tools/weldingtool.dm
code/modules/reagents/reagent_dispenser.dm

l
You can refill welders from bottles, like the one that spawns in synthkits! Just click one onto the other, and it'll try and fill it! Just keep the thing off tho

Welders arre fillable from containers

---

tgui/package.json
tgui/yarn.lock

Actually finishes the work to deduplicate and fix all of the TGUI dependencies
:cl:
server: updates packages used by TGUI to resolve dependabot warnings and remove as much duplication as possible
/:cl:

Update packages one last time

---

code/game/objects/items/shrapnel.dm
code/modules/mob/living/simple_animal/hostile/f13/chinese.dm
code/modules/mob/living/simple_animal/hostile/f13/raider.dm
code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/projectiles/projectile/bullets/pistol.dm
code/modules/projectiles/projectile/bullets/rifle.dm
modular_sunset/code/mob/renegade.dm

Ranged mobs have a delay between seeing you and shooting you. Except certain bosses. 
NPC bullets are slower.

Ranged mob bullet balance

---

code/modules/clothing/under/f13.dm

This turns my previous PR #1457 into hopefully functional sprites
I added "mutantrace_variation = STYLE_DIGITIGRADE" to all the ones I added sprites for and am frankly hoping it works.
:cl:
add: Added access to my sprites... I hope.
/:cl:

Hopefully digi's a bunch of underclothes.

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Adds a new room with little bedrooms, replaces the torches with real light so players can dye it. Also removes a extra light in a house. No need for two lights to be right next to one another. Come on, who's paying this power bill?
:cl:
/:cl:

changes to the sewers around heavens night

---

code/__DEFINES/dcs/signals.dm
code/datums/elements/ghost_role_eligibility.dm
code/modules/mob/dead/observer/observer.dm
code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
code/modules/mob/living/simple_animal/simple_animal.dm

3 minute delay between dying as a mob and grabbing a new one
also support for making it per-mob class, but right now everything is tied to the same cooldown

3 minute delay between dying as a mob and grabbing a new one

---

code/game/objects/effects/spawners/f13lootdrop.dm
code/modules/jobs/job_types/wasteland.dm
code/modules/projectiles/boxes_magazines/ammo_boxes.dm
code/modules/projectiles/boxes_magazines/internal/revolver.dm
code/modules/projectiles/guns/ballistic/revolver.dm
code/modules/projectiles/projectile/bullets/rifle.dm

It's too op right now. It'll be added when it isn't a bullshiet two shot against combat armor.

Explosive ammo? Really? No.

---

code/modules/clothing/under/f13.dm

The follower clinic outfit wasn't digi due to it's path, it now is. Tada!
:cl:
fix: fixed an 'S' preventing it from loading the right sprite.
/:cl:

Updates a path

---

code/game/objects/items/validball.dm

The validball scanner's alt-click never knew where the ball was. Now, it should.

Fixes the validball scanner

---

modular_citadel/code/modules/client/loadout/__donator.dm

Loadout kit locked to Ckey ArchyZT (first one)
Loadout kit locked to Ckey TrueDark (Fourth one)

Two loadouts!

---

modular_citadel/code/modules/client/loadout/__donator.dm

Loadout kit fix
