- code/game/objects/items/loadout_beacons.dm
- code/modules/jobs/job_types/wasteland.dm
Adds compact RCW and wattz 1000 to energy loadouts.
tribals can get the swampstar gloves
redwater residents and watchers get actual kits.
> Loadout tweaks

- code/modules/projectiles/ammunition/_firing.dm
so i did a dopelike and made it so everyone had no spread. ever. at all. this fixes that
> One keystroke fix to spread being broke

- code/modules/mob/living/carbon/human/species_types/synthliz.dm
- code/modules/mob/living/carbon/life.dm
- code/modules/mob/living/carbon/monkey/life.dm
they used to take tox from rads, but, not anymore
> synths dont take rad tox anymore

- code/game/objects/items/devices/multitool.dm
- code/modules/projectiles/guns/ballistic/automatic.dm
- code/modules/projectiles/guns/ballistic/pistol.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
Loadout kit locked to ckey Bonirus.
Loadout kit locked to ckey SeermanKhajitt.
Changes the name of the alien multitool to ultracite multitool.
> Loadout Stuff and Tool name change

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> Stinky nash gate buttons fixed

- code/modules/projectiles/guns/ballistic/automatic.dm
- code/modules/projectiles/guns/ballistic/pistol.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
If tox doesn't end up winning this, I'll be surprised. If they somehow don't, hold off merging this until I make edits.
> Mayor stuff + Plus fixes for Seerman

- code/modules/jobs/job_types/followers.dm
A lot of it is in the files changed.
All roles were editted, mainly their spawn text and the job slot number. Senior doctors no longer get a loadout choice, just hard spawn items.
> Clinic Rework

- code/modules/mob/living/living.dm
- code/modules/mob/living/say.dm
In theory lol.  Dans touching up.
:cl:
/:cl:
> Suckumb Fixes

- code/modules/mob/living/living.dm
- code/modules/mob/living/say.dm
Reverts ARF-SS13/coyote-bayou#1485
> Revert "Suckumb Fixes"

- code/game/objects/effects/landmarks.dm
- code/game/objects/items/cards_ids.dm
- code/modules/jobs/job_types/followers.dm
- code/modules/jobs/jobs.dm
HELLOOOOOOOOOOOO NURRRRRRRSE!~
> Clinic Nurse Hotfix

- code/modules/cargo/packs/organic.dm
Burger box and chinese added!~
> Cargo Food!

- code/modules/cargo/packs/security.dm
Adds plasma grenades and clustergrenades to the cargo shuttle.
Adds the advanced mods and zax module to the cargo shuttle.
(all of these are in separate tabs in munitions)
https://youtu.be/qudzjypUteA
> Bad ideas! *bomb/mods edition*

- code/modules/cargo/packs/security.dm
I always forget something in my bloody prs.
> Clustbang/Advmods Cargo Listing Hotfix

- code/__DEFINES/random_mob_spawner.dm
specifically in the random mob spawner spawners. Oops, knew I forgot something lol
:cl:
/:cl:
> Activates gecko variety

- code/modules/cargo/packs/security.dm
> Goodies for the cargo!

- code/modules/mob/living/simple_animal/hostile/f13/tunnelers.dm
> Tun Desc Update

- code/modules/cargo/packs/security.dm
everything that should be giving more defaults to one. I fixed that. Also adjusted the clusterbang listing.
> Final Cargo Fix, AAA

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
Build ICly by a player, just mapped in and dirtied it up. Also moves a house to make room for it. 
:cl:
/:cl:
> Adds a new home to upper nash

- code/modules/mob/living/simple_animal/hostile/f13/chinese.dm
They didn't have them before. Now they do!
> Adds various phrases for the chinese soldiers!

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Redoes Peabus Combat Arena
Fixes some stairs
adds a second floor to a small area on the nash z
general map wiggling
:cl:
/:cl:
> Peabus 2 and Other Map Fixings

- code/modules/cargo/packs/security.dm
- code/modules/reagents/chemistry/recipes/slime_extracts.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
STUFFED ANIMAL FOX. Itty bitty.
> Edits Tasald's Loadout

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> I hate this door

- code/modules/hydroponics/grown/cocoa_vanilla.dm
Chocolate should taste like CHOCOLATE, NOT DATUM REAGENT CONSUMABLE COCO, LIONEL.  WAT.
:cl:
/:cl:
> Chocolate taste

- code/modules/clothing/suits/arfsuits.dm
> fixes razorclaw armor sprite

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- code/controllers/subsystem/ticker.dm
Adds some more stuff to the corner box that we keep mapping reference objects in.
:cl:
/:cl:
> Expands reference corner on Nash z

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- code/game/objects/items/cards_ids.dm
- code/modules/projectiles/ammunition/energy/laser.dm
- code/modules/projectiles/projectile/beams.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
- modular_sunset/code/modules/fluff/happyshark_recipe.dm
- modular_sunset/code/modules/food_and_drinks/happy_shark/happy_shark.dm
See files changed.
Various edits to the donators (added new things to folks loadouts).
Fixed up tiana for mayor listing.
Adjusted elly's gun.
> Various changes!

- code/datums/components/crafting/recipes/recipes_misc.dm
Massive oof. Fixes the two nests that were added.
> Thiiink this is why crafting ui is borked

- code/datums/components/crafting/recipes/recipes_misc.dm
> Final edit to the fix!

- code/modules/vending/toys.dm
- fortune13.dme
- modular_coyote/code/lewd.dm
> spork wood

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
> putting a kink mate into heavens night

- modular_coyote/code/modules/mapping/wren_billboards.dm
lmao density = 000000
:cl:
/:cl:
> Fixes powerpole density

- code/modules/mob/living/simple_animal/hostile/abilities_common.dm
> Makes newts beastmaster controllable

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RockSprings.dmm
Just some various map touchings, including adding some more background grasses.
:cl:
/:cl:
> Small map touches

- code/datums/traits/good.dm
Adds info to let people know its still broken, but lick healing can close your wounds.
:cl:
/:cl:
> Update tough skin desc

- modular_citadel/code/modules/client/loadout/__donator.dm
Adds a second ckey kit locked to ckey lucine. 🐺
> Loadout kit! Bunny edition

- code/__DEFINES/armor.dm
- code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
- code/modules/mob/living/simple_animal/hostile/hostile.dm
Lmao lol
Deathclaw rebuild and experimentation
:cl:
/:cl:
> Deathclaw Updating

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Starting to fix those smelly bushes that are rocks for some reason in Nash
:cl:
/:cl:
> Deep water spots & Bushes

- code/game/objects/structures/flora.dm
Makes trees block line of sight.  Consider test merging this and seeing how it plays.  Though, I think all it really does is offer more ways to break mob line of sight.  Which isn't bad, really.
:cl:
/:cl:
> Tree Opacity

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Replaces more rocks with proper bushes
:cl:
/:cl:
> More rock replacement

- code/modules/mob/living/living_defense.dm
Makes player controlled mobs mostly unable to hurt you while you're in crit or asleep. Also applies to projectiles!
> Player controlled mobs wont kill you

- code/game/objects/items/stealthboy.dm
clearer instructions and placement
:cl:
/:cl:
> Stealthboy desc update

- code/game/objects/items/cards_ids.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
Just as the tin says. Adds all the important mayor stuff to their loadout!
> Mayor Stuff for Honey

- modular_citadel/code/modules/client/loadout/__donator.dm
Edits aldrics Loadout
Adds saltyscabbards loadout request!
> Loadout Fix Ups

- code/datums/emotes.dm
- code/game/objects/items/stacks/sheets/sheet_types.dm
- code/modules/mob/mob_helpers.dm
- code/modules/mob/say_vr.dm
>  Maybe fixes subtler

- code/modules/projectiles/guns/ballistic.dm
- code/modules/projectiles/guns/ballistic/rifle.dm
You can rack the AMR now. Yay.
> Fixes the AMR not working

- code/game/objects/items/grenades/ghettobomb.dm
> Dan Kelly is a nerd

- code/controllers/subsystem/nightcycle.dm
co-gnawed on by dan. hopefully tells tiles to behave when placed over lit or unlight tiles, so indoors remains dim and outdoors remains bright
:cl:
/:cl:
> should hopefully fix a lighting bug. hopefully

- code/modules/projectiles/guns/ballistic/rifle.dm
- code/modules/projectiles/guns/ballistic/shotgun.dm
- code/modules/projectiles/guns/hoboguns.dm
lowers the fire rate on bolt action guns so they're actually ponderous to fire, with and without bolt worker. i cri
:cl:
/:cl:
> gun nerf for reeeeals

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
Reworking the underground, one tile at a time.  Or something
:cl:
/:cl:
> Adds Kuds Undernash

- modular_coyote/code/mob.dm
> Fixes the gator not having s prite 

- code/modules/projectiles/ammunition/ballistic/rifle.dm
- code/modules/projectiles/ammunition/caseless/rocket.dm
- code/modules/projectiles/projectile/bullets/grenade.dm
- code/modules/projectiles/projectile/special/rocket.dm
fixes the grenade launcher double explosion, 40mm buckshot spread, mininuke radiation contamination, and mininuke reload
:cl:
/:cl:
> nad fixin's

- code/__DEFINES/inventory.dm
- code/datums/components/storage/concrete/belts.dm
- code/game/objects/items/storage/belt.dm
- modular_citadel/code/modules/client/loadout/belt_loadout.dm
exactly what the title says
:cl:
/:cl:
> tactical plushie rig

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
adds matrix and access req to main door
:cl:
/:cl:
> Some den changes

- code/modules/projectiles/projectile/bullets/grenade.dm
fixes 40mm grenades
:cl:
/:cl:
> grenade fixins

- code/game/objects/items/loadout_toolkits.dm
fixes the stealth and thief loadouts
:cl:
/:cl:
> loadout fixins

- code/game/objects/items/plushes.dm
- code/game/objects/items/storage/belt.dm
Server got too horny for all the plush animals and crashed. Server now keeps its dick in its pants now.
> Plushie rig no longer crashes the server.

- code/modules/mob/living/carbon/emote.dm
- code/modules/projectiles/ammunition/caseless/misc.dm
changes the new "*rock" to "*find rock" to avoid a conflict
:cl:
/:cl:
> rock fixin's

- code/modules/mob/living/simple_animal/friendly/mouse.dm
- code/modules/mob/living/simple_animal/hostile/regalrat.dm
> Tubular Mice

- code/modules/clothing/shoes/miscellaneous.dm
- code/modules/clothing/under/costume.dm
- modular_citadel/code/modules/client/loadout/head.dm
- modular_citadel/code/modules/client/loadout/mask.dm
- modular_citadel/code/modules/client/loadout/shoes.dm
- modular_citadel/code/modules/client/loadout/uniform.dm
Re-adds jester and clown clothes and adds them to the loadouts.
Including shoes, masks and hat.
Mime's soon!
:cl:
/:cl:
> Clowns clothes

- code/datums/components/crafting/recipes/recipes_medicine.dm
- code/datums/martial/sleeping_carp.dm
- code/game/objects/items/stacks/medical.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
One sterile bandage for ten sterilizine? Gross. Five instead. Lowered the long arse crafting times too.
Also adds a new kit for caseapollo58143, imbubbl, and gives elly sleeping carp in her kit.
> Makes med crafting less asanine + Loadout stuff

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
More loot, because some places are a bit barren.  Only really touches the underground Z.
:cl:
/:cl:
> More loot!

- code/modules/projectiles/ammunition/_firing.dm
> Deadeye no longer makes you dead in the eye

- code/modules/holiday/easter.dm
Removes the -1 slowdown on both suit and hood
:cl:
/:cl:
> fixes the bunny suit

- modular_citadel/code/modules/client/loadout/head.dm
Adds the purple beret to the loadout. 
:cl:
/:cl:
> she wore a raspberry beret

- code/modules/mob/living/simple_animal/hostile/megafauna/captainarlem.dm
Shortens arlems vision some
:cl:
/:cl:
> A bit short sighted

- README.md
Thanks @ZeroNetAlpha :)  I appreciate the reminder.
:cl:
/:cl:
> Updating because Zero reminded me

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Adds tents to the shop, finally and adjusts the train station to be a bit uh.  Less full of super mutants.  The underground one that is.
:cl:
/:cl:
> Tents in the shop, adjusted train station

- code/modules/fallout/obj/structures/mob_spawners.dm
adds
/obj/structure/nest/gelcube
a spawner for gelatenous cubes. a few sewer ghoul spawns need replaced with these
:cl:
/:cl:
> water cube

- code/__HELPERS/do_after.dm
Just something for me. Makes it possible for do_afters to not be interrupted by movement.
> Adds a move-okay do_after arg

- code/modules/fallout/obj/structures/mob_spawners.dm
- code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
gelatinous cube fixins
:cl:
/:cl:
> some fixins for gelatinous cubes

- code/game/objects/items/stacks/sheets/mineral.dm
- code/game/objects/items/stacks/sheets/sheet_types.dm
- code/modules/cargo/exports/materials.dm
- code/modules/cargo/packs/security.dm
reduces material value of metal/high qual/electronic parts.
removes metal and high qual part crafting.
reduces titanium and plasma sell price.
increases high end weapon crate price
:cl:
/:cl:
> salt and iron II

- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
- code/controllers/subsystem/processing/quirks.dm
- code/datums/traits/good.dm
Just a lot of little shit, including gel cube nests underground
:cl:
/:cl:
> Map updates

- code/__DEFINES/weather.dm
fixes weather and ghostmobs in garlic town
> fixes weather and ghostmobs in garlic town

- _maps/map_files/Pahrump-Sunset/Garland-City.dmm
Makes the guys on the bridge always be a buncha angry raiders.
:cl:
/:cl:
> Garland Bridge Raiders

- code/game/objects/structures/flora.dm
- code/modules/fallout/obj/structures/cargocrate.dm
> Tree hide spaceman

- _maps/map_files/Pahrump-Sunset/Garland-City.dmm
> who shot the sheriff

- _maps/map_files/Pahrump-Sunset/Garland-City.dmm
Yeah.  Just trash carts.
:cl:
/:cl:
> removes a few uh.  Trash carts.

- code/__DEFINES/inventory.dm
- code/datums/components/crafting/recipes/recipes_primal.dm
- code/game/objects/items/devices/portable_chem_mixer.dm
- code/modules/reagents/chemistry/machinery/chem_cartridge.dm
> Fixes some ammo sprites, adds quiver recipes, makes the chemmixer beltthing hold more stuff

- code/modules/mob/living/simple_animal/hostile/hostile.dm
AI tweaks! This stops agro's through walls and removes a little bit of load on the CPU once again ~ w~ Hopefully this helps!
> Small AI tweaks

- code/__DEFINES/mobs.dm
- code/modules/mob/living/living_mobility.dm
- code/modules/mob/living/simple_animal/animal_defense.dm
- code/modules/mob/living/simple_animal/damage_procs.dm
- code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm
- code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
- code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
- code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
- code/modules/mob/living/simple_animal/hostile/hostile.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- code/modules/projectiles/ammunition/energy/stun.dm
- code/modules/projectiles/guns/energy/stun.dm
- code/modules/projectiles/projectile/beams.dm
- modular_coyote/code/mob.dm
You can now stamcrit most mobs. Just blast them with rubbers and they'll fall over. They can still attack while stamcritted@
> Mobs can be stamcritted

- code/game/objects/items/loadout_beacons.dm
> Fixes some loadout cases

- code/datums/martial/rising_bass.dm
This is going to the players soon tm. Time to make it more appropriate!
> Rising Bass Dodge has stamina cost now

- modular_citadel/code/modules/client/loadout/__donator.dm
> Fenny loadout fix for ammo!

- code/__DEFINES/traits.dm
- code/datums/components/crafting/recipes/recipes_primal.dm
- code/datums/traits/neutral.dm
- code/modules/projectiles/guns/ballistic/rifle.dm
- code/modules/reagents/chemistry/reagents/drink_reagents.dm
- code/modules/reagents/chemistry/reagents/food_reagents.dm
fixes some descriptors with the hunting rifle.
fixes pathing with quiver crafting.
adds three new neutral quirks: chocolate intolerance, peanut butter difficulties, and autobrewery syndrome.
maybe probably should be tested to be sure eating gets you drunk, peanut butter triggers, all three quiver recipes show, and hot coco poisons
:cl:
server: …
> traits n fixes

- config/config.txt
> Use IRV for map vote

- code/modules/jobs/job_types/followers.dm
A minor hiccup caused oopsies. That's fixed now teehee.
> Scientist now has ID again

- code/datums/martial/rising_bass.dm
- code/modules/mob/living/carbon/carbon_defense.dm
Makes it so it requires 10 stamina to dodge.
Also costs 8 stamina to chop an object thrown at you away.
> Final Rising Bass fixups

- code/modules/reagents/chemistry/recipes/medicine.dm
Medicated sutures require ephedrine instead of a bullshit chem from a rare mutated plant.
Medicated mesh requires oxandrolone now instead of aloe (??? literally weaker stuff than made medicine).
Reason being is these are hard already to make with you having to have access to chem knowledge **AND** a grinder as well as many bandages to grind up for the cellulose. Like wtf was these people high on making it this expensive.
> Makes medicated supplies cheaper

- code/modules/cargo/packs/security.dm
With the nerfed salvage, this'll make it so that those premium guns will be buyable with much more ease. Do note, it'll still be a bitch to nab. Ration your credits!
> Lowers the cost of cargo guns

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
- _maps/map_files/Pahrump-Sunset/RockSprings.dmm
More trees on the roads, and vines, and less open spaces that you can see forever in.
:cl:
/:cl:
> Springs Greenings

- code/modules/projectiles/guns/energy/laser.dm
> Changes the Cells of Wattz2ks and Solar Scorcher

- code/modules/mob/living/simple_animal/hostile/f13/mirelurks.dm
> Mirelurk Awakening

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> Tiny baby map fixes

- code/game/objects/effects/spawners/f13lootdrop.dm
- code/modules/clothing/suits/arfsuits.dm
- modular_citadel/code/modules/client/loadout/suit.dm
Adds the bomber jacket to the armor coat list.
Makes the khan leather battlecoat light armor instead and lowers cost.
> Adds the Bomber Jacket as armor + Khan Leather Coat Change

- code/modules/client/preferences.dm
Fixes neutral quirks being counted as positive. Now you can load up all 6 positive quirks, and still pick neutral ones!
> Fixes neutral quirks being counted as positive

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> tenny map fixins

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
https://i.gyazo.com/thumb/1200/715a214759c47ec1459c4a7bc400930c-png.jpg
Eat my ass.
:cl:
/:cl:
> Library 2.0

- code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
> Skittlegecks

- code/game/objects/items/manuals.dm
- code/modules/fallout/obj/manual/basic_advice.dm
Its not that long of a book, tbh. Also helps fight inventory stuffing (my least favorite kind of stuffing, beside turkey)
> Makes the wasteland survival guide tiny

- code/modules/mob/living/carbon/emote.dm
Bricks and rocks have a 2.5 second cooldown, unless you're a Builder or Primitive, respectively.
> Brick and rock cooldown, unless quirks

- code/__DEFINES/maths.dm
- code/game/machinery/autolathe.dm
- code/game/objects/items/stacks/stack.dm
- code/modules/fallout/misc/boarding.dm
- code/modules/reagents/chemistry/holder.dm
Fixes a thing where you could abuse our shitty shitty barricades or something and make infinite drugs. Pulled from https://github.com/tgstation/tgstation/pull/69017
> fixes nan shit

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Restyled the bar and moved the stairs for the library out of the crackshack
Nevermind, I did the whole fucking town.
:cl:
/:cl:
> Bar Restyling

- code/__HELPERS/text.dm
- modular_coyote/code/modules/examine_images.dm
Unless you're an admeme, < and > are offlimits for input text.
> Fixes html injection with unsanitized shit

- code/game/objects/items/storage/belt.dm
fixes heavy sheaths having a sabre in em.
fixes heavy sheaths fitting two handed weapons.
:cl:
/:cl:
> thicc sheath

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
this is in prep for moving Nash over, since its easier to move stuff around on the upper Z's than the lower ones.
:cl:
/:cl:
> Moves the under-clinic onto the third floor

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> Quick Clinic Fixes

- modular_citadel/code/modules/client/loadout/__donator.dm
Comes with the biogenerator, seed extractor, and plant dna machine. Lad always seems to just join to make plants and vibe. 
🤷
> Gives Tasald Goodies

- code/modules/cargo/exports/misc_export.dm
adds export values to some tribal chems
:cl:
/:cl:
> smol fixin

- code/modules/mob/living/carbon/human/species_types/humans.dm
Fixes the removal of skin tones. Woops
:cl:
/:cl:
> Whoops, removed humans skin tones. This fixes it

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> Small map fixes

- code/datums/emotes.dm
> Most emotes work in soft crit now!

- code/modules/client/client_procs.dm
- fortune13.dme
- modular_coyote/code/python.dm
- scripts/vptdetect.py
Run an IP reputation check if a player is <10 days old. Interpret the resulting exit code and message admins if it is shady.
:cl:
add: Added an IP reputation check to new players
/:cl:
> Add the script to run an IP check

- code/modules/mob/living/say.dm
Lets people speak and emote and sing in softcrit, all without dying too.
> HELP BILLY SHITS IS MURDERED ME!!!

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/RockSprings-Upper.dmm
> Map fixes but I have to potty

- code/modules/admin/verbs/playsound.dm
- config/config.txt
- tools/tgs4_scripts/PreCompile.sh
- tools/tgs4_scripts/WatchdogLaunch.sh
You want fixed internet noises? Fine.
:cl:
add: Fix internet noises
/:cl:
> Move from youtube-dl to yt-dlp

- code/game/objects/items/devices/radio/encryptionkey.dm
- code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
- code/modules/smithing/finished_items.dm
> Fixes radio + Integration tests + L + Ratio

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
don't worry kenny, we still love you <3
:cl:
/:cl:
> Fixes poor kennsy pr

- code/game/machinery/colormate.dm
- code/modules/WVM/wvm.dm
They can resist to escape colormates, and cant be put in vending machines at all. shrimple as.
> Carried mobs no longer get trapped in vending machines and colormates

- code/modules/mob/living/simple_animal/simple_animal.dm
Ghost role timeout increased to 15 minutes, and admemes can't override the timeout. Nobody actually did, gotta make that clear, its just in case, ya know. *Ya know*.
> Decreases monster mashing by 45%

- code/game/objects/items/granters.dm
Title
Someone figured this out the hard way and made the suggestion to stick a heads up in the grant text.
Sleeping carp already has the mention of it.
:cl:
/:cl:
> Mentions the gunlessness in the rising bass grant text

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
some general hotfixes around the cowbikers
fixes a table in nash
makes the highway patrol station more policey
:cl:
/:cl:
> even more cowbiker fixes

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Unfucks a table and fixes a railing blocking a path
this path had a railing under all the wood that nobody could see nor walk through, lol, lmao
make this table look nicer :3 (I scooted it in an effort to make it look better before, but ended up making it look more scuffed, zamn
:cl:
/:cl:
> super minor (map) fixings

- code/game/turfs/simulated/walls.dm
- code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
> makes newts friendly for critter friendly perkowners + fixes freerunning to climb into windows

- code/__DEFINES/inventory.dm
- code/game/objects/items/loadout_beacons.dm
- code/game/objects/items/melee/weaponry.dm
buffs the pitchfork a lil and sticks it in the suit slot, adds it to loadout beacons. adds the fire axe to loadout beacons too
:cl:
/:cl:
> a few melee thingies

- code/modules/mob/dead/new_player/preferences_setup.dm
> Fixes clothes being visible in the erp menu

- code/modules/arousal/organs/vagina.dm
Adds a # to vaginas so they have the right color.
> #justpussythings

- code/modules/reagents/chemistry/reagents/other_reagents.dm
- code/modules/reagents/chemistry/recipes/others.dm
Also added shrink chemicals following the current formula. 
<Adds in missing chem recipes, following the previous recipes slightly.>
:cl:
add: Recipes for chem functions we already had
add: Slightly different names and descriptions for some chems.
del: Removed a bit of description code
/:cl:
> Added Chem Recipes for Butts and Bellies

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- code/modules/fallout/obj/trash_stack.dm
Words are hard. I get it.
:cl:
/:cl:
> Trash Stack Desc fix

- code/game/objects/items/storage/firstaid.dm
- code/modules/cargo/packs/emergency.dm
- code/modules/cargo/packs/medical.dm
> Removes the medi hud from cargo

- _maps/map_files/Pahrump-Sunset/Garland-City.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
more puddles, give cuddles
:cl:
/:cl:
> First pass radpuddling

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> Forgot to make fennecs carnivores

- code/datums/components/largeobjecttransparency.dm
Look at the code.
Look at how easy it was to fix.
Look.
Do it.
I dare you.
What are you, a wussy?
I bet you kiss geckos, lmao, ha.
> Fucking fixes the god awful trees

- code/game/objects/items/loadout_beacons.dm
- code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
- code/modules/projectiles/guns/ballistic/automatic.dm
- code/modules/projectiles/guns/ballistic/launchers.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
loadout and donator quivers get arrows now! yay!
gelatinous cube is chilling the FUCK out and slowing down.
combat carbine no longer takes drums, so it actually has a downside compared to service rifles.
grenade launcher no longer fits in bag, be reasonable~
:cl:
/:cl:
> a few balance changes

- code/game/objects/items/stealthboy.dm
Still hard to see, but much more noticable.
:cl:
/:cl:
> Pulls Stealthboy alpha up to 60

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
accidently used the labcoat subtype version of the khancoat instead of the breastplate subtype version
god 
:cl:
/:cl:
> delabcoatening

- code/__HELPERS/do_after.dm
- code/game/objects/items/stacks/medical.dm
You can use bandages and lick yourself while on the ground.
> im a cat and i lick on the ground

- code/modules/smithing/anvil.dm
The first update and partial port from Desert Rose. Actually makes the sounds functional.
:cl:
add: Added new sounds to smithing.
/:cl:
> Adds smithing sounds and new descriptors.

- code/modules/admin/admin_verbs.dm
- code/modules/client/client_procs.dm
- modular_coyote/code/python.dm
Does checks on everyone once now. Gives admins a proc to check any warnings
:cl:
admin: Added "Check Clients" admin verb
/:cl:
> Update the scripts and give an extra admin verb

- code/datums/martial/sleeping_carp.dm
salt pr moment, bye bye op carpies
> fuckin removes sleeping carp combos and one hit knock downs lmfao

- code/__DEFINES/traits.dm
- code/datums/traits/negative.dm
- code/modules/fallout/reagents/drugs.dm
- code/modules/reagents/chemistry/reagents/drug_reagents.dm
> Adds a trait that makes drugs suck

- code/modules/vending/medical.dm
You are very becoming, Aristocrat!
<Adds in a vendor for implants.>
:cl:
add: Added a new implant vendor
/:cl:
> Adds a becoming nook

- code/modules/WVM/wvm.dm
Tweaks the three infinite vendors added to town to both have more reasonable things on sale and at more reasonable prices.
:cl:
- Weapons vendor got:
Machete
Fire Axe
.22 pistol
.22 carbine
Browning High Power
Colt N99
M1911
.357 revolver
Varmint Rifle
Hunting Rifle
Hunting Shotgun
Shortbow
- Ammo vendor got:
.22 pistol mag (16 bullets)
9mm singlestack mag (10 bullets)
10mm pistol mag (12 bullets)
.45 pistol mag (7 bullets)
.357 speedloader (6 bullets)
Small rifle mag (10 bullets)
.308 stripper clip (5 bullets)
12 gauge box (12 shells)
Field arrow (1 arrow)
- Medical Vendor got:
Healing Powder
Chemistry book increased to 300 caps
Rad-X bottle
- Medical Vendor lost:
empty pill bottle
:cl:
> Kelp infinivendor

- code/game/objects/items.dm
- code/game/objects/items/stacks/stack.dm
- code/modules/hydroponics/grown.dm
they broke cus of a couple oversights
> fixes blenders

- code/datums/martial/raging_boar.dm
- code/game/objects/items/loadout_beacons.dm
- code/modules/mob/living/simple_animal/animal_defense.dm
- code/modules/spells/spell_types/wizard.dm
> Fixes the boar

- code/modules/smithing/furnace.dm
Adds the updated furnace sprite and sounds from Desert Rose.
Everything from here on out will be behind the scenes code and maybe weapon additions.
:cl:
add: Added new icon and sounds for the furnace.
/:cl:
> Final Icon update from Desert Rose

- code/game/objects/effects/step_triggers.dm
Makes it so the teleporter Z var uses a string reference to the map's level name.
Adds a player choice step trigger.
> Steptriggeronis

- code/modules/reagents/chemistry/recipes/others.dm
:cl:
tweak: tripled lewdchem outputs
/:cl:
> tripled lewdchem outputs

- code/__HELPERS/do_after.dm
> makes matrixes usable

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
scanner lmao and monkey cubes
:cl:
/:cl:
> More stuff for discount genetics

- code/__DEFINES/dcs/signals.dm
- code/controllers/subsystem/events.dm
- code/modules/admin/secrets.dm
- code/modules/client/client_procs.dm
- code/modules/holiday/holidays.dm
- code/modules/projectiles/boxes_magazines/_box_magazine.dm
- code/modules/projectiles/gun.dm
Lets admins turn every gun and magazine into american 180s. Also makes every gun and magazine runtime when they're spawned and fuck up the garbage thing.
> Adds a horrible april fools """""prank"""""

- code/__DEFINES/dcs/signals.dm
- code/controllers/subsystem/events.dm
- code/modules/admin/secrets.dm
- code/modules/client/client_procs.dm
- code/modules/holiday/holidays.dm
- code/modules/projectiles/boxes_magazines/_box_magazine.dm
- code/modules/projectiles/gun.dm
Reverts ARF-SS13/coyote-bayou#1842
> Revert "Adds a horrible april fools """""prank""""""

- code/game/objects/effects/step_triggers.dm
Ye, just change it in the map instead, don't change the vars in the text file. <3
> Reverts back step trigger for player choice

- _maps/map_files/Pahrump-Sunset/Garland-City.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> Map tweakins

- modular_citadel/code/modules/client/loadout/__donator.dm
Changes bladeburstninja box 1 and 2.
:cl:
code: changed donator box for bladeburstninja
/:cl:
> Donator Item Change

- code/game/objects/effects/step_triggers.dm
> Ghosts now dont get included in steptriggers

- code/datums/traits/negative.dm
> Can not sleep to 2 points

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Adds a shantytown right outside Nash gates, chock full of hidey holes and general seediness.
A bazaar has propped up around the ruins and slums, mainly centered in the parking lot of a convenience store.
Brings back blue oyster for the hell of it.
Mainly just recycling the fluff from an old mapping pr that was denied due to mechanical reasons
I like tents
:cl:
/:cl:
> Clash of Slumlords 2

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Fixes some issues with the slums
goddamn you github desktop
:cl:
/:cl:
> Day 1 tentpatch, zamn. 

- code/game/machinery/autolathe.dm
- code/game/objects/items/loadout_toolkits.dm
> Some fixes

- code/game/objects/items/devices/radio/headset.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
I changed a few things, none of these should affect anyone else. It's mainly for aesthetic when I'm not in a role that gives me specific things. Basically, I did my own donator work and all of that.
- [x ] You documented all of your changes.
:cl:
add: Reconfigured donation item for Merek, and also adjusted a headset with the item state which no one uses (available in the science wardrobe in the clinic) and also added it to the donator list.
/:cl:
> Loadout: Merek

- code/modules/reagents/chemistry/reagents/drug_reagents.dm
I made an oopsie that made nobody able to do drugs. Now you can get wasted once more
> makes drugs doable

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Fixes the banks floating lights
:cl:
/:cl:
> No one likes floating lights

- code/datums/traits/good.dm
- code/datums/traits/neutral.dm
like the title says
This is black magic to me, I just squinted at the code both here and on TG and it seemed similar.
May god spare my soul
:cl:
/:cl:
> Ports Persistent Personal Photoalbums (PPPP) from TG

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Adds Bounty, Personals, Projects, Adventure & News boards to Nash!
:cl:
/:cl:
> Persistent Boards - Nash!

- code/datums/martial/raging_boar.dm
> boar breaking backs by barely bidding battle

- code/modules/projectiles/guns/ballistic/pistol.dm
- code/modules/projectiles/guns/energy/laser.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
updates nayriin's model RCW to be a child object of the starter compact RCW.
moves Nay's RCW and thingpony's pistol to their proper weapon files, from _donator.dm
:cl:
/:cl:
> a couple updoots to donator guns

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RockSprings.dmm
> map touching #249324852158

- code/__HELPERS/matrices.dm
- code/datums/traits/neutral.dm
As the title goes.
Also fixes SpinAnimation spinning forever!
> Makes sure items spawn on the floor atleast if all slots are full. For journalists and photographers.

- code/datums/traits/good.dm
- code/datums/traits/negative.dm
- code/datums/traits/neutral.dm
- code/game/objects/items/melee/f13onehanded.dm
Swaps out mob_tar for H on some quirks. Also adjusts unarmed weapons so it better matches fists of iron and steel. Corrects lifegiverplus.
:cl:
tweak: tweaked certain unarmed weapon values
fix: fixed some quirk issues
/:cl:
> Fixes Certain Traits Not Applying Correctly

- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/silicon/silicon.dm
Its set pose, you troglodyte.  Also tacking on the concept of using it to set afk messages.
:cl:
/:cl:
> Murder (renaming temp flavor text)

- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
I am eating scrydens legs
:cl:
/:cl:
> More map fixes, reee

- code/game/objects/items/devices/instruments.dm
- code/modules/instruments/instrument_data/guitar.dm
I fixed the Eguitar, and made all the (well, most) of the instruments viable weapons.  Maybe not the best, and I might be biased towards the eguitar, but hey.
Smash heads in.
Fixes #793 
:cl:
/:cl:
> Rock on - And other assorted musical instrument changes

- code/modules/smithing/anvil.dm
- code/modules/smithing/furnace.dm
Adds some comments to the anvil recipies. Useful later.
:cl:
/:cl:
> Adds some comments to the anvil code. [Ready]

- code/_globalvars/lists/flavor_misc.dm
For draining blood!  Bleh!
:cl:
/:cl:
> Vampire Tongues

- code/datums/traits/neutral.dm
Stupid typo from ya boi.
This is why you don't copy and paste code.
> Certified DUMBASS MOMENT (Fixes photographer)

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
Fenny sent me a map, and here it is.
> Map update

- _maps/map_files/Pahrump-Sunset - Backup/Dungeons.dmm
- _maps/map_files/Pahrump-Sunset - Backup/RedRiver.dmm
- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
- modular_citadel/code/modules/client/loadout/__donator.dm
Demon of the east, I revile you.  Return henceforth to the land of lava and the realm of the munchkin.
:cl:
/:cl:
> Begone, overpowered gamer juice

- modular_sunset/code/mob/renegade.dm
one mob at a time bby
:cl:
/:cl:
> Gives renegades waddles

- code/modules/projectiles/boxes_magazines/internal/rifle.dm
- code/modules/projectiles/guns/ballistic/rifle.dm
makes the enfield magazine 9+1 instead of 5+1
:cl:
/:cl:
> powercreeps the british

- code/game/objects/items/melee/coyotemelee.dm
> God damnit civ13, figure out how you want to spell kanabo

- code/game/objects/items/melee/coyotemelee.dm
- code/modules/projectiles/guns/ballistic/flintlock.dm
> fixes double loading flints and combataxe in hand

- code/modules/cargo/packs/organic.dm
- code/modules/cargo/packs/security.dm
Exactly what the title says.
:cl:
- Adjusted prices yet again to account for what looks like the average round to round income of cargo and players.
- Commented out the gauss barrels 'cause they do nothing.
- Fixed a super tiny bug regarding a crate name.
- Minor grammar tweaks.
:cl:
> Cargostuff

- code/modules/clothing/under/miscellaneous.dm
All clothing/under now works with digigrade legs
:cl:
/:cl:
> Fixing all clothing/under

- code/__DEFINES/say.dm
- code/modules/client/preferences_savefile.dm
- code/modules/mob/dead/new_player/new_player.dm
I couldn't get templates to new line correctly, I don't have the energy or thought rn how to do it. The macro definition is there if anyone wants to mess with it. 👍
> OOC notes are now required

- code/modules/projectiles/guns/ballistic/rifle.dm
tweaked the damage and fire rate of the jungle carbean down slightly, so it isn't better in every way than a cowboy repeater
:cl:
/:cl:
> smol jungle carbean adjustment

- code/modules/food_and_drinks/food.dm
Voring food shouldnt give you endless food.
> Solves world satiation

- code/modules/clothing/suits/arfsuits.dm
- modular_citadel/code/modules/client/loadout/suit.dm
> Armor Tweaks

- code/controllers/subsystem/shuttle.dm
> Neverending mapping

- code/modules/mob/living/living_movement.dm
- code/modules/vore/eating/belly_obj.dm
- code/modules/vore/eating/bellymodes.dm
> should fix some wierd slowdown stuff

- code/modules/projectiles/guns/ballistic/pistol.dm
- code/modules/projectiles/guns/energy/laser.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
adjusts a few sprite things merek noticed, and gives him some fancy pistols
:cl:
/:cl:
> merek loadout stuffs

- code/datums/components/spawner.dm
- code/modules/mob/living/simple_animal/hostile/hostile.dm
- code/modules/projectiles/projectile/special/debug_projectiles.dm
We'll get CDDA zombies at some point. Not this way tho. Fixes dead mobs getting nest'd
> fixes zombie mobs

- code/game/objects/items/loadout_beacons.dm
Didnt know you could do that. Cool shit.
> Prevents loadout hax

- code/game/objects/items/loadout_beacons.dm
- code/game/objects/items/shields.dm
Fuck yer integrity, we're about avin fun around here.  Also adds buckler to the weapon kit in misc
:cl:
/:cl:
> Shield Update

- code/__DEFINES/dcs/signals.dm
- code/__DEFINES/voreconstants.dm
- code/controllers/subsystem/prefbreak.dm
- code/controllers/subsystem/vore.dm
- code/game/objects/items/storage/_storage.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/food_and_drinks/drinks/drinks.dm
- code/modules/food_and_drinks/food.dm
- code/modules/food_and_drinks/food/snacks.dm
- code/modules/vore/eating/belly_obj.dm
- code/modules/vore/eating/bellymodes.dm
- code/modules/vore/eating/vore_core.dm
- code/modules/vore/eating/vore_emotes.dm
- code/modules/vore/eating/vore_prefs.dm
- code/modules/vore/eating/vorepanel.dm
- tgui/packages/tgui/interfaces/VorePanel.js
Fixed food being fuckin wierd when you vore them.
Fixed slowdowns not updating properly.
Added an option to yartz up trash when a snack is fully digested, with a pref not to see that shit.
Added a master vore pref that, if off, blocks all vore stuff.
> SOme vore updates

- code/game/objects/items/loadout_beacons.dm
> stop sign shield

- code/modules/mob/living/carbon/human/species_types/ghoul.dm
they deserve love too <3
(removes fake death from ghouls, this prevents them from being hugged)
> huggable ghoulies :)

- modular_citadel/code/modules/client/loadout/suit.dm
- modular_citadel/code/modules/client/loadout/uniform.dm
> Pirate stuff in the loadout

- code/game/objects/effects/effect_system/effects_smoke_new.dm
Fixes a divide by zero error due to me failing middleschool math. Its true! I did!
> kiss my PEMDAS

- code/datums/components/spawner.dm
- code/modules/mob/living/simple_animal/hostile/hostile.dm
If a mob was touched by an admeme, it'll never despawn. Also despawning mobs record their iconstate.
> Adminbussed mobs won't despawn

- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
BoS Dungeon! Playtesting required. (It's hard), also hour time lock.
> BoS Dungeon

- code/datums/components/chasm.dm
- code/game/turfs/simulated/floor/plating/dirt.dm
Chasms no longer delete people. instead, they yell at the admins that something fucked up.
> No more turf vore

- code/datums/traits/good.dm
AKA; I can not believe people powergamed this item to valid hunt. Adds an OOC note to the perk on spawn and removes the medical text.
:cl:
tweak: tweaked the perk.
/:cl:
> Cannibal AntiMeta PR

- code/game/objects/items/melee/energy.dm
Armor pen sucks for doing anything, lets make these actual usable.
:cl:
/:cl:
> Update Plasma Cutters

- code/game/objects/items/melee/f13onehanded.dm
- code/game/objects/items/melee/weaponry.dm
Hahahaha, fucking LETS GO!!
Tested with the kanobo, actually fun as FUCK!
:cl:
/:cl:
> Adjusts bokken parry, and adds it to ALL MELEE WEAPONS!

- _maps/RandomZLevels/VR/yuma_VR.dmm
- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
> FIXES SHITTY LADDERS AND MAPS NOT SAVING

- code/modules/mob/living/living_defense.dm
So turns out vore intent was useful. But, dont have it, so away that goes!
> choking people out no longer tries to feed them to themself

- code/game/objects/items/loadout_beacons.dm
- code/game/objects/items/melee/energy.dm
tweaks the plasma cutters to be a lil more unique from each other, adds them to loadouts. 
re-sorts some loadout stuff
:cl:
/:cl:
> plasma cutter and weapon spawner work

- code/game/objects/items/stunbaton.dm
- code/modules/mining/ores_coins.dm
- code/modules/paperwork/pen.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
title
:cl:
Seerman kitty cat loadout
- Removed some stuff
- added Salvaged Eastern Rifle
- gave a cookie
Weredoggo loadout
- added energy sword pen
- added peanutbutter cookie
- added 1 dogecoin
Misc gear changes
- Stun batons can now harmbaton again and maybe kill something
- the energy sword pen actually does damage in line with F13 code.
:cl:
> loadout stuff

- code/game/objects/items/melee/f13twohanded.dm
ate dis repo, got damn
:cl:
/:cl:
> Adds parry to the fallout two handed weapons

- code/modules/research/designs/autolathe_desings/autolathe_designs_sec_and_hacked.dm
reenables the RCD crafting recipe from hacking the autolathe
:cl:
add: The RCD
/:cl:
> Brings back the rapid construction device

- code/datums/traits/good.dm
> weh 1 line pr

- code/controllers/subsystem/processing/mob_spawner.dm
- code/datums/components/spawner.dm
- code/modules/fallout/obj/structures/mob_spawners.dm
- code/modules/mob/living/simple_animal/hostile/hostile.dm
We keep track of a unique string tag of them!
> Fixes spawners spawning waaaaaay too many mobs when some of them go to sleep

- code/datums/chatmessage.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/mob/living/carbon/carbon.dm
Lets you change your runechat. Set up in char prefs, or with a verb in IC. that also saves it.
> you can change ur runechat

- code/datums/materials/basemats.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
Removes Transparancy from Diamonds
Comments out Mayor from Donator
:cl:
/:cl:
> Diamond-is-not-transparent-

- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
- code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
StrongDMM is a piece of shit that doesn't save my changes. (Enclave Scientists no longer shoot clone damage projectiles.)
> Final fixes to Enclave dungeon.. hopefully.

- code/modules/clothing/suits/arfsuits.dm
so tired
fixes pa sprites
:cl:
/:cl:
> I am tired (fixes pa sprites)

- code/datums/components/crafting/recipes/recipes_misc.dm
> kill kenny

- code/modules/fallout/obj/trash/electronics.dm
Don't stick your tongue in toasters.
Or do.
I'm not your boss.
:cl:
/:cl:
> makes licking toasters hazardous

- code/modules/clothing/suits/arfsuits.dm
> pokes numbers on some armor

- code/modules/WVM/wvm.dm
- code/modules/cargo/exports/materials.dm
- code/modules/cargo/exports/misc_export.dm
- code/modules/cargo/packs/engineering.dm
- code/modules/cargo/packs/materials.dm
- code/modules/cargo/packs/medical.dm
- code/modules/cargo/packs/misc.dm
- code/modules/cargo/packs/organic.dm
- code/modules/cargo/packs/science.dm
- code/modules/cargo/packs/security.dm
- code/modules/cargo/packs/vending.dm
- code/modules/mining/equipment/explorer_gear.dm
t i t l e
:cl:
Armor:
- Slightly improved the Explorer/SEVA armor stats (+1 DT) to make it more palatable to people (seriously, who the fuck complains melee armor is bad vs guns I s2g)
- Fixed SEVA/Explorer hiding ears and tails
- Changed price from 100 to 50 in the vendor
- Added Radsuit and Radhood to the Explorer/SEVA vendor
Economy:
- Too many changes overall to mention all of them, but generally slashed prices to bring in line with Bayou's economy and so selling something besides guns is viable
- Added solar panels back because people keep doing a fuck at Mass Fusion. May not actually be helpful, but hey, I tried.
- Toys and booze now have value so both be can be added to loot pools. Might also get people to collect these for fun if they have value.
- Added value degradation to raw …
> Economy Touchies - Good to merge

- modular_citadel/code/modules/client/loadout/hands.dm
Adds pipboys, headset and the ID card in the loadout
:cl:
/:cl:
> Pip pip hooary

- code/modules/language/common.dm
Isn't yet selectable at round start, also can't really test it solo.
:cl:
/:cl:
> Sign language

- code/modules/fallout/turf/wall_damage.dm
- modular_coyote/eris/code/gun_firemode.dm
> should fix some runtimes

- code/modules/language/common.dm
- code/modules/language/language_holder.dm
- code/modules/surgery/organs/tongue.dm
> fixing signlanguage

- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
fuck
evil spooky scary stuff, also evil and colossus is down there he'll gib you (also magic)
> The Cult's Crypt

- code/__DEFINES/vv.dm
- code/game/atoms.dm
Ports a PR from Skyrat
https://github.com/Skyrat-SS13/Skyrat-tg/pull/20607/files
:cl:
/:cl:
> Spon Omintion

- code/game/objects/items/devices/PDA/PDA_types.dm
> kenny try to make a bugless feature challenge (impossible)

- code/__DEFINES/inventory.dm
- code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
- code/modules/smithing/finished_items.dm
- code/modules/smithing/smithed_items.dm
> in fact, i fixed it!

- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
> No more zombies.

- code/game/objects/items/loadout_beacons.dm
- code/game/objects/items/loadout_toolkits.dm
- code/game/objects/items/melee/f13onehanded.dm
- code/modules/cargo/packs/organic.dm
- code/modules/projectiles/guns/ballistic/automatic.dm
makes switchblades tiny and adds em to the loadout boxes.
hopefully fixes .22 machine pistols with extended magazines.
adds the mcrib crate
:cl:
/:cl:
> few nibblings

- code/__DEFINES/dcs/signals/signals_atom_main.dm
- code/game/atoms.dm
Fixes inventories hiding behind your UI because of poorly-made blenders.
> My blender ate your backpack

- code/game/objects/items/devices/PDA/PDA.dm
- code/game/objects/items/devices/PDA/PDA_types.dm
I hate beyond clintcode I hate beyond clintcode
:cl:
/:cl:
> someone take away kenny's green name (fixes teachboy take 2)

- modular_citadel/code/modules/client/loadout/__donator.dm
literally the title, why do we gotta fill out these things?
:cl:
/:cl:
> Stockholm syndrome (Gives Saltspider a kit)

- code/game/objects/items/fishingrod.dm
It delt less damage 2 handed then every 2 handed weapon we have.
35 damage wielded to 55 damage weilded
Powercreep good :thumbs_up:
:cl:
/:cl:
> fishingrod meta powercreep

- code/modules/mob/living/simple_animal/hostile/retaliate/frog.dm
frogs are now multi-colored and pixel shifted.
:cl:
add: frogs of DIERS COLOURS
/:cl:
> frupdate(frog update)

- code/datums/components/spawner.dm
> Okay actually fixes nests again

- modular_citadel/code/modules/client/loadout/__donator.dm
Zonq for mayor, may brick something something.
> Gives Zonq their mayor stuff

- code/datums/traits/negative.dm
- code/modules/clothing/under/miscellaneous.dm
- code/modules/reagents/chemistry/reagents/medicine_reagents.dm
- code/modules/surgery/advanced/toxichealing.dm
fixed some semi-random stuff because what's sleep
:cl:
- Mute is now equal to tongue tied since it can't be taken with it and does pretty much the same thing
- Tox/Oxy heal surgery is fixed and can actually be used now. Needs low surgery (roundstart trait, 150 cap book)
- Gear harnesses no longer planti you
- Omnizine should heal clone damage now
:cl:
> Small touchies

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
> Adds an ore silo to town

- code/datums/components/melee_special.dm
- code/game/objects/items.dm
- code/game/objects/items/melee/coyotemelee.dm
- code/game/objects/items/melee/f13onehanded.dm
- code/game/objects/items/melee/f13twohanded.dm
- code/game/objects/items/melee/misc.dm
- code/modules/projectiles/guns/energy/plasmaf13.dm
- code/modules/smithing/finished_items.dm
Didnt actually push the changes, lol.
> Actually adds the components to weapons

- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
> STOP CHEESING MY FUCKING DUNGEONS

- code/__DEFINES/preferences.dm
- code/__DEFINES/say.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
> tacks on a grody OOC notes template to everyone

- code/modules/client/preferences_savefile.dm
> Unfucks the save files

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Mostly ready, just need a ladder attached to it to the surface somewhere near nash/tribal village that's mostly safe. Placed a ladder inside the area, just don't know how to connect. 
:cl:
/:cl:
> Catslug cave

- code/datums/components/melee_special.dm
- code/game/objects/items/melee/coyotemelee.dm
Fixes things piercing through walls, wierdly.
Fixes damage ramping, I think.
Pikes have a slightly different damage calc.
added damages work properly.
> Fixes some melee specials

- code/controllers/subsystem/processing/quirks.dm
> Stops you from taking zoomies and super zoomies

- code/datums/traits/good.dm
- code/datums/traits/neutral.dm
- code/game/objects/structures/flora.dm
- code/game/turfs/closed.dm
- code/modules/mob/living/carbon/carbon_sprint.dm
makes zoomies a positive trait (cheap), fixes super zoomies stamina buffer, should work, haven't tested, LUL
:cl:
/:cl:
> changes to zoomies

- code/__DEFINES/dcs/signals.dm
- code/__HELPERS/verbs.dm
- code/modules/arousal/genitals.dm
- code/modules/vore/eating/living.dm
- code/modules/vore/eating/vore_core.dm
Also people without dicks able to change their undies.
> makes catslugs able to vore

- code/modules/client/preferences.dm
- modular_coyote/code/_pmon_defines.dm
- modular_coyote/code/mob.dm
Fixes a runtime which can occur if the creature list changes and the player has a selection which is no longer valid.
Also added support for developers to manually add mob types to the creature spawn list. I included some that I thought were appropriate to start.
> Runtime Catch & Manual Creature List Addition Support

- code/game/objects/items/melee/coyotemelee.dm
lmfao fuck unwielded is a dumb var to have when you already have normal force.  Why the fuck do you need all three?
:cl:
/:cl:
> Coyote Weapons Fix

- code/datums/components/melee_special.dm
Special attacks that dont hit anything have a shorter delay between swings
> adds a shorter delay for whiffed swings

- code/modules/crafting/items.dm
Detuning Technophreak some now that loot is able to be turned in for caps.
Lmfao lol
:cl:
/:cl:
> Dori me, interimo adapare dori me (fenny touches technophreak)

- modular_citadel/code/modules/client/loadout/backpack.dm
Adds the lock collars to the backpack loadout, so you can put them on when you want to.
Includes
Two tone locked
One tone locked
shock
shocked with shackles
:cl:
/:cl:
> Adds some kinky collars to the backpack loadout

- code/game/objects/items/devices/radio/electropack.dm
Because no one uses these things for their 'intended' purpose anymore anyways, so let people who want to have fun with em pull em off if they want.
:cl:
/:cl:
> Turns off shock collar unremoval

- code/modules/clothing/under/miscellaneous.dm
Reverts ARF-SS13/coyote-bayou#2039 due to it breaking the sprite entirely, need to get cache to look at this one lol
> Revert "for fen"

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Fixes some nash door names
:cl:
/:cl:
> Fixes some nash doors

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
yeah. moves some spawners in the park, replaces indoor spawns, adds some lootspawns, but also guarenteed raiders
:cl:
/:cl:
> removes rat spawners south of nash and changes park a bit

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
> Fixes bball stairs

- code/game/objects/effects/spawners/f13lootdrop.dm
- code/modules/fallout/obj/stack/f13Cash.dm
just adds higher tier coins to the loot pools again
> coinage re-additus

- code/__DEFINES/mobs.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/mob/living/living.dm
- code/modules/mob/mob.dm
Lets mobs have a persistent pixel offset.
> lets mobs control their /shift/

- _maps/map_files/Pahrump-Sunset/i_hate_fenny.dmm
> barely anything changed (thanks work moments!!!!!!!!!)

- code/modules/vending/_vending.dm
> Sloight change two hour coyn meganixs

- code/_onclick/hud/generic_dextrous.dm
- code/_onclick/other_mobs.dm
- code/game/objects/structures/ladders.dm
- code/modules/fallout/turf/walls.dm
- code/modules/mob/dead/new_player/new_player.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/living_defense.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- fortune13.dme
- modular_coyote/code/mob_hotkeys.dm
- modular_coyote/code/pmon_actions.dm
- modular_coyote/code/pmon_mob.dm
- Adds many hotkeys and missing UI elements to creature characters (throw, wield, intent, etc)
- Lets dextrous simple mobs use unarmed attacks while on harm/grab/disarm intent and friendly verbs on help intent
- ~~Lets ghosts traverse up/down ladders (most of the time)~~
- Fixes creature characters always being examined with nonbinary gender pronouns (probably)
- Adds an alert in deadchat when a creature character spawns in
- Makes pokemon laying down work like other simple animals
- Lets creature characters despawn themselves with matrixes
- Gives creature characters a flashlight, gauze, and knife on spawn
> [ready] Loads of fixes and improvements

- _maps/map_files/Pahrump-Sunset/i_hate_fenny.dmm
- code/modules/WVM/wmv_buyer.dm
> wvm says coins now, and also map

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
help please god save me from this hell
:cl:
/:cl:
> Fenny can't stop fiddlefucking the map

- code/_onclick/hud/generic_dextrous.dm
- code/_onclick/other_mobs.dm
- code/game/objects/structures/ladders.dm
- code/modules/fallout/turf/walls.dm
- code/modules/keybindings/keybind/carbon.dm
- code/modules/mob/dead/new_player/new_player.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/living_defense.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- fortune13.dme
- modular_coyote/code/mob_hotkeys.dm
- modular_coyote/code/pmon_actions.dm
- modular_coyote/code/pmon_mob.dm
- Fixes hotkeys not working for some, although some may need to reset their hotkeys to fix them.
:cl:
/:cl:
> [ready 2: merek smells] Revert "Revert "[ready] Loads of fixes and improvements""

- _maps/map_files/Pahrump-Sunset/i_hate_fenny.dmm
> Minor changes. Pausing for now.

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> Oops all frogs

- code/modules/jobs/job_types/oasis.dm
> secretary to council berson

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> Adds some gold and silver coins.

- code/game/objects/items/electrostaff.dm
- code/modules/fallout/obj/stack/f13Cash.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
- modular_citadel/code/modules/client/loadout/head.dm
title
:cl:
- Gob's kit (electrostaff / momento mori)
- Kelp's kit (Worn WT550, 1 reload, a shitty medkit)
- Added a bunch of flowers to the loadout menu
- Fixed a small issue with copper coin flavor text
:cl:
> Hats and things (should be good to merge)

- code/modules/mob/living/simple_animal/simple_animal.dm
> [ready if compiles] fixes creature examine pronouns

- code/modules/mob/living/emote.dm
title
it's literally the title
adds user.jitter to *twitch what is there to say
you twitch when you twitch
when you twitch, you twitch
I need to stop typing stuff at 4 am
:cl:
/:cl:
> adds twitching to *twitch

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> bad frogge

- code/modules/mob/living/carbon/carbon_sprint.dm
da math was reverseddxd AAA
:cl:
/:cl:
> fixes zoomies

- code/game/objects/items/melee/coyotemelee.dm
Getting these bad boys worked out, fr
:cl:
/:cl:
> Coyote Melee Tweaks

- code/game/turfs/closed.dm
Now coming to a tree near you.
:cl:
/:cl:
> The Wall Plappening

- code/game/objects/effects/effect_system/effects_animation.dm
> Fixes nodding shrinking you into a dot

- code/game/objects/effects/effect_system/effects_animation.dm
Makes the bag animations animate significantly faster.
:cl:
tweak: reduces bag animation.
/:cl:
> Shortens bag animations significantly

- code/game/objects/structures/beds_chairs/sofa.dm
> Taking the ratty out of the not so ratty looking sofa

- modular_coyote/code/_pmon_defines.dm
> hopefully this stops it from being on the creature list

- code/datums/traits/good.dm
- code/datums/traits/neutral.dm
- code/modules/mob/living/carbon/carbon_sprint.dm
zoomies got moved to neutral.dm, pretty sure it was by accident when multiple people were working on same files, now moving back to positive since da code is Fixed:tm: in this PR, as well, with visual confirmation of it actually working
:cl:
/:cl:
> fixes zoomies!

- code/modules/fallout/obj/food_and_drinks/food.dm
- code/modules/mob/living/emote.dm
Thanks, Fwoosh.  You chud.
Also adds more flirts.
:cl:
/:cl:
> Fallout 13 previous servers were racist any% speedrun (impossible)

- code/modules/clothing/head/f13factionhead.dm
- code/modules/clothing/under/accessories.dm
> han remembers clothing exists

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> Quick map fix

- code/modules/WVM/wmv_buyer.dm
on average increases hide prices to make it more worf, and also adds bones, while removing cloth and leather, since they're very, very ez to get en masse, and there's doubtlessly going to be 1000000 ways to get cheap ez cloth/leather. gives hides more of a purpose, now, as well, and this technically makes ranching more desirable, since it doubles the profits in some places
had a discord vote about it and dis won
:cl:
refactor: refactored …
> wvm buyer changes

- code/game/objects/effects/spawners/lootdrop.dm
- code/game/objects/effects/spawners/masterlootdrop.dm
- code/modules/fallout/obj/trash_stack.dm
> Fixes spawners again

- code/datums/components/spawner.dm
> Fixes covered spawners spawning shit

- code/game/objects/items/loadout_beacons.dm
- code/modules/clothing/glasses/_glasses.dm
We've come full circle.
https://youtu.be/5EXFilTUiko
:cl:
/:cl:
> Believe in me.

- _maps/map_files/Pahrump-Sunset/RockSprings.dmm
touches:
- old mango matt
- gas station
- enclave base (needs work)
- prison
- mansion
- some houses on the outskirts that technically now have more loot than ever
- gecker nest *geck
:cl:
/:cl:
> rocksprings loot

- code/datums/weather/weather_types/acid_rain.dm
- code/datums/weather/weather_types/cold_wave.dm
- code/datums/weather/weather_types/radiation_storm.dm
- code/datums/weather/weather_types/rain.dm
No more temperature snaps, a lot more rain and fog
> Changes up the weather weights

- code/game/objects/effects/spawners/masterlootdrop.dm
They don't work, they've never worked.  Why even have them?  Lets be real.
:cl:
/:cl:
> Pulls Molotovs from loot

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> Final laundrymat tadpoles

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
> A table for the undershop to undersell at

- code/modules/clothing/shoes/miscellaneous.dm
- code/modules/vehicles/scooter.dm
- modular_coyote/code/objects.dm
aerfggggggg
also attempt at wheelys fix
:cl:
/:cl:
> misc lore shtuff

- modular_coyote/code/objects.dm
> take me to snurch

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
> Genetics oops

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> More map touching

- code/game/objects/effects/spawners/masterlootdrop.dm
also moves boar to uncommon tools instead of common since it literally doesn't matter and it's roundstart and raging boar is fuckin COOl okay?
:cl:
/:cl:
> moves rising bass to rare

- code/datums/components/spawner.dm
Turns out that proc was there for a reason. Moved it so it'll only be special or something
> Makes special mob spawners actually spawn mobs

- code/controllers/subsystem/processing/quirks.dm
- code/modules/antagonists/wizard/equipment/spellbook.dm
- code/modules/projectiles/projectile/magic.dm
> Charge to 2 points

- code/modules/mob/living/living.dm
Should make sure if you despawn, you lose your spells
> when a mob is destroyed, remove their spells

- code/modules/antagonists/wizard/equipment/spellbook.dm
> more fixes

- code/modules/antagonists/wizard/equipment/spellbook.dm
- code/modules/projectiles/guns/magic/wand.dm
- code/modules/projectiles/projectile/magic.dm
> More magic tweaks

- code/modules/tgui_panel/tgui_panel.dm
- This may fix the fancychat not loading, but it might not. I don't have the issue of fancychat not loading on my local server so I can't test it- However, this does load fine so it's at least not going to break anything.
> Possibly Fixes Fancychat not Loading

- code/modules/antagonists/wizard/equipment/artefact.dm
> scrying orb timer

- code/modules/antagonists/wizard/equipment/artefact.dm
> scrying orb part 2: im sorry

- code/modules/antagonists/wizard/equipment/artefact.dm
> scrying orb part 3

- code/modules/clothing/under/costume.dm
I added the flags to allow the clothes to use digi sprites. for cheongsams and quipaos.
:cl:
fix: fixed mutant variables.
/:cl:
> Hopefully fixes Lunar clothes

- code/modules/client/client_procs.dm
- code/modules/tgui_panel/tgui_panel.dm
It probably works, but i'm not happy about it
> [ready] Automatically fixes the client's chat window 5 seconds after first connection.. yeah

- code/modules/antagonists/wizard/equipment/spellbook.dm
https://youtu.be/4cZqRzHnI8s
:cl:
/:cl:
> Releasing the wizards wizards.

- code/controllers/subsystem/matchmaking.dm
- code/game/machinery/slotmachine.dm
- code/game/objects/items/cards_ids.dm
- code/game/objects/items/loadout_beacons.dm
- code/game/objects/items/toys.dm
- code/modules/cargo/exports/materials.dm
- code/modules/cargo/packs/misc.dm
Changes references from caps to coins. Yay going through sevearal files using 'caps'
:cl:
/:cl:
> Cap killing part one

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- code/game/machinery/porta_turret/portable_turret.dm
- code/game/objects/buckling.dm
- code/modules/mob/living/simple_animal/hostile/f13/centaur.dm
- code/modules/projectiles/ammunition/_ammunition.dm
- code/modules/projectiles/ammunition/_firing.dm
- code/modules/projectiles/boxes_magazines/_box_magazine.dm
- code/modules/projectiles/boxes_magazines/internal/_cylinder.dm
- code/modules/projectiles/guns/ballistic/flintlock.dm
Fixes revolvers runtiming if they spawn with less than a full clender.
Fixes Lazy Larry runtiming cus he's buckled to `1`. Also makes him actually buckled to his sofa, and not smash shit. Also makes him his own mob type. Fun!
> Runtime Roundup

- code/modules/projectiles/guns/magic/wand.dm
> Wands charge

- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RockSprings.dmm
- code/game/objects/effects/spawners/masterlootdrop.dm
- code/modules/clothing/suits/arfsuits.dm
- modular_sunset/code/mob/renegade.dm
power armor remapping, adds stuff to rare armor pool to dilute stuff
:cl:
/:cl:
> meows at u

- code/datums/components/crafting/recipes/recipes_forge.dm
- code/datums/components/crafting/recipes/recipes_tools.dm
> workbench and smithing bench fix (good to merge)

- code/datums/traits/good.dm
- code/modules/vehicles/scooter.dm
> wheelys buff, deadeye/shar pcost down

- code/__DEFINES/inventory.dm
- code/game/objects/items/shields.dm
- code/modules/antagonists/wizard/equipment/spellbook.dm
- code/modules/projectiles/guns/magic/staff.dm
> Stick now not too big

- code/__DEFINES/radio.dm
- code/game/objects/effects/landmarks.dm
- code/game/objects/items/cards_ids.dm
- code/modules/jobs/job_types/oasis.dm
- code/modules/jobs/jobs.dm
- modular_citadel/code/modules/client/loadout/head.dm
- modular_citadel/code/modules/client/loadout/suit.dm
- modular_citadel/code/modules/client/loadout/uniform.dm
- strings/phobia.json
fixes bugs from #2144
:cl:
/:cl:
> [ready if ci] fixes the mayor and secretary job renames from #2144

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
- _maps/map_files/Pahrump-Sunset/RockSprings.dmm
Loot n shit, and timers
:cl:
/:cl:
> Redwater Update

- code/game/objects/items/loadout_beacons.dm
- code/game/objects/items/storage/survivalkit.dm
- code/modules/projectiles/guns/hoboguns.dm
- modular_citadel/code/modules/client/loadout/backpack.dm
Adds sling and slingstaff to improvised guns with updated descriptions on examine.
Adds jons firebow to the tribal (SB) loadout, and to the loadout menu for the deranged.
:cl:
/:cl:
> Sling, Slingstaff & Firebow additons

- code/modules/projectiles/guns/hoboguns.dm
adds the fact it can use literal rocks, lmao
:cl:
/:cl:
> Updates autopipe desc

- code/modules/projectiles/ammunition/caseless/misc.dm
- code/modules/projectiles/guns/hoboguns.dm
Lets you know how you can get your own.
:cl:
/:cl:
> Changes the desc for bricks and rocks

- code/datums/components/crafting/recipes/recipes_assemblies.dm
- code/game/objects/effects/spawners/masterlootdrop.dm
- code/game/objects/structures/fireplace.dm
- code/modules/fallout/obj/structures/mob_spawners.dm
- code/modules/jobs/job_types/oasis.dm
- code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
- code/modules/projectiles/guns/mods/mods.dm
Co-authored-by: Superlagg <Superlagg@users.noreply.github.com>
makes som edits to the masterlootdrop based on feedback.
tones down the spawner for gel cubes so people aren't overwhelmed as much.
gives the banker a premium gun instead of a lawman robust gun.
gives the prewar scope a sprite.
massively buffs the stone fireplace duration, tones down its volume, and makes craftable.
:cl:
config: changed some …
> some fixins

- modular_citadel/code/modules/client/loadout/__donator.dm
givs yours truly a loadout box containing just a dna injector for spawning snow sheets
:cl:
/:cl:
> fuzzy loadout box

- code/datums/outfit.dm
- code/modules/fallout/obj/manual/basic_advice.dm
> CB Guide Update

- code/modules/mob/living/simple_animal/hostile/f13/raider.dm
to help hit a breakpoint
:cl:
/:cl:
> Lowering some raider health

- code/game/objects/items/melee/f13powerfist.dm
- code/modules/projectiles/guns/ballistic/shotgun.dm
moves the ballistic fist to the shotgun file where I can actually find it, and updates it to the new format
:cl:
/:cl:
> ballistic fist gnawing

- code/modules/antagonists/wizard/equipment/spellbook.dm
no more stealing coins out of peoples pockets because you left a copper on the sidewalk, as funny as that honestly is.
:cl:
/:cl:
> Turning off Summon item until its refactored

- code/modules/clothing/head/misc.dm
> typo murder

- code/modules/mob/living/emote.dm
side-eye
throwback
oopstouch
:cl:
/:cl:
> 3 more flirtmotes

- code/modules/WVM/wvm.dm
> Fixes silver coin prices in vendors

- code/modules/clothing/suits/wiz_robe.dm
- modular_citadel/code/modules/client/loadout/backpack.dm
- modular_citadel/code/modules/client/loadout/head.dm
- modular_citadel/code/modules/client/loadout/suit.dm
Adds wizard robes and hats to the loadout (and removes the needless code on them)
Adds the wizard broom too. Can't be a wizard without it!
:cl:
/:cl:
> Yer a wizard harry

- code/datums/components/crafting/recipes/recipes_tailoring.dm
> Welding helmet recipe

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> Fixes nash recycler conveyors

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> fixes a tent

- code/modules/clothing/suits/arfsuits.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
> Loadout for Aldric (good to merge if it passes checks)

- code/datums/traits/good.dm
> comments out wasteland wizard

- code/game/objects/items/melee/coyotemelee.dm
> Sadly nerfs pike and sarissa because their math is FUCKED

- code/modules/vending/_vending.dm
> Should remove vending machine head gib RR

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RockSprings.dmm
- code/game/area/areas.dm
- fortune13.dme
- modular_coyote/code/modules/area_blurb.dm
- modular_coyote/code/modules/mapping/areas.dm
adds area blurbs, blurbs that appear whenever you enter an area
:cl:
/:cl:
> area blurbs!

- code/modules/clothing/shoes/f13.dm
- modular_citadel/code/modules/client/loadout/shoes.dm
- Makes tough feet unremovable and un-droppable so you cannot lose them (unless you lose your whole body or your legs but that's rare).
- Also fixes them being capitalized as if they were a proper noun.
> [ready] glues tough feet to your feet

- code/game/objects/structures/watercloset.dm
> [ready] showers clean your neck and suit storage slots

- code/__DEFINES/armor.dm
Adds Energy armor tokens. That's literally it.
:cl:
- Adds Energy armor tokens
:cl:
> Armor define expansion (good to merge if checks pass)

- code/modules/projectiles/guns/magic/staff.dm
lowers the charge to 1 charge every 30 seconds
BUGS: the correct projectile isn't being shown, will fix later when i stop getting back to back phone calls
everything else works
> unstable staff

- code/datums/components/crafting/recipes/recipes_tailoring.dm
> welding hardhat crafting fix (good to merge if it passes checks)

- code/game/objects/items/melee/f13onehanded.dm
- code/game/objects/items/tools/crowbar.dm
whack a mole, or something
:cl:
/:cl:
> Shovel melee

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RockSprings.dmm
yar har and all that
:cl:
/:cl:
> booty cards

- code/game/atoms.dm
> Fixes 570,000 runtimes

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> Oops,. I forgot to save

- code/modules/mob/living/emote.dm
Now you can flirt with others from across a table.
:cl:
/:cl:
> upping flirt emote range to 2

- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
- _maps/map_files/Pahrump-Sunset/RockSprings.dmm
- modular_coyote/code/modules/mapping/areas.dm
nerfs loot in SE redwater military dungeon
buffs loot at end of underground supermutie dungeon
adds lotsa area desc
:cl:
/:cl:
> lots of map changes

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RockSprings.dmm
I might have put down a few too many good ones lol
:cl:
/:cl:
> Pulling back bounties a hair

- modular_coyote/code/modules/area_blurb.dm
> changes narrate color to light blue

- code/modules/fallout/obj/structures/simple_door.dm
> [ready] fixes gmod error messages on doors

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> Adds the coin conversion machine to the bank

- code/controllers/subsystem/statpanel.dm
> Back to round number, lol

- code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
Fixes a loadout issue I accidentally overlooked when making the funny loadout. Pvt. Eye was stuck in the foreverbox :(. Also adds an LT pin into the loadout as I forgot it the first time around, and fixes Pvt. Eye spamming the shit out of text chat. 
- [ Y ] You tested this on a local server.
- [ Y ] This code did not runtime during testing.
- [ Y ] You documented all of your changes.
:cl:
add: Pvt. Eye's pet carrier
tweak: added LT pins to loadout
fix: stopped Pvt. Eye from spamming the shit out of text chat
/:cl:
> minor loadout fix (+tiny edit)

- _maps/map_files/Pahrump-Sunset/Garland-City.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
Fuck you to, strong dmm
:cl:
/:cl:
> Redlick & Garland City Take 2

- code/modules/mob/living/simple_animal/hostile/f13/centaur.dm
No more injecting fev from centaurs
:cl:
/:cl:
> removes them injecting fev.

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
It works, somehow.  Honestly, I'm kind of surprised.
:cl:
/:cl:
> Request Console for the Trade Workers

- _maps/pahrump-everything.json
> Reverting the changes to this json file

- code/modules/mob/living/simple_animal/hostile/animalhostile.dm
- code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm
- code/modules/mob/living/simple_animal/hostile/f13/centaur.dm
- code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
- code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
- code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
- code/modules/mob/living/simple_animal/hostile/f13/insects.dm
- code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
- code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
- code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
- code/modules/mob/living/simple_animal/hostile/f13/wolf.dm
- code/modules/mob/living/simple_animal/hostile/synth.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- modular_coyote/code/mob.dm
By replacing it with emote_taunt, which does work.
lmfao lol
:cl:
/:cl:
> Fi(o)xes Aggrosound not working

- code/modules/mob/living/simple_animal/hostile/f13/raider.dm
- code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
- code/modules/persistentcurr/persistentcurrmachine.dm
- code/modules/vending/_vending.dm
- code/modules/vending/matvend.dm
> More caps to coins

- code/game/objects/items/melee/f13onehanded.dm
What a fantastic mechanic, so good I should just tear it out by the toes.
:cl:
/:cl:
> The Forever Update: Removal of Armor Pen

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver-Upper.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
- code/game/objects/structures/spirit_board.dm
- code/modules/mob/living/simple_animal/hostile/f13/raider.dm
Preparing my brain for making a non euclidian dungeon, because I fucking hate everything.
:cl:
/:cl:
> Updating the Mansion a bit

- _maps/map_files/Pahrump-Sunset/RedRiver-Upper.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
- code/__DEFINES/preferences.dm
- code/game/objects/effects/landmarks.dm
- code/modules/jobs/job_types/hells_nomads.dm
- code/modules/jobs/job_types/wasteland.dm
- code/modules/jobs/jobs.dm
*as well as adding the Ashdown Overlook Wastelander, a wastelander job that will spawn in the same town as the Hells Nomads and can work for them when they want to be 'off duty' or something similar.
:cl:
/:cl:
> Map Fixes for Ashdown Overlook*

- _maps/map_files/Pahrump-Sunset/RedRiver-Upper.dmm
> More fixes, lmao

- code/modules/mining/lavaland/necropolis_chests.dm
- code/modules/mob/living/carbon/human/species_types/ghoul.dm
Gives ghouls hardcrit again (gives them back some defense to accommodate)
Removes no_hardcrit from memento mori
> Ghoul Immortality begone

- _maps/map_files/Pahrump-Sunset/RedRiver-Upper.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
> Fuckyoutostrongdmm

- code/datums/components/lore_dump.dm
- code/datums/components/reskin.dm
- code/modules/projectiles/guns/ballistic/rifle.dm
- fortune13.dme
- strings/martini_henry.txt
The martini henry is now a reskin of the gras. also fixes the gras icon state.
P14 is a hunting rifle skin
removed the jungle carbine skin, cus its a different gun
> Reshuffles some skins

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver-Upper.dmm
- code/datums/components/crafting/recipes/recipes_assemblies.dm
- code/game/turfs/simulated/wall/mineral_walls.dm
- code/modules/fallout/turf/walls.dm
> Mapneverending

- code/__DEFINES/armor.dm
ROLL IT BACK, BABY.  ROLL IT DOWN HILL AND THROW IT BACK.
:cl:
/:cl:
> Redefining the meisters sharmor (shit armor)

- code/modules/surgery/organs/tongue.dm
> Should fix the lizard tongue runtime

- code/modules/surgery/organs/tongue.dm
what better way to fix an untested PR than with another untested PR.
> Should fix tongues

- code/modules/mob/living/carbon/carbon_sprint.dm
Tested and works.  Zoomies last about 40% longer and super lasts a LONG time.
:cl:
/:cl:
> Fixing zoomies on my phone with no internet

- code/modules/projectiles/guns/ballistic/automatic.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
pancake kit
guy drooled about tacticool stuff enough 
it's literally just a varmint reskin in a kit
:cl:
add: Added new thing
/:cl:
> Kenny tries to do custom kits again

- modular_citadel/code/modules/client/loadout/__donator.dm
This is me adding a loadout for my characters.
:cl:
add: Added a loadout for my characters
/:cl:
> Pawn's Loadout

- code/_globalvars/lists/flavor_misc.dm
- code/datums/accents.dm
- code/modules/surgery/organs/tongue.dm
> more tongues and accents

- code/modules/projectiles/guns/energy.dm
- code/modules/projectiles/guns/energy/plasmaf13.dm
No longer rotates when wielding laser or plasma weapons
:cl:
/:cl:
> No idea why, but it's fixed

- code/__DEFINES/blender_brain.dm
- code/__DEFINES/maths.dm
- code/__HELPERS/unsorted.dm
- code/game/objects/items/devices/portable_blender_brain.dm
- code/game/objects/items/devices/portable_blender_brain_impulses.dm
- code/game/objects/items/devices/portable_blender_brain_memories.dm
- code/game/objects/items/devices/portable_chem_blenderbelt.dm
- strings/blenderbrain_blender.json
They'll now actually listen to mute commands, and not *fucking talk all the goddamned time*
> makes blenders much less chatty

- code/modules/clothing/suits/arfsuits.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
> Adds a reskinned leather coat for the Drgn

- code/modules/mob/living/simple_animal/hostile/f13/centaur.dm
> Abom sounds down again

- code/modules/vore/eating/vorepanel.dm
> [ready] Fixes #2084

- _maps/map_files/Fortress Nash/FortNash1.dmm
- _maps/map_files/Pahrump-Old/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset - Backup/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Temp Map Storage/Pahrump-Sunset - Outdated.dmm
- code/modules/clothing/under/f13.dm
> [ready] fixes 50s dress having a missing sprite

- tgui/packages/tgui/interfaces/PersonalCrafting.js
So people know to change categories to fix the issue
:cl:
/:cl:
> Adds the crafting note

- code/modules/food_and_drinks/food/snacks_pastry.dm
- code/modules/mob/living/simple_animal/friendly/farm_animals.dm
A small pull to hopefully fix some of the integration test's recorded fail-states and some runtimes I've seen it output.
:cl:
fix: changed the code for some of the peanut butter pastries to use the actual reagent instead of trying to make them use an object.
tweak: added some code to the udder initialization for big horner calfs since in their current state, the code tries to add milk to improperly initialized udders and makes a runtime. Hopefully this fixes that.
/:cl:
> Integration failure/runtime fixes

- code/modules/mob/living/simple_animal/simple_animal.dm
THe floor. The answer is the floor, its always the floor.
> Fixes a runtime with mobs not knowing where to drop stuff

- code/modules/projectiles/guns/ballistic/shotgun.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
> Jaggachi kit

- modular_citadel/code/modules/client/loadout/__donator.dm
Title
:cl:
- Added a loadout item for Drgn
- Removed my worn WT550 and replaced it with an engineering satchel because style > function
:cl:
> Loadout stuff (good to go)

- code/game/objects/structures/bedsheet_bin.dm
kill murder destroy
:cl:
/:cl:
> Thats wizard, chief

- code/modules/mob/living/life.dm
Jon I grab you by the antlers and comment out your horns.
> Fixes fire

- code/controllers/subsystem/vote.dm
- code/modules/client/verbs/ooc.dm
> More Obfuscation

- _maps/map_files/Pahrump-Sunset/i_hate_fenny.dmm
Just gotta add button to gate, watchtowers, and puzzle piece the upper levels where they need to be. I'm exhausted, will do it tomorrow, probably.
> Castle Nash 95% done

- code/controllers/subsystem/progress_bars.dm
- code/datums/components/crafting/crafting.dm
- code/datums/components/storage/storage.dm
Turns out the crafting menu never expected a result to be a turf. But then they never expected Fenny =3
> Fixes bricks bricking crafting, and some progbar runtimes

- _maps/map_files/Pahrump-Sunset/i_hate_fenny.dmm
> More updates for Nash 3.0

- code/modules/clothing/suits/aurora_suits.dm
- modular_citadel/code/modules/client/loadout/suit.dm
Whoopsie, wrong path.
:cl:
/:cl:
> Fixes the suits

- code/modules/WVM/wvm.dm
- code/modules/clothing/gloves/f13gloves.dm
Touches WVM and makes a new glove type
:cl:
- Changes the Weapon vendor to have updated prices
- Changes the Crafting vendor to have updated items and prices
- Adds the Military Engineering Gloves. Literally just insulated/burn-proof Military Gloves that can be bought
:cl:
> Some kelp touches (If it passes checks, it's good)

- code/game/objects/effects/misc.dm
Some day i'm gonna make people fall down these and stone themselves if they're overburdened and carrying a half-eaten cockatrice.
> Adds fake stairs that go no where

- code/game/objects/structures/stairs.dm
- code/modules/vending/_vending.dm
> makes stairs godmode, also fixes hungry vendors

- code/modules/projectiles/guns/ballistic/automatic.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
> Update's Gamma's kit, adds lowpower's kit

- code/modules/hydroponics/grown/peach.dm
- code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
I made peach cider.
:cl:
add: Added peach cider
/:cl:
> Peach cider

- modular_citadel/code/modules/client/loadout/__donator.dm
It's a shoddy vest, what can I say?
Also gruntcop for gruntcoppage
:cl:
/:cl:
> Rubeebee's and Delta_Dav's kits

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
> Map fixes don't stop for breaks

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
>  It never ends, this shit

- code/modules/mining/equipment/mining_tools.dm
Overhauls picks, drills, and shovels so they're viable weapons
:cl:
- Shovels now deal basic 1h/2h damage and have reach
- Pickaxes are fairly brutal, but bulky, weapons across the board; actual melee weapons are faster tho
- Drills have good base damage, don't really benefit from 2h, and are just as slow as picks despite doing less damage per attack; you're not Simon, sadly. But they're still viable-ish
:cl:
> diggy diggy hole (merge if checks pass and all that)

- modular_coyote/code/mam_horns_coyote.dm
<3 Thanks Desa, big hugs, sorry for not knowing they were yours!
:cl:
/:cl:
> Crediting the sheep horns to Guidesa

- code/datums/components/spawner.dm
Dunno why mobs keep building nests in nullspace.
> Fixes like 1400 runtimes

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
Tosses a slot machine into nash and ashdown
Squeezes in a single booth in the nash bar.
Tosses common loot spawns all over nash.
Makes the tribal cave town-basement _thing_ into this cave-people aesthetic place, may have gone too far with making it feel lived in, used a lot of the filled containers/closets from nash2 tribal, threw in some of my own, idk.
The entrance-tunnel things are jank, hate em, better than ladders but I feel inclined to replace them with stairs already. Redoing the undernash feels like am massive pain in the balls.
fixes some weird see-into-house things to do with the outside walls being transparent
Redlick's oddly deleted bridge got replaced with a ruined, mirelurk infested, girder-blocked thing that's honestly more dangerous than just fording the river. It felt …
> Spruces up Nash3 (and stuff)

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
fixes layer issue with a carpet
fixes railing around nash
fixes roofs
fixes
:cl:
/:cl:
> i love mapping

- modular_citadel/code/modules/client/loadout/__donator.dm
ZomboTheSkunk's kit, just a crown, that's it
:cl:
/:cl:
> Cynthia kit

- code/game/objects/items/melee/energy.dm
Tweaks TG E-swords to be comparable to other weapons. Very powerful.
:cl:
- s w o r d
:cl:
> Buffs basic e-swords (good to go if it passes checks)

- code/modules/admin/verbs/adminhelp.dm
- code/modules/client/client_procs.dm
Send more stuff to the admin Discord chat
:cl:
admin: Now adminhelps come in on Discord all the time!
/:cl:
> Make some small changes

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Just needs some changes from Fenny (the billboard thing). I also added a new hospital for the clinic to use instead of the one in Nash. Just outside, I want approval before I push push this though, so.. this will be a draft until Fenny and I talk about it. (That and the old clinic will need replaced.)
> Makes the city a bit more homey

- code/modules/projectiles/guns/ballistic/flintlock.dm
Took the new melee system off the smaller than full sized flintlocks.
:cl:
/:cl:
> Rearranged Flintlock Melee

- code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
Still trying to hunt down that crash bug
:cl:
/:cl:
> We do a little testing.

- _maps/map_files/Pahrump-Sunset/RedRiver-Upper.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
More counter-space, moved the arcade machines, fixed the walls splitting the booth in an odd way, and changes the stair direction to make it so people don't just constantly bump into patrons at the counter.
:cl:
add: More space to the bar counter
add: Shimmied around the arcade machines, stairs, and barsign to actually advertise the bar _outside_ the bar.
del: Removed a single cave of mirelurks and its associated uncommon spawn.
/:cl:
> Changes to Ashdown's bar.

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
> Realigns 2nd floor.

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Fixes the misalignment as per #2461, but also re-adds chem machines to the bottom floor, fixes the misaligned window, and fixes the roof tiles/connects the upper floor for thematic consistency. Also gives the clinic a roof-access door.
:cl:
add: Clinic roof access and rooftop tiles
fix: Rooftops, mangled window placement, lost chem machines. missing floor tiles, etc.
/:cl:
> Nash 2 Clinic Fixes

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver-Upper.dmm
Adds a light to the chem room. Changes some curtain density to avoid blocking the pool.
:cl:
add: Light to Nash chem room
fix: Curtain density.
/:cl:
> Adds a light to the Nash clinic- minor Ashdown fixes.

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
I think I received the best compliment I possibly could've on my work with Ashdown's bar, that it was unfair and I'd have to make another for Nash's, so here's that PR!
:cl:
add: Poker room, arcade 2nd floor, private booth, big group booth 1st floor. Redecorating supplies and instruments to the barkeep's quarters.
del: The single heart sign.
/:cl:
1st Floor:
2nd Floor:
> Nash Bar Parity

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
this should fix its power issues
:cl:
/:cl:
> Setting the clinics area back to hospital/clinic

- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
This wasn't an okay combo when we tested magic, and its still not now.  Wowee zowee lmao
:cl:
/:cl:
> Naw, I think not chief

- code/game/objects/items/loadout_beacons.dm
Can't spamdupe loadout boxes anymore =3
> fixes a silly exploit

- code/datums/traits/good.dm
> Adds weapons of texarkana to weaponsmith

- code/modules/cargo/packs/security.dm
You don't need hilariously overpowered xenobiology stuff at round start for nearly nothing.
> no more hilariously op shit for basically free (removes slimecores from shop)

- code/datums/components/spawner.dm
- code/modules/fallout/obj/structures/mob_spawners.dm
aDDED several vars that spawners can save of mobs
also added a var on spawner nests to let them have custom factions set
> mobs save more cool stuff

- code/__DEFINES/say.dm
- code/modules/mob/living/emote.dm
- code/modules/mob/say.dm
Listen, it's not PRETTY, but its better than just NOT KNOWING, which is where most players are.  We can beautify it later.
:cl:
/:cl:
> Quality of Life Say/Emote Info

- code/datums/components/spawner.dm
mmmmf if I wasnt working on merp, I would refactor this fucker's ass into the milky way
> armor datms are wierd

- _maps/_basemap.dm
- _maps/map_files/Pahrump-Sunset/Westlands.dmm
- _maps/pahrump-everything.json
- code/modules/mapping/map_config.dm
Actually compiles the map and un-fuckinates the configuration file. Empty z's? They're gone too.
:cl:
/:cl:
> Compile the map and actually use the thing

- code/modules/mob/living/simple_animal/hostile/f13/insects.dm
- code/modules/mob/living/simple_animal/hostile/hostile.dm
Reverts ARF-SS13/coyote-bayou#2419
might be bork?
> Revert "In code Implementation for mob pathfinding."

- code/datums/components/spawner.dm
- code/modules/mob/living/simple_animal/hostile/hostile.dm
Mobs will now actually fully wake up and act like mobs after they wake up.
Also makes them more aggressively go to sleep.
> Fixes mob post-nap grogginess

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Was no need for two farms in Nash, so replaces the smaller farm near the guard shake with a hot tub building. 
Small, but cozy and I wanted a hot tub to lounge in. 
:cl:
/:cl:
> Small hottub

- code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
> stop gibbing pls

- code/controllers/subsystem/itemspawners.dm
- code/datums/components/spawner.dm
Fixes spawners not deleting themselves when they should
> everyone dies, the end

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
> Quick update

- _maps/pahrump-redriver-westlands.json
Adds the missing map rotation to the list so they can be enabled
:cl:
/:cl:
> Make map rotations possible again

- modular_citadel/code/modules/client/loadout/__donator.dm
> Updates ARandonHyena's donator kit

- modular_citadel/code/modules/client/loadout/__donator.dm
Kits the kit, kit. 
Kit.
:cl:
/:cl:
> Updates Norads' kit

- code/game/objects/items/circuitboards/machine_circuitboards.dm
vr a fuck, 6,024,429,498,945 dead runtimes
:cl:
/:cl:
> Removing vr boards

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver-Upper.dmm
Gives Ashdown a cell-charger, gives Nash's clinic 3 rad-away packs and a makes curtains 'work' though at the cost of being openable from the outside.
:cl:
add: 3 Rad-Away to Nash clinic, Cell Charger for Ashdown workshop.
fix: Nash Clinic Curtains
/:cl:
> Clinic Rad-Away, Curtain Fixes, Ashdown Cell Charger

- code/controllers/subsystem/COOLBOOKss.dm
- code/controllers/subsystem/atoms.dm
- code/game/atoms.dm
- code/game/mecha/mecha.dm
- code/game/mecha/mecha_actions.dm
- code/game/mecha/mecha_control_console.dm
- code/game/mecha/mecha_topic.dm
- code/game/objects/objs.dm
- code/modules/admin/admin.dm
- code/modules/atmospherics/gasmixtures/gas_mixture.dm
- code/modules/atmospherics/machinery/portable/canister.dm
- code/modules/buildmode/submodes/advanced.dm
- code/modules/mob/living/simple_animal/friendly/farm_animals.dm
- code/modules/projectiles/boxes_magazines/_box_magazine.dm
- code/modules/projectiles/guns/ballistic.dm
Mechs and cannisters no longer runtime, and in fact, no longer have anything to do with atmos.
Admin spawned guns will spawn will full ammo.
Animals with nonexistant udders no longer runtime when they try to lactate.
> Runtime Roundup 6-11

- code/modules/mob/living/say.dm
> Fixing whisper range (with the help of a danimal)

- code/game/atoms.dm
- code/modules/admin/admin.dm
- code/modules/buildmode/submodes/advanced.dm
- code/modules/projectiles/boxes_magazines/_box_magazine.dm
> Roundtime Runup fuck

- code/modules/projectiles/boxes_magazines/_box_magazine.dm
- code/modules/projectiles/guns/ballistic.dm
> fixes bullet

- code/modules/mob/dead/new_player/sprite_accessories/_sprite_accessories.dm
- code/modules/mob/living/carbon/human/species.dm
> Actually adds the togglable sex mask

- modular_citadel/code/modules/client/loadout/__donator.dm
> Updates Tasalds' kit

- code/game/objects/items/validball.dm
Lets players know when the validball becomes detectable.
:cl:
/:cl:
> Validball notice

- code/modules/clothing/suits/utility.dm
Title
:cl:
- Makes the bomb suit have basic Heavy Armor stats/slowdown along with the hood
:cl:
> Fixes the EOD suit (good to go if it passes checks)

- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
https://www.youtube.com/watch?v=zwZISypgA9M
> shhh its a secrit..

- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
Have to block this off, cause had found that there was a way into the secrit area through a means that wasn't intended.. then showed two people how to do it.
Fixes a weakpoint, you can't bomb your way in anymore.
> Lee forcing my hand >:((((

- code/_onclick/item_attack.dm
- code/modules/mob/living/simple_animal/animal_defense.dm
Now mobs will actually use their melee armor. was  broken before!
> fixes melee ignoring mob armor

- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/emote.dm
:cl:
add: Emote and fix.
/:cl:
> Two Change

- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
Adds a Vertibird drop-point to Ashdown. That's it.
:cl:
add: Adds a Vertibird drop-point to Ashdown.
/:cl:
Here it be:
> Adds a Vertibird point to Ashdown

- modular_citadel/code/modules/client/loadout/__donator.dm
> potato gobbo gear

- code/modules/mob/living/carbon/carbon.dm
displays how many licks you got left!
:cl:
/:cl:
> lick counter!

- code/__DEFINES/mobs.dm
- code/modules/fallout/obj/food_and_drinks/food.dm
- code/modules/mob/living/simple_animal/hostile/retaliate/deathclaw
Currently; This is just a test. It **_'should'_** be ready to merge, long story short; It permits deathclaw ranching. Is it safe? Oh goddess no, is it cool. Ye. 😎
:cl:
add: Added new deathclaw subtype and the ability to literally ranch deathclaws.
/:cl:
> Deathclaw eggs

- code/modules/cargo/exports/misc_export.dm
Makes forged weapons have a small value in the store, meaning blacksmiths can make some cash for their work. Right now, It ain't much, but it's honest work.
:cl:
add: Added values to forged weapons.
/:cl:
> Adds sale value to forged weapons.

- modular_citadel/code/modules/client/loadout/uniform.dm
Loadouts didnt like the navy uniform, so I made it two of them.
> Fixes a loadout runtime

- code/modules/WVM/wmv_buyer.dm
- code/modules/WVM/wvm.dm
Bearpelts and Nightstalker pelts now sell.
You can now buy advanced medical books, SCAV! issue 1 and Weapons of Texarkana and the Nash Defense Force. They're more expensive than the other books; I'm not giving them away. Prices can change or they can be completely removed, don't tempt me.
:cl:
tweak: tweaked a few vendors.
/:cl:
> Vendor touchy-touches

- code/controllers/subsystem/dummies.dm
- code/game/objects/items/mannequin.dm
Cute staticky mobs should turn into more than 1 person
> Fixes mannequins

- code/game/objects/items/implants/implant_misc.dm
Missed a line, making people throw up.
> Fixes the adrenal implants again

- code/modules/projectiles/guns/ballistic/automatic.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
And culling some shit from my own loadout.
:cl:
/:cl:
> Fixing the Mac-10s Supressor Offset

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver-Upper.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
Yea, I did a few things.  I guess.
:cl:
/:cl:
> Fenny touches the map part 6,342,332

- code/_onclick/item_attack.dm
- code/game/objects/items/loadout_beacons.dm
buffs big & lil leagues a bit
removes some of the wackier round start weapons from loadout selection so they can go be loot
:cl:
/:cl:
> Some Weapon changes

- code/modules/projectiles/guns/ballistic/rifle.dm
> Fixes mosins in the wild

- _maps/map_files/Pahrump-Sunset/RedRiver-Upper.dmm
So people don't have to
:cl:
/:cl:
> Removes a fence from ashdown

- code/game/objects/items/implants/implant_misc.dm
- code/modules/movespeed/modifiers/reagents.dm
- code/modules/reagents/chemistry/reagents/medicine_reagents.dm
The implant no longer ODs you.
The adrenaline juice gives you 50% DR toward brute and burn while active.
The juice lasts a bit longer.
The juice also makes you run a bit faster.
The implant gives more epi, and a little atropine and protozine, just in case you were kicked into hardcrit by a supermob.
> Tweaks the adrenal implant

- code/game/machinery/limbgrower.dm
- code/modules/research/designs/limbgrower_designs.dm
Limbgrower should hopefully be able to make genitals; 'cause why not?
:cl:
add: Added new limbgrower recipes
/:cl:
> Dong printer

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
> I map for my entire life

- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
> No, I don't think so chief.

- modular_citadel/code/modules/client/loadout/__donator.dm
Title.
:cl:
- Added the cosmetic Chinese stealth suit/helmet to Tox's loadout
:cl:
> Tox Loadout Update (good to merge if it passes checks)

- code/__HELPERS/_lists.dm
- code/__HELPERS/unsorted.dm
- code/controllers/subsystem/dummies.dm
- code/game/objects/items/mannequin.dm
- code/modules/admin/create_mob.dm
- code/modules/awaymissions/corpse.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/carbon/human/human.dm
- code/modules/research/designs/limbgrower_designs.dm
Dumies no longer make fuckloads of runtimes
> fixes dummies 

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
-hellpig mi-ga-ration
-added some buildans to da redlick z
-tearin da roads up chief
-shits gettin real ugoluggo
https://youtu.be/nU1VfYYKMDk?list=RD2LkVKCWL0U4
:cl:
/:cl:
> licking the map

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
> The rotational exageration of the cuckold council

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RockSprings.dmm
I am going insane help
:cl:
/:cl:
> I touch the map and the map touches back

- code/datums/components/storage/concrete/belts.dm
This is a simple fix, allowing you to put circular saws, alien saws and laser scalpels into medical belts.
:cl:
fix: fixed fucky storage of med belts
/:cl:
> Update belts.dm (Should be ready)

- code/game/objects/items/stacks/sheets/mineral.dm
- code/modules/reagents/chemistry/recipes/slime_extracts.dm
- code/modules/research/xenobiology/xenobiology.dm
READY
nerfs some slime stuff to make it more modestly acceptable for the wastes
:cl:
/:cl:
> slime stuffs!

- code/modules/clothing/spacesuits/hardsuit.dm
- code/modules/projectiles/guns/energy/plasma_cit.dm
Makes the soviet hardsuit in the PLA bunker have reinforced combat armor value and slowdown so it's not solely cosmetic, while reworking the laser AK in there to be something else than the vanilla SS13 laser rifle it currently is, changing it into a soviet version of the RCW, with the capacity to self charge it's cell, but unable to be reloaded in any other way besides waiting.
RinPin :cl:
Tweak : Soviet hardsuit has armor now, laser AK were reworked into self charging RCW's analogues
/:cl:
> Soviet hardsuit +  lasers AK rework

- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
snanks snafterglow, you actually did something worthwhile. :)
:cl:
/:cl:
> smissing smires

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
Adds a pool just above heavens night by quite a few who requested one. 
:cl:
/:cl:
> Adds a pool

- code/datums/martial/sleeping_carp.dm
> okay you can have your light speed dodges

- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
- _maps/map_files/Pahrump-Sunset/RockSprings.dmm
> Mmmlemming maps makes me merry

- code/controllers/subsystem/job.dm
- code/modules/client/preferences.dm
So, your loadout gear will no longer fight for the last suit standing, and they'll all go into your bag.
However, you can only choose 4 *free* things from each category. Things that cost points arent restricted by this!
> Disables loadout displacement

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
Adds some extra fluff, the chief of police's office in the texarkana PD building on the second floor.
> Minor Map Tweaks

- code/modules/WVM/wmv_buyer.dm
fortunes were broke, now they fix
> Fixes fortunes

- code/modules/projectiles/ammunition/energy/plasma.dm
> ITS BULLET HELL IN HERE HOLY SHIIIIT

- modular_citadel/code/modules/client/loadout/__donator.dm
<I hecked up and renamed the wrong kit earlier.>
:cl:
add: Swapped the names of two loadouts to be correct.
/:cl:
> Mistakes were made.

- code/game/objects/items/melee/coyotemelee.dm
I'm a dirty Nobushi kickspammer, feel my slipper >:D
:cl:
/:cl:
> Tox's test PR

- modular_citadel/code/modules/client/loadout/belt_loadout.dm
- modular_citadel/code/modules/client/loadout/suit.dm
- modular_citadel/code/modules/client/loadout/uniform.dm
<!Me adding a few things to the loadout, iunno. Was out of desire, and learning things.>
:cl:
/:cl:
> Jaggachi's electric boogaloo

- modular_citadel/code/modules/client/loadout/shoes.dm
- modular_citadel/code/modules/client/loadout/suit.dm
- modular_citadel/code/modules/client/loadout/uniform.dm
exactly what the title says
Rinpin :cl:
tweak: cosmetic clothing cost 0 now
/:cl:
> Makes cosmetic uniforms and unarmored / non mechanical clothing cost 0 points

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver-Upper.dmm
> Readds fucking color mates to the spawn points

- modular_citadel/code/modules/client/loadout/glasses.dm
Adds a cybernetic eyepatch to the loadout, cosmetic only, github screwed up the first one.
> Github why (second attempt at eyepatch)

- code/_globalvars/lists/maintenance_loot.dm
- code/game/objects/items/loadout_beacons.dm
Adjusts the flashlight so it isn't in a weird spot on the medusa, adds a weapon case for both so they can spawn with ammo, and adds them both to the loot pool
> Fixes for hermes and medusa

- _maps/map_files/Pahrump-Sunset/Westlands.dmm
unga bunga, my dude
:cl:
/:cl:
> Removes westlands wabbawater

- code/modules/fallout/obj/structures/cargocrate.dm
- modular_coyote/code/objects.dm
Fuel pumps and cargo crates.
:cl:
add: Added more salvagables
/:cl:
> More salvagables. (should be ready)

- code/_globalvars/lists/maintenance_loot.dm
- code/game/objects/effects/spawners/masterlootdrop.dm
- code/game/objects/items/melee/f13onehanded.dm
> Power fist fix 100% real no fake

- _maps/map_files/Pahrump-Sunset - Backup/Dungeons.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
- _maps/map_files/Pahrump-Sunset/Westlands.dmm
- _maps/map_files/generic/CentCom.dmm
- code/modules/fallout/obj/structures/cargocrate.dm
And atmos shit die die die die die die die die die die die die die die die die die die die die die die die die die die die die die die die die die die die die
:cl:
/:cl:
> I hate cameras to death

- code/game/objects/effects/spawners/masterlootdrop.dm
- code/modules/projectiles/guns/ballistic/automatic.dm
- code/modules/projectiles/guns/ballistic/pistol.dm
This PR changes the guns to be more C.B lore friendly, also adds the M3 SOCOM and T25 Carbine to the common loot pools for others to find.
:cl:
/:cl:
> New names for the guns + added to the common loot pool.

- code/modules/WVM/wmv_buyer.dm
Now random fortunes wont just be bad ones. Also adds in some more of them. Birch.
> Beefs up fortunes

- code/modules/mob/living/simple_animal/hostile/hostile.dm
Turns Dodging on for *all* mobs at 30%.  They seek to survive.  They seek your blood.  Beware.
:cl:
/:cl:
> Let Them Dodge

- code/modules/WVM/wmv_buyer.dm
So you wont see any more fortunes for tk42069
> Fortunes no longer print out fortunes for people who havent joined the game

- code/datums/components/crafting/recipes/recipes_forge.dm
- code/datums/components/crafting/recipes/recipes_misc.dm
- code/datums/components/crafting/recipes/recipes_tailoring.dm
- code/game/area/Space_Station_13_areas.dm
- code/game/machinery/computer/card.dm
- code/game/machinery/doors/unpowered.dm
- code/game/machinery/msgterminal.dm
- code/game/machinery/telecomms/machines/server.dm
- code/game/objects/effects/landmarks.dm
- code/game/objects/items/cards_ids.dm
- code/game/objects/items/devices/radio/encryptionkey.dm
- code/game/objects/items/fallout13misc.dm
- code/game/objects/items/melee/f13twohanded.dm
- code/game/objects/items/shields.dm
- code/game/objects/items/storage/backpack.dm
- code/modules/clothing/head/f13factionhead.dm
- code/modules/clothing/neck/mantle.dm
- code/modules/clothing/suits/arfsuits_unused.dm
- code/modules/fallout/areas/area.dm
- code/modules/jobs/job_types/legion.dm
- code/modules/jobs/jobs.dm
> IT BEGINS (Lil' Ceasar's Pizza Legion Pt. 1)

- modular_coyote/eris/code/gun_firemode.dm
a small fix to an error in a datum. some might see this as a nerf to some guns that have low fire rates as they've never truly had to experience low fire rates before. we shall see, and may revisit fire rates later. not now.
:cl:
/:cl:
> smol gun fix

- code/modules/mob/living/simple_animal/hostile/hostile.dm
Yeah, we don't like that
:cl:
/:cl:
> Pulling in mob dodge until we fix them moving thru players

- code/datums/traits/negative.dm
Fixes masked mook to include all masks instead of one specific mask. Also removes the free mask on-spawn.
> Masked Mook Fix

- code/modules/projectiles/gun.dm
adds a lil sound when your gun is ready to fire, improving audio feedback during a fight
:cl:
/:cl:
> best QOL pr of all time

- code/modules/fallout/obj/structures/simple_door.dm
Allows simple doors to count for the purposes of checking if a room is sealed with the create area action.
> Fixing Doors

- code/modules/smithing/finished_items.dm
Gives wakisashi the sharp_edged trait so it can butcher and cut trees.
:cl:
/:cl:
> Makes Smithed Wakisashi's sharp. [READY]

- code/modules/photography/camera/camera.dm
> Fixes new cameras turning into old cameras

- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
> Aldric told me to do a thing

- code/modules/projectiles/guns/ballistic/automatic.dm
makes the ratling do around 57 dmg per hit, down from 87
> Lowering that dmg, adding to that kick

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
Fixes the holes in Nash Bar's roof.
> Finally fixes the roof of the Nash Bar.

- code/modules/reagents/chemistry/reagents/food_reagents.dm
> Fix Hot Chocolate glass name to include hot and to use cup to match sprite

- code/_globalvars/lists/maintenance_loot.dm
- code/datums/components/crafting/recipes/recipes_primal.dm
- code/game/objects/effects/spawners/masterlootdrop.dm
- code/modules/projectiles/boxes_magazines/ammo_boxes.dm
Only holds seven rocks, cuz they're chonky bois
:cl:
/:cl:
> Adds a rock bag for slings and slingstaffs to use

- _maps/map_files/Pahrump-Sunset/RockSprings.dmm
sesesesesesesesesese
:cl:
/:cl:
> More lootses in Redwaterses Townses

- modular_citadel/code/modules/client/loadout/__donator.dm
> Merek update

- code/datums/components/crafting/recipes/recipes_tailoring.dm
Fixed facewrap that was referring to the same thing with headwrap.
:cl:
fix: fix facewrap
/:cl:
> Fix facewrap

- code/modules/projectiles/guns/energy/plasmaf13.dm
> Renames Aldrics Blaster

- code/datums/components/crafting/recipes/recipes_misc.dm
> Reduces aireal support girder requirements

- code/datums/components/crafting/recipes/recipes_assemblies.dm
One for each direction, mostly because I'm not sure if you do just stairs that they will point in a sensible manner.  Should test it, but its 8:30AM and I'm tired as shit lmao
:cl:
/:cl:
> Adds 4 recipes for stairs

- code/game/objects/items/loadout_beacons.dm
Rocks fall, you die.
:cl:
/:cl:
> Adds a beacon for a bag of rocks

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
The red ones south of nash need fixing, they are infinite scrap.  For now I've removed them.
:cl:
/:cl:
> Hate gas pumps

- code/game/objects/hand_items.dm
> Adds single turf attack component to *cla

- code/modules/clothing/under/miscellaneous.dm
- modular_citadel/code/modules/client/loadout/uniform.dm
> fixes spelling for peasant

- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
To make the idea of killing him maybe worthwhile.
:cl:
/:cl:
> Updates Traitors room with more loot

- modular_sunset/code/game/objects/watercloset_sunset.dm
So it blends in a little better, but is still noticable.
:cl:
/:cl:
> Makes deep water alpha 150

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- code/modules/surgery/bodyparts/_bodyparts.dm
As well as our new rockstar, Lil' Biter
:cl:
/:cl:
> Moves Farm & Adds The Waterin Hole

- code/__DEFINES/dcs/signals.dm
- code/datums/components/reskin.dm
- code/modules/projectiles/guns/ballistic.dm
- code/modules/projectiles/guns/ballistic/automatic.dm
- code/modules/projectiles/guns/ballistic/pistol.dm
- code/modules/projectiles/guns/ballistic/rifle.dm
- modular_coyote/code/game/objects/structures/sacredwell.dm
Now most ballistics can support a reskin component.
Service rifles and ALR-15 can reskin into each other cus they are the same damn gun
the stock assault carbine can reskin into the SCARL
the volcanic pistol can reskin into the custom
the glock can reskin into the plock
why is the sacred well fucking high
> expands support for reskins to magrifles and piss

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
:cl:
fix: fixed a few things in Nash's Map
/:cl:
> Fixes some some Couches and Iron Bars [READY]

- code/modules/fallout/reagents/alcohol.dm
- code/modules/fallout/reagents/drinks.dm
This is updating the values on Nuka Love trait (which is known as Cosmic though the trait name is still Nuka.) Nayriin told me that for the perk the amount it heals was too low, so I gave it a small buff.
:cl:
/:cl:
> Update Nuka Lover

- code/modules/mob/living/simple_animal/hostile/retaliate/frog.dm
They're much cuter, and not quite as horrifyingly huge now.
https://gyazo.com/1e8d4b4393ff228e282889ee12b374c1
:cl:
/:cl:
> Half sizes frogs.

- code/game/objects/items/cards_ids.dm
- code/modules/WVM/bountypuncher.dm
> Fixes a game breaking dupe, and a sound

- code/datums/components/crafting/guncrafting.dm
Talked to Superlagg. And she said it was alright to go ahead and makes these wrenchable again!
:cl:
/:cl:
> Wrench Workbench

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
I put the door in that Thingpony asked for, I also added a better flooring to the bathroom places along Nash, white didn't go well with the wood. I also fixed up the clinic because no one likes the door button location thing. (And walls where the windows were because people break into it.)
:cl:
/:cl:
> Update Pahrump-Sunset.dmm Add and Fix Thing

- code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
Antivenom now goes into alchemy racks.
:cl:
fix: tribal medicine now goes on tribal shelf.
/:cl:
> Antivenom into Alchemy racks. (Should be ready to merge.)

- code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
> Racing Tassy to readd Firey Purg

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
https://i.gyazo.com/425a605fbbc7aca7e7e01cf431cfd778.png
Lets players get the hell out of this hole, lol
:cl:
/:cl:
> Fixes a player trap on the map

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
Minor adjustment to a medical place underneath nash
:cl:
balance: adjusted a loot place
/:cl:
> Adjusts a medical loot area under Nash

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
What the puddle doin
:cl:
/:cl:
> Fixes the random workshop water

- code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
shotgunner (hover at 1-2 tiles)
varmint (try to keep 3 tiles at all times)
:cl:
/:cl:
> Modifies ranged super mutant attack logic

- code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
Since they're small, let em pass thru!*
:cl:
/:cl:
*pr not endorsed by the shadow council of Nash
> Scurrying Newt Changes

- code/modules/cargo/packs/medical.dm
- code/modules/reagents/chemistry/reagents/other_reagents.dm
- fortune13.dme
Removes the ability to microdose red ambrosia / elixir vitae
> Elixir Vitae Rebalance

- code/__DEFINES/mobs.dm
- code/modules/fallout/reagents/drugs.dm
- code/modules/fallout/reagents/juices.dm
- code/modules/fallout/reagents/medicines.dm
- code/modules/reagents/chemistry/holder.dm
- code/modules/reagents/chemistry/reagents.dm
- code/modules/reagents/chemistry/reagents/medicine_reagents.dm
- code/modules/reagents/chemistry/reagents/other_reagents.dm
- code/modules/reagents/chemistry/reagents/toxin_reagents.dm
If you have a fraction of one full metabolization cycle's worth of a reagent, it'll give that fraction's worth of effect.
> Microdosing gives a lesser effect

- code/modules/plumbing/plumbers/acclimator.dm
- code/modules/plumbing/plumbers/filter.dm
- code/modules/plumbing/plumbers/pill_press.dm
- code/modules/plumbing/plumbers/reaction_chamber.dm
- code/modules/plumbing/plumbers/splitters.dm
- code/modules/plumbing/plumbers/synthesizer.dm
Makes it so that all chem plumbing machines require chem whiz in order to know how to use.
Used to be able to circumvent the perk by using plumbing to make chems.
> Chem Plumbing Fix

- code/game/objects/items/granters.dm
- code/modules/cargo/packs/security.dm
Stealth merc kit didnt populate contents because I forgor to tell it not to select a random item
also tribal healing book didnt give elixirs, this fixes that too
> Fixes a broken kit in cargo

- code/modules/reagents/chemistry/reagents/other_reagents.dm
- code/modules/tgui_panel/telemetry.dm
hate telemetry warnings, yeah they're great and all but fuck the fuck off
:cl:
/:cl:
> Don't worry about it

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Fix the walls of the clinic where windows were, though this time with a single window and curtain which actually works. (As well as metal bars to protect it.) Add a radaway that can be used roundstart. A few more curtains. That way if there is no one around people can use it easily.
:cl:
/:cl:
> Fix The Clinic Thing

- code/game/objects/items/loadout_beacons.dm
but also yumi needs more work, i'll get it later tho
:cl:
/:cl:
> fixes shortbow

- _maps/map_files/Pahrump-Sunset/RedRiver-Upper.dmm
- _maps/map_files/Pahrump-Sunset/RockSprings.dmm
I'm going to wear scroggle like a sock
:cl:
/:cl:
> Fixes two more gates

- _maps/map_files/Pahrump-Sunset/RedRiver-Upper.dmm
> fixes a light in ashdown

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- code/__DEFINES/economy.dm
- code/game/objects/items/melee/energy.dm
- code/modules/WVM/wmv_buyer.dm
- code/modules/cargo/exports/misc_export.dm
- code/modules/vending/medical.dm
Adds a category of melee weapon to the scrapper
Makes the esword implant do as much damage as the weakest plasma cutter
Adds a ticket puncher to the sheriff's office
Re-adds the clinic's filing cabinet but makes it have no density so it doesnt block people/objects from reaching the middle desk
Expands clinic's desk and adds a shutter under the vendor
Adds a wall under the smartfridge
Fixes some double-placements around the map
> Capitalism 3.5 And More

- code/game/objects/items/loadout_beacons.dm
not devist, just don't loike it
:cl:
/:cl:
> 'ate codin',
