code/game/objects/effects/spawners/f13lootdrop.dm
code/game/objects/effects/spawners/masterlootdrop.dm
code/game/objects/effects/spawners/themed_loot_tables.dm
code/modules/projectiles/guns/mods/mods.dm

fixes invisible sledgehammers
adds in an upgraded forged barrel as random loot
:cl:
add: makes a barrel better
fix: fixes bad sledgehammer spawn
/:cl:

fixes a few invisible things [NOTREADY]

---

code/datums/looping_sounds/ambient_sounds.dm

This is due to them hoes being quiet AF man whoa
:cl:
/:cl:

Cranks up some of the ambient sounds about 20%

---

code/datums/looping_sounds/weather.dm

enquiets sandstorms s'mores

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Expands the bank ever so slightly and gives it a break room.
:cl:
tweak: Fixes up the bank.
/:cl:

Expands the Bank a bit and gives it a break room [Ready]

---

code/modules/clothing/suits/arfsuits.dm
code/modules/clothing/suits/miscellaneous.dm
modular_citadel/code/modules/client/loadout/suit.dm

Adds a slew of crap from Civ13, thanks y'all.
:cl:
/:cl:

More jackets & armor from civ13

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Yep, small.  Stuff.
:cl:
/:cl:

Some small stuff

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Seals off a specific loot area to work on it later.
:cl:
/:cl:

Seals off a very overpowered area. [MERGEPLS]

---

modular_citadel/code/modules/client/loadout/uniform.dm

The teal suit skirt. Totally not for selfish reasons as I want to use it and it's not ther,e nope.
:cl:
/:cl:

Adds one thing to the loadout

---

_maps/_basemap.dm
_maps/pahrump-everything.json
code/modules/mapping/map_config.dm

Remove westlands

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm

Not quite ready yet
:cl:
/:cl:

Prepping Viro & Xenobio for Nash

---

code/game/objects/structures/flora.dm

Trees hamper view of swamp.

---

code/modules/fallout/obj/structures/mob_spawners.dm
modular_coyote/code/birds.dm

Makes them half sized so they're not WAR BIRDS, also gives crows a nest like tadpoles have.  But doesn't map any in yet.
:cl:
/:cl:

Fleshes out birds some more

---

_maps/map_files/Pahrump-Sunset/Garland-City.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RedRiver.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm
code/controllers/subsystem/events.dm
code/datums/components/spawner.dm
code/game/objects/effects/effect_system/effects_sparks.dm
code/game/objects/effects/landmarks.dm
code/modules/events/_event.dm
code/modules/events/carp_migration.dm

gee billy your mom lets you have 250 carp spawners?
:cl:
/:cl:

Mid round mob spawn points

---

code/game/objects/effects/spawners/masterlootdrop.dm
modular_citadel/code/modules/client/loadout/backpack.dm
modular_coyote/code/objects.dm

By request of Cebu
Adds a kit to the loadout for 2 points, contains 2 keys, a lock and a keychain thing. 
:cl:
/:cl:

Adds a locksmith toolset to the loadout

---

code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm

shouldnt have been happening anyway, but, now they wont gib if you nudge one into a wall while its alive. While dead, yeah it'll splortch.

Deathclaws no longer explode when given a gentle push into the wall

---

modular_coyote/code/mam_ears_coyote.dm

Fixes the vaporeon ears

---

modular_citadel/code/modules/client/loadout/suit.dm

Adds farmer overalls to the loadout

---

code/modules/mob/living/simple_animal/hostile/hostile.dm

Lowers mob dodge chance

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Not sure how this happened, but hey. A Fix.
:cl:
/:cl:

Fixes an errant sand tile.

---

_maps/map_files/Pahrump-Sunset/RedRiver.dmm

Ashdown Potluck space

---

modular_coyote/code/objects.dm

Don't judge the puns, or do. IDC
:cl:
/:cl:

Gives the new fish a desc.

---

code/modules/jobs/job_types/tribals.dm

Gives Scorb to the Smelly Butt Tribal Shaman

---

code/modules/events/carp_migration.dm

How can a thing that cant even move runtime?

fixes integ check

---

code/modules/jobs/job_types/tribals.dm

idk why the shits even broken what in the god damn I hate this fucking code

Fixes scorb

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
code/__DEFINES/traits.dm
code/modules/hydroponics/gene_modder.dm
code/modules/jobs/job_types/tribals.dm

Tribal Update

---

code/__DEFINES/mobs.dm
code/controllers/subsystem/mobs.dm
code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
code/modules/mob/living/simple_animal/simple_animal.dm

All the mobs got together and decided to put aside their differences and focus on the real problem: you. Specifically you. 
Mobs no longer fight other mobs.

Mobs no longer fight each other

---

code/__HELPERS/areas.dm
code/game/objects/effects/decals/crayon.dm
code/game/objects/items/crayons.dm
code/modules/shuttle/shuttle_creation/shuttle_creator.dm
tgui/packages/tgui/interfaces/Crayon.js

The whole world is my living room
The room builder will give up after reaching too many tiles.
More things count as walls for the builder.
You can set crayons and spraycans to mark floors as to be considered walls for the floor builder. Dunno about this one,

Fixes some room-builder stuff

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/modules/jobs/job_types/tribals.dm

Adjusts descriptions and supervisors to be a bit more clear.  Not that anyone reads this shit lmfao
Also a few map fixes
:cl:
/:cl:

Adjusts Tribal job information

---

code/datums/traits/negative.dm

Removes/updates the bit about not being able to call for God/Admin help. Was bit unneeded, and ignored.
:cl:
/:cl:

updates the text of the hardcore quirk

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/game/objects/structures/spirit_board.dm
code/modules/fallout/areas/area.dm

Spank their fucking SOULS.
:cl:
/:cl:

Tribal Spiritualism & Punishment Update

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/modules/antagonists/wizard/equipment/artefact.dm

Makes the Scorb need darkness
Also small tribal mapping fixes
:cl:
/:cl:

More Tribal Updates & Scorblight

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Cleans up the new paths in the Tribal Camp
Adds Clinic spawns to the town tunnel.
:cl:
/:cl:

Adds Clinic spawns to Nash, FIxes some dirt paths

---

code/modules/mob/living/simple_animal/hostile/bees.dm
code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
code/modules/mob/living/simple_animal/simple_animal.dm

Pokemon get fucked up by mobs.
Also vaultie NPCs fight the enclavies.

Makes some mobs fight u

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

More Tribal Camp enbeautiment.

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Adds a northern exit for the tribe with a proper gate.
:cl:
/:cl:

I'll stop mapping when I'm dead

---

code/datums/traits/good.dm
code/modules/jobs/job_types/followers.dm

Lets scientists and trait havers use plant machines

---

code/modules/hydroponics/gene_modder.dm

Makes dna manipulators WORK

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Smol map fix

---

code/modules/hydroponics/gene_modder.dm

Chatgpt figured out that I needed to delete 2 of the ! symbols for the code to work
:cl:
/:cl:

Chatgpt to the rescue

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Gives the clinic a *cough "weedfarm"  *cough

---

COOLBOOK_books/example_book/json_chapter_url_test.json
COOLBOOK_books/example_book/this_is_a_json_chapter.json
COOLBOOK_books/example_book/this_is_a_text_chapter_2.txt
COOLBOOK_books/example_book/zzzzzzzz.json
COOLBOOK_books/shaman_guide3/Dangerous Rituals.txt
COOLBOOK_books/shaman_guide3/Healing.txt
COOLBOOK_books/shaman_guide3/Our History.txt
COOLBOOK_books/shaman_guide3/Outlanders.txt
COOLBOOK_books/shaman_guide3/Safe Rituals.txt
COOLBOOK_books/shaman_guide3/Shamanic Variancies.txt
COOLBOOK_books/shaman_guide3/Your Place In The Tribe.txt
COOLBOOK_books/shaman_guide3/index.json
code/__DEFINES/COOLBOOK_defines.dm
code/__HELPERS/_lists.dm
code/__HELPERS/files.dm
code/controllers/subsystem/COOLBOOKss.dm
code/game/objects/items/COOLBOOK.dm
code/modules/jobs/job_types/tribals.dm

Shaman Guidebook take 2

---

COOLBOOK_books/druid_guide/aaa_Important_Plants.json
COOLBOOK_books/druid_guide/aab_Composts.json
COOLBOOK_books/druid_guide/aac_Genetics.json
COOLBOOK_books/druid_guide/aad_Medicines.json
COOLBOOK_books/example_book/zzzzzzzz.json
COOLBOOK_books/shaman_guide3/Our History.txt
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/game/objects/structures/spirit_hole.dm
fortune13.dme

Reverts the changes to spirit boards
Creates a new parallel to spirit boards, referred to as a 'spirit hole', so fenny can have his own unique tribal version to play with.
Also adjusts druids' seed spawns and fixes their book.

Fixes Spirit Boards

---

COOLBOOK_books/warrior_guide/Hiding.txt
COOLBOOK_books/warrior_guide/Hunting.txt
COOLBOOK_books/warrior_guide/Our History.txt
COOLBOOK_books/warrior_guide/Outlanders.txt
COOLBOOK_books/warrior_guide/Your Place In The Tribe.txt
COOLBOOK_books/warrior_guide/index.json
code/game/objects/items/COOLBOOK.dm
code/modules/jobs/job_types/tribals.dm

For everybody that hunts butts
:cl:
/:cl:

Tribal Hunter Guidebook

---

COOLBOOK_books/chief_guide/Leadership.txt
COOLBOOK_books/chief_guide/Our History.txt
COOLBOOK_books/chief_guide/Outlanders.txt
COOLBOOK_books/chief_guide/Your Place In The Tribe.txt
COOLBOOK_books/chief_guide/index.json
COOLBOOK_books/villager_guide/Growth.txt
COOLBOOK_books/villager_guide/Our History.txt
COOLBOOK_books/villager_guide/Outlanders.txt
COOLBOOK_books/villager_guide/Your Place In The Tribe.txt
COOLBOOK_books/villager_guide/index.json
code/game/objects/items/COOLBOOK.dm
code/modules/jobs/job_types/tribals.dm

Villager & Chief Guidebook

---

code/modules/mob/living/carbon/emote.dm
code/modules/mob/living/carbon/human/emote.dm

Emotes never ending

---

code/modules/smithing/smithed_items.dm

Black Bronze Black Bronze be like

Fixes Black Bronze Ingot's Name

---

modular_coyote/code/mam_tails_coyote.dm

Fixes raccoon tail and nightstalker tail not wagging, disappearing

---

code/modules/jobs/job_types/_job.dm

Fixes unghoulification for jobs

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/modules/cargo/exports/misc_export.dm

I did an oops and mis-placed armor spawners in place of armor in exports, haha heehee
Also creates a science facility
Gonna make science jorbs l8r.

Fixes Some Cargo Stuff and Reworks The Science Dungeon

---

code/modules/client/preferences.dm

100 quirk points

---

code/__DEFINES/traits.dm
code/controllers/subsystem/processing/quirks.dm
code/datums/traits/good.dm
code/game/objects/hand_items.dm
code/modules/mob/living/carbon/emote.dm

Mo fuckin fangies n fingies for the fun loving swamplands
:cl:
/:cl:

Big & Fast for Biters & Clawers

---

code/controllers/subsystem/processing/quirks.dm

2 braincell moment

---

code/modules/client/preferences.dm

Fixes Prosthetics quirk point giving

---

code/datums/traits/good.dm
modular_citadel/code/modules/client/verbs/who.dm
modular_coyote/code/modules/verbies/whocares.dm

Adds a line of text to who and fixes silent step

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Touches up just outside of nash a bit
:cl:
/:cl:

More mapping

---

code/_onclick/item_attack.dm

matches big/small to the negative versions, a small buff overall
:cl:
/:cl:

Big leagues micro buff

---

code/__DEFINES/traits.dm
code/controllers/subsystem/processing/quirks.dm
code/datums/traits/good.dm
code/game/objects/hand_items.dm
code/modules/mob/living/carbon/emote.dm

- Big
- Whiplike
- Thagomizer
- Venomous
- Playful
The sprite sucks, I won't lie.  We can pick a better one later, or get code to point it to the players tail.
:cl:
/:cl:

Tail quirks

---

code/datums/status_effects/debuffs.dm
code/modules/mob/living/living.dm

For sake of avoiding clutter, sleeping for a long time makes the player dream less.
:cl:
fix: Fixes Sleep Toggle
/:cl:

Dreaming a tad slower when sleeping for a long time

---

code/datums/mood_events/needs_events.dm
code/modules/mob/living/carbon/life.dm

Technically it removes the drunk moodlet too, but it needs refactoring. lmfao
:cl:
/:cl:

Turns off drunkenness spam

---

code/datums/traits/negative.dm

Turns off Phobia - Bright Lights & Dark

---

code/datums/traits/negative.dm

Only if we have to :tm:
:cl:
/:cl:

Turns off Masked Mook

---

code/datums/mood_events/generic_negative_events.dm
code/datums/traits/negative.dm

Makes them slightly worse, but way less likely to trigger.
:cl:
/:cl:

Adjusts Depression & Pessimist

---

code/modules/mob/living/simple_animal/hostile/f13/insects.dm

Lowers Giant Ant and Fire ant HP.
:cl:
balance: lowered HP on ants
/:cl:

Nerfs Ant HP even more

---

code/datums/traits/good.dm
code/datums/traits/negative.dm
code/modules/smithing/finished_items.dm
code/modules/smithing/smithed_items.dm

Fixes a few quirk values and also fixes pickaxes

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Heavens Night v. I have no idea

---

code/controllers/subsystem/ticker.dm
code/modules/holiday/party_time.dm

Simple little ping on round start if round start occurs on potluck day. Also use US Central Standard Time (UTC -6) time offset (514+).
:cl:
/:cl:

Potluck Pinger

---

code/datums/mood_events/generic_negative_events.dm
code/datums/mood_events/generic_positive_events.dm
code/datums/traits/negative.dm

Maybe fixes masked mook?
me right now:
:cl:
fix: fixed "masked mook" 
/:cl:

Fixes "masked mook" perk

---

code/modules/projectiles/guns/ballistic/automatic.dm

Literally just makes the rpd not be outclassed by a 45acp thompson

---

code/datums/components/mood.dm
code/datums/traits/negative.dm

Mood
Sounds.
To help you know when your mood.  Moods.
I guess.
Mood honestly.
:cl:
/:cl:

Mood sounds

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

And some small upgrades, mostly in better bedrooms on the second floor.
:cl:
/:cl:

Tribal Camp Map Fixes

---

COOLBOOK_books/ashdowncitizen_guide/The Village of Ashdown.txt
COOLBOOK_books/ashdowncitizen_guide/index.json
code/game/objects/items/COOLBOOK.dm
code/modules/jobs/job_types/hells_nomads.dm
code/modules/jobs/job_types/wasteland.dm

Ashdown Lore Book

---

code/modules/mob/living/carbon/emote.dm

- Powerpose
- Snaplook
- Peace
- The bird
- The birds
- vlick
- cheekpoke
- headbob
- hairflick
- hairchew
:cl:
/:cl:

Got bored, it never ends.  More verbs.

---

code/controllers/subsystem/processing/quirks.dm

Watch me WHIP nay nay

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RedRiver.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm

Adds a bunch of fuckin' street signs to the main z, and a few off of it.

---

code/datums/mood_events/generic_positive_events.dm
code/game/objects/items/storage/dakis.dm

Adds a mood event to the dakis

---

code/modules/jobs/job_types/wasteland.dm

Makes em' free, and wasters get em by DEFAULT.
:cl:
/:cl:

Updates reprogramable ID

---

code/datums/traits/good.dm
code/datums/traits/negative.dm

lowers carry quirk costs massively
:cl:
/:cl:

Carry me cheaply, my legs are tired

---

modular_coyote/code/modules/area_blurb.dm

Update The Night

---

code/modules/mob/living/living.dm

Adds some text and makes heavy sleeper matter.
:cl:
/:cl:

Sleep Toggle Update

---

code/modules/clothing/under/accessories.dm
modular_citadel/code/modules/client/loadout/backpack.dm

This is mostly to make sure I still know what I'm doing with github and stuff. Expect more from me eventually

corrects some awkward language

---

code/datums/components/crafting/recipes/recipes_assemblies.dm
code/game/machinery/obstacles_barricades.dm

Made it possible to craft the pre-war television. It does not use any tools, that's because I did not think about that. Either way it's a for fun thing, perhaps will be changed in the future!
:cl:
/:cl:

Add Television

---

code/datums/components/crafting/recipes/recipes_tribal.dm
code/datums/traits/good.dm
code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm

Add a global init to the trait that is given to you by the quirk. This means that people can actually take the quirks.
:cl:
/:cl:

Fix Rustwalking

---

code/datums/components/crafting/recipes/recipes_misc.dm
code/modules/instruments/instruments/item.dm

Includes damage on the instruments, dans weapon system on them, and upgrade versions you can craft!
:cl:
/:cl:

Instrument Update

---

code/datums/components/crafting/recipes/recipes_medicine.dm
code/modules/fallout/reagents/medicines.dm
code/modules/reagents/chemistry/recipes/medicine.dm

Make Imitation Stimfluid Reaction

---

code/datums/traits/negative.dm

:cl:
add: Adds masked mook again, because it works now
/:cl:

Masked mook reactivation, it was commented out

---

code/modules/reagents/chemistry/recipes/medicine.dm

I adjusted numbers with sutures along the mesh to make it so that it takes more reagent to make. Also adjusted mesh to make a stack of one instead of a full stack, which made people able to make about 10 entire stacks of mesh with only a little reagent.
:cl:
/:cl:

Balance Medicine (Suture Mesh) READY FOR MERGING

---

code/modules/projectiles/guns/ballistic/bow.dm

Temporary fix for the yumi bow.
:cl:
/:cl:

Fix missing icon yumi bow

---

code/modules/WVM/wmv_buyer.dm

waa
Title. Needs actual testing, I just did build.bat for error checking
:cl:
/:cl:

Adds artifacts to the scrapper(?)

---

code/controllers/subsystem/events.dm
code/modules/admin/admin_verbs.dm
code/modules/holiday/holidays.dm
code/modules/holiday/party_time.dm
code/modules/mob/dead/new_player/new_player.dm

Adds `trigger-holiday` so admemes can make it any holiday they want, any time they want. even mid-round

Lets admemes make it whatever holiday they want

---

code/datums/components/crafting/recipes/recipes_misc.dm

I gave people the ability to craft flares. One wrench, five welding fuel, one metal.
:cl:
/:cl:

Craft Flare (MERGE READY)

---

code/__DEFINES/traits.dm
code/datums/traits/good.dm
code/game/objects/hand_items.dm
code/modules/antagonists/changeling/powers/mutations.dm
code/modules/mob/living/carbon/emote.dm

Needs quirk to use, its probably overpowered.  lmfao
:cl:
/:cl:

Adds *armblade verb

---

code/controllers/subsystem/processing/weather.dm
code/datums/looping_sounds/_looping_sound.dm
code/game/objects/effects/sound_emitter.dm

Encheapens sound rocks

---

modular_citadel/code/modules/client/loadout/__donator.dm

Delta Kruger Custom MERGE READY

---

code/__HELPERS/mobs.dm
code/controllers/configuration/entries/game_options.dm
code/modules/mob/living/carbon/human/species_types/ghoul.dm

Fixing my mistakes, variable use in this case
:cl:
/:cl:

woops my bad, fixing variables [Ready to merge]

---

code/modules/projectiles/ammunition/energy/laser.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/projectile/beams.dm

AER14 has 20 shots with 42 damage. It's updated from the damage that an AER9 has, with 5 less shots than an AER9 and AER12 (to balance it to other weapons because ammo is fairly easy to get.)
:cl:
/:cl:

AER14 Updating (MERGE READY)

---

code/datums/components/crafting/recipes/recipes_tribal.dm
code/datums/traits/good.dm

Fixes Eighties. People are able to get the crafting from the quirk perk.
:cl:
/:cl:

Update Eighties Fix

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm

Clears up the vault dungeons 'round start battle' that eats up processing of mobs fighting each other needlessly.
:cl:
/:cl:

Hopefully this helps some of the roundstart lag.

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Expands the shooting range under Nash some.
:cl:
tweak: Adjusts the shooting range.
/:cl:

Expands the Shooting range.

---

code/datums/view.dm
code/modules/admin/admin_verbs.dm

Admins can now set everyone's view range with a single command. READY

now admemes can fuck up EVERYONE's view - READY

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Tribal Showers

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/shuttles/cargo_pahrump.dmm
code/modules/mob/living/emote.dm

it never ends, this shit
:cl:
/:cl:

Fenny is licking maps again

---

code/modules/cargo/exports/large_objects.dm
code/modules/cargo/exports/misc_export.dm

Makes power armor not sell for 15k a set
Also sorta fixes the old crate export

Some smol fixes to exports

---

code/datums/traits/negative.dm
modular_coyote/code/mailbird.dm

light sensitivity lumen check from 0.85 > 0.8
Fixes a typo under mailbird.dm that stopped non tribals from shrugging

Smol quirk tweaks

---

code/game/objects/items/loadout_toolkits.dm

Exactly what it says on the tin

Add Bronze to Smithing Kit

---

code/datums/traits/good.dm

removes the 'movement quirk' category and puts it where it should be, in movement quirkS
:cl:
/:cl:

Fixes a typo on light step

---

code/modules/instruments/instruments/item.dm
modular_coyote/code/mailbird.dm

Fixes two things, although one is more of a tweak. The mailbird now properly flies away instead of laying dead on the ground, and also Primitive no longer prevents you from playing intruments

two small fixes!!!!!!!!!!!!!!!!!

---

code/modules/mob/dead/new_player/new_player.dm
code/modules/mob/login.dm

Now it only asks you when you actually join the game!

Less stealthmin dialogs - READY

---

modular_coyote/code/objects.dm

smol fix PRs amirite. eventually I'll do something bigger
Now the kit has the correct kind of lock and keys. I don't actually know what the ones it had before are used for.

fixes the locksmith kit

---

config/policy.txt

Update revival so that it works with the policy that we have in place.
:cl:
/:cl:

Update Revival Message

---

code/modules/jobs/job_types/followers.dm

They should get it for their job, like Town Scientist.
:cl:
/:cl:

Add Toolbelt to Senior Science

---

code/modules/jobs/job_types/tribals.dm

2 druid slots

---

COOLBOOK_books/hn_guide/Petals in the Breeze.txt
COOLBOOK_books/hn_guide/Roses in the Garden.txt
COOLBOOK_books/hn_guide/Songbirds on the Vine.txt
COOLBOOK_books/hn_guide/The Beating Heart.txt
COOLBOOK_books/hn_guide/index.json
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/__DEFINES/access.dm
code/__DEFINES/jobs.dm
code/__DEFINES/preferences.dm
code/datums/datacore.dm
code/datums/world_topic.dm
code/game/objects/items/COOLBOOK.dm
code/modules/admin/topic.dm
code/modules/jobs/job_types/heavensnight.dm
code/modules/jobs/jobs.dm
fortune13.dme

Also does some map stuff for heavens night and some other stuff I forgot to pr earlier

Creates A Faction and Jobs For Heavens Night

---

code/game/objects/hand_items.dm

Mail order bites

---

code/modules/admin/verbs/adminhelp.dm

yeah, you didn't need to know that.

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Sneavens Snights Snall Snix

---

code/datums/datacore.dm

What it says on the tin
I forgor to add the block to the code after creating its variables lol

Adds heavens night roles to manifest

---

modular_citadel/code/modules/client/loadout/__donator.dm

Thnigs and stfuf

---

modular_coyote/code/modules/verbies/whocares.dm

Updates status message

---

code/controllers/subsystem/processing/weather.dm
code/datums/looping_sounds/_looping_sound.dm
code/game/objects/effects/sound_emitter.dm

Reverts ARF-SS13/coyote-bayou#2999
not only did it not fix the lag, but it also broke other shit. fyl

Revert "Encheapens sound rocks"

---

code/modules/mob/living/carbon/human/species.dm

Fixes fat people getting spammed about their guts being empty

---

code/modules/food_and_drinks/drinks/drinks/bottle.dm
code/modules/vending/boozeomat.dm

Make a bottle of kitsune sake. It was already in the code as a random initialize for sake. I made it its own thing. Works when tested. Do tell me if anything works weird with the thing.
:cl:
/:cl:

Kitsune Sake

---

code/modules/power/antimatter/control.dm

murders an admin log in its sleep

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm

Updates the thing Fen and I talked abouts. 

---

code/modules/food_and_drinks/recipes/food_mixtures.dm

It wasn't broken, I was just annoyed by it. 
:cl:
/:cl:

Fixes the chocolate bar recipe 

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Removes Message Monitor Console Because Bugged And Maybe Causes Severe Lag Lol

---

code/datums/traits/good.dm

oops, knew I forgot something lol
:cl:
/:cl:

Adds actual musician shit to Life of the party

---

code/modules/mob/living/emote.dm

Touches up *flirtcustom

---

code/modules/mob/living/carbon/life.dm
code/modules/surgery/organs/heart.dm
modular_coyote/code/modules/misc_patches.dm

yeye
Only happens once, has a big text.

Gives a chat notification when you enter crit

---

code/game/machinery/obstacles_barricades.dm
code/modules/projectiles/guns/magic.dm

I changed pre-war television name and description so that it looks more like other things.
I changed a line in magic.dm that was called by tentacle arm, it had a typo, I noticed it when someone used it.
:cl:
/:cl:

Fix Grammar

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm

Tried to follow Kelp-Cat's suggestions on this, Should be less manglable and more spacious!
:cl:
/:cl:

Vertibird Upgrade

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RedRiver-Upper.dmm
_maps/map_files/Pahrump-Sunset/RedRiver.dmm
code/modules/fallout/areas/area.dm
modular_coyote/code/modules/area_blurb.dm
modular_coyote/code/modules/mapping/areas.dm

Oh yeah, that's the stuff baby.
:cl:
/:cl:

Begins naming areas correctly for 'where'

---

code/game/objects/items/holy_weapons.dm

Should add dans melee system to all the nullrod weapons

---

code/datums/traits/good.dm

If you take the quirk you now get the benefit of chem whiz recipe. This makes no change to the tribal table.
:cl:
/:cl:

Fixes Tribal Chemist

---

code/datums/emotes.dm
code/modules/admin/admin_verbs.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm

Fixes Problem

---

code/modules/mining/lavaland/necropolis_chests.dm
code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm

No more anomalous crystal

---

code/controllers/subsystem/vore.dm
code/modules/vore/eating/vore_core.dm

You can eat just about any simple mob! Its gotta be dead first, or have a player currently in it. 
Also, simplemobs can eat *you*, but only if theres a player in them. Do note, they can't hold the emote, so you'll have to do the backup thing, where you grab someone and type *vore.

Lets players eat mobs, sort of

---

tgui/packages/tgui-panel/chat/constants.js

You can now use TGUI to filter nash radio into it's respective radio tab.
:cl:
config: configured the radio listings to include Nash
/:cl:

Nash radio can now be filtered by radio chat.

---

code/modules/mob/mob.dm

360 degrees baby, easy on those knees, do it as you please
:cl:
/:cl:

Unlocks Pixel Tiltin

---

code/modules/projectiles/gun_keybinds.dm

Simple and plain
:cl:
add: Adds keybinds
/:cl:

Rebinds keybinds [ready to merge]

---

modular_citadel/code/modules/client/loadout/__donator.dm

empty defib for kelp because I'm already a fuckin bottom as is
above, smite the cat if using it on non-clinic char
:cl:
/:cl:

kelp defib (good to go, TENATIVELY approved by aldric)

---

code/datums/world_topic.dm

Makes a topic handler for when you send the key "border" in a packet.
Will look for a "mode" from 0, 1, 2, comment has more info in the file, along with a "ckey" within the packet. Returns text based on the mode, will whitelist/unwhitelist a player via the topic handler.
Have fun!

Adds a whitelist wrapper for the bot

---

code/datums/world_topic.dm

don't ask, I don't know.
ONLY ANDY CAN TOUCH THIS, DO NOT TOUCH IF NOT A DRGN NAMED ANDY
:cl:
/:cl:

Andy said to do it, so I did it

---

code/modules/cargo/packs/security.dm

You can apparently buy PA on the train and resell it. This should make it unprofitable.
:cl:
-Increased price of basic armor
-Decreased quantity of rare armor bought
:cl:

Cargo exploit hotfix

---

code/modules/clothing/suits/arfsuits.dm
code/modules/projectiles/guns/magic.dm
code/modules/projectiles/guns/magic/wand.dm
modular_citadel/code/modules/client/loadout/suit.dm

Just fixing a few tiny things.
:cl:
- The electrowand now sounds electric-y
- Added Gear Harness armors to the code and loadout
- Gear Harness armors are invisible on the body, tiny sized, but have no pockets and no bonus stats.
:cl:

Small Kelptouches (Good if it passes checks)

---

.gitignore
_maps/pahrump-unit-test.json
code/controllers/configuration/configuration.dm

…onsiderable amount)
Doesn't affect actual gameplay, just makes it so github checks are like, considerably faster.

Makes it so unit tests only load one map (should reduce checks by a c

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm

There was a hole, it is fixed now.
:cl:
fix: fixed a hole in the tribal camp
/:cl:

Fixes a hole in the tribe camp

---

code/game/objects/items/devices/radio/electropack.dm

This really shouldn't be in autolathe. You can craft one if you need.
:cl:
/:cl:

Remove Slave Collar From Autolathe

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Moves the pool uptop since most were suggesting it. Combines the hot tub with the pool. 
:cl:
/:cl:

Moves the pool

---

code/modules/mob/living/living.dm
config/config.txt

Leaning against a wall (pixel shifting all the way out), makes the player behave as if it's out of the way, meaning that people can walk over them now.
Thanks Jon for the brilliant idea!
:cl:
add: Pixel sliding iteration II
/:cl:

Pixel sliding iteration II [ready to merge]

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm

Etheo needs to fix these shutters properly. They are not ID set.
:cl:
/:cl:

Replaces some shutters with doors for now

---

modular_citadel/code/modules/client/loadout/__donator.dm

Tiny whoops in the pathing, fixed now.
:cl:
/:cl:

Hotfix for Rattles' loadout (Good to go if it passes checks)

---

code/game/objects/items/storage/belt.dm
modular_citadel/code/modules/client/loadout/uniform.dm

Adds in the basic sweaters to the loadout, so you can run around without pants in style.
Also adds some dumb belt jokes????????

adds in naomi reids

---

code/modules/research/designs/ammolathe_designs.dm

Does what it says on the tin.
solves: https://github.com/ARF-SS13/coyote-bayou/issues/3235
:cl:
add: Unktehila magazine now printable in the ammo bench
/:cl:

Adds Unktehila magazine to the ammo bench

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Adds a roof
Adds a changing room
Adds male shorts
:cl:
/:cl:

Updates the pool some

---

code/datums/weather/weather_types/rain.dm

Unlags rain maybe

---

code/datums/components/glow_heal.dm

Null-ass mobs kept trying to glowheal. bad.

Fixes like 14000 runtimes

---

code/modules/projectiles/projectile/magic.dm

Turns out, the second brute check overrode the first, not added to it
:cl:
- Removes redundant bruteheal code from tend projectile
- Changes core bruteheal to 15 as intended
:cl:

Fixes staff healing (Good to go if it passes checks

---

code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/mob/living/living.dm
code/modules/mob/living/living_defines.dm
code/modules/mob/living/update_icons.dm
code/modules/mob/transform_procs.dm

🦊 Fuzzy Scaling!
:cl:
add: Fuzzy Scaling
/:cl:

Add fuzzy scaling

---

code/__HELPERS/unsorted.dm
code/controllers/subsystem/who.dm

You're relieved from cow duty, Aldric.

Makes players less likely to be cows, and fixes who

---

code/game/objects/items/storage/belt.dm

Makes the hunter's belt actually able to carry things:tm:
:cl:
/:cl:

Powergame for fenny (good to go if it passes checks)

---

code/modules/cargo/exports/materials.dm
code/modules/cargo/exports/misc_export.dm
code/modules/cargo/packs/goodies.dm
code/modules/cargo/packs/materials.dm
code/modules/cargo/packs/medical.dm
code/modules/cargo/packs/misc.dm
code/modules/cargo/packs/security.dm
code/modules/cargo/packs/skillbooks.dm

Title.
:cl:
- Finally added NVGs and Pres. NVGs to the shop like I said I would a month ago
- Upped the sale price of the good ingots
- Decreased the sale price of crates to 200
- Made the minimum order cost of an item 400 in the shop (crate + paper = 400 cr, breaking even)
- Adjusted some prices to be more reasonable
 
:cl:

Cargo abuse fixes and NVGs (Good to merge if it passes checks)

---

code/modules/mob/living/emote.dm

Skip emote. That's literally it. (Good to merge if it passes checks)

---

code/modules/projectiles/guns/magic/staff.dm

Kelpwand fix, it was my fault all along! [HIGH PRIORITY] [ready to merge]

---

code/__DEFINES/preferences.dm
code/controllers/subsystem/statpanel.dm
code/controllers/subsystem/time_track.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/client/preferences_toggles.dm
code/modules/mob/login.dm
code/modules/mob/logout.dm

Status panel shows the number of sexes, and the tops/bottoms/switches. Also makes the TBS a pref.
dunno if it works, cant test it cus of the fuckin bad list thing

status now shows the distriution of sex and position

---

code/controllers/subsystem/statpanel.dm

Making it a little more clear what it is has been added.
:cl:
/:cl:

Licking the status panel

---

code/modules/jobs/job_types/followers.dm

It was spawning for some people and not for others, I made a workaround.
:cl:
/:cl:

Medbeam Fix

---

code/__DEFINES/preferences.dm

Status information wordage fix

---

code/modules/mob/living/simple_animal/hostile/f13/wolf.dm

white woman moment for fenny (if it passes check it's good to go)

---

code/__DEFINES/preferences.dm
code/controllers/subsystem/statpanel.dm
code/modules/client/preferences_toggles.dm
code/modules/mob/login.dm
code/modules/mob/logout.dm

THe stat panel now supports bisexuality. Thought it did before, but I must have overlooked it.

Changes bisexual alpha from 0 to 255

---

code/controllers/subsystem/parallax.dm

Shut up parallax no one loves you

---

code/datums/components/reskin.dm
code/modules/clothing/under/miscellaneous.dm

I did the thing Fenny wanted.
:cl:
spellcheck: I changed 5.56 to 5mm as requested
/:cl:

Did the thing Fenny wanted!

---

code/modules/clothing/head/f13factionhead.dm
modular_citadel/code/modules/client/loadout/head.dm
modular_citadel/code/modules/client/loadout/neck.dm

Adds the khan full helmet which was previously unavaliable as a loadout option + brings down the price of the shoulder holster jackets to 2, as the regular shoulder holster also cost 2 and these are just cosmetic variants.

Adds the Khan full helmet to the loadout + reduces the price of the cosmetic shoulder holsters from 3 to 2.

---

code/modules/projectiles/boxes_magazines/external/lmg.dm
code/modules/research/designs/ammolathe_designs.dm

RPD magazine

---

code/modules/research/designs/ammolathe_designs.dm

We're taking his fucking balls
:cl:
/:cl:

Fixing Merek

---

code/modules/clothing/suits/arfsuits.dm
code/modules/projectiles/ammunition/energy/laser.dm

Title
:cl:
- Fixes the Wattz 1k-s pistol having 40 shots still; brought it down to 30 instead
- Fixes the FTM medium armor using the wrong pocket
:cl:

Two minor fixes (good to go if it passes checks)

---

code/game/objects/items/stacks/medical.dm

healing a creature with stackables or quirks now takes some time instead of no time

creature instant healing fix

---

code/game/objects/empulse.dm
code/game/objects/items/grenades/ghettobomb.dm
code/game/objects/items/grenades/grenade.dm
code/modules/hydroponics/grown/citrus.dm
code/modules/hydroponics/grown/misc.dm
code/modules/mining/ores_coins.dm
code/modules/research/designs/ammolathe_designs.dm

because BOY am I tired of seeing that, lol
:cl:
/:cl:

de-verbositying the admin log for grenades

---

code/game/machinery/syndicatebomb.dm
code/game/objects/hand_items.dm
code/game/objects/items/hot_potato.dm

More bullshit

---

code/datums/elements/mob_holder.dm

allows dextrous simple animals to use the "smol" quirk and pick people up
:cl:
/:cl:

mobs can interact with smol quirk characters

---

code/modules/jobs/job_types/oasis.dm

Just a temp fix to removing this worthless job
:cl:
/:cl:

Removes council slots

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
code/__DEFINES/jobs.dm
code/game/objects/effects/landmarks.dm
code/modules/jobs/access.dm
code/modules/jobs/job_types/oasis.dm
code/modules/jobs/jobs.dm

I asked, people like the idea.
:cl:
/:cl:

Nash Curator

---

code/modules/cargo/packs/security.dm

Nerfs advanced armor yet again.
:cl:
/:cl:

Hotfix to cargo yet again (good to go if it passes checks)

---

code/datums/components/crafting/recipes/recipes_tools.dm

Hand saw crafting recipe

---

code/modules/jobs/job_types/oasis.dm

Librarian Update

---

code/modules/spells/spell_types/shapeshift.dm

fixes the runtimes by adding more safeties, but doesn't fix the source of the problem (the creator can do that)

shapeshift runtime fix

---

modular_coyote/code/birds.dm

Fixing birds a bit

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Returns the librarys decorations

---

code/modules/mob/living/living.dm

Title
:cl:
tweak: tweaked a variable on pixel sliding
/:cl:

Adjusting pixel sliding variabls [ready to merge]

---

code/modules/client/preferences_savefile.dm

it should now save and set the preferences properly.
:cl:
fix: fixed ACSI
/:cl:

Animal crossing-like sound indicator fix [ready to merge]

---

code/modules/mob/living/simple_animal/hostile/hostile.dm

Turns off decomposing bodies for now
:cl:
tweak: Turns off decomposing bodies.
/:cl:

Disabled Decomposing hostile mobs

---

code/_onclick/hud/map_popups.dm

Updating map_popups.dm from upstream

---

code/modules/research/techweb/all_nodes.dm
code/modules/research/techweb/nodes/medical_nodes.dm

CI should stop failing with this PR merged (forgot these existed lol)
:cl:
/:cl:

fixes research nodes

---

code/game/objects/effects/spawners/masterlootdrop.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/guns/ballistic/automatic.dm
modular_coyote/eris/code/gun_firemode.dm

Fixes RPMs and adjusts the damage and RPMs of some guns and loadout firearms as well.
:cl:
/:cl:

(Merge whenever possible) RPM fixes

---

code/game/turfs/simulated/floor/f13_floors.dm
code/modules/fallout/turf/ground.dm
modular_coyote/code/modules/turf_changes/PlantGrass.dm

Makes plants not hard del every time they're destroyed, *Jon*

Destroying ambient plants no longer hard dels

---

code/datums/components/crafting/recipes/recipes_forge.dm

Theres probably plenty of people that have experienced spending the minute and a bit it takes to craft one just to get bumped or nudged, or find out someone else already made one and they wasted that time. Its pretty frustrating!

Reduces crafting time of the Sledgehammer to make it more reasonable

---

code/modules/projectiles/guns/ballistic/bow.dm

Examine text for bows

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Moves some vending machines around the bar

---

code/modules/WVM/wmv_buyer.dm

fixes a typo for expensive items 100-299 coins

---

code/__HELPERS/icons.dm
code/controllers/subsystem/mobs.dm
code/modules/fallout/turf/walls.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/carbon/monkey/monkey.dm

SSmobs has a var there_is_no_escape that will disable matrixes from letting you leave. Hows that for player retention?
testing to see how much lag people despawning is.

disables leaving the game!

---

code/datums/action.dm
code/game/machinery/Beacon.dm
code/game/machinery/embedded_controller/embedded_controller_base.dm
code/game/machinery/firealarm.dm
code/game/objects/effects/decals/cleanable/humans.dm
code/game/objects/items/devices/beacon.dm
code/game/objects/items/devices/taperecorder.dm
code/game/objects/items/tanks/jetpack.dm
code/game/objects/structures/crates_lockers/crates.dm
code/game/turfs/turf.dm
code/modules/atmospherics/machinery/airalarm.dm
code/modules/clothing/gloves/tacklers.dm
code/modules/food_and_drinks/kitchen_machinery/deep_fryer.dm
code/modules/food_and_drinks/kitchen_machinery/grill.dm
code/modules/lighting/lighting_source.dm
code/modules/mob/living/carbon/alien/humanoid/alien_powers.dm
code/modules/mob/living/simple_animal/bot/bot.dm
code/modules/paperwork/ticketmachine.dm
code/modules/power/apc.dm
code/modules/power/lighting.dm
code/modules/recycling/disposal/pipe.dm

Copying tg pr #57736, even if we don't need it.
:cl:
/:cl:

Fenny cavemans the code

---

code/modules/jobs/job_types/wasteland.dm

Preachers have citizen access now. As Jaggachi requested.
:cl:
tweak: tweaked preacher access.
/:cl:

Preachers are citizens too [ready to merge]

---

code/datums/traits/good.dm

Fixes Prices That I Forgot To Commit

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

For bottoms who don't want to travel, but want to be seen.
:cl:
/:cl:

Horny Hutches

---

code/modules/projectiles/guns/ballistic/rifle.dm

Does what it says on the tin. Unfortunately scope sprites are broken and don't appear. They used to on Sunset, so no clue where it might've broken.

.22 Lever actions now silencable and scopable

---

code/modules/mob/living/carbon/human/species_types/dwarves.dm
code/modules/mob/living/carbon/human/species_types/humans.dm

- Lets Drawves have snouties, tailies, wingies, and hornies. (hehe)
- At last, humans may wag their tail
:cl:
/:cl:

Have your snouty drawves and your wagging tails on your humans too!

---

code/datums/traits/good.dm
code/datums/traits/negative.dm
code/game/gamemodes/objective.dm

No no, no.  Please no.  Stop hard del'ing you son of a bitch
:cl:
/:cl:

Family Heirloom Switched off

---

code/datums/weather/weather_types/rain.dm

Gonna see if this helps with the rain lag
:cl:
/:cl:

Lowers rain proc prob to washies

---

code/modules/food_and_drinks/food/snacks_other.dm

because fuk u *augh
:cl:
/:cl:

Put Lollipops in your mask slot

---

code/modules/client/preferences.dm

fixes backpack and persistent scar settings

---

code/game/objects/items/melee/f13onehanded.dm

F13 knives gain
- Go in mouf slot
- counts as a screwdriver (but shitty)
:cl:
/:cl:

Knife Update

---

code/datums/mind.dm
code/datums/wounds/_wounds.dm
code/modules/projectiles/projectile.dm

Harddelbegone

---

modular_splurt/code/datums/modules/client/verbs/character_directory.dm

TGUI doesnt like nulls. I dont blame it.

fixes species not workinging

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Small fix to Heaven's Night

---

code/modules/mob/living/brain/brain.dm

big brain maneuver

---

code/_onclick/hud/screen_objects.dm
code/datums/tattoo.dm
code/game/objects/items/cards_ids.dm
code/modules/fallout/turf/walls.dm
code/modules/surgery/bodyparts/_bodyparts.dm

- Fixed tattoos causing bodyparts to hard delete
- Fixed another source of green ghosts in your inventory (probably not the last 😸 )
- Fixed a runtime when attempting to matrix something that isn't a /living mob

Hard del prevention clinic 2

---

code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm

It wasn't showing up because it was a child of the normal hunting shotgun recipe and that fucks things up and I don't know why but I do know it do so now its promoted to its own thing

Fixes the sawed off hunting shotgun crafting recipe because I'm a little stupid

---

code/modules/mob/inventory.dm
code/modules/mob/living/living.dm
code/modules/mob/mob.dm
config/maps.txt

woooops who dropped these many global variables on this code? certainly not me! haha... might as well move them out of the way...
Sweeping under the rug a bunch of variables.
Pixel shifting does this:
It remembers position and direction faced
Now the smart unholstering should also recognize weapons held on the backpack slot.
:cl:
fix: fixes my mistakes, chapter I
/:cl:

Fixing my mistakes before Dan notices chapter I [ready to merge]

---

code/game/gamemodes/dynamic/dynamic.dm

peanut butter jelly time

---

code/modules/projectiles/guns/ballistic/automatic.dm

Adds a tidbit to the descriptions to show how the multi-cal function works
:cl:
/:cl:

Sidewinder Description update

---

COOLBOOK_books/chief_guide/Leadership.txt
COOLBOOK_books/chief_guide/Our History.txt
COOLBOOK_books/druid_guide/Our History.txt
COOLBOOK_books/villager_guide/Our History.txt
COOLBOOK_books/warrior_guide/Our History.txt
COOLBOOK_books/warrior_guide/index.json
code/modules/jobs/job_types/tribals.dm
code/modules/mining/lavaland/necropolis_chests.dm

Changes all references to Head Hunter to Hunt Master
:cl:
/:cl:

Retitles Head Hunter(Ready to Merge)

---

_maps/map_files/Pahrump-Sunset/Dungeons.dmm
code/game/objects/structures/lavaland/necropolis_tendril.dm
code/modules/mob/dead/new_player/logout.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm

goliaths suck

---

code/datums/components/crafting/recipes/recipes_primal.dm

Just takes one wheat in the primal tab
:cl:
/:cl:

Adds a crafting recipe for hay

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
_maps/map_files/Pahrump-Sunset/RedRiver.dmm
_maps/map_files/Pahrump-Sunset/RockSprings-Upper.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm
code/modules/mob/dead/observer/observer.dm

snobserber & bodyparts

---

code/datums/brain_damage/severe.dm
code/modules/mob/living/simple_animal/friendly/farm_animals.dm
code/modules/mob/living/simple_animal/friendly/mouse.dm
code/modules/mob/living/simple_animal/friendly/pet.dm

Moves a variable inside mobs to define in an easier way what mob is a pet and what isn't.
Amazingly cats are now pets
:cl:
tweak: tweakes monophobia
/:cl:

Monophobia modularity [ready to merge]

---

code/game/gamemodes/dynamic/dynamic.dm

Revert "peanut butter jelly time" for dan

---

code/_onclick/hud/screen_objects.dm

removes another source of green ghosts

---

code/_globalvars/lists/maintenance_loot.dm
code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm

fixes ghouls hard deleting and speeds up init time

---

code/modules/clothing/under/accessories.dm

fixes some accessory names being proper nouns

---

code/modules/projectiles/gun.dm
code/modules/projectiles/guns/ballistic/flintlock.dm
code/modules/projectiles/guns/energy.dm
code/modules/projectiles/guns/energy/laser.dm

FUn fact, laser guns never cleaned up their lens. lovely

Fixes some hard dels

---

code/__DEFINES/combat.dm

I HAVEN'T TESTED THIS BUT FENNY SAID IT SHOULD BE FINE
:cl:
tweak: doubled literally all fire-rates in the defines
/:cl:

Doubled gun RPM in defines.

---

code/modules/client/preferences.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/projectiles/boxes_magazines/_box_magazine.dm

Update preferences.dm 2

---

code/modules/projectiles/guns/ballistic/automatic.dm

Turns out, it was a carbine all along!
:cl:
/:cl:

Class Reassignment of 14MM Rifle

---

code/modules/client/preferences.dm

Okay maybe not (prosthetics fix)

---

code/_onclick/hud/screen_objects.dm

It cropped up again while I was refactoring how they render

fixes active hand bug again sorry

---

code/game/machinery/computer/dna_console.dm
code/game/objects/items.dm
code/modules/mob/logout.dm
code/modules/mob/mob.dm
code/modules/research/nanites/nanite_chamber.dm
code/modules/research/nanites/nanite_chamber_computer.dm

Thanks tg.
Fuck you FO13.
:cl:
/:cl:

Insanity - The rest of 59371 that I can get myself

---

code/game/gamemodes/dynamic/dynamic.dm
code/game/objects/structures/watercloset.dm
code/game/turfs/simulated/water.dm
code/modules/fallout/turf/ground.dm

fixes washing not updating your sprite
disables annoying midround antag messages
allows players to alt-click water turfs to clean themselves like if they'd used a shower

I don't need it

---

code/game/objects/effects/spawners/masterlootdrop.dm
code/game/objects/items/dualsaber.dm
code/game/objects/items/melee/energy.dm

Adds non toy versions of the eutactic blade as rare melee weapons, and the broken version as an uncommon variant, i'd add the regular energy swords as well but their sprites are broken.

adds eutactic blades to the  loot pool + fixes the neptune being missing from the  loot pool as well

---

code/datums/traits/good.dm

Didnt give the tackling ability because Im a dummy and forgor to add the component codeblock

Fixes Rooftop Nomad Quirk Package

---

code/modules/mob/dead/observer/observer.dm

jk it just reverts the bandaid fix

adds more lag

---

code/modules/mob/dead/new_player/new_player.dm

Once more into the breach (testmerge)

---

code/game/objects/items/fallout13misc.dm

it actually wasn't a dupe but it was misleading. The cost of a flag was 1 but it told you that it was 10 lol
:cl:
/:cl:

fixes flag pole dupe

---

code/game/objects/structures/watercloset.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/mob/status_procs.dm

fixes your body temperature never going down by making it so it never goes up or down ever again :^)
also does not fix the fact that being on fire doesn't do any actual damage but I do not get paid enough to fix that

fixes body temperature not going down ever

---

code/modules/mob/inventory.dm
modular_coyote/eris/code/wielding.dm

Making dual wielding more consistent and making smart holstering a little smarter.
:cl:
fix: fixed dual wielding
/:cl:

Melee dual wielding - bug fix & smart holstering update [ready to merge]

---

modular_citadel/code/modules/client/loadout/__donator.dm

Title. Accidentally gave someone the wrong Trek uniform. Also fixes a formatting error.
:cl:
/:cl:

Fixes someone's loadout (Good to go if it passes checks)

---

code/modules/mob/living/carbon/human/species_types/dwarves.dm

Dwarf colors

---

code/modules/admin/verbs/adminhelp.dm
code/modules/admin/verbs/adminpm.dm

Aff/Neg Ahelp response

---

code/modules/projectiles/projectile/bullets/pistol.dm

Lowers most of the low end percent rolls
decreases most top end damage
increases crit chance
Main goal: dopamine my beloved
secondary goal: dial in damage to reasonable levels
:cl:
/:cl:

Updates pistol bullet damage

---

_maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
_maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm

Some map fixes

---

code/modules/mob/living/simple_animal/hostile/regalrat.dm

fixes skitter rat destroy

---

_maps/map_files/Pahrump-Sunset/RedRiver.dmm
_maps/map_files/Pahrump-Sunset/RockSprings.dmm
code/modules/mob/living/emote.dm

Map fixes, never ends

---

code/modules/projectiles/ammunition/energy/plasma.dm

Title. Nerfs the bouncy unique plasma gun from 30 shots to 20
:cl:
/:cl:

Fix for the bouncy Neptune blaster (good to go if it passes checks)

---

code/modules/projectiles/guns/energy/plasma_cit.dm

downgrades it's RPM from 300 (which was actually 600) to 100 (200) which hopefully will make it a LOT less insane than it currently is, alongside a minor damage decrease.

Nerfs the laser AK firing speed by a considerable amount and the damage by T1

---

code/modules/projectiles/guns/magic/staff.dm
code/modules/projectiles/guns/magic/wand.dm
code/modules/projectiles/projectile/beams.dm
code/modules/projectiles/projectile/bullets/rifle.dm
code/modules/projectiles/projectile/energy/tesla.dm
code/modules/projectiles/projectile/reusable/arrow.dm
code/modules/projectiles/projectile/special/ion.dm

…mage
what are you gonna DO about it?
:cl:
/:cl:

Projectile Smojectiles, yes practice arrows can do 70,000 some odd da

---

code/_onclick/hud/parallax.dm

seems to run fine, will need a testmerge or full merge to do proper testing

ports tgstation 78066

---

code/_onclick/click.dm
code/modules/mob/living/living.dm
modular_coyote/eris/code/dual_wielding.dm

Only me and God know how this fixes basically all issues with dual wielding, and now that my brain is fucking dead, only Gods know how.
fix: fixed dual wielding bugs
/:cl:

Fixing some bugs on dual wielding - iteration I [ready to merge]

---

code/modules/mob/living/simple_animal/hostile/hostile.dm

Reverts ARF-SS13/coyote-bayou#3309
dead mobs now creates more lag than deleting them after our optimizations

Revert "Disabled Decomposing hostile mobs"

---

code/modules/jobs/job_types/wasteland.dm

all my homies hate tribal traditions (good to go if it passes checks)

---

code/modules/projectiles/guns/ballistic.dm

makes guns squish when you manipulate them

---

code/modules/mob/living/simple_animal/hostile/f13/mirelurks.dm
code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm

"Fixes" butchering

---

code/modules/projectiles/guns/energy/laser_crank.dm

Making my own code a little bit more readable and more modular.
:cl:
fix: fixes my mistakes.
/:cl:

Crankable Laser Guns - Update I [ready to merge]

---

code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm

Fixes geckos sprinting at half health

---

code/modules/clothing/spacesuits/hardsuit.dm

Title.
:cl:
- Hardsuits are now Normal-sized so they actually fit in bags like other armors
- Fixes the flavortext of Kelp's custom armor
- Changes the name of the Cydonian Hardsuit to 'powersuit' to help reflect it's supposed to be akin to PA in flavor
:cl:

Tiny Loadout/Hardsuit fixes (Good to go if it passes checks)

---

code/modules/client/verbs/newbie.dm

newbie renamed to newbie/help (new verb is help)

---

code/game/objects/effects/spawners/masterlootdrop.dm

Title.
:cl:
- TL;DR I moved a bunch of common, uncommon, and rare guns into the respective cowboy loot pools because 40% chance to get a brush gun or compound bow made people sad
:cl:

Yet another loot list overhaul (Good to go if it passes checks)

---

modular_coyote/code/mob.dm

Re-adds cats to the creature list
:cl:
add: Added cats back
/:cl:

Adds Cats back

---

code/game/objects/items/defib.dm
code/modules/mob/living/emote.dm
modular_citadel/code/modules/client/loadout/hands.dm

Freedom of Medical Act

---

code/datums/traits/good.dm

:cl:
add: Added some medical records for your quirks
add: Added more messages for when you gain a quirk, like getting the Zoomies quirk
spellcheck: Fixed a few typos and grammatical errors in the Quirks
/:cl:

QuirkFix =Typo fix, Grammar fix, and punctuation=

---

code/modules/mob/living/emote.dm

Touches up the new verbs, not perfect tho

---

code/modules/mob/living/emote.dm

Oops #439749237597

---

_maps/map_files/coyote_bayou/Texarkana_underground.dmm

:cl:
tweak: Changed Science to be smaller. 
tweak: Science also has some minor machines that need to be repaired. 
/:cl:

Texarkana underground Sci Lab

---

_maps/map_files/coyote_bayou/Texarkana_underground.dmm

Fuck I didnt realize how bad the fucking hallway was, I fixed it here :(
:cl:
tweak: Made hallway smoller in sci
/:cl:

Mapping - SMOLLER SCI YES

---

code/game/objects/items/miscellaneous.dm

fixes the combat carbine being unselectable

---

_maps/map_files/coyote_bayou/Texarkana_underground.dmm

Reverts ARF-SS13/coyote-bayou#3600

Revert "Mapping - SMOLLER SCI YES"

---

code/modules/admin/verbs/adminhelp.dm

admin HELP ME I'M DYING

---

code/__DEFINES/misc.dm
code/game/objects/items.dm
modular_coyote/eris/code/dual_wielding.dm
modular_coyote/eris/code/wielding.dm

displays DPS alongside the regular damage when examining a weapon's stats

---

code/modules/WVM/wvm.dm

money dupe fix

---

code/datums/components/crafting/recipes/recipes_misc.dm

Now you can craft Abraxo!

---

code/datums/components/storage/concrete/bags.dm
code/game/objects/items/storage/bags.dm
code/modules/projectiles/guns/ballistic/bow.dm

also makes bow feeding a bit easier to use
maybe

quivers load only arrows

---

modular_citadel/code/modules/client/loadout/__donator.dm

Title. Just gives someone some e-daggers to mess around with.
:cl:
/:cl:

Updates a loadout (Good to go if it passes checks)

---

_maps/map_files/coyote_bayou/Ashdown.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Redwater.dmm
_maps/map_files/generic/CentCom.dmm

:cl:
add: Crows have been added to ... I think everywhere!
/:cl:

Mapping - Crows and Splashart fix!

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

:cl:
tweak: Removed one row of fences on the northern street near the outskirts of Nash. 
/:cl:

Mapping - Smol bridge removal of mine woops

---

code/game/objects/objs_set_vars_verbs.dm

Small fixes
:cl:
fix: fixed my bad life decisions.
/:cl:

fixing my mistakes III - iteration I [ready to merge]

---

code/modules/mob/living/carbon/human/species.dm

clicking yourself on harm intent doesn't hurt you anymore.
maybe this needs some sort of extra check, let's merge it and fix the issues tomorrow if they come up.
:cl:
tweak: can't hurt yourself on harm intent.
/:cl:

stop people from punching themselves - iteration I [ready to merge]

---

code/modules/clothing/under/accessories.dm

No more stacking radiation

---

code/modules/projectiles/guns/energy/laser.dm

Title. Made self-charging guns largely take longer to recharge. Did some math, they should all be roughly the same shots/second (maybe).
AK470 and Worn Nuclear Rifles untouched for the moment because they seem to be fine (may be biased on the WNR but I will say it kind of chugs and is nooooot great)
:cl:
server: something server ops should …

Nerfs self-charging guns somewhat (good to go if it passes checks)

---

code/modules/projectiles/guns/ballistic/pistol.dm

On gods green earth if you are gonna import a glock, dont butcher the description. Anyways i made it more rational
:cl:
/:cl:

Fixed Glock Descrip, Learnign VSC

---

code/game/gamemodes/dynamic/dynamic.dm

Needs a test merge, but since threat is never not 0.1... well... nothing should ever trigger?
:cl:
/:cl:

Sunsets Dynamic 2021

---

code/game/objects/effects/spawners/masterlootdrop.dm
code/modules/WVM/wvm.dm
code/modules/cargo/exports/misc_export.dm
code/modules/projectiles/ammunition/energy/laser.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/energy/plasma_cit.dm
code/modules/projectiles/projectile/beams.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Title. Fixes a lot of things, including a duplicated loot pool that was screwing things up.
:cl:
- Removes an infinite money exploit
- Unfucks the Laser AK
- Makes the AK740 for loot and loadouts
- Fixes the AK470 for loot
- Makes a unique AK470M for someone's loadout
- Unfucks masterlootdrop.dm yet again so people stop getting a billion compound bows
- Makes it so TG blasters and a few other guns can be sold through cargo
:cl:

Lots of fixes in general (Good to go if it passes checks)

---

_maps/map_files/coyote_bayou/Texarkana_underground.dmm

It's totally not a "listening post", shut the front door
:cl:
/:cl:

Updates the "radio station"

---

code/__DEFINES/traits.dm
code/datums/traits/good.dm
code/modules/mob/living/carbon/carbon_sprint.dm
code/modules/mob/living/living_defines.dm
code/modules/mob/living/living_sprint.dm
config/game_options.txt

- Fixed the Zoomies and Super Zoomies traits
- Increased the base sprinting stamina buffer from 13 to 30
- Fixed the Deadeye trait description

Fixes Zoomies and Deadeye Description

---

code/modules/projectiles/boxes_magazines/ammo_boxes.dm
code/modules/projectiles/projectile/bullets/pistol.dm
code/modules/projectiles/projectile/bullets/rifle.dm

Title. Just adjusts .308 and .44 mag to be a little more reasonable.
:cl:
- Increased consistency of .308 damage rolls
- Nerfed .44 but buffed the ammo box
:cl:

Adjusts some ammo stuff (Good to go if it passes checks)

---

code/__HELPERS/_lists.dm
code/__HELPERS/cmp.dm
code/controllers/subsystem/who.dm

Attempts to increase the QOL of our new who a bit

---

code/controllers/subsystem/garbage.dm
code/game/objects/items.dm
modular_coyote/eris/code/mods/_upgrades.dm
modular_coyote/eris/code/mods/mod_types.dm

I mean, what's the worst that could happen, right?
:cl:
/:cl:

Just a rogue thought, don't mind this pr.  Probably not important.

---

_maps/map_files/coyote_bayou/Dungeons.dmm
_maps/map_files/coyote_bayou/Texarkana_underground.dmm
code/controllers/subsystem/research.dm
code/game/objects/effects/spawners/f13lootdrop.dm
code/modules/reagents/reagent_containers/bottle.dm

Removes FEV and curling

---

_maps/map_files/coyote_bayou/Ashdown-Upper.dmm
_maps/map_files/coyote_bayou/Ashdown.dmm

Adds a proper, full sized clinic to Ashdown, located juust outside the bridge and has an alternate path in via Ashdown itself.
:cl:
add: clinic (rough)
/:cl:

Ashdown Clinic

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm

*cutely removes your landing spot

---

code/modules/client/client_procs.dm

Fingers crossed, might help lag at the cost of join time
:cl:
/:cl:

Load more sounds into the pre-loader

---

_maps/map_files/coyote_bayou/Ashdown.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Redwater.dmm
code/modules/fallout/obj/structures/mob_spawners.dm

Removes crow nests, so they can be refactored.

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

Aslo adds a sammish for the chuby fox girl
:cl:
/:cl:

Fixes the blocked tile in the bank

---

code/game/objects/items/devices/PDA/PDA.dm

More renaming of the pipboy. Code is slippery

---

_maps/map_files/coyote_bayou/Ashdown-Upper.dmm
_maps/map_files/coyote_bayou/Ashdown.dmm

What this PR does is opens the wall up so you can go into the clinic and go up the stairs.
:cl:
bugfix: ashdown clinic
/:cl:

Map Bugfix: Ashdown Medical Clinic

---

code/modules/mob/mob.dm

"Grab their wrist.",
"Corner them.",
"Check them for wounds.",
"Play with their hair.",
"Squeeze them.",
"Shove them.",
"Sneer at them.",
"Pay them more attention.",
"Appear more demure to them.",
"Bend over for them.",
"Look heroic for them.",
"Look like you need their help.",
"Grab their arm.",
"Pull their hair.",
"Grab their belt."
Also thank @TalkingCactus for helping me fix the their thing <3
:cl: …

Flirt pass #3

---

code/__DEFINES/_flags/_flags.dm
code/__HELPERS/icons.dm
code/modules/asset_cache/asset_cache_item.dm
code/modules/asset_cache/transports/asset_transport.dm
code/modules/mob/dead/new_player/preferences_setup.dm

updates our icon2html to mostly parity with tgstation

---

code/datums/components/spawner.dm

mobs suck, hate em, pvp now
:cl:
/:cl:

100% chance to spaghetti when being weird

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

cope cope cope cope cope bar cope cope cope

---

code/__DEFINES/armor.dm
code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm

Deathclaws feel like complete and utter pushovers. All of them. For some, this is okay! For the big powered armor deathclaw fight? Not so much. The only one I am iffy on is the legendary ones and the Mothers...
:cl:
tweak: deathclaws
/:cl:

Deathclaw buffs

---

modular_citadel/code/modules/client/loadout/mask.dm

Because people too lazy to just craft the dang thang
:cl:
/:cl:

Adds the chameleon mask to loadout (Good to go if it passes checks)

---

code/modules/clothing/head/helmet.dm

Fixes the Borderlands helmets having snoots poking through (Good to go if it passes checks)

---

code/modules/mob/emote.dm
modular_citadel/code/modules/client/loadout/suit.dm

You silly goober, lol
:cl:
/:cl:

Removes two rogue object trees from @RinPin

---

code/modules/client/preferences.dm

so it all fits onto one page without needing to scroll

reorganizes the preferences tab

---

code/modules/projectiles/projectile/bullets/rifle.dm

See title, no longer does sub mean .30-06/.45-70 damage 40% of the time, also now has bane.
:cl:
tweak: .50MG damage
/:cl:
Satisfying. 
https://github.com/ARF-SS13/coyote-bayou/assets/80431951/235034c1-6c9f-48f4-9f25-61997c1d1f46

.50MG is no longer Anemic

---

modular_citadel/code/modules/client/loadout/__donator.dm

Fixes a loadout, hopfully this works.
:cl:
/:cl:

(MERGE WHEN CAN) Potential loadout fix

---

code/modules/mob/living/simple_animal/hostile/hostile.dm

edit of fenny's edit in #3722 
:cl:
/:cl:

Cardinal Dodging + Bumping

---

config/game_options.txt

Updates the maximum penis size that someone can set using prefs menu, private menu, or slime transformation menu to make use of the new sprites added in https://github.com/ARF-SS13/coyote-bayou/pull/3695 without needing to mix up a growth chem every round.
Getting to a size larger than 50 still requires a person to make growth chems, but the actual sprite differences end at 50. So I figured that's a good point to cap it at.
:cl:
tweak: max donger size that someone can set using various menus.
/:cl:

Hotdog Size

---

code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/mob/mob.dm

This list is literally never ending, we need to make it a tgui window that can have these and custom ones.  Then players can make their own flirts while the defined ones exist as a 'baseline' for creativity.
But this is fine for now.
:cl:
/:cl:

Flirt alphabetizing & 24 more of the damn things

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

https://images-ext-2.discordapp.net/external/3zlYORyk3P-9oWWV45ktIuWn-cd_oVNzPitHFSJAKXM/https/i.gyazo.com/thumb/1200/46f412f6ae06dcdad7262366799195cd-png.jpg?width=796&height=764
Still mostly dirty and a mess, but does add in some of the design to help with round start building their faction idea.
:cl: …

Offrldr's group hideout

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

The new place for the player faction had no roof in one place. whoops!

---

code/modules/mob/mob.dm

Stops ghost flirts & flirting with things with no ckey

---

code/__DEFINES/misc.dm

disables cargo errors

---

code/modules/fallout/obj/trash_stack.dm

fixes a trash sound bug

---

code/datums/traits/good.dm

Fixes a tiny typo

---

code/__DEFINES/is_helpers.dm
code/game/objects/items/crayons.dm

lets you spraypaint any floor

---

code/datums/traits/neutral.dm
code/game/objects/structures/crates_lockers/closets/bodybag.dm
code/modules/client/preferences.dm
code/modules/clothing/head/misc_special.dm
code/modules/fallout/obj/rockitlauncher.dm
code/modules/mob/dead/new_player/new_player.dm
code/modules/mob/living/living_defines.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/projectiles/guns/ballistic/flamethrower.dm
code/modules/projectiles/guns/ballistic/minigun.dm
code/modules/projectiles/guns/energy/laser.dm
modular_coyote/code/pmon_mob.dm

fixes a few bugs as well
:cl:
/:cl:

creature special and quirk examine

---

code/modules/mob/dead/new_player/sprite_accessories/Citadel_Snowflake.dm

Fixes Ruby's tail

---

modular_citadel/code/modules/client/loadout/backpack.dm

fixes missing ID card from loadout

---

code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/living.dm

moves subtle and subtler to living

---

_maps/map_files/coyote_bayou/Ashdown.dmm
_maps/map_files/coyote_bayou/Dungeons.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm

Adds the roof to a house, oops

---

code/modules/mob/living/simple_animal/hostile/bees.dm

Stops radbees from dodging like lunatics

---

code/modules/admin/admin_verbs.dm
code/modules/admin/verbs/debug.dm
code/modules/projectiles/guns/energy.dm

This verb, when used, will compile a list of every gun in the fucking game and then sort them by how absolutely OP they are.

Adds a Gun Balancing Debug Verb

---

code/modules/jobs/job_types/oasis.dm

Basically an actual mayors lackey, but there is no actual mayor.  Funny that.
:cl:
/:cl:

Adds Deputy Mayor to Nash

---

code/modules/clothing/under/miscellaneous.dm

Fixes the gear harness so it fully uncovers a body.
:cl:
/:cl:

(MERGE WHEN READY) Gear harness fix

---

code/game/objects/items/granters.dm

And then Fenny did unto the code as a mad butcher would onto his sweet meats.  Slicing it in twain and allowing nature to finally heal.
:cl:
/:cl:

Let them drop the fucking book, you mongrels

---

code/modules/reagents/chemistry/reagents/toxin_reagents.dm

Actually removes the reagent for FEV. Forgot about this part of it

---

code/__DEFINES/mobs.dm
code/datums/components/waddling.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/mob/dead/new_player/new_player.dm

Adds waddling settings to character creation 

---

code/__HELPERS/text.dm
code/game/objects/structures/flora.dm

jungle tree color randomizer

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

also makes bball court at the school usable
cleaned up gas station entrance
:cl:
/:cl:

gas station tune up

---

code/controllers/subsystem/artifacts.dm

also adds a system to individually remove any more we find
:cl:
/:cl:

fixes error-sprite artifact

---

code/controllers/subsystem/npcpool.dm

Why yes, I want you to die.

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

A lot of gravel on the base Texarkana Z had /inside/ as its turf. Thus making a weird stepping sound.
This fixes that.
:cl:
tweak: changed some gravel turfs.
/:cl:

Changes inside gravel for outside gravel [Ready]

---

code/modules/projectiles/guns/ballistic/shotgun.dm

Fixes capacity typo for tox

---

code/controllers/subsystem/npcpool.dm

Okay, don't die that hard, fuck me

---

code/datums/components/butchering.dm
code/modules/mob/dead/new_player/new_player.dm
code/modules/mob/living/simple_animal/friendly/farm_animals.dm
code/modules/mob/living/simple_animal/hostile/animalhostile.dm
code/modules/mob/living/simple_animal/hostile/f13/geckotribe.dm
code/modules/mob/living/simple_animal/hostile/f13/insects.dm
code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/elites/goliath_broodmother.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/goliath.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/polarbear.dm
code/modules/mob/living/simple_animal/hostile/mining_mobs/wolf.dm
modular_coyote/code/mob.dm

- Don't believe me? You shouldn't.
:cl:
/:cl:

Fixes all of the bugs with butchering

---

code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/mob/dead/new_player/new_player.dm
code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/simple_animal/simple_animal.dm
code/modules/mob/mob.dm
modular_coyote/code/modules/examine_images.dm

moves profile pictures off of discord

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Texarkana_underground.dmm

Adds some locks and fixes up a few doors around the tribal camp
Also makes it so you can actually touch the showers in the Tribal bathing area.
Rejoice.
:cl:
tweak: tweaked the tribal camp some
/:cl:

Fixes up the tribal camp a bit more. [READY]

---

code/modules/mob/mob.dm

Typo in a flirt

---

code/modules/clothing/neck/_neck.dm
modular_citadel/code/modules/client/loadout/neck.dm

JUST SPEEDMERGE
:cl:
JUST
FUCKING
SPEEDMERGE!!!
/:cl:

fixes my oopsie

---

modular_citadel/code/modules/client/loadout/backpack.dm
modular_citadel/code/modules/client/loadout/hands.dm

Adds zippos' to the loadout and changes their cost from 2 to 1 to go along with the cheap lighter
Changes the coin purse from 2 to 0 since the wallet is 0 and it's the same thing
:cl:
/:cl:

Some loadout things

---

code/modules/mob/living/carbon/human/human.dm
code/modules/mob/mob.dm
modular_coyote/code/modules/examine_images.dm

Set Profile Picture Verb Fix & Larger Profile Picture Pop-Up Window

---

modular_sand/code/datums/interactions/interaction_datums/lewd/self/cb_does_it_better/coy_crotch.dm

:peach: :hand: (x47) - Bongo Butt Beat Verb

---

code/modules/mob/living/carbon/human/species_types/dullahan.dm

fixes the headless horseman race

---

modular_sand/code/datums/interactions/interaction_datums/lewd/self/cb_does_it_better/coy_crotch.dm

Merp logic typo

---

code/modules/mob/living/carbon/carbon.dm

Fixes handcuffs

---

code/modules/clothing/suits/arfsuits.dm
code/modules/clothing/suits/arfsuits_unused.dm
modular_citadel/code/modules/client/loadout/suit.dm

What this PR does is readds this sprite from the junkyard. Costs two points in the loadout menu. Description for the item was rewritten and touched up to fit in more of line with coyote lore. 💮 🥀 🌹 
:cl:
readds: Tattered peace duster 
/:cl:

Armor Addition: Peace Duster

---

modular_sand/code/datums/interactions/interaction_datums/lewd/self/breasts.dm

No, I don't think so

---

modular_sand/code/datums/interactions/_interaction.dm
modular_sand/code/datums/interactions/lewd_interactions.dm

Now you gotta be in the same room with someone to see them chokeslam their hog.

Reduces range of intercontinental ballistic merp

---

code/modules/arousal/organs/penis.dm

Wiggity woodle, your dick is now a pool noodle

Unshrinks everyone's dicks

---

modular_sand/code/datums/interactions/interaction_datums/lewd/self/cb_does_it_better/coy_crotch.dm

:chicken: :poultry_leg: - Or, how i learned to pull the wishbone apart and love it

---

modular_sand/code/datums/components/interaction_menu_granter.dm
modular_sand/code/datums/interactions/_interaction.dm

You can now interact with yourself when interacting with others. Also, you no longer runtime when you do literally anything in the menu. Was causing infinite loops!

Fixes self-tweaking and some runtimes

---

code/controllers/subsystem/recoil.dm
code/modules/projectiles/ammunition/_firing.dm

love when shooting literally anything causes hella runtime.

Makes recoil suck assballs

---

code/__DEFINES/say.dm
code/datums/emotes.dm

add color to quotations in /me's

---

code/__DEFINES/span.dm
code/__HELPERS/text.dm
code/datums/emotes.dm

`/proc/alternating_color_span()`
:cl:
/:cl:

quickfix + generalization

---

_maps/map_files/CB-WIP/deerpinepass-alpha.dmm
_maps/map_files/CB-WIP/kuddlesprefabs.dmm
_maps/map_files/coyote_bayou/Legacy Storage/[wip]_mapping_resources.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

fixed some zoning in Nash so no more rain in buildings and stuff like that. You're welcome. Also touched up my favorite little oasis where I like to go to get out of sight. (And maaaybe expanded it with a big grotto above the ants mound, I dunno that would be cozy if I did I think.)
:cl:
/:cl:

very small changes

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Texarkana_underground.dmm

Hey, you know?  Nash can look okay.  If we try.

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

Map touch ups, because this shit really never ends.

---

code/modules/mob/living/simple_animal/friendly/cat.dm
code/modules/mob/mob.dm

Cat fix, and a flirt

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Texarkana_underground.dmm

… just saying man.
Title.
:cl:
/:cl:

You know, a radio tower shouldn't be a fucking bunker underground I'm

---

code/modules/reagents/chemistry/recipes/medicine.dm

The Synthi-Sang recipe has now been offered a chemistry alternative. The previous method of 
`Banana Yucca > Heat > Sali` is a bit tribal, don't you think? Follow the Quik-Clot recipe, you'll do fine.
:cl:
add: new Synth-Sang recipe option
/:cl:

Synthi-Sang, Chem Version

---

code/controllers/subsystem/mobs.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm

VSC didnt want to pull Fenny's PR, so I just made a new one. Makes it so mobs need to have a player within 12ish tiles to target other non-cliented mobs.

mobs need players round to fight each other

---

modular_sand/code/datums/interactions/interaction_datums/lewd/self/cb_does_it_better/coy_crotch.dm

MERP Typos

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm

small fixes for rad tower

---

modular_sand/code/datums/interactions/interaction_datums/lewd/self/cb_does_it_better/coy_climax
modular_sand/code/datums/interactions/interaction_datums/lewd/self/cb_does_it_better/coy_thighs.dm

I'll add moister verbs for climax tomorrow. This is a good starting point.
:cl:
/:cl:

MERP Verbening - Snimax & Thighs

---

modular_coyote/code/creature_species.dm

Aerodactyl Fix & Deathclaws Ported

---

code/modules/clothing/head/f13head.dm
code/modules/clothing/suits/arfsuits.dm

Hotfixes broken loadout armor for a user.
:cl:
/:cl:

(MERGE PLS) Hotfix no.??

---

modular_coyote/code/objects.dm

Credit for the sprites, go to them.
:cl:
/:cl:

Ports cave decor from Mojave Sun. 

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Texarkana_underground.dmm

- Makes the stone torches dense so you can't roast yourself on them
- Adds curtains to the hottub. Privacy!
- Adds a cozy wall fire to the hottub area. warm!
:cl:
/:cl:

Some small fixes to the pool

---

modular_sand/code/datums/interactions/interaction_datums/lewd/self/cb_does_it_better/coy_climax.dm

Oops, dumbass moment

---

code/modules/projectiles/ammunition/energy/laser.dm

gob's gun fix (good to go if it passes checks)

---

modular_sand/code/datums/interactions/interaction_datums/lewd/self/cb_does_it_better/coy_climax.dm
modular_sand/code/datums/interactions/interaction_datums/lewd/self/cb_does_it_better/coy_crotch.dm
modular_sand/code/datums/interactions/interaction_datums/lewd/self/cb_does_it_better/coy_head.dm

Adds
Squirbs 
- ✔️ 
Sherbs 
- ✔️ 
Ballerbs
- ✔️ 
Cookearbs 
- ✔️ 
Earbs 
- ✔️ 
Hairerbs 
- ✔️ 
Brederbs 
- ✔️ 
Other various things
- ✔️ 
:cl:
/:cl:

The Enplappening

---

code/modules/projectiles/projectile/beams.dm

I DEFY YOU SERDYKOV

---

code/modules/projectiles/guns/ballistic/automatic.dm

Blesses a gun
:cl:
tweak: Blessed be.
/:cl:

Blesses a particular Carbine [READY]

---

code/game/atoms.dm
code/game/say.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/mob.dm

image of lord farquaad
:cl:
/:cl:

fix chat color radio messages being white

---

modular_coyote/code/objects.dm

oops.dmi
:cl:
fix: fixed a file path
/:cl:

fixes a thing for a cat

---

modular_coyote/code/creature_species.dm

Fixes eevee carbon not being round start

---

code/datums/traits/neutral.dm
code/modules/surgery/organs/tongue.dm

adds 2 more language quirks

---

code/game/objects/items/devices/PDA/cart.dm
code/modules/mob/living/status_procs.dm

Mostly custom personal item changes <3
:cl:
/:cl:

Make changes to size cart

---

fortune13.dme
modular_sand/code/datums/interactions/_interaction.dm
modular_sand/code/datums/interactions/interaction_datums/lewd/self/cb_does_it_better/coy_climax.dm
modular_sand/code/datums/interactions/interaction_datums/lewd/self/cb_does_it_better/coy_crotch.dm
modular_sand/code/datums/interactions/interaction_datums/lewd/self/cb_does_it_better/coy_head.dm
strings/sausage_rolls.json

We do a lil trolling (I'm an idiot)

---

code/modules/projectiles/ammunition/energy/plasma.dm
code/modules/projectiles/projectile/beams.dm

fuck plasma, all my homies hate plasma

---

_maps/map_files/coyote_bayou/Ashdown.dmm

Enthickens the uncommonality of your neer'do'welledness, as well as engorging the rotten flesh of the foes below the green liquid death zone
:cl:
/:cl:

Updates Ashdown Z loot and spawners

---

code/_onclick/drag_drop.dm
code/modules/client/client_defines.dm

Remove some bloat

---

modular_sand/code/datums/interactions/interaction_datums/lewd/self/cb_does_it_better/coy_climax.dm

born to please climax
:cl:
/:cl:

Oh yeah, now we're cooking with fire

---

code/modules/admin/verbs/adminhelp.dm
code/modules/keybindings/keybind/client.dm

took longer to compile than write, hope it works

Fixes ahelp key thing whatever

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
code/__DEFINES/jobs.dm
code/game/objects/effects/landmarks.dm
code/modules/jobs/job_types/wasteland.dm
code/modules/jobs/jobs.dm

Adds Den Waster job, so people can go on vacation in the LOVE NOOK.
:cl:
/:cl:

Full Den Job & Area Additions

---

code/modules/mob/living/emote.dm

God this took way too long to get in

---

code/game/turfs/open.dm

Add missing air check

---

code/modules/clothing/clothing.dm
code/modules/clothing/head/helmet.dm

Axes 3 init lists from clothing

---

code/game/atoms.dm

qdel was overtiming hard, thats not good

maybe helps some tidi?

---

code/modules/fallout/obj/structures/simple_door.dm

adds ctrl clicking doors

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

We do a lil mapping

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

Brightens up the Tribe camp a bit.
Adds some missing Roofs
:cl:
add: Added a few misisng roofs
tweak: tweaked some grass and gravel
/:cl:

Brightens up the Tribe Camp

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm

removes old ladder in nash

---

code/datums/elements/beauty.dm

Removes beauty

---

code/controllers/subsystem/chat.dm

Fixes emoticon runtime

---

code/modules/fallout/obj/structures/simple_door.dm
strings/tips.txt

Tips & stuff

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm

Small radio tower fix

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm

Hold this.
:cl:
mapshit I know your ass isn't reading this... cunt
/:cl:

UPDEN FUCK YOU UP

---

code/modules/fallout/obj/structures/simple_door.dm

thought I already fixed this but I didn't

---

code/controllers/subsystem/ticker.dm
code/modules/admin/verbs/randomverbs.dm

fixes the Show Tip verb

---

code/modules/mob/living/simple_animal/hostile/f13/raider.dm
modular_coyote/code/flora_coyote.dm

also fixes a broken cultist dead sprite
:cl:
/:cl:

lets you set plant transparency per plant

---

_maps/map_files/coyote_bayou/Dungeons.dmm
_maps/map_files/coyote_bayou/Texarkana_underground.dmm

You always need mo koolaid

---

code/game/objects/effects/spawners/f13lootdrop.dm

adds mappable bounty hunter ticket spawners

---

code/__DEFINES/traits.dm
code/datums/components/combat_mode.dm
code/datums/looping_sounds/item_sounds.dm
code/game/objects/hand_items.dm
code/game/objects/items/devices/PDA/PDA.dm
code/game/objects/items/devices/geiger_counter.dm
code/modules/clothing/shoes/f13.dm

- Adds a built-in geiger counter into the PDA. Also fixes geiger counters not really working for most sources of radiation.
- Fixed characters briefly facing the direction they moved while in Combat Mode.
- Tough Feet are now glued to your actual feet and shouldn't ever come off, be destroyed, have their nonexistent laces tied, or collapse into a black hole. Hand items from verbs should also now not burn off from fire and acid anymore.

Datapal Geiger Counter, CI Movement Bug Fix, Tough Feet Covered in Superglue & Water

---

code/modules/mob/living/carbon/human/update_icons.dm
code/modules/mob/mob_transformation_simple.dm

quirks get assigned when CtrlShiftClicking an observer

---

_maps/map_files/coyote_bayou/Dungeons.dmm

updates it to be more cozy vault  like. Now just need a way to get into the thing, someone else can do that though
:cl:
/:cl:

Updates Tox's vault

---

code/modules/fallout/turf/ground.dm

sno fixins

---

code/modules/fallout/turf/ground.dm
modular_coyote/code/modules/turf_changes/PlantGrass.dm

reduces initialization time and gives us finer control over the number of specific plant groups

reduces plant count for memory saving

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm

Don't leave a hole in the damn floor

---

code/modules/mob/living/carbon/life.dm

Hey fun fact, their healing doesnt scale with rads at all! Instead, they just heal 2 of everything every tick when they have more than 0 rads.
Also fixes puddles not irradiating ghouls.

Ghouls absorb rads again

---

code/game/turfs/openspace/openspace.dm

You are no longer super duper careful around stairs, if you cant run. or are clumsy

Lets people walk down stairs

---

modular_coyote/code/modules/turf_changes/PlantGrass.dm

Reduces Init time by 250%

---

code/modules/mapping/space_management/space_transition.dm
modular_coyote/code/modules/turf_changes/PlantGrass.dm

Revert some stuff

---

code/game/objects/items/toys.dm
code/modules/mob/living/carbon/emote.dm

adds *snow and *snowball.
this code is just rough enough for people to hopefully enjoy while inspiring a better coder to make it more streamlined.
ready for morgle
:cl:
/:cl:

snow stuffs

---

modular_citadel/code/modules/client/loadout/__donator.dm

We will see about carters, ckey checks and all
:cl:
/:cl:

Fourty2's loadout and maybe fixing Carters

---

code/__HELPERS/text.dm
code/game/atoms.dm
code/game/say.dm
code/modules/client/client_procs.dm
code/modules/client/preferences.dm
code/modules/client/verbs/checkbgcolor
code/modules/client/verbs/checkbgcolor.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/say.dm
code/modules/mob/mob.dm
fortune13.dme

BG color checking is done manually through an OOC verb
:cl:
/:cl:

enforces contrast in chat colors

---

modular_citadel/code/modules/client/loadout/__donator.dm

Gitt loadout

---

code/datums/traits/good.dm
code/game/turfs/f13concrete.dm
code/modules/antagonists/blob/blob/blobstrains/cryogenic_poison.dm
code/modules/antagonists/blob/blob/blobstrains/regenerative_materia.dm
code/modules/fallout/reagents/alcohol.dm
code/modules/fallout/reagents/drinks.dm
code/modules/fallout/reagents/medicines.dm
code/modules/fallout/reagents/other_reagents.dm
code/modules/fallout/reagents/teas.dm
code/modules/reagents/chemistry/holder.dm
code/modules/reagents/chemistry/reagents.dm
code/modules/reagents/chemistry/reagents/drink_reagents.dm
code/modules/reagents/chemistry/reagents/food_reagents.dm
code/modules/reagents/chemistry/reagents/medicine_reagents.dm
modular_citadel/code/modules/reagents/chemistry/reagents/healing.dm

Made nukalover based healing into its own proc.
Added it to a lot of things that didnt have it before.
Rebalanced the numbers to be a bit more viable.

Expands nuka lover a bit

---

code/modules/fallout/reagents/alcohol.dm
code/modules/fallout/reagents/drinks.dm
code/modules/food_and_drinks/recipes/drinks/drinks_fallout.dm

Missed some soda stuff

---

code/datums/components/footstep.dm
code/modules/clothing/shoes/f13.dm
code/modules/mob/dead/new_player/new_player.dm
modular_sand/code/modules/pixel_shift/pixel_shift.dm

Tough feet fix

---

modular_coyote/icons/mob/tgmc/CREDIT.txt

credits tgmc as the icon source explicitly

---

code/modules/projectiles/guns/ballistic/bow.dm

No, I won't be nerfing them.  Bows get to just rock shit now. Don't like my balance?  Didn't ask homie.
:cl:
/:cl:

Gives bows their link to the quiver back.

---

code/game/say.dm
code/modules/asset_cache/asset_list.dm

also makes `/atom/movable/attach_spans()` return its input if there's no spans to attach, instead of returning a span with an empty class.
:cl:
/:cl:

chatcolor bugfix for lang icons

---

modular_citadel/code/modules/client/loadout/__donator.dm

I forgor to set the ckey when done testing :c

Fixes Kuba's Custom Loadout

---

code/modules/projectiles/guns/ballistic/pistol.dm
code/modules/projectiles/guns/energy/laser.dm

Trigger Guards on pistol template and tg laser templates

---

code/modules/cargo/export_scanner.dm

print currency conversions in export scan

---

code/datums/traits/good.dm
code/datums/traits/negative.dm
code/game/turfs/openspace/openspace.dm
code/modules/client/preferences.dm

- Can Not Run actually makes you not run when you spawn
- quick and dirty check during openspace fall prevention to ignore tackling players
- Fixes incorrect descriptions for Pixel Offset character preferences
- Makes Dumb quirk exclusive with packages that include other quirks that Dumb is exclusive with
- Flimsy and Very Flimsy are exclusive with the Bruiser package
:cl: …

several small fixes

---

code/modules/admin/verbs/dice.dm

Just changes it from 'Gods rolled' to 'The Spirits rolled', feels relevant.

Tweaks Dice Roll Command

---

_maps/map_files/coyote_bayou/Dungeons.dmm
modular_coyote/code/modules/doors.dm

Make small changes to player vault

---

_maps/map_files/coyote_bayou/Dungeons.dmm

I forgot cards. ;~;
:cl:
/:cl:

Add a deck of cards

---

code/datums/traits/negative.dm

fix very smart typo i made in quirk code

---

code/game/objects/effects/spawners/masterlootdrop.dm
code/modules/cargo/exports/misc_export.dm
code/modules/clothing/suits/arfsuits.dm
code/modules/projectiles/ammunition/energy/plasma.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/energy/plasmaf13.dm
code/modules/projectiles/projectile/beams.dm

Caster's were doing brute damage, as well as multiple other plasma guns, so I made them do burn instead.
Also makes casters use ECPs and changes their projectiles and such. 
Eve caster, aldric's loadout caster, does as much damage as before but cell drain is reduced and burst fire was bumped down to 3 with a single shot alt fire
Plasma Caster does 60dmg per shot, same fire modes as the eve caster, but fires slower than before 
Aldric also asked me to comment out his fluff jacket too, so I did

Adjusts, Fixes Casters, And Comments Out Aldric's Fluff Jacket

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
code/game/objects/effects/landmarks.dm
code/modules/jobs/job_types/tribals.dm
code/modules/jobs/jobs.dm

Submitted for review, do not merge until approved by Fenny and Thingpony
Adds a dual citizen, which is half villager, half Nash citizen.
:cl:
/:cl:

Tribal dual citizen

---

code/game/say.dm

custom say verbs broke
:cl:
/:cl:

fix unexpected attach_spans output

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

3 of 4 were already gone, lmao
:cl:
/:cl:

Removes the last of Garland Cities timelocks

---

code/game/say.dm

fix radio emotes

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm

Connects the outside private rooms to the 2nd floor with a hallway, adds a new private stripper pole, a new staff area, and a manager's office.
:cl:
add: 2nd floor in heaven's night is now more than 1 private room and a bathroom!
/:cl:

Heaven's Night 2nd floor additions

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Texarkana_underground.dmm

- Adds seating to the tribal tower and some light
- Area's the grassy bit above the tribal kitchen and adds a rug for laying upon
- Puts a bartending spawner in the bar so no more spawning outside of Nash
- Fixes up the xeno cave some as per their request
:cl:
/:cl:

Smol map touchups

---

_maps/map_files/coyote_bayou/Dungeons.dmm

A couple small bunker tweaks

---

_maps/map_files/coyote_bayou/Dungeons.dmm

Final fixes because Fen's fast on the trigger

---

code/game/objects/hand_items.dm

Yarp.
What it says on the tin.

Fixes Swing Combat Function With *armblade

---

code/modules/vending/megaseed.dm

Basically this PR adds in plums to the seed vendor so Seer and friends can make plum cake, when Superlaggs pr gets in will add the rest of wine plum juice in the game.
:cl:
add: plum to seed vendor
/:cl:

Plant Addition: Plums to Seed vender

---

code/__DEFINES/traits.dm
code/datums/traits/negative.dm
code/datums/traits/neutral.dm
strings/phobia.json

Adds a new alien identifier quirk, and an alien phobia quirk to go along with it.
Also fixes skelephobia's value, because I missed that one earlier somehow.

Bogos Binted

---

modular_citadel/code/modules/client/loadout/__donator.dm

Gib items to alt plz

---

code/modules/mob/living/emote.dm

`*rollfor` alias for `*special`
`initiative` alias for agility check
:cl:
/:cl:

funny additions to *special

---

modular_coyote/code/modules/examine_images.dm

Allow for SAFE jpg and png image embeds without breaking current pfp images
:cl:
/:cl:

Do what Fenny asked without breaking anyone

---

_maps/map_files/Pahrump-Old/Pahrump-Sunset-Lower.dmm
_maps/map_files/coyote_bayou/Ashdown-Upper.dmm
_maps/map_files/coyote_bayou/Garland-City.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

- setting up for moving the trader job eventually
- tweaks to garland city
- small tweaks to nash and nash upper/lower z
:cl:
/:cl:

A few map changes

---

code/modules/projectiles/guns/energy/laser.dm

Title
:cl:
- Changes the description of the retro laser gun so it's less painful to read and accurately tells the user what it does without needing to use the weapon status menu
:cl:

Fixes the desc of the retro laser gun (Good to go if it passes checks)

---

code/modules/fallout/obj/food_and_drinks/food.dm

Someone thought radscoropion was spelled like that and now I fixed it.
:cl:
tweak: words
/:cl:

Bug Fix: Radscoropion to Radscorpion 

---

code/modules/WVM/wvm.dm

Title
:cl:
- Adds the 1000 point card to the Mining/Salvage WVM machine. Priced it in such a way you can't infinitely profit (hopefully) and so the mining rewards stuff can be P2W'd for the lazy
:cl:

Adds mining points you can buy for money (good to go if it passes checks)

---

modular_coyote/code/modules/doors.dm

Add more access to doors

---

_maps/map_files/coyote_bayou/Dungeons.dmm
fortune13.dme
modular_coyote/code/game/machinery/cloning.dm

Cloning stuffs

---

code/game/objects/items/loadout_beacons.dm

hotfix for the laser carbine/pistol case and spamlaser loadout kits (good to go if it passes checks)

---

code/modules/projectiles/guns/ballistic/automatic.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Ballin.
(changes darknova's loadout kit to add the requested m5a1.)
(Deletes most of prismaticnova's first loadout kit item list, and add a rancher kit. Motorcycle memes)

Two loadout changes for Ckey Darknova92, and Ckey Prismaticnova

---

code/game/objects/effects/spawners/masterlootdrop.dm
code/modules/projectiles/guns/energy/laser.dm

Title sums it up. HUGE overhaul of the Energy Weapon loot lists adding a bunch of comments that explains things as well as adjusting various loot chances so common weapons are common, rare weapons are... Rarer-ish? Nothing huge, but hopefully we'll stop seeing AK470s every three feet and certain weapons will actually show up now. As a note, I think the common/uncommon energy weapon spawns might need a few more added to the map but I'm not actually that sure.
Also fixes a pair of problems with the laser gatling I'd noticed.
:cl:
- Overhauls e-wep loot lists by adjusting values and adding comments that explain what each weapon does (and, implicitly, how that impacts loot rarity) because e-weps are weird and can't quite be judged purely on DPS
- Adjusts various loot values for weapons so …

Overhauls the Energy Weapon loot list + laser gatling bugfix (Good to go if it passes checks)

---

code/datums/traits/good.dm

plus small text changes
:cl:
/:cl:

Sleight of Hand storage automatically implants

---

code/_onclick/hud/screen_objects/character_actions.dm

Fixing my small mistakes, mainly just flavor text.
(It's an excuse to get back into coding).
:cl:
fix: fixed my old mistakes, I ain't dead yet
/:cl:

 fixing my mistakes IV [ready to merge]

---

_maps/map_files/coyote_bayou/Garland-City.dmm

https://gyazo.com/286ddfba7b90c200714f30f53a15ce90
:cl:
/:cl:

Small garland city fix

---

code/modules/arousal/organs/testicles.dm

Implement fix for mid round grundle adjustments

---

code/modules/admin/verbs/adminhelp.dm
code/modules/client/client_defines.dm

Try to limit ahelp spam to once every 3 minutes

---

code/datums/traits/good.dm
code/game/objects/items/implants/implant_storage.dm

shirt that says i ❤️  garbage collection
:cl:
/:cl:

extra qdels for storage implants

---

code/modules/projectiles/guns/ballistic/automatic.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Adds new player loadout, adjusts a custom one
:cl:
/:cl:

(MERGE WHEN CAN) Loadouts!

---

modular_citadel/code/modules/client/loadout/__donator.dm

Errant-XIV, Sindy, A Strike from the Shadows loadout kits

---

code/game/machinery/recycler.dm

Recyclers don't butcher creatures anymore, unless they get emagged.
:cl:
tweak: added OSHA approved surveillance to coyote bayou.
/:cl:

OSHA approved recyclers [ready to merge]

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
code/modules/smithing/finished_items.dm

Makes the Smithed lance Better
Fixes the lack of a hole
:cl:
tweak: tweaked the lance
tweak: fixed a hole
/:cl:

Fixes the Smithed Lance [READY]

---

modular_citadel/code/modules/client/loadout/__donator.dm

errant-xiv loadout armor is powered

---

code/game/objects/items/stacks/stack.dm

machine frames will let you wire them when you have 5 cable exactly
:cl:
/:cl:

tool check passes at equal amount

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

removal of christmas

---

_maps/map_files/coyote_bayou/Ashdown.dmm

What this PR does is replace a simple invisble mutant with a bright smiling mutant that should of been there in the beginning hes protecting his brahmins in redlick.
:cl:
add: Brah-Min
/:cl:

Map Tweak: Return of Brah-min

---

code/modules/food_and_drinks/food/snacks_pie.dm

What this PR does is fixes the gosh darn french silk pie to be sliceable instead of lying to you
:cl:
adjust: cutting code for french silk
/:cl:

Food Fix: French Silk Pie

---

modular_citadel/code/modules/client/loadout/__donator.dm

Adjusts the loadout of one person, more like a downgrade but it's a personal requested adjustment!
:cl:
/:cl:

(MERGE WHEN POSSIBLE) Loadout adjustments

---

code/modules/research/stock_parts.dm

Make parts more obvious

---

code/modules/mob/dead/new_player/preferences_setup.dm

I did an oopsie while fixing it the first time, now it's completely fixed.
:cl:
fix: fixing my mistakes.
/:cl:

Fixing genitals showing up in character preview [ready to merge]

---

_maps/map_files/coyote_bayou/Texarkana_underground.dmm

removal of seed puddles from sewers

---

code/game/objects/items/loadout_beacons.dm

The Kanobo has proven these should be fine.
:cl:
/:cl:

Returning the crude blade and mauler to spawn loadouts

---

tgui/packages/tgui/interfaces/ListInput.js

Adds listinput to the interface tgui menu

---

_maps/map_files/coyote_bayou/Garland-City.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Texarkana_underground.dmm

Loot amounts increased on Texarkana underground, and Garland City.
:cl:
/:cl:

The coming of the cum beast

---

code/_globalvars/lists/maintenance_loot.dm
code/game/objects/effects/spawners/masterlootdrop.dm
code/modules/projectiles/guns/mods/mods.dm
modular_coyote/eris/code/mods/mod_types.dm

Two types of bluespace paint, each one with its own dream to be GREAT...or the worst thing you could possibly find. Why do people throw this crap away?
Also have some gold paint! Better than red, slightly. Still cant remove it though teehee.

Adds Bluespace and Gold paint!

---

code/_onclick/hud/human.dm
code/game/objects/structures/mirror.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/mob/living/carbon/human/species.dm
config/maps.txt
modular_coyote/code/modules/hair_gradient/hair_gradient.dm

Adds the ability to choose a second hair style to compliment the first.
AKA let out the sparkledog within you!
This is an example:
:cl:
add: Adds Hair 2
/:cl:

Secondary hair layer [ready to merge]

---

code/game/objects/items/artifacts.dm

removes the downsides to stalker artifacts

Stalkerfacts no longer bad

---

code/game/objects/items/manuals.dm

That was this recipe isn't hidden but only found in the code
:cl:
add: Cosmic strawberry isnt hidden in code anymore.
/:cl:

Book Addition: Cosmic booklet gets strawberry

---

code/modules/projectiles/guns/ballistic/automatic.dm

Will go in hand with Tox giving them sprites in another pr, because we're lazy assholes.
:cl:
/:cl:

Allows most 308s to use 10 round mags

---

code/modules/WVM/wmv_buyer.dm

Title
:cl:
- Adds weapon mods to the scrapper buy list
- Adds text in the scrapper to say it buys weapon mods
:cl:

Adds weapon mods to the scrapper buy list (good to go if it passes checks)

---

code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/projectiles/guns/ballistic/pistol.dm
modular_citadel/code/modules/client/loadout/__donator.dm

(MERGE WHEN READY) Loadouts

---

code/controllers/subsystem/artifacts.dm
code/datums/components/artifacts.dm

Fixes staminartifacts.
Also fixes the reddening on healtifacts

Whoops, take a shot of fabuloso

---

code/datums/components/storage/concrete/implant.dm
code/game/objects/items/melee/coyotemelee.dm

-storage implant can't hold other storage items or the validball
-old quarterstaff attack proc includes a cooldown check
:cl:
/:cl:

sleight of hand + old quarterstaff fixes

---

code/game/objects/effects/spawners/masterlootdrop.dm

This is until we can find a code way to stop players (you know who you are) from metarushing these spawners for gear via code.
:cl:
/:cl:

Dilutes the rare weapon and armor spawns a tad

---

modular_citadel/code/modules/client/loadout/__donator.dm

sprawaobwodusergala commits a lend lease

---

modular_citadel/code/modules/client/loadout/__donator.dm

Reverts ARF-SS13/coyote-bayou#4171

Revert for Academic Purposes "sprawaobwodusergala commits a lend lease" 

---

code/game/objects/items/loadout_beacons.dm
code/modules/projectiles/ammunition/special/magic.dm
code/modules/projectiles/guns/magic/staff.dm
code/modules/projectiles/projectile/magic.dm

not on a loot table yet, because i'm lazy as SHIT, but tested.  Feels pretty okay.
:cl:
/:cl:

we do a lil magic

---

modular_coyote/code/creature_species.dm
modular_coyote/code/pmon_mob.dm

Removes two pokemon that were just a little bit too much for the server. Thank you to the player who pointed it out to us.
:cl:
/:cl:

Updates the pokemon list

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

removes the libaries xmas stuff

---

code/modules/projectiles/projectile/bullets/rifle.dm

See title.
:cl: Jaeger
balance: un-nerfs .50MG
/:cl:

un-nerfs .50MG

---

code/modules/mob/mob.dm

Because I'm braindead.
:cl:
/:cl:

Grab their hips flirt

---

_maps/map_files/coyote_bayou/Ashdown.dmm

This adds the secret recipe to ashdown and the defib.
:cl:
add: secret recipe and defib.
/:cl:

Map Addition: Secret Recipe + Defib Ashdown

---

modular_citadel/code/modules/client/loadout/uniform.dm

big dumb I was in a rush to go out before everything closed on sunday and forgot to fix the loadout part.
this makes the loadout bits lead to the correct... bits?

tribal clothes loadout fix

---

_maps/map_files/coyote_bayou/Dungeons.dmm
_maps/map_files/coyote_bayou/Texarkana_underground.dmm

Dungeon Time x2

---

_maps/map_files/coyote_bayou/Dungeons.dmm
_maps/map_files/coyote_bayou/Texarkana_underground.dmm

I had ladders

---

_maps/map_files/coyote_bayou/Dungeons.dmm

Seems strong DMM decided not to save the 4th ladder. Fun.

Last Ladder

---

_maps/map_files/coyote_bayou/Dungeons.dmm

Ladders (i'm smart edition)

---

_maps/map_files/coyote_bayou/Dungeons.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
modular_coyote/code/modules/doors.dm

Three people have access: Tox, orian, and joseph. All per tox's request!

Special beach bunker for Tox

---

code/modules/mob/living/living.dm

god fucking damn it

---

_maps/map_files/coyote_bayou/Dungeons.dmm

Fixes up Tox's beachhouse

---

modular_citadel/code/modules/client/loadout/__donator.dm

Lord Plapapus Custom Loadout

---

modular_citadel/code/modules/client/loadout/__donator.dm

WEREDOGGO LOADOUT

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm

salt PR removes the army depot mine

---

code/modules/spells/spell_types/shapeshift.dm

wildshape waddle

---

modular_citadel/code/modules/client/loadout/gloves.dm

Adds these gloves into the loadout menu, Three in total but one has different onmob assests then the other
:cl:
add: four new gloves to loadout menu
/:cl:

Gloves Addition: Patrol Ranger & Fingerless Glovvies in loadout

---

_maps/map_files/coyote_bayou/Ashdown-Upper.dmm

Ashdown Market Stalls

---

modular_citadel/code/modules/client/loadout/__donator.dm

also fixes lord plap's loadout

fixes my loadout

---

modular_citadel/code/modules/client/loadout/gloves.dm

I did a typo and I forgot to push it into the PR, and so I had to make another PR cause brain go brrrrrrrrrr. like VHS tv.
:cl:
fix:typo
/:cl:

Glove Fix: glvoes is not gloves

---

code/modules/client/preferences.dm

As the title says.
:cl:
tweak: renaming hair
/:cl:

Renaming hair sections in character preview [ready to merge]

---

code/modules/fallout/obj/structures/mob_spawners.dm

Hole Destruction
:cl:
add: Adds Hole Destruction
/:cl:

Hole Destruction [ready to merge]

---

code/controllers/subsystem/chat.dm
code/controllers/subsystem/dummies.dm
code/modules/arousal/genitals.dm

Should no longer proc in deadchat or whatever.

Restricts emoticons to actually functional message modes

---

code/controllers/subsystem/dummies.dm
code/modules/arousal/genitals.dm

You should no longer have random peoples' genitals show up on your mob in character prefs.

Removes unsolicited dick pics

---

code/modules/clothing/head/f13head.dm
code/modules/clothing/head/helmet.dm
code/modules/clothing/suits/arfsuits.dm
code/modules/projectiles/gun.dm

The operation may have been a success. Reduces lag on the client on the private test server.

Bunnymization

---

code/modules/clothing/head/f13head.dm
code/modules/clothing/head/helmet.dm
code/modules/clothing/suits/arfsuits.dm
code/modules/projectiles/gun.dm

{TM ONLY} Disables the PA trait requirement.

---

_maps/map_files/coyote_bayou/Dungeons.dmm

A lot of valid ball spawners for artifacts, some rare artifact spawners, that sort of stuff.
Totally not salty I got hardly anything for doing the hard dungeon one round.
https://media1.tenor.com/m/qn4AhUrbgDAAAAAC/salt-dance.gif

Makes BoS dungeon loot better

---

code/modules/mob/mob.dm

I don't know how I missed this, what the fuck
:cl:
/:cl:

Flirt - Tail pulling

---

_maps/map_files/coyote_bayou/Dungeons.dmm

While the Validball spawners made the loot slightly better, it wasn't consistent with decent loot. Also noticed that a lot of loot spawners/lockers were giving extremely low loot considering the difficulty.
All bosses have some form of medium to king/medium to high bounty ticket to make it worthwhile.
Also added a ton of artifact spawners of uncommon to Rare in the archives. The place is meant to be run when you have good loot anywho, so this'll make it far more worth your time.
Difficulty is untouched cause it's still hard for someone with 2 stoneflowers and combat armor to do without taking their time :)

Further improves the BoS loot

---

code/datums/elements/mob_holder.dm
code/datums/traits/neutral.dm

Smol -> Scoopable

---

code/modules/client/client_defines.dm
code/modules/fallout/turf/walls.dm
code/modules/mob/dead/new_player/new_player.dm

Few lines of code that act as an annoucement system for players that are joining in, I tried to make this little logic as smart as possible, featuring:
- It recognizes the custom job the player has selected and defaults to the chosen role name in case they don't have any custom id;
- In case someone joins in, but immediately matrixes out (before 5 minutes have elapsed), nothing will appear in chat, so it won't spam it;
- Waits 5 minutes before actually announcing that said new player has joined in.
:cl:
add: Adds Rumors Welcomer
/:cl:

Rumors Welcomer [ready to merge]

---

code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
code/modules/mob/living/simple_animal/hostile/f13/tunnelers.dm

Enclave soldier now uses the gutsy plasma bolt instead of the carbine which COMPLETELY goes through armor. No more of that rediculous gunk. Should be far easier but they're still a difficult mix of boss raider and gutsy.
Gives the regular tunneler a weaker version of the nightstalker venom.
Also adds sounds. They're screams. They scream. Enjoy the nightmare fuel!
https://youtu.be/pglbDy_aEfI

Fixes two specific mobs (Enclave Soldier and Tunneler)

---

_maps/map_files/coyote_bayou/Ashdown-Upper.dmm

Adds deep water spots to Ashdowns upper ponds

---

code/modules/mob/dead/new_player/new_player.dm

People in the lobby shouldn't see the message anymore
:cl:
fix: fixes Rumors Welcomer
/:cl:

Rumors Welcomer - iter II

---

code/modules/clothing/suits/trait_no_med_hvy_armor.dm
code/modules/mob/dead/new_player/new_player.dm

…let's experiment it like this
Armor aversion change, it should have the same effect, but it's less dumb
:cl:
tweak: tweaks armor aversion
/:cl:

I'll be real, I don't think this simple thing needs a quality check [ready to merge]

---

_maps/map_files/coyote_bayou/Ashdown-Upper.dmm

Ashdown Conveyor

---

code/game/objects/items.dm

Click dragging an held object onto someone else, will trigger the "give" proc just like the give verb
https://github.com/ARF-SS13/coyote-bayou/assets/64517916/f8b5f937-1329-4ae1-9e00-9be846fe9d2d
:cl:
add: Adds you want? I give
/:cl:

you want? I give [ready to merge]

---

code/__DEFINES/random_mob_spawner.dm
code/modules/events/carp_migration.dm
code/modules/fallout/obj/structures/mob_spawners.dm
code/modules/mob/living/simple_animal/hostile/giant_spider.dm

The three sojourn giant spiders are in greater.
Regular spiders already in code in the lesser.

Adds Lesser spider and Greater spiders to Mob SPAWNER list

---

code/controllers/subsystem/monster_wave.dm
fortune13.dme

Removes monster spawner sub system because its ass

---

code/modules/fallout/turf/walls.dm

AIAIAIAIA [ready to merge]

---

code/modules/jobs/job_types/wasteland.dm
code/modules/jobs/jobs.dm

as title says
- [ i did ] You tested this on a local server.
- [ HAHAHAHA ] This code did not runtime during testing.
- [ YOU FUCKING WISH ] You documented all of your changes.
:cl:
/:cl:

YOU WANT? I GIVE, I GIVE BECAUSE PEOPLE WANTED [ready to merge]

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

ammo bench & shit for rangers

---

code/modules/jobs/job_exp.dm
code/modules/jobs/jobs.dm

actually fixing it this time, texas ranger [ready to merge]

---

code/controllers/subsystem/job.dm
code/modules/jobs/job_exp.dm
code/modules/jobs/jobs.dm

Maybe fixes the ranger job

---

code/modules/jobs/job_types/wasteland.dm

title
:cl:
tweak: tweaked TR
/:cl:

Removing time requirement for TR [ready to merge]

---

code/modules/clothing/masks/miscellaneous.dm

Desertwrap fix [ready to merge]

---

code/modules/clothing/shoes/miscellaneous.dm
modular_citadel/code/modules/client/loadout/shoes.dm

Fixes the cowboy boots alt to have a knife slot

---

code/modules/mob/mob.dm

I'M LEON AND I FUCKING LOVE BREAKING PIXELSHIFTING ARRRRRR
- [GRRRRRRRRRRRRR] You tested this on a local server.
- [GRRRRRRRRRRRRR] This code did not runtime during testing.
- [GRRRRRRRRRRRRR] You documented all of your changes.
:cl:
/:cl:

ARRRRRGH FUCKING PIXELSHIFTING [READY TO MERGE]

---

code/modules/mob/inventory.dm

Its a bite sound, fuck you
:cl:
/:cl:

Adds sound to 'can not equip that' function

---

code/modules/hydroponics/grown/prickly.dm

… you can just eat them instead of mentats
Tribal fucking gaming ayo don't gimme yo shitty fucking candy homie I don't want nothing to do with that shit fuck off you god damn Nashie 2,439,478,243 dead nashites
:cl:
/:cl:

Adjusts prickly pears so that when you headbutt walls and want to die

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

where the fuck did that lightpost come from

---

code/__DEFINES/mobs.dm

Max age set to yes

---

code/__DEFINES/jobs.dm
code/modules/jobs/job_types/followers.dm
code/modules/jobs/job_types/oasis.dm
code/modules/jobs/job_types/tribals.dm
code/modules/jobs/job_types/wasteland.dm

- Purged Nash Clinic down to Scientist & Doctor: Moved to Nash tab
- Den & Garland need their own groups, with Den Waster and Garland Waster put in them as "Den Citizen" and "Garland Citizen"
- Purge Nash jobs: Sheriff, rename Deputy (renamed to Nash Law), Purge Detective
- Merge Villager & Hunter together. (Still needs a new name, cant remember what was decided on)
- Rename Shaman to Spiritual Leader
- Rename Druid to Harvest Leader

Various Job changes, tldr in Desc

---

code/modules/jobs/jobs.dm

Fixes the Job listings

---

code/modules/client/preferences_savefile.dm
modular_splurt/code/datums/modules/client/verbs/character_directory.dm
tgui/packages/tgui/interfaces/CharacterDirectory.js

Adds gender and preference to the character directory
