ARF-SS13/coyote-bayou

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Removed Sunsets dungeons, they can still be found in the older map files folder for future reference.  For now they were just taking up space, and don't fit with what we want moving forward.
Also removed their dungeon elevators from the main map.
Dungeon Z was overhauled entirely, setting it up for moving forward with an area for the Texarkana Mall.  The Enclave Bunker/BOS Bunkers are placed down with future plans to make them easy to setup for events.
Also also added a few things to the vault, and poked about in it to straighten some stuff out.  Mostly added just a few things to the armory.
> Dungeon removal, and some small map changes

- code/game/machinery/msgterminal.dm
Someone please tell me why two seconds of birds wings flapping needs to be four Mb.
> Sus af sized sound file removal

- code/game/objects/items/grenades/grenade.dm
Ping instead of beep beep beep for all grenades.  Makes the pineapples actually feel like pineapples.
> Grenade Ping

- code/game/objects/items/broom.dm
Makes the max things a broom can sweep be a variable.
Brooms no longer check if there's something anchored on the tile, just sweep around it, nerd.
Something I always wanted to do, its my lifelong dream to make a broom work slightly better.
:cl:
tweak: Broom can now push 40 things at once, which is more than 20!
/:cl:
> broom changes

- code/game/objects/items/stacks/crafting.dm
- code/game/objects/items/stacks/rods.dm
- code/game/objects/items/stacks/sheets/sheet_types.dm
- code/game/objects/items/stacks/sheets/sheets.dm
- code/game/objects/items/stacks/stack.dm
- code/game/objects/items/storage/bags.dm
- code/game/objects/items/storage/f13storage.dm
Reduces most stack sizes by 99% (from 5000 to 50 lol)
Fixes a wierd multiplier in the topic.
Casing bags hold 600 instead of 6000.
Salvage storage bags (the ones that hold advanced tools and not much else) now can carry 30 things, and not fuckin INFINITY
Not gonna stick 5000 sheets of steel in my pocket.
:cl:
tweak: Most stacks have their max amount reduced by 99% (5000 to 50)
tweak: Salvage *storage* bags now can hold 30 things max, down from INFINITY.
tweak: Casing bags hold 600 bullets instead of 6000. Just throw out the empties, gosh.
/:cl:
> Nerfs stack sizes

- code/__DEFINES/layers.dm
- code/_onclick/hud/ghost.dm
- code/_onclick/hud/plane_master.dm
- code/_onclick/observer.dm
- code/game/objects/items.dm
- code/modules/client/preferences.dm
- code/modules/fallout/reagents/alcohol.dm
- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/mob_movement.dm
- code/modules/mob/status_procs.dm
- code/modules/reagents/chemistry/reagents/toxin_reagents.dm
- modular_citadel/code/modules/client/client_procs.dm
oops! complete oversight with that movement code. Fixed it <3
Anyway, added in the feature to stop non-admin ghosts from seeing obj/items. This prevents unintentional metagaming and also removes that worry that we may have if some cheeky buggers observe first to find all that loot while no admins are active/aware of it.
Because of this, I had to seperate all the obj/items on your screen to be rendered seperately. You know what this means? I can fuck with all the items you can click on. Do you know the power you gave me? How I can make every item you come across SPEEN? AND HOW YOU WON'T EVER BE ABLE TO CLICK IT BECAUSE OF THE PAINFUL SPIN IT HAS ROTATING ACROSS YOUR SCREEN???
perish.
Here's some pics.
https://user-images.githubusercontent.com/68038883/178081365-628e60b4-fbb0-4be1-bdd4-d6531 …
> Observer blindening + Fixes Observers not being able to move around when non-admin

- code/game/objects/items/defib.dm
Corpses will never be too old to revive. They can still be too mangled to revive, but it'll never be *time* that keeps someone from being revived.
Also rewords the defib messages to be more helpful.
Zap is a zap.
:cl:
balance: Corpses are never too old to revive.
/:cl:
> Removes rot timer, rewords defib messages

- code/game/objects/structures/fence.dm
- code/modules/mob/living/living_defines.dm
- code/modules/mob/living/living_sprint.dm
Dingaling, there you go.
Stops the exploit from being able to juice out all the stamina bitties from spamming spacebar.Because of this, had to add 1 extra tile to the buffer to retain vanilla sprint distance with the buffer (42 tiles)
Fences can now be damaged again! They hadn't called ..() on the proc to allow you to hit it with anything other than wirecutters or metal rods.
No checkbox this time cause I playtested before making the PR and it's good to go 👍
> Fences can be attacked! New product lineup: ExploitBGone - Sprint!

- code/modules/unit_tests/_unit_tests.dm
makes the error worse, so...guess its better than a pure linter fail
> Revert "disables failing linter for now"

- code/__DEFINES/combat.dm
- code/__DEFINES/melee.dm
- code/game/objects/items/kitchen.dm
- code/modules/smithing/anvil.dm
- code/modules/smithing/finished_items.dm
- code/modules/smithing/smithed_items.dm
Some crude changes to smithing.
First, just about every smithed weapon has been nerfed in some way. Swords all do roughly the same thing, (15 *1.1) + 8 damage, + 50% when wielded if available. They also do a lot of wounding damage, if you want to PVP with it.
Maces do a lot of fracture damage.
Axes do a shitload of damage to most doors and barricades.
Removed blockchance on all smithed weapons.
All recipes are available on all anvils.
Reflavored the weapons that are craftable.
AS WITH ALL THINGS these are subject to change!
> First pass of smithing changed

- _maps/map_files/Pahrump-Old/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Old/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
- _maps/map_files/Temp Map Storage/Pahrump-Sunset - Outdated.dmm
- _maps/map_files/Temp Map Storage/Pahrump-Sunset-Lower - Outdated.dmm
- code/__DEFINES/inventory.dm
- code/datums/components/crafting/recipes/recipes_clothing.dm
- code/game/objects/items/storage/belt.dm
- code/game/objects/items/storage/survivalkit.dm
- code/modules/fallout/misc/gang_items.dm
- code/modules/jobs/job_types/bos.dm
- code/modules/jobs/job_types/enclave.dm
- code/modules/jobs/job_types/followers.dm
- code/modules/jobs/job_types/khan.dm
- code/modules/jobs/job_types/legion.dm
- code/modules/jobs/job_types/ncr.dm
- code/modules/jobs/job_types/oasis.dm
- code/modules/jobs/job_types/wasteland.dm
- code/modules/mob/living/simple_animal/corpse.dm
So first thing's first, you cant store a backpack on your suit anymore. I know, it was great, and it'll be back when i can get it to have some slowdown in that slot, but it was just too much loot hoarding for too little drawback.
Most specialized belts now hold a lot more. For instance, toolbelts can hold 14 items, and can also hold stuff that would fit in a mining belt, along with components, boards, mats, welding goggles, basically anything even vaguely tool-like. Also a chainsaw.
Also mining belts (and sinew belts) are essentially reskinned toolbelts. 
medibelts also hold 14 items, and can also hold a folded up IV stand, a needler and ammo, and a razor.
Holsters can hold a total of 7 guns, including rifles. However, bigger guns take up more room, meaning you can only hold *one* large …
> Belt and suit storage changes

- code/_globalvars/lists/maintenance_loot.dm
- code/modules/fallout/obj/stack/f13Cash.dm
- code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
- code/modules/mob/living/simple_animal/hostile/f13/raider.dm
- code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
Raiders drop some caps on death (bosses drop more)
Ghouls will SOMETIMES drop some caps when they die
Supermutants carrying hunting rifles now drop the hunting rifles after dying
The time travellers bringing NCR dollars and Legion coins from the future have been dealt with
:cl:
add: Raiders and ghouls are now carrying some caps on themselves
add: Supermutant-made rifles no longer disintegrate after their owner dies
fix: Legion and NCR money is no longer in the loot lists
/:cl:
> Raiders and Ghouls drop caps

- code/datums/components/crafting/recipes/recipes_tribal.dm
This fixes craft menu crashing due bandage eyepatch not having proper category (and subcategory) variables. It should now appear in tribal tab.
:cl: Anonymous
fix: Fixes eyepatch bandage crashing menu due not having proper category set.
/:cl:
> Fixes bandage eyepatch crashing craft menu

- code/modules/fallout/reagents/medicines.dm
It was originally intended for stimfluid to deplete this quickly, to work with how much stimpaks are designed to heal.
> Adjusted stimjuice depletion rate

- code/__DEFINES/inventory.dm
Most armor can hold spears and two-handed melee weapons.
> Spears and other two-handers fit in suit storages now

- code/datums/components/crafting/recipes/recipes_tailoring.dm
- code/modules/clothing/head/helmet.dm
- code/modules/clothing/suits/arfsuits.dm
Steel breastplates evolved into the wrong heavier breastplate. Now, they properly turn into reinforced steel breastplates.
Renamed the heavy steel breastplate to oasis breastplate, cus that's what it was, dunno why it was called what it was.
Army helmets evolve into a better army helmet.
:cl:
balance: Made heavy steel helmets better than steel helmets and not the other way around.
balance: Steel breastplates properly turn into reinforced steel breastplates.
fix:  Oasis breastplate has the right name, just in case you see one!
/:cl:
> Fixes some recipes and helmets

- code/modules/jobs/job_types/vault.dm
Removes the chem trait from Overseer and replaces it with a Chemistry Book so they can craft drugs and stims.
Jet's good for the vault, right?
> Overseer loadout update

- code/modules/mob/living/carbon/human/species_types/ipc.dm
- code/modules/mob/living/carbon/human/species_types/synthliz.dm
- code/modules/mob/living/carbon/update_icons.dm
- code/modules/surgery/bodyparts/_bodyparts.dm
Finally enables ~~Synthetic Anthromorphs,~~ (Not enabled on this server.) Synthetic Lizardfolk, and IPCs having actual, honest to god robotic limbs.
:cl:
fix: Makes Synthetic Species actually have robotic limbs and sprites.
/:cl:
> Ports #234 from Sunset Wasteland 'Enables Robotic Limbs for Synthetic Species'

- code/game/objects/items/devices/radio/radio.dm
Radios will now only pick up dialogue from you and the squares adjacent to you.
:cl:
tweak: Radios will only pick up sound from you and areas next to you.
/:cl:
> changes radius of sound radio will pick up

- code/__DEFINES/inventory.dm
- code/game/objects/items/storage/belt.dm
Holsters can now carry ammo, but are limited to normal-sized guns and smaller. Mainly so it doesnt intrude on bandoliers!
:cl:
balance: Holsters can hold ammo, but are limited to normal sized guns and below.
/:cl:
> Holster changes

- code/modules/fallout/turf/walls.dm
- tgui/.gitignore
Bit scuffed but it only turns green when you're transitioning, cba making a new sprite just in blue for it to transition, but hey! It  goes back to bloo.
Also added some stuff to gitignore.
:cl:
tweak: Icon for matrix tiles go back to their original icon after you leave the round with them.
/:cl:
> Fixed matrix tiles turning permanently green once they've been used

- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
Nothing Tiles in Fort Ghussy Removed
Nothing Tiles in Fort Ghussy Removed
:cl:
add: Replaced Floor Tiles in Fort Ghusy so they aren't portals the the dark abyss of forever.
/:cl:
> Fixed Nothing in Ghoul Fort

- code/modules/projectiles/guns/ballistic/revolver.dm
Instead of the Peacekeeper being full-auto, it is now semi-automatic, but able to shoot really quickly. Careful, it has a kick!
#371
:cl:
tweak: Peacekeeper is no longer automatic. Instead, it can be fired semi-automatically really quickly. 
/:cl:
> Tweaked Peacekeeper's firemode

- code/modules/fallout/obj/structures/mob_spawners.dm
- code/modules/mob/living/simple_animal/hostile/f13/insects.dm
- code/modules/mob/living/simple_animal/hostile/hostile.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
Radroach HP halved, damage lowered to 5-8 from 10 (like bloatflies)
Radroach nests spawn three roaches instead of just one
Radroaches can now move through other mobs, including other roaches
Radroaches and Bloatflies can move through tables
Mob movement is now s m o o t h
> Nerfs radroaches but makes them able to swarm, smooth mob movement, support for nests spawning more than one mob, long PR title

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Adds some solar panels to the roof of Texarkana General as well as adds a morgue to the hospital for Followers Use. Brings Texarkana General off of Fiat Power and actually makes the APC required to keep the building powered for long periods of time.
:cl:
add: Adds a smoke break area to the hospital.
add: Adds a solar panel to the rooftop of the hospital.
add: Adds a vertibird landing spot to the rooftop of the hospital.
add: Adds a morgue to the second floor of the hospital.
add: Adds a basement level to the hospital.
tweak: Changed the location of the janitor's closet on the second floor of the hospital.
tweak: Makes the bathroom on the second floor of the hospital actually usable.
/:cl:
> Texarkana General Generators

- code/modules/power/cable.dm
GDI I forgot to update the cable coils burn affect to let it heal past 25 the last time.
:cl:
tweak: Lets Synthetics use cable coils to heal burn damage past 25, like I should have done the first go-around.
/:cl:
> Actually fixes synths not being able to heal burn damage.

- _maps/map_files/Pahrump-Old/Pahrump-Sunset-Upper.dmm
Byond considers [square brackets] in quotes to be replacement bits for a variable in the square bracket
ie: "There are [number_of_apples] in this pile.", where number_of_apples is a variable.
Which is why MDB is failing, because map files can't be changed during compile-time.
> Escapes opening square brackets which were causing MDB to fail

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- code/modules/fallout/areas/area.dm
Fixes the basement having walls in places it shouldn't be having walls as well as renames the hospital area to Christus Saint Michaels Hospital to fall in line with landmarks and the location of the area. 
:cl:
tweak: changed the basement a bit because i left walls where i shouldn't have.
tweak: renames hospital area from Yuma General to Christus Saint Michaels to better fit with our lore.
/:cl:
> Hospital udate 2 electric boogaloo

- code/modules/mob/living/carbon/human/species_types/synthliz.dm
We'll come back to this later, Zero.  For now tho, lets not buff a race only you play, okay? :)
Removes Toxin lover from synthlizards, because we don't like it when people add things to just their own race.
:cl:
del: Removed Toxin Lover from Synthlizards, this wasn't quite the right trait to give them.
/:cl:
> Synth lizard unfix

- code/_compile_options.dm
Because Auxmos/Auxtools can fuck up if you're compiling on this version, I've added a warning if you compile on 1585 or after.
> Adds a warning if you try to compile on 514.1585 or later

- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
Bascially makes the free blueprint into a lower tier blueprint, and makes the tier 3 armor into
:cl:
tweak: free raider camp has mobs instead of free as it had a blueprint and lower tier. 
tweak: Free possible t45b is gone.
/:cl:
> Free T45b is gone & Replaced medium blueprint with mid-low blueprint

- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
Remove stimulants syringe for extra large syringe 
:cl:
tweak: stimulants go bye, for extra large syringe
/:cl:
> removes stimulant to xlarge syringe

- code/modules/clothing/head/f13factionhead.dm
- modular_citadel/code/modules/client/loadout/hands.dm
- modular_citadel/code/modules/client/loadout/head.dm
- modular_citadel/code/modules/client/loadout/shoes.dm
Great khan stuff repurposed, the khan helmets renamed and put into loadouts, boots are put into loadout wise. That way they aren't sitting in code. These will most likely end up into modkits down the road, but this gives more love in a way.
:cl:
tweak: Great Khan Helmets are renamed and removed of khans
add: great khan helmets are put into loadout and boots are too.
/:cl:
> khan stuff into loadouts

- code/datums/components/edible.dm
- code/modules/food_and_drinks/food/snacks.dm
Voracious folk can continue eating even after they're full. However, they're much faster to be forcefed, and still can be forcefed while full.
:cl:
tweak: Voracious lets you keep eating even while you're full, but makes it easier for people to forcefeed you things.
/:cl:
> Voracious tweaks

- code/game/objects/items/devices/flashlight.dm
Flashlights can go in your neck slot. Some can, at least.
Vertical flashlights, penlights, and glowsticks can go in your neck slot. The last two can go in your mouth and ears too!
:cl:
tweak: Vertical flashlights and glowsticks can go in your neck slot.
tweak: Penlights can go in your neck slot, or your mouth, or your ear.
/:cl:
> Flashlights can go on your neck

- code/datums/components/crafting/recipes/recipes_misc.dm
- code/game/objects/items/stacks/sheets/sheet_types.dm
- code/modules/fallout/obj/smelling_salts.dm
- code/modules/food_and_drinks/food/customizables.dm
- code/modules/mining/lavaland/ash_flora.dm
Smelling salts no longer fail to work depending on the time since death.
Crafting wooden floor tiles in sets of 20 no longer crafts a single wooden barricade at 5x cost.
Wooden bowls are now completely functional and the sprites work well.
Crafting paper no longer requires a hatchet as a tool. In exchange, ash is required.
:cl: Fel 
tweak: Paper no longer requires a hatchet to craft. Instead, it requires 20u of ash in addition to the water.
fix: Smelling salts now works more consistently.
fix: Bulk-crafting wooden floor tiles now actually works.
fix: Wooden bowl sprites update properly, and give the proper custom soup and salad.
/:cl:
fixes: #428
> Various Tribal Fixes, Paper No Longer Requires Hatchet

- modular_coyote/code/modules/regeneration/sleepingpart/regenerate_sleeping.dm
As the title says. Slightly lowers the base maxHealAmount, but you can roughly double it by sleeping while buckled to a bed.
Without a bed, you heal on average about 0.2 damage per second. With a bed, this becomes 0.5 or so, give or take.
requires #436 for the global list outdoor_areas.
:cl:Fel
add: Sleeping in a bed heals you faster! Just make sure you have a roof over your head.
/:cl:
> Sleeping while buckled to a bed heals more

- modular_sunset/code/modules/client/loadout/head.dm
PR removes cost value for RGBY colored peaked caps, thus making them have the same cost as cheap helmets (since in loadout they're a downward path of helmets). Previously, it was `cost = 3` as it was copying idea of USA/PLA officer caps' "+1 point for style".
Please note that RGBY/GWTB peaked caps have same armor value as cheap helmets.
:cl: Anonymous
tweak: Makes GWTB/RGBY cost one point less in the char-setup loadout selection.
/:cl:
> Decreases loadout cost for peaked GWTB/RGBY caps

- code/modules/food_and_drinks/recipes/tablecraft/recipes_wastefood.dm
changes the recipe for molerat stew from needing the beer bottle snack item, to needing the beer reagent.
:cl:
Change: swapped the beer in molerat stew from object to datum reagent
/:cl:
> Molerat stew fix

- _maps/map_files/Pahrump-Old/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Temp Map Storage/Pahrump-Sunset - Outdated.dmm
- code/__HELPERS/_cit_helpers.dm
- code/game/objects/items.dm
- code/game/objects/items/stacks/sheets/leather.dm
- code/modules/clothing/suits/arfsuits.dm
- code/modules/clothing/suits/arfsuits_unused.dm
- code/modules/clothing/suits/f13factionarmor.dm
- code/modules/clothing/suits/toggles.dm
- code/modules/clothing/under/miscellaneous.dm
- code/modules/jobs/job_types/legion.dm
Added in a var to separate genital coverage from defensive coverage. So, we can have armor kits that dont hide genitals, labcoats that show off everything while open, jackets and vests that have your danglies peek out the bottom. Course if you're wearing anything underneath, or underwear, its all hidden.
Also gear harnesses no longer hide genitals.
:cl:
add: Armor that should reasonably not hide your unmentionables will no longer hide your unmentionables.
/:cl:
> Added support for armor to show genitals

- code/__HELPERS/files.dm
Sorts the `Get Server Log` verb menu by reverse alphabetical.
This makes it show the dates in descending order, so newer dates will show at the top.
It does have the side effect of causing the actual log bit to be reverse alphabetical, but that's a relatively minor thing.
:cl:
admin: The "Get Server Logs" verb is now sorted so newer dates are at the top.
/:cl:
> Sorts the Get Logs verb in desc numberical

- code/modules/projectiles/boxes_magazines/ammo_boxes.dm
- code/modules/projectiles/boxes_magazines/external/pistol.dm
Socom mags: Now visible when half empty.
:cl:
fix: Socom mags: now visible when half empty.
/:cl:
> Fixes socom mags

- code/modules/hydroponics/grown/towercap.dm
- code/modules/research/stock_parts.dm
T2 Capacitors and Analyzers had improperly set icons, resulting in a missing and improper sprite respectively. Bonfires used some pretty weird code to check for areas resulting in some errors with determining if potential "listeners" to smoke signals were outside, used the wrong logging, and failed to properly fire_act items afterattack. All of this is fixed!
:cl:Fel
fix: Capacitor and Analyzer icons have been fixed!
fix: Tribals no longer have X-ray vision for specifically smoke. (They no longer see smoke signals while indoors.)
fix: Bonfires can light things used on them on fire again. Revolutionary, I know.
/:cl:
> Fixes some improperly set stock part icons, some issues with bonfires.

- code/modules/arousal/arousal.dm
- code/modules/arousal/genitals.dm
- modular_citadel/code/datums/status_effects/chems.dm
You can get boners now. Just click "Toggle genital arousal" and turn whichever part you want on or off.
Still cant ejerkulate, working on that. 
Also reimplements a verb to toggle lewd hypnosis. Doesnt really do much, but for those who like to play with MK Ultra, it'll probably make it work a bit better. Its a work in progress!
:cl:
add: Readded a verb that toggles genital arousal.
/:cl:
> Re-enabled manually toggled biological turgidity

- code/__DEFINES/combat.dm
- code/modules/projectiles/guns/ballistic/automatic.dm
- code/modules/projectiles/guns/ballistic/shotgun.dm
The FAL was a bananas person deleter. 57 damage at 600RPM? not on my watch!
The FAL now fires at 200RPM and does 37 damage per shot. Might be a bit low, open for suggestions.
Most assault rifles have had their fire rate halved, and their damage reduced by 15%. Again, open for suggestions.
Most semiauto shotguns are now, instead, pump action shotguns with a much higher pump speed. The only semiauto shotgun left (that isnt a mag-fed autoshotty) is the auto-5. You can still pump that lever action pretty darn fast, its more than twice as quick as a normal shotgun.
Rifleman gloves and the perk itself lets you cock the gun twice as fast instead of *ten* times as fast.
:cl:
balance: FAL now fires at 200RPM and does 37 damage with match ammo.
balance: most assault rifles have had their fire rate …
> Gun balance changes

- code/modules/projectiles/guns/ballistic/automatic.dm
So apparently the FAL spawned with a magazine that doesnt actually exist. Normally this is okay, but it had the wrong amount of ammo in it, so it made the gun invisible. welp. Now its visible and has the right mag
:cl:
fix: FAL comes with ammo and is now visible.
/:cl:
> FAL no longer spawns with an imaginary mag of null references

- interface/skin.dmf
Re-adds the handy changelog button to the menu, between the tg wiki button and the github button.
:cl:
add: Re-added the changelog button to the upper right, next to the github button.
/:cl:
> Re-adds the changelog button

- code/modules/clothing/head/f13head.dm
- code/modules/clothing/shoes/miscellaneous.dm
- code/modules/clothing/suits/arfsuits.dm
- code/modules/jobs/job_types/oasis.dm
- code/modules/jobs/job_types/wasteland.dm
- code/modules/jobs/jobs.dm
MINOR TWEAKS
/obj/item/clothing/suit/armor/light/leather/rig
- Added 4 small pockets
- Fixed the description
/obj/item/clothing/suit/armor/medium/duster
- The bullet armor wasnt good, so I changed it to be better for PVP combat.
/obj/item/clothing/shoes/galoshes
Removed slowdown
/obj/item/clothing/head/f13/flatranger
- Changed name and description, one of many NCR items that need to be reworked
OASIS LOADOUT CHANGES
MAYOR
no longer has shit guns that make no sense between loadouts and other jobs. It is a command position, and as such they have access to higher tier side arm weapons.
Frontier Leader = from Snub to Peacekeeper
First Citizen = From AEP7 to Auto Beretta
High Roller = From Type 17 (???????????????) to MK23
Mayor for Life keeps their custom M1911, its a really good gun …
> Redwater/Nash Loadout Updates + Minor Tweaks

- code/modules/mob/emote.dm
- code/modules/mob/living/emote.dm
- code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
- code/modules/mob/say.dm
You can put line breaks in standard custom emotes, so you can have paragraphs in your *me posts.
Also allows capitalization in inline *me emotes. So you can do '*me waves to YOU FUCKASSS' and have it show up correctly.
:cl:
add: Added linebreaks to *me.
fix: Inline *me emotes now get their punctuation.
/:cl:
> Adds linebreaks to *me

- code/modules/clothing/masks/miscellaneous.dm
- modular_citadel/code/modules/client/loadout/mask.dm
This PR renames the legion bandanas and puts it under the loadout menu so that way people can use them instead of them sitting in code.
:cl:
tweak: rename bandanas
add: adding them into loadout menu
/:cl:
> Legion bandanas renamed and put into loadout

- code/modules/arousal/genitals_sprite_accessories.dm
- code/modules/arousal/organs/testicles.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- config/game_options.txt
Changes the upper limits for Dongs to 24 inches. Don't have to merge this but I figured it'd be nice for any taur players to have dongs to match.
Fixes not being able to select vaginas. #507 
Adds sheaths.
:cl:
add: Adds sheaths as a ball options.
config: Changes PENIS_MAX_INCHES_PREFS from 10 to 24
fix: Fixes #507 and allows vagina types to be selected.
/:cl:
> Update game_options.txt & more

- code/_globalvars/lists/flavor_misc.dm
- modular_citadel/code/modules/client/loadout/hands.dm
So that way I dont use three points on a backpack and I can spawn with it as my backpack instead of having a backpack within a backpack.
Remove the legion backpack from the loadout menu.
:cl:
add: backpack to backpain menu in a way.
remove: legion backpack from the lloadout menu.
/:cl:
> Adds backpack to the backpack section

- code/modules/jobs/jobs.dm
Moves outlaw back under 'redwater' in spawn menu to reflect their alleigances.
:cl:
tweak: moves outlaw back to redwater under spawn menu for clarity.
/:cl:
> moves outlaw back under 'redwater'

- code/modules/mob/emote.dm
- code/modules/mob/living/emote.dm
- code/modules/mob/say.dm
You can put line breaks in standard custom emotes, so you can have paragraphs in your *me posts.
Also allows capitalization in inline *me emotes. So you can do '*me waves to YOU FUCKASSS' and have it show up correctly.
No longer breaks everything! Message input verbs suuuuuuuck!
:cl:
add: Added linebreaks to *me.
fix: Inline *me emotes now get their capitalization.
/:cl:
> *me gets multiline support that doesnt ruin everything

- code/game/objects/items/fallout13misc.dm
Removes the Khans, NCR, Legion and Oasis flag from the menu and replaces the names for Locust and gunner flag, so that way they can be made. Gunners flag is named Outlaw flag with a new description and Locust flag was renamed to Bandit flag.
The image below is example on what is now.
:cl:
tweak: renames locust flag to bandit flag with same old description.
add: outlaw flag aka renamed Gunner to outlaw flag
/:cl:
> Gunner / Locust flag gets renamed and put into flag menu.

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Fixed more mapping issues with the FoA hospital, Should be brighter and internal walls near the workshop should be properly deconstruct-able. The mystery of the FoA Admins missing lamp has also been solved.
:cl:
add: FoA Hospital - More lighting.
add: FoA Hospital - Chemistry trashcan.
fix: FoA Hospital - Workshop now uses correct, deconstructable internal walls.
fix: FoA Hospital -  matrix turfs are now properly bordered by concrete wall turfs.
fix: FoA Hospital - Swapped errant concrete turfs for rock turfs near the south external wall.
fix: FoA Hospital - Fixed a LoS issue where people in the supply room doorway couldn't see the north end of the lobby.
fix: FoA Hospital - Front lobby desk now has metal bars like it used to.
/:cl:
> Even More FoA fixes

- code/__DEFINES/inventory.dm
- code/datums/components/storage/concrete/pockets.dm
- code/game/objects/items/storage/belt.dm
- code/modules/clothing/suits/arfsuits.dm
Had an oversight with holsters, made them all shoulder holster sized when the belt one should be bigger.
Made holsters and belts hold about twice as much volume. Open for suggestions here!
:cl:
tweak: Storage belts hold more volume.
fix: Fixed holsters being too smol.
/:cl:
> Fixes holsters and embiggens specialized belts

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
- _maps/map_files/Pahrump-Sunset/RockSprings.dmm
Oli fixes the cheese in one of the north bunker and puts a tier5 melee instead of random free supersledge in a way, and also adds colormate to nash and redwater.
:cl:
tweak: Northern bunker into an actual bunker worth it and not so cheeseable
add: colormate to redwater and nash.
/:cl:
> Oli fixes the north bunker a tad, adds colormate to nash & redwater

- code/datums/traits/good.dm
I've seen some complaints that the chem-whiz quirk doesn't give the recipes you'd get if you read the book. This fixes that, as well as the explosive crafting quirks
I don't think any other quirks should have recipes, but if they do, complain at me
Should fix issues #484 and #425
:cl:
add: Gave recipes to the chem-whiz and explosives crafting quirks
/:cl:
> Gives some quirks their recipes

- code/__DEFINES/citadel_defines.dm
- code/modules/client/preferences_savefile.dm
What it says on the tin. There was a missing line in the character save files that wasn't allowing the balls to save properly. Fixes #525 
:cl:
add: ability to save balls shape
tweak: renamed default balls.
fix: Fixes #525 
/:cl:
> Redefines default Balls shape, enables saving of balls type.

- code/datums/components/crafting/recipes/recipes_misc.dm
Changes Shutters and Blast Door Crafting Recipes to use Pre-War Alloys instead of Plasteel to A: Give PWA a bit more use and B: Make it a bit easier to make shutters and blast doors for our weird engineering nerds. 
:cl:
tweak: Changes Shutter recipe to use 10 Pre-War Alloy instead of 10 Plasteel
tweak: Changes Blast Door recipe to use 20 Pre-War Alloy instead of 20 Plasteel
/:cl:
> Changes Shutters and Blast Door Crafting Recipes

- code/modules/reagents/chemistry/machinery/chem_dispenser.dm
This PR brings the wasteland drink machines changes to here, so less mechanical farming and more rping. Which is good, so the process goes as followed.
tier 1 = Juices
tier 2 = a tad bit more juices / rare drinks / premade drinks.
tier 3 = premade drugs / Monkey Energy / Antihol
emagged/hacked = Rotgut / cryoxadone / Iron / Superlaughter
Dont like them, please leave comments + feedback on how to make it better or worse, either way. More bar rp incoming to a bar near you.
:cl:
tweak: drink machine fitting more drinks, so that way more roleplay less mechanical farming for the bartender to get you a fancy drink. 
/:cl:
> Brings Wasteland Drink machine change to here.

- code/modules/projectiles/guns/ballistic.dm
- code/modules/projectiles/guns/ballistic/automatic.dm
- code/modules/projectiles/guns/ballistic/pistol.dm
- code/modules/projectiles/guns/ballistic/revolver.dm
- code/modules/projectiles/guns/ballistic/shotgun.dm
Most pistols, aside from 9mm and the .22, are normal sized.
All SMGs are bulky now (let me know if some arent)
Sawing off a gun removes its double-fire capability, makes it to 15% less damage, and makes it one-hand non-akimboable.
Shotguns are two-handed guns.
:cl:
balance: Most guns are larger, especially SMGs and large pistols.
balance: Sawing off a gun removes its double-fire, reduces its damage by 15%, and makes it not akimboable.
/:cl:
> Rebalances guns again

- code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
- code/modules/fallout/obj/crafting.dm
- code/modules/jobs/job_types/wasteland.dm
Mainly removes the service rifle/R82 blueprints that let Redwater get auto weapons super easily. Additionally, changes recipe for m1 carbine, and comments out a literally useless misspelling item.
:cl:
tweak: nerfs oops
/:cl:
> the epic auto rebalancing: part 1

- code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
Re-adds ability to add powder to the alchemical rack thingy
:cl:
fix: Readds the ability to add healing powders too alchamey racks
/:cl:
> Can add powder to rack

- code/__DEFINES/combat.dm
- code/modules/mob/clickdelay.dm
- code/modules/mob/mob_helpers.dm
- code/modules/projectiles/ammunition/_firing.dm
- code/modules/projectiles/gun.dm
- code/modules/projectiles/guns/ballistic.dm
- code/modules/projectiles/guns/ballistic/automatic.dm
- code/modules/projectiles/guns/ballistic/bow.dm
- code/modules/projectiles/guns/ballistic/crafting.dm
- code/modules/projectiles/guns/ballistic/pistol.dm
- code/modules/projectiles/guns/ballistic/revolver.dm
- code/modules/projectiles/guns/ballistic/rifle.dm
- code/modules/projectiles/guns/ballistic/shotgun.dm
- code/modules/projectiles/projectile.dm
- code/modules/projectiles/projectile/bullets/pistol.dm
- code/modules/projectiles/projectile/bullets/rifle.dm
- code/modules/projectiles/projectile/bullets/shotgun.dm
Manually cycled guns can be racked by just clicking again, so you can just keep clicking to rack your gun.
Pumping the gun is no longer tied to the gun's firing rate, so you can pump/rack it immediately after firing. However, the firing rate itself still limits how often the gun can be fired. 
Messed with the ranged click delay so that you'll cock your gun quickly after firing, instead of just before firing. Just some feely things.
Fun fact, the rifleman trait didnt really do much in the new system! Now it does, it reduces the refire rate on manual rifles and shotguns by 20%. I know its a lot less than 50% faster, but, now it actually works.
Certain guns have different chances to hit specific zones on people. Most semiauto guns work as they did, but automatic guns have a much lower chance …
> Gun changes, again

- code/modules/fallout/obj/structures/mob_spawners.dm
standing on top of a mob next/putting a dense object on top blocks it from spawning
todo in a future PR: probably have mobs inside simulate an attack on what is blocking them?
fine with this being reverted if it's a bad change idk, it's experimental basically. this may involve some remapping 
:cl:
add: standing on top of/dragging a dense object on top of a mob nest blocks its spawning
/:cl:
> nests with dense objects on top of them no longer spawn

- code/_globalvars/lists/maintenance_loot.dm
- code/game/objects/effects/spawners/f13lootdrop.dm
- code/game/objects/effects/spawners/themed_loot_tables.dm
Pulls Mosin Nagants from the Trash and low tier gun spawning pools. This should technically remove them from most rounds for the time being but that's only until we can decide on where they really should go.
:cl:
del: Deleted the Mosin Nagant from the loot tables of trash piles and low tier guns.
/:cl:
> No. More. Mosin.

- code/modules/projectiles/guns/energy/laser.dm
Just improves the fire rate of the Magneto Wattz to be equal to that of the regular Wattz pistol. Magneto is meant to be an upgraded version but was probably worse with the fire delay.
- [y] You tested this on a local server.
- [y] This code did not runtime during testing.
- [y] You documented all of your changes.
:cl:
balance: buff to magneto
/:cl:
> Magneto Wattz buff

- code/modules/projectiles/guns/ballistic/bow.dm
Fixes bows needing to be jerked off harder than usual to fire again. Now it'll uncock when fired.
Also makes bows not toss imaginary casings on the ground. No more kaplink!
:cl:
fix: Bows pull back properly.
fix: Bows no longer make a brass-hitting-the-ground noise when firing.
/:cl:
> Fixes bows

- code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
- code/modules/research/designs/ammolathe_designs.dm
Fixes it to call it .45 (muh three world wars) instead of 9 malamutes.
Fixes it to call it .45 (muh three world wars) instead of 9 malamutes.
:cl:
tweak: Renamed Greasegun mags to 45, because that's what they're in now (M3WW)
/:cl:
> Greasegun Mags Renames

- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
This PR fixes what bug I have made in redriver map setting.
only one mirror now not three.
:cl:
fix: two mirrors gone only one remains.
/:cl:
> RedRiver Map Bug fix

- code/__DEFINES/random_mob_spawner.dm
- code/__HELPERS/_lists.dm
- code/controllers/subsystem/mob_spawners.dm
- code/modules/fallout/obj/structures/mob_spawners.dm
Reworks spawners, again.
Now, the mob list is how many of each mob the spawner can spawn total. When a mob is spawned, it is decremented from the list. This way, ghoul spawners can spawn 10 ghouls, 1 reaver, and 1 glowing one before collapsing.
Spawners have a limit to how many of any mob can be around it, depending on the spawner's difficulty generally. If there are that many living simplemobs around, it'll skip spawning until there are less than that many around.
Most spawners require a player to be around to spawn anything. Should prevent huge clouds of mobs everywhere.
Reworks the dense object thing to use a weakref to improve performance a little bit if something's on the spawner for multiple fires.
Makes spawned mobs stop referencing this nest if its destroyed before they all die. …
> Reworks how spawners work sorta

- code/modules/client/client_procs.dm
Sorry Lummox...
Removes the "Become a BYOND member to access member-perks and features, as well as support the engine that makes this game possible. Only 10 bucks for 3 months!" message
There are other things connected to the proc that have to do with BYOND membership and admin stuff, so I decided to let the proc stay.
> Removes the BYOND advertisement

- code/game/objects/items/grenades/flashbang.dm
- code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm
- code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
- code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
- code/modules/mob/living/simple_animal/hostile/hostile.dm
- code/modules/mob/living/simple_animal/hostile/synth.dm
Mobs with extra projectiles can have the delay between their projectiles adjusted. Defaults to about 2-3 times slower than usual.
If a mob has an autofire delay shorter than one burst, it's changed to be just one long continuous spray. Like sentrybots, they fire slower, but they dont stop shooting.
Securitrons and sentrybots stop shooting when you're downed. Fuckers.
Nerfed the defensive flashbang to go off several seconds later, and have about half the bang range.
Securitrons can now also drop stingbangs and smokebombs. Its mostly smokebombs, with a 10% chance to be a flash or stingbang instead.
Gutsies should be a bit more fair.
:cl:
add: Securitrons can prime smokebombs and stingbangs too. Mostly smokebombs.
tweak: Ranged mobs can have their burst fire rate adjusted.
balance: Secbots …
> Tweaks mob burstfire and securitron grenades

- code/game/objects/items/stacks/sheets/sheet_types.dm
12 cloth = autopipe belt. its empty~
:cl:
add: Autopipe belts are craftable from 12 cloth.
/:cl:
> Make an autopipe belt out of cloth

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- code/controllers/subsystem/economy.dm
- code/modules/cargo/packs/emergency.dm
- code/modules/cargo/packs/engine.dm
- code/modules/cargo/packs/engineering.dm
- code/modules/cargo/packs/medical.dm
- code/modules/cargo/packs/misc.dm
Adds the ability for the shopkeep to order from cargo using the ol' 009 Tunnel, aka 'two railroad tracks underground that disappear'. _**Don't merge this yet :)**_
:cl:
add: shopkeep cargo arggb
/:cl:
> [WIP] adds cargo to shopkeep

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RockSprings.dmm
:cl:
del: Deleted Ammo Workbench from Redwater
tweak: Adjusted Nash's Workshop area
tweak: Moved some medical plants from near Nash's Workshop area to other areas in Nash.
/:cl:
> Changes Nash's Workshop + Removes Redwater Ammo Bench

- code/__DEFINES/inventory.dm
- code/game/objects/items/storage/belt.dm
- code/game/objects/items/storage/wallets.dm
- code/modules/mining/money_bag.dm
- code/modules/projectiles/guns/energy/laser.dm
Fixed the shoulder holster being too small. still has 4 slots.
Chest rig, the bandolier, goes on the belt, and has 7 slots for small ammo.
Fixed money pouch's throbbing red text, and made it hold anything a wallet can, including screwdrivers and keys.
Wattz 1000 is a small gun.
Combat dusters get 3 small slots.
> Storage changes again

- code/modules/clothing/suits/arfsuits.dm
removes laser negative armor from leather armor to be more in line with Fallouts setting saying that leather works well against lasers
:cl:
tweak: tweaked leather armors laser protection value
/:cl:
> Adjusts leather armor

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
The pixel shifted curtains in Nash have been replaced with proper curtains. Railings have been placed underneath the windows to prevent outsiders from opening the curtains.
I also shifted the showers up in the Heaven's Night bar second floor to be easier to reach.
:cl:
add: Added railings underneath Nash windows to prevent them from opening on the outside.
tweak: Changed Pixel shifted curtains with normal curtains
tweak: pixel shifted the showers in Nash's bar up to be easier reached when on the same tile.
/:cl:
> Fixes Nash Curtains + Shifts Upstairs Showers

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
heeh
Moved the redlick blue matrixes around to fit properly
:cl:
tweak: tweaked the red river matrix tiles to the SE to fit properly
/:cl:
> Red river blue matrix fix

- code/modules/newscaster/newscaster_machine.dm
Simple number lower. Gave almost DOUBLE the materials for a crafted device from the lathe. This fixes that. It now gives slightly lower! (by like 100 less for each one)
> Fixed Infinite Metal/Glass exploit

- code/modules/jobs/job_types/wasteland.dm
Replaces the single stack 9mm mags with doubles to match the ones the hipower comes with.
:cl:
tweak: switched the ex-mil wastelander jobs spare mags from single stack to doubles to fit with the theme.
/:cl:
> 9mm Mag Fix for Ex-Mil Waster

- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
removes a totally hidden pungi spawn that's 5 tiles from the road you can spawn on in Redlick (also can cause you to be stunned long enough for nearby mobs to crit you before you can even start moving again)
:cl:
/:cl:
> Pungi culling

- code/__DEFINES/is_helpers.dm
Everyone got synth repair kits cus I misdid a macro. This fixes that macro, so only synths should get the kits.
> Synth repair kits are only given to synths

- code/game/machinery/cell_charger.dm
- code/game/machinery/recharger.dm
- code/game/objects/effects/spawners/f13lootdrop.dm
- code/modules/power/cell.dm
- code/modules/projectiles/ammunition/energy/laser.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/projectile/beams.dm
This will be modifying the laser weapon damages, tweaking what guns are in what tier. 
The new tier list, ranked in order of damage output per ammo cell is as follows.
Wattz 1000 - 28 Damage - 15 Shots - 3 DT Pen - 420 DPC
Wattz 1000 Magneto - 26 Damage - 15 shots - 7 DT Pen - 390 DPC
AEP7 - 24 Damage - 30 shots - 4 DT Pen - 720 DPC
Wattz 2000 - 52 Damage - 12.5 shots - 7 DT Pen - 780 DPC
AER9 - 32 Damage - 25 Shots - 5 DT Pen - 800 DPC
AER9 Overcharged - 34 Damage - 5 shots - 10 DT Pen - 136 DPC
AER12 - 36 Damage - 25 shots - 6 DT Pen - 900 DPC
Wattz 2000e - 40 Damage - 25 shots - 4 DT Pen - 1000 DPC
Cell chargers now charge 10% of whatever cell is in them per cycle, leading to more even charge times across the board.
Weapon chargers now charge 10% of Fallout style cells per cycle now. …
> Laser Weapons Rebalance & Cell Charger Tweaks

- code/datums/components/crafting/recipes/recipes_tailoring.dm
- code/game/objects/items/cards_ids.dm
Allows the crafting of Chameleon masks and re-enables reprogrammable ids to change names and jobs.
:cl:
add: Chameleon Mask to Crafting
tweak: Re-Enabled reprogrammable IDs
/:cl:
> Incognito Mode

- _maps/map_files/Pahrump-Old/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Old/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Temp Map Storage/Pahrump-Sunset - Outdated.dmm
- _maps/map_files/Temp Map Storage/Pahrump-Sunset-Lower - Outdated.dmm
So several spawners were set to spawn_once, but spawn_once is no longer a thing (and is instead done by setting its mob_types to have one mob in it, use that!), so it just runtimed. No more!
> Spawner runtime fixes

- code/modules/mob/living/simple_animal/hostile/megafauna/behemoth.dm
behemoth rage now activates at 1.5k hp and is at full enrage. turns out it was that way for a reason. who fucking knew.
:cl:
tweak: the behemoth hates corn syrup and refuses to drink it
/:cl:
> fixes behemoth enrage, my behated

- code/controllers/subsystem/job.dm
- code/modules/client/preferences.dm
- modular_citadel/code/modules/client/loadout/_loadout.dm
- modular_citadel/code/modules/client/loadout/donor.dm
So used to be that if you had something in your loadout, and that thing had its type changed or deleted, it'd ruin everything in your loadout and only load like half of it on your mob. Now, if something's in your loadout that doesnt exist, instead of runtiming, it'll just remove that entry from your loadout.
Also, made the item ckey checker check the ckey version of its required key against your ckeyed ckey. Now you can capitalize whatever you want and it'll still work.
And that's all I did, honest.
> Fixes loadouts freaking out over missing stuff

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Who did this?
Removes a duplicate spawner nest from the same tile.
:cl:
del: Removed an erroneous nest that occupied the same tile as another nest.
/:cl:
> Removes a second nest on the same tile as another.

- code/modules/projectiles/guns/energy/laser.dm
swaps aep7 and wattz fire-rates.
:cl:
tweak: aep7 now fires faster than the wattz
/:cl:
> aep7 fires faster than the wattz

- code/_globalvars/lists/maintenance_loot.dm
- code/modules/projectiles/guns/mods/mods.dm
DO YOU EVEN MOD, BRUH?!
Adds the overdrive, battery shunt, giga lens, and overshooter to the loot table.
Lowers the fire rate increase of the overdrive mod and edits its // description as well as the mods description to convey the change.
> More mods in the trash loot!

- code/game/objects/items/stacks/sheets/sheet_types.dm
- code/modules/farming/farming_tools.dm
Makes the hay recipes, straw hats and baskets, available for crafting. Changes baskets to drop hay when destroyed or dismantled rather than plasteel. Tribal and homesteader storage enthusiasts rejoice.
:cl:
fix: hay sheet recipes now craftable
/:cl:
> Restore hay recipes and correct basket material

- code/__DEFINES/inventory.dm
- code/datums/components/storage/concrete/backpack.dm
- code/datums/components/storage/concrete/boxes.dm
- code/datums/components/storage/concrete/pockets.dm
- code/datums/components/storage/storage.dm
- code/datums/components/storage/ui.dm
- code/game/objects/items/storage/survivalkit.dm
Adds in support for multiple rows of storage, so large inventories dont get smooshed into smallness.
Tweaks the combat armor's bandolier to be a bit less of a hold-everything sack.
Resizes backpacks, duffels, and scav duffels to be divisible by their rows, to minimize wierdness.
> Volumetric storage changes

- code/game/world.dm
- config/config.txt
Not tested, as I'd have to host my testing server on the hub lmao.
Should have no adverse effect, though.
I also uncommented and locked the server name in `confix.txt`, so it'll appear in places.
> Updates discord link in hub description

- code/modules/jobs/job_types/wasteland.dm
Wasters no longer spawn with the wrong survival kits.
> Wasters get the right pouch

- code/game/objects/items/tools/weldingtool.dm
- code/modules/fallout/obj/smelling_salts.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
Two loadout kits locked to ckey truedark, as well as a custom item that's basically a reskinned industrial welder that's slightly better. (Item currently in the donator file)
Loadout kit locked to thingpony.
Loadout kit locked to baticon.
Removes the reference to Caesar's legion from the smelling salts.
Changed the // from SUNSET FLUFF ITEMS to COYOTE FLUFF ITEMS.
> Loadout kit stuff!

- code/modules/fallout/obj/crafting.dm
- code/modules/fallout/obj/decals.dm
Adds the oft-requested ability to remove puddles of radioactive goo, the bane of construction- and restoration-minded wastelanders since the dawn of man. Sprinkling a full box of Abraxo cleaner onto a puddle will absorb and neutralize it, leaving behind an easily-cleaned pile of mostly harmless powdered chemical waste. The flavor text for Abraxo has also been modified to hint towards this ability, reducing the amount of code diving necessary to learn such terrible power.
:cl:
add: Added the ability to clean up puddles of goo with Abraxo
tweak: Tweaked Abraxo's flavor text to hint towards its new goo-obliterating powers
/:cl:
> Cleaning radioactive goo with Abraxo

- code/datums/components/storage/concrete/backpack.dm
Adds the ability to fit javelins made from blacksmithing to fit in a javelin 
:cl:
tweak: Javelins made from blacksmithing now fit in the appropriate quiver
/:cl:
> Allows javelins made from blacksmithing to fit in the Spear Quiver

- code/modules/projectiles/projectile.dm
Bullets didnt really check what you clicked on, making them not hit things unless they're dense. Now? They do.
> Bullets hit things again

- code/modules/jobs/job_types/followers.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
Loadout kit locked to ckey trueDARK. (third one)
Changes the followers administrators loadouts like this:
Surgery specialist gets a medibeam gun instead of the medical treatment stuff.
Chemistry specialist gets a cmo hypospray kit instead of a bluespace beaker.
> Loadout Kit and Followers Administrator Stuff

- code/datums/traits/good.dm
- code/modules/jobs/job_types/followers.dm
- code/modules/jobs/job_types/oasis.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
Ckey locked loadout kit for sage1990.
Ckey locked loadout kit for Caseapollo58143.
Ckey locked loadout kit for Merek2.
Adds loadout options to the shopkeeper:
Energy Specialist = Aer9, light plasma pistol
Ballistic Specialist= Riot Shotgun, Desert Eagle
Jack-Of-All Trade= Aep7, Uzi
Fixes the Followers Administrators Chemistry loadout.
Changes the formal tribal trait up. Now should give stuff similar to sulfer 🅱️ottoms.
> Ckey Kits and Shopkeeeper changes!

- code/__DEFINES/say.dm
- code/datums/elements/flavor_text.dm
- code/modules/mob/dead/new_player/new_player.dm
Rewrites #764 for better code quality and to fix the inverted checks.
:cl:
add: Adds a minimum flavortext length
tweak: Allows ghosts to always see character flavortext, even when someone is wearing a mask.
/:cl:
> Add minimum flavortext length, always let ghosts see flavortexts

- code/modules/smithing/anvil.dm
- code/modules/smithing/finished_items.dm
- code/modules/smithing/smithed_items.dm
Adjusts the XP gain modifiers, adjusts how many levels you can get from good items, adjusts what the max level bonus for an item is.
Essentially: This PR will reduce how quickly you can get high-tier forging items, and make you expend more resources + time to get to it, and decreases the maximum 'gain' you can get from massively levelling up your forging level. It still keeps it viable to level up, but you REALLY shouldn't be able to get quality 8 iron hammers in less than 5 minutes
:cl:
tweak: Makes forging less insane
/:cl:
> Hopefully Slightly makes Forging Worse

- code/_onclick/item_attack.dm
anything over 36 damage gets a bonus over just big leagues. you can also stack big leagues with this so uh it'll probably be fine, you will live somehow, i am sure of it.
:cl:
tweak: fev melee damag eargh
/:cl:
> changes the FEV trait melee bonus from a flat 20 bonus to 35%

- code/modules/smithing/anvil.dm
Makes blacksmithing slightly less grindy.
:cl:
tweak: re-adjusts blacksmithing to be slightly better, since the absurd damage stacking WAS fixed
/:cl:
> Blacksmithing tweaking

- code/__DEFINES/traits.dm
- code/game/objects/items/devices/scanners.dm
- code/modules/mob/living/carbon/human/inventory.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/status_procs.dm
- code/modules/modular_computers/computers/machinery/modular_computer.dm
- code/modules/projectiles/ammunition/_firing.dm
- code/modules/research/rdconsole.dm
Fixes glasses bug with FEV, makes them have more spread, fixes near-sighted, fixes poor aim not working, both buffs and debuffs the FEVmans rad resistance, properly restricts the R&D console we use.
:cl:
tweak: FEV trait tweaks
/:cl:
> FEV Tweaks

- code/modules/jobs/job_types/oasis.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
Edits Swirlby's loadout kit, giving the vault exile jumpsuit.
Loadout kit locked to ckey yawet330.
Fixed a loadout option for nash citizen, the snub for prospector wasn't set up properly to actually fill the bag.
Fixed a loadout option for the mayor, first citizen loadout didn't give the flash like it should have.
> Various Loadout Stuff

- code/datums/materials/basemats.dm
- code/game/objects/effects/spawners/f13lootdrop.dm
- code/game/objects/items/stacks/sheets/leather.dm
- code/game/objects/items/stacks/sheets/sheet_types.dm
- code/modules/cargo/exports/large_objects.dm
- code/modules/cargo/exports/materials.dm
- code/modules/cargo/exports/misc_export.dm
- code/modules/cargo/packs/emergency.dm
- code/modules/cargo/packs/engine.dm
- code/modules/cargo/packs/engineering.dm
- code/modules/cargo/packs/goodies.dm
- code/modules/cargo/packs/livestock.dm
- code/modules/cargo/packs/materials.dm
- code/modules/cargo/packs/medical.dm
- code/modules/cargo/packs/misc.dm
- code/modules/cargo/packs/organic.dm
- code/modules/cargo/packs/science.dm
- code/modules/cargo/packs/security.dm
- code/modules/cargo/packs/service.dm
- code/modules/fallout/obj/stack/f13Cash.dm
- code/modules/fallout/obj/stack/hide.dm
This PR greatly expands the list of both what is importable and exportable through cargo, making it a stronger tool at the hands of the Shopkeeper. What this DOESN'T fix is Large Object exports, which don't work at all currently, this means that crate selling - the old backbone of cargo, is currently defunct. I think our cargo train could work without crates, but I don't want to make this a full PR until we've decided what to do about large objects.
:cl:
add: Added a ton of new crates to cargo, 
add: Greatly expanded the list of exports to cargo, most notably in the form of guns, caps, and produce now being exportable.
del: Commented out crates that no longer fit the server
tweak: Swapped categories of crates to make more sense 
balance: Adjusted cargo crate values to reflect our codebase …
> Cargo Expansion

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Removes the peeping tom windows in the upper hotel
Rearranges the shopkeeper lower. Mostly the bedroom, and adds a bathroom
Adds cargo stamps, and the cargo shuttle/train timer thingy
Fixes a missing area in the house Greed touched up
:cl:
/:cl:
> Nash updates

- code/modules/projectiles/ammunition/_firing.dm
Fixes bullet spread for poor aim/etc
:cl:
fix: Poor aim/etc now actually randomise how far their projectiles spread
/:cl:
> Makes this less predictable

- code/modules/jobs/job_types/followers.dm
- code/modules/jobs/job_types/oasis.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
Loadout kit locked to ckey BWOIncognito.
Adds an egun loadout to the follower guard, sheriff, and deputy.
Guard and Sheriff gets a scatter rifle. Reason for guard is they are designed to be protecting the hospital with effectiveness. That and it's no different the police shotgun, if not slightly weaker far away.
Deputy gets an aer9 which is admittadely stronger than the scatter if not all bullets hit.
Info about the scatter: Has massive spread. Lacks armor penetration %. Fires extremely slow. Has terrible cell charge shot amount. Does good damage point black (up in the targets face). Good pvp wise versus someone lacking energy protection armor, but not all too great for pve.
> Ooops all eguns + Ckey item (Loadout wild ride)

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
moves medivendor into sewers below pharmacy, moves chem stuff back into pharmacy
moves med vendor from museum into vault display
:cl:
tweak: change med vendor locations
/:cl:
> changes location of the med vendors, once more

- code/modules/research/designs/mining_designs.dm
- code/modules/research/techweb/nodes/tools_nodes.dm
This PR disables the ability to make plasma cutters as their interaction with Eris gun code appears to be incredibly buggy. Plasma cutters are also linked to inconsistent  server crashes related to mining.
:cl:
del: Removes plasma cutter and advanced plasma cutter from RnD
/:cl:
> remove plasma cutter from RnD

- code/game/objects/items/cards_ids.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
Loadout kit locked to ckey Nightmare6669
Removes an old reference of NCR on an heirloom item, and legion reference from another. No glitch in the matrix here I swear!!!
> Ckey item and NCR/Legion reference removal

- code/modules/food_and_drinks/recipes/drinks_recipes.dm
Fixes a funny typo in the recipe for barrel tea stemming from #697 that makes brewing it impossible
:cl:
fix: Fixes typo in barrel tea recipe
/:cl:
> Fix Barrel Tea temperature requirement

- modular_citadel/code/modules/client/loadout/__donator.dm
The fusion lighter and Slime lighter just has the special component of heating much hotter than a normal one. The slime one can even be ground up it seems too! Yay for fluff!
Loadout ckey's affected: Bwo/tasald, risingstar/blue (don't shoot for shameless self add plz)
Also gave Merek2 a fusion lighter/vault113 flask!
> Put lighters and two different loadout kits!

- code/modules/clothing/suits/arfsuits.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
Ooopsy'd his loadout. That's fixed!
While this leather battle coat will let you go faster baseline than ordinary medium armor, and protect against melee...bullets will destroy you, whilst laser weapons will destroy you (but not as much as bullets). Good luck fighting anything that doesn't punch you. Adds the tier 4 down tag to the bullets which effective lowers the base medium armor listing of 26 down to 35% of the value. Laser weapon wise it's baseline protection for medium armor, while the armor is finetuned to protect heavily against melee trauma.
PS. The main gimmick of the armor is its speed to dodge shots. Granted the slowdown is only effectively lowered to 80% of its normal slowdown.
> Final edition of the leather coat + Ckey kit fix

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Also moves a few barrels so the north wall doesn't explode constantly.
:cl:
tweak: Moved a pig and two barrels around from the north Nash Wall
/:cl:
> Moves a pig so it doesn't blow up the north Nash Wall

- code/_onclick/hud/screen_objects/storage.dm
- code/game/atoms_movable.dm
- code/game/objects/items/grenades/flashbang.dm
- code/game/objects/obj_defense.dm
- code/modules/mob/mob_helpers.dm
Fix for some runtimes I found while testing for The Mining Bug (tm)
:cl:
fix: Runtime when non-mob atoms try to open doors
fix: Runtime caused by arguments being given incorrectly by flashbangs/stingbangs.
fix: Qdeleted items no longer runtime when thrown. They'll log to qdel_log instead.
fix: Qdeleted items no longer runtime when somehow taking damage. They'll log to qdel_log instead.
fix: Runtime in volumetric_box objects not having an item associated tot hem.
/:cl:
> Runtime fixenings

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Don't use /constructionlathe anymore.
:cl:
tweak: Removes /constructionlathe from maps.
/:cl:
> Yeets the Constructionlathe from Parhump

- code/datums/components/crafting/guncrafting.dm
advanced workbenches are super duper stationary.
Also certain other workbench-looking things also function as basic workbenches, like the machine workbench that did nothing.
> Advanced workbenches are no longer wrenchable

- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
- _maps/map_files/Pahrump-Sunset/RockSprings.dmm
re-adds bos spawns to redwater, moves bunker to dungeons.dm
:cl:
/:cl:
> re-adds the bos spawns to redwater. moves the bunker

- code/modules/jobs/job_types/bos.dm
- code/modules/jobs/jobs.dm
This replaces the system we were currently using to gatekeep the BoS with the proper code.
As it states. Please NEVER remove a job from its respective job-list unless it is the last and only solution, as if an admin decides to re-enable it midround, they will NOT show up beneath the faction, and other issues (like access to faction doors and/or gear) may occur.
For clarity sake, this only adjusts initiate slots up to 3, from 2 and that's because 4 people is _not nearly enough_ (that's if we have 1 scribe, 2 inits and 1 head-knight).
:cl:
fix: Fixes some broken code that would otherwise cause a LOT of problems if we added systems to the BoS that began to rely on their job/faction list.
tweak: Bumps initiate slots by 1.
/:cl:
> Fixes potentially admin-tool breaking code

- code/datums/mood_events/drug_events.dm
This is a simple change to Jet Inhalant mood so it isn't permanent.
:cl:
tweak: Modified settings to the Jet Inhalant mood.
balance: No longer permanent buff from jet.
/:cl:
> Jet Inhalant Mood fixed to not be permanent to people

- code/__DEFINES/economy.dm
- code/game/objects/items/storage/firstaid.dm
- code/modules/reagents/reagent_containers/hypospray.dm
- code/modules/vending/medical.dm
Removes hyposprays from medical vendors. Also tweaks prices on some medical items
:cl:
tweak: Normal medical vendors no longer contain hypo sprays
tweak: Hyposprays now have a default vendor price of 120 caps
tweak: Hypospray kits now have a default vendor price of 240 caps
tweak: Redwaters medical vendor now costs caps as opposed to being completely free, Though it's still cheaper then normal vendors for most items.
/:cl:
> Vendor Pricing and content pass

- code/datums/components/crafting/recipes/recipes_clothing.dm
- code/game/objects/items/storage/belt.dm
Allows heavy-duty sheath to actually fit and take the items listed in fitting_swords. Adjusts the volume of the twin sheath so that it can fit its respective swords. Both items now fit on the belt slot. New knife bandolier that fits on neck and can hold knifebelt_allowed items.
:cl:
fix: fixes heavy-duty sheath and twin sheath
add: adds knife bandolier
/:cl:
> Fixes heavy-duty sheath and twin sheath; adds knife bandolier

- code/game/objects/items/stacks/sheets/leather.dm
Adds gear harnesses to the list of items craftable with leather straps in hands. Part-time and/or forced nudity enthusiasts rejoice.
:cl:
add: Added gear harness recipe for leather straps
/:cl:
> Adds gear harness recipe for leather straps

- code/game/objects/items/melee/f13onehanded.dm
dragonfire katana: damage up by 15 for parity with high tier melee weps, can now parry.
:cl:
tweak: aye
/:cl:
> dragonfire katana buffs

- code/modules/fallout/obj/decor.dm
- code/modules/farming/farming_structures.dm
- code/modules/hydroponics/grown/cotton.dm
As it stands, decorative tattered rags are exactly as durable as solid steel doors. Bringing them down to the integrity level level of a standard glass window will ensure that a good swipe or two with a decent melee weapon will tear them down like the ruined scraps of cloth they are. Reclaimed raider buildings will be that much easier to clean up and renovate.
:cl:
tweak: Reduced decorative rag integrity from 300 to 25
/:cl:
> Nerf decorative rag durability

- code/modules/hydroponics/grown/corn.dm
Switches what you get when you grind corn, or juice it.
Because grinding corn to get corn oil, and juicing corn to get corn starch does not make sense. Aa
:cl:
/:cl:
> Sir, we do not grind our corn to get oil around these parts.

- code/__DEFINES/sound.dm
- code/controllers/subsystem/timer.dm
- code/datums/looping_sounds/_looping_sound.dm
- code/datums/looping_sounds/ambient_sounds.dm
- code/datums/looping_sounds/item_sounds.dm
- code/datums/looping_sounds/machinery_sounds.dm
- code/datums/looping_sounds/weather.dm
- code/game/area/Space_Station_13_areas.dm
- code/game/area/areas.dm
- code/game/area/areas/away_content.dm
- code/game/area/areas/ruins/space.dm
- code/modules/awaymissions/mission_code/moonoutpost19.dm
- code/modules/client/client_defines.dm
- code/modules/client/preferences_toggles.dm
- code/modules/fallout/areas/area.dm
- fortune13.dme
Adds in support for areas to use layerable sound loops as ambient effects! Doesn't actually add any, but that's where you come in!
TO MAKE A NEW AMBIENT SOUND LOOP:
Goto code\datums\looping_sounds\ambient_sounds.dm
make sure direct = TRUE
v- this is the most important part
mid_sounds = list(
SOUND_LOOP_ENTRY('sound/file.ogg', num SECONDS, pick weight), 
SOUND_LOOP_ENTRY('sound/file.ogg', num SECONDS, pick weight), 
SOUND_LOOP_ENTRY('sound/file.ogg', num SECONDS, pick weight), 
SOUND_LOOP_ENTRY('sound/file.ogg', num SECONDS, pick weight)
)
Works best if you make an ambient loop be just a bunch of similar sounds, like animal noises, or machinery stuff, cus we can layer them all together in the area!
To assign ambient sound loops to an area, add it to a list of type paths on the …
> Reworks ambient sound effects

- code/modules/mob/dead/new_player/new_player.dm
WHen he tries to join the game through the menu, it deadmins him so he doesnt have to hear anything about the skeleton war.
> Makes fenny autodeadmin

- code/modules/fallout/obj/trash_stack.dm
Removes the check preventing one from searching trash piles while in harm intent, mitigating the need to shuffle intents while scavenging especially when using fist weapons. The check has survived for years and serves no readily apparent purpose.
:cl:
tweak: Allowed searching garbage piles while in harm intent
/:cl:
> Allow scavenging trash while in harm intent

- code/controllers/subsystem/ticker.dm
- code/modules/mapping/map_config.dm
- code/modules/projectiles/guns/ballistic.dm
- code/modules/projectiles/guns/ballistic/pistol.dm
- config/game_options.txt
- modular_citadel/code/modules/client/loadout/__donator.dm
This PR fixes a bug, and includes a lore fix, and an enhancement
:cl:
fix: Fixed gun disallowed magazines lists. Now the M1911 and Sig P220 cannot use SOCOM magazines.
fix: Fixed the in game year, changed to 2222 to match lore.
add: Make in game time (almost) real world time. Requested by Fenin.
add: Updated my custom loadout to add a holster
/:cl:
> Various small fixes

- code/controllers/subsystem/ticker.dm
Fixes time tracking when the round starts late. Also fixes time zones.
:cl:
fix: fixed the round time deviating substantially from real time when the round doesn't start immediately
fix: fixed the in game timezone matching ET, now using a timezone offset to match CT
/:cl:
> Add timezone offset and closer time tracking

- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
This PR adds a firing range just south of the police station in RedRiver, presently occupied by everyone's favorite Renegades! Yayyy. 
Loot is comprised entirely of ballistics, most in the hobo-low tiers, with one low-mid and one mid spawn - in addition to a .44 variant spawn.
:cl:
add: Adds Firing Range to Red River.
tweak: Also fixes a blank tile in one of the nearby dungeons ;)
/:cl:
> Adds Firing Range to RedRiver

- code/__DEFINES/weather.dm
- code/controllers/subsystem/processing/weather.dm
- code/datums/weather/weather.dm
- code/datums/weather/weather_types/acid_rain.dm
- code/datums/weather/weather_types/ash_storm.dm
- code/datums/weather/weather_types/cold_wave.dm
- code/datums/weather/weather_types/floor_is_lava.dm
- code/datums/weather/weather_types/heat_wave.dm
- code/datums/weather/weather_types/radiation_storm.dm
- code/datums/weather/weather_types/rain.dm
- code/datums/weather/weather_types/snow_storm.dm
- code/game/area/Space_Station_13_areas.dm
- code/game/area/areas.dm
- code/game/objects/items/devices/scanners.dm
- code/game/objects/structures/ladders.dm
- code/modules/fallout/areas/area.dm
- fortune13.dme
Weather is now shared across all Z levels! No more wierdness where one map is having a sunny day and another is a raging shitstorm!
Weather is also a lot more configurable as to where it happens. Areas have a list of weather types that are allowed to affect them, so you can have some areas that are affected by just rain, some by just radstorms, or even have some weather effects even affect you inside areas that're otherwise protected! No more fuckery with area subtypes!
Weather warnings should be broadcast to all above-ground non-admeme Z levels. Now if a radstorm is coming, and you're not in the sewers, you'll know! No more surprise storms!
Also fixes radstorms doing fuck all. Seriously, it was checking rad resistance twice, and then delivering a tiny dose even before armor! I changed it …
> Fixes weather not working, like, at all

- code/modules/clothing/spacesuits/miscellaneous.dm
- code/modules/mining/lavaland/necropolis_chests.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
Changes up bubblegums loot. Replaces the heck suit with a fitting armor. Replaces the guardian creators with ichor. Replaces the mayhem in a bottle with holywater.
Said fitting armor also was adjusted to be medium armor with appropriate stats towards melee and ~~magic~~ energy lasers!
Loadout kit locked to lifeless ghoul.
Loadout kit locked to risingstar. (third one)
> Some changes + Loadout kits! (see description)

- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
If someone has more than 6 positive quirks saved and, say, someone makes another quirk positive, if it pushes them over 6, it resets the character's quirks when it loads.
> Prevents people having more than 6 positive quirks

- code/__DEFINES/mobs.dm
- code/datums/mood_events/generic_negative_events.dm
- code/datums/mood_events/generic_positive_events.dm
- code/datums/traits/negative.dm
- code/modules/client/preferences.dm
Increases the chance for depression to trigger from 5 to 15 and last for much longer.
Makes the moodlet for Depression & losing your Family Heirloom much more serious (may need balancing.)
Makes being jolly give you a lot more happiness for a lot longer.
:cl:
/:cl:
> Common Negative Quirk Rebalance (take 1)

- code/modules/projectiles/boxes_magazines/ammo_boxes.dm
The 14mm improvised bag had no sprite. Now it does.
:cl:
fix: fixed the lack of a sprite on a bag.
/:cl:
> Fixes 14mm Improvised Bag not having a sprite

- code/__DEFINES/traits.dm
- code/datums/traits/neutral.dm
- code/modules/mob/living/carbon/human/examine.dm
Yeah, it's just splurts in heat but worded down to be more straight forward and less.  Idk.  Raunchy.
Scalable with a few other concepts as well, definitely going to use it as a springboard.
For those who I know will be concerned about rampant horni, what this does is basically totally ignorable if you choose not to take either of the free neutral quirks.  It's totally obfuscated to those without them.  It just streamlines the process of two players looking for specific interactions to be able to know what they're about a bit swifter.
Credit to whoever over at splurt made it, only had to modify it a bit, also didn't port all of its features but we couldn't even use ALL of them anyway so who gives a shnart.
:cl:
tweak: …
> Naughty Time Roleplay Quirks

- code/__DEFINES/traits.dm
- code/controllers/subsystem/processing/quirks.dm
- code/datums/components/chasm.dm
- code/datums/traits/good.dm
- code/datums/traits/negative.dm
- code/game/objects/structures.dm
- code/modules/mob/living/carbon/human/human_movement.dm
- code/modules/mob/living/living.dm
- code/modules/mob/living/living_movement.dm
Freerunning - Can now go over tables MUCH faster, and fall from one z level up FAIRLY safely.  Not more than that tho.  Go jump off the Followers roof and find out.
Hard Yards -> Mobility - Wasteland Trekker (Unchanged mechanically)
Remember that Hard Yards, and these derivatives only effect off-roading speed.
Added Positive Traits
Mobility - Wasteland Wanderer (Slower than Hard Yards, faster than normal)
Added Negative Traits
Mobility - Wasteland Slug (Slower than normal running, without hard yards)
Mobility - Wasteland Molasses (even SLOWER than slug when off roading)
:cl:
sounddel: removed an old sound …
> Mobility Quirk Overhaul

- code/modules/jobs/job_types/wasteland.dm
Replaces the ID for the Vaultie Wasteland role to a customizable ID.
:cl:
tweak: Changed the Vaultie ID.
/:cl:
> Gives Vaulties a customizable ID.

- code/__DEFINES/traits.dm
- code/controllers/subsystem/traumas.dm
- code/datums/brain_damage/phobia.dm
- code/datums/traits/negative.dm
- strings/phobia.json
I hate phobias.
Now we have like 8 of them.
Phobias include negatives quirks suchs as
Being afraid of spiders
Being afraid of skeletons
Being afraid of masked strangers
Being afraid of doctors
Being afraid of things happening to your eyes
Being afraid of cats
Also renames the light and dark 'phobias' to be in line with being afraid of them as well.
Also also unratfucks traumas.dm
:cl:
config: changed some …
> Phobia Overhaul

- code/modules/projectiles/ammunition/_ammunition.dm
- code/modules/projectiles/boxes_magazines/_box_magazine.dm
- code/modules/projectiles/guns/ballistic.dm
- code/modules/projectiles/guns/ballistic/revolver.dm
- code/modules/reagents/chemistry/machinery/chem_master.dm
when you click on a revolver, it dumps out the empty casings. click it again to empty the rest.
you can load empty casings into a revolver that isnt full of casings without it kicking out other casings. if the revolver is full, it'll still kick out an empty casing.
rewords a legion reference in chemmasters.
> Revolvers can eject empties with a click

- code/datums/wounds/bleed.dm
So fun fact, you need to apply a max level fracture and a max level bleed to roll severing. I broke the bleed part, so I fixed it. Cannibals, rejoice.
> Makes wounds sever limbs properly

- code/__DEFINES/combat.dm
- code/datums/components/pellet_cloud.dm
- code/modules/projectiles/ammunition/_firing.dm
Shotguns are no longer unusably shit, and have generally tighter spreads more in line with what I *assume* was intended.
Disabled the exponential bit of recoil spread calculation, to see if there's any real difference.
> Shotgun fixes and recoil tweaks

- code/modules/mob/living/carbon/human/life.dm
Maybe prevents a runtime when humans without DNA breathe?
> Maybe fixes integs?

- code/modules/mob/living/emote.dm
Adds emote parameters to
*blush
*burp
*choke
*cross
*chuckle
*cough
*drool
*frown
*gasps
*grins
*giggle
*groan
*grimace
*laugh
*chitter
*pout
*scowl
*shake
*shiver
*sigh
*sit
*smile
*sneeze
*smug
*sniff
*stretch
*tremble
*wave
*wsmile
*yawn
*slap
These are the the system that *kiss uses to target what you're blowing a kiss at. Try them out, saves a few seconds of time from writing out the emote long hand, mostly just quality of life.
Also muted choking for now due to upset tummy complaints from some players.  Understandable, I suppose.
Adds Emotes, with params
*hearthand, you make a heart with your hands.
*ok, you make an okay sign.
*thumbsup & *thumbsdown, self explanatory.
:cl:
balance: …
> More Emotes Take 2

- code/modules/fallout/reagents/other_reagents.dm
Punga juice is now unobtainable. Let's switch from requiring punga juice to prickly pear pink pulque instead. That way there's a reason to cultivate prickly pear fruit for that pleasant American Southwest flavor and the most nourishing compost can be a soothing pink color instead of radioactive green.
:cl:
fix: Fixed alacritous compost recipe. Punga juice -> pink pulque
/:cl:
> Fix alacritous compost recipe

- code/modules/client/verbs/ooc.dm
Idk why it wasn't like this
Removes the player from seeing the admin's ingame character. I must have smoothbrained it.
> Hides ingame chars for admins

- code/__DEFINES/ammo.dm
- code/__DEFINES/combat.dm
- code/modules/mob/living/damage_procs.dm
- code/modules/projectiles/ammunition/_ammunition.dm
- code/modules/projectiles/ammunition/ballistic/pistol.dm
- code/modules/projectiles/ammunition/ballistic/revolver.dm
- code/modules/projectiles/ammunition/ballistic/rifle.dm
- code/modules/projectiles/ammunition/ballistic/shotgun.dm
- code/modules/projectiles/ammunition/ballistic/smg.dm
- code/modules/projectiles/ammunition/ballistic/sniper.dm
- code/modules/projectiles/ammunition/caseless/ballistic.dm
- code/modules/projectiles/boxes_magazines/external/pistol.dm
- code/modules/projectiles/boxes_magazines/external/rifle.dm
- code/modules/projectiles/boxes_magazines/internal/revolver.dm
- code/modules/projectiles/boxes_magazines/internal/shotgun.dm
- code/modules/projectiles/gun.dm
- code/modules/projectiles/guns/hoboguns.dm
Zipgun no longer can have its magazine caliber changed. Instead, it supports multiple casings by default.
Autopipe can take a few more calibers.
Piperifle and rebored can be made to take 40mm grenades.
Knucklegun and knifegun can take a few different calibers.
Shotgun bat can also accept .50MG.
Scaled misfire damage and chance to how much heavier the casing is compared to what it normally shoots. So, smaller than the casing it comes with will never misfire, and bigger will misfire a lot more.
Misfire damage is lessened by armor. It does melee damage.
> Hobogun changes

- code/datums/traits/good.dm
- code/game/objects/hand_items.dm
- code/game/objects/items/stacks/medical.dm
- code/modules/fallout/areas/area.dm
- code/modules/surgery/organs/tongue.dm
Lickhealing is faster, and loops for the damage healing stuff.
Adds support for medical items playing a sound when starting and ending use.
Removes music from the bar, pending moving it to the jukebox.
> Makes lickhealing better

- code/_globalvars/lists/mapping.dm
- code/datums/weather/weather_types/acid_rain.dm
- code/datums/weather/weather_types/ash_storm.dm
- code/datums/weather/weather_types/cold_wave.dm
- code/datums/weather/weather_types/heat_wave.dm
- code/datums/weather/weather_types/radiation_storm.dm
- code/datums/weather/weather_types/rain.dm
- code/modules/fallout/areas/area.dm
Listen, I get why ruins had weather in them but we haven't been using them that way -at all-.  This adjusts them to work the way we expect them to.
:cl:
/:cl:
> Ruins weather

- code/modules/admin/admin_verbs.dm
- fortune13.dme
Almost crashed the server. For some reason decided to toss an admins physical body into the null zone, chugging the server. This removal was requested by the host for its broken nature.
> Removes Possess from admin verbs

- code/modules/jobs/job_types/tribals.dm
This is just to give Druid's their surgery and primative tech traits as well as giving the Druid and Shaman their Spiritual Traits.
:cl:
balance: Gave back druids and shamans some roundstart traits back.
/:cl:
> Re-adds Druid's and Shaman's roundstart traits.

- code/modules/fallout/obj/structures/obstacle.dm
Adds the ability to deconstruct otherwise invincible and immutable junk decals with wrenches. You know, the rusty sinks and toilets in dilapidated buildings.
Also replaces the proc for deconstructing barbed wire but that's all under the hood.
:cl:
add: Adds proc to deconstruct junk decals with wrenches
fix: Fixes barbed wire deconstruction proc
/:cl:
> Junk deconstruction

- code/modules/smithing/anvil.dm
This is just a simple change to make the throwing spear and lance recipes not overlap.
I made this to hopefully resolve the overlapping recipe between the throwing spear and lance. This is literally my first ever PR and I'm just winging it. I changed one line of forging, so hopefully it does not require a local test.
:cl:
tweak: Changed the lance recipe to make it actually produceable.
/:cl:
> Fixes an overlapping recipe on anvils

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Fixes an errant desert tile under the upper Heaven's Night
Gives the Tribal Chief a lockable door as well as a key and lock.
More minor map fixes
:cl:
tweak: Fixed some map issues and gave the tribal Chief a lockable door with key and lock.
/:cl:
> Minor fixes and additions to Nash and the tribal camp

- modular_coyote/code/game/objects/structures/sacredwell.dm
I added a few items to the sacred well list, namely bows, the stormdrum and some regular tribal outfits. So they don't geep getting the same three items over and over.
I was sick of seeing the tribals constantly get the same three items over and over. I decided to change that, I added two tribal armours (One medium, one heavy.), Three bows and a ballistic weapon in the form of the stormdrum. (Considering tribal wastelanders can just spawn with one with the right loadout, I see no harm in them getting something.)
:cl:
add: Added new things; Three bows, one SMG and two armours.
/:cl:
> New tribal items added to Sacred well.

- config/game_options.txt
Simple change to disable the race Synthetic in the character menu. This DOES NOT affect the Synthetic Lizardperson race, nor does it affect or remove any underlying code for the Synthetics.
The race 'Synthetic' is currently totally broken with invisible sprites, no Species Markings, disabled genitals, etc. This simply removes the broken race as a QOL patchfix until such time in the future as the race's code issues get actually addressed.
:cl:
config: Disables Synthetic race in Setup Character menu's Species Selection list.
/:cl:
> Removes broken synth race

- code/game/objects/items/storage/belt.dm
This should hopefully make it so that gardening tools can once again be stored in the gardening belt, it seemed to have lost it's utility storage datum.
:cl:
fix: hopefully fixed the gardening belt's storage abilities.
/:cl:
> Gardenbelt fix

- code/modules/food_and_drinks/recipes/tablecraft/recipes_wastefood.dm
Certain foods required for recipes are very limited in supply, due to vendors being awkward to get to or only having five or so of each supply. However, why would a wastelander even go scouring the world for macaroni cheese boxes when they can literally make their own... I set out to resolve this by adding a few recipes.
Imitation BlamCo! Mac and Cheese.
Imitation Saddle-Up Salisbury Steaks.
Imitation Cram.
Imitation Pork and beans.
They're so good, they're indistinguishible from the real thing... (p.s. it totally creates the real thing, I didn't want to make entirely new items for no real reason.)
:cl:
add: Added new ways to get some pre-war foods.
/:cl:
> Pre-war Imitation foods

- code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
- code/modules/projectiles/guns/ballistic/rifle.dm
- code/modules/projectiles/guns/ballistic/shotgun.dm
I love my tribe and wanted to make it feel less... restrictive, everything usually ended up in the well and there was little interaction with the town's merchant. Now, tribals can sanctify a handful of guns to use themselves, meaning they will buy them and potentially the ammunition. The list is; Lever action shotgun, cowboy repeater, trailcarbine, brushgun and .308 repeater. (See the pattern here?)
Edit: Okay, Fixed capitalization errors, should be good.
:cl:
add: Added access to the five gunsprites I added earlier.
/:cl:
> Tribal guns, access and crafting.

- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
- _maps/map_files/Pahrump-Sunset/RockSprings.dmm
- code/controllers/subsystem/research.dm
- code/controllers/subsystem/traumas.dm
- code/datums/components/crafting/recipes/recipes_medicine.dm
- code/datums/components/crafting/recipes/recipes_misc.dm
- code/datums/components/crafting/recipes/recipes_robot.dm
- code/game/objects/effects/spawners/lootdrop.dm
- code/modules/crafting/items.dm
- code/modules/jobs/job_types/followers.dm
- code/modules/jobs/job_types/oasis.dm
- code/modules/research/designs/medical_designs.dm
- code/modules/research/designs/stock_parts_designs.dm
- code/modules/research/designs/tool_designs.dm
- code/modules/research/techweb/nodes/alien_nodes.dm
- code/modules/research/techweb/nodes/bluespace_nodes.dm
- code/modules/research/techweb/nodes/computer_hud_nodes.dm
- code/modules/research/techweb/nodes/engineering_nodes.dm
- code/modules/research/techweb/nodes/medical_nodes.dm
- code/modules/research/techweb/nodes/misc_nodes.dm
- code/modules/research/techweb/nodes/tools_nodes.dm
Removed most of the high tier research stuff that can be printed. (Can't be printed from the lathe anymore)
Removed medihuds from the kits. (Reason being they both show mobs health and remove the main point of a certain quirk and health analyzers. That being checking health.)
All clinic workers get tier 3 parts recipes.
Scientists get low level implant recipes.
Nerfed research notes points amount by half. (Putting emphasis on rationing more.)
Nerfed most of the Senior doctors stuff. You can get the pre war chem master in dungeons anyway, and that arm medbeam gun is too strong.
Put the tier 4 parts in dungeons along with a good portion of the good quality implants.
Changed up the spawn texts of the town doctors. They never were changed to not reference the followers anymore. While they can …
> Clinic workings and research change up!

- code/game/objects/items/toys.dm
Due to pre-war regulations recently uncovered, Tragic the Garnering tournaments now limit deck sizes. It's a bonus, because now they fit in your pockets, pouches and bags. Those with treasured family decks can now rejoice.
:cl:
tweak: tweaked the weight class of TtG decks.
/:cl:
> Reduces the size of TtG decks

- code/modules/reagents/chemistry/machinery/chem_cartridge.dm
It's come time for me to do what I said I was going to do in #873
Chem Cartridges are having their reagent values nerfed. Now that players have had time to get used to how they work it's now time to make them a more significant factor in game. Over the three months or so this mechanic has existed doctors have had no trouble continuing to stockpile medicine and even the cartridges themselves.
Actual value changes. (For a un-upgraded chem dispenser.)
Ancient Cartridges (Old crusty red) 200 Units.. (Value Unchanged.)
Knock-Off Cartridges (Blue): 800 Units -> 400 Units.
Improvised Cartridges (Brown Crafted):1200 Units ->600 Units.
Pristine Cartridges (Vibrant Red): 1600 Units -> 800 Units.
:cl:
tweak: Chemical Cartridges have had their charge amounts halved.
/:cl:
> Tuning cartridge values

- code/modules/mob/living/simple_animal/simple_animal.dm
- code/modules/mob/mob.dm
- modular_coyote/code/mob.dm
Catslugs no longer runtime when they ask for help.
Ghosts cant hop into mobs that have a ghost in them.
> Catslugs dont runtime as much, also blocks ghosts from inhabiting inhabited mobs

- code/game/objects/items/cards_ids.dm
- code/modules/jobs/job_types/oasis.dm
Any newly elected mayor should get the /obj/item/card/id/captains_spare in their loadout box.
Manage job slots is the admin verb for adding a mayor slot for the elected mayor!
> Changes up the Captains spare, and Removes Mayor slots (able to still be admin added)

- code/modules/hydroponics/grown/buffalogourd.dm
- code/modules/hydroponics/grown/horsenettle.dm
- code/modules/hydroponics/grown/pinyon.dm
This PR fixes the typos in gourd, horsenettle and pinyon nut.
Gourd and horsenettle fixes the reagent typos and pinyon nuts is the description of seed and plant alike.
:cl:
fix: typos in gourd, horsenettle and pinyon nut.
/:cl:
> Fixes in wasteland plants

- code/modules/cargo/exports/misc_export.dm
I noticed we could make bottle presses, seal booze and then it was worthless. I felt this was kinda irksome, considering in a wasteland, I wouldn't mind a drink now and then... So I've given booze export value. So you could use it as trade fodder, if you don't want to go and farm caps or aren't capable.
There's two bands; Cheap liquour (worth about 10-12 caps) and Classy liquour (worth about 25-30).
Cheap is your usual, easy to brew suspects like beer, whiskey, wine and the kin, Classy is harder to obtain things like champagne, goldschlager and nukashine.
Now the doctors don't need to salvage every car in the area to be able to afford fancy tools, they can brew beer in their downtime. Which is something that they would do, since grain alcohol is an antiseptic.
:cl:
add: Added export value …
> Booze exports!

- modular_coyote/code/mob.dm
Should work.
Makes it so the cute eevee mobs nuzzle and get pet instead of poked or attack others.
:cl:
fix: fixed verbs for eevees
/:cl:
> Adds proper verbs to the base mob for Eevees

- code/__DEFINES/traits.dm
- code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
- code/datums/traits/good.dm
- modular_coyote/eris/code/mods/_upgrades.dm
Weaponsmithing is... useless, annoyingly useless. A 2 point trait which can be outpaced by five minutes of searching junk piles inside Nash. It serves next to no true mechanical purpose besides flavors. My hope with these changes is to give it a reason to exist and maybe encourage more crafter types then everyone rushing speed + HP + damage.
:cl:
-Added a trait_weaponsmith define
-Added said define to the weaponsmith trait.
-Fixed an issue with hunting rifles being given twice by the weapon smith trait, corrected to hunting shotgun. 
-Commented out advanced explosive crafting since everything iit did was done by regular explosives crafting, giving it no purpose.
-Fixed a missing descriptor to technophreak so it details that it gives T3 machine part recipes.
-Added a wide selection of …
> Improved Weaponsmith + Fixes

- code/modules/hydroponics/grown/towercap.dm
When originally designing smoke signals, I was worried that they might be just a little too close to radio to give to tribals. I may have been a little hasty for balance, though, because in their current state it is very difficult to tell if a signal is being sent unless you are, by happenstance, outside at the time.
I figure preventing people from seeing the signal while underground, but giving them the ability to see while indoors (windows generally exist in Nash!) is a good halfway point.
If someone else could do me the favor of testing this quickly locally, I'd appreciate it - I've run into the updated-byond-client issue from before and am too split between servers at the moment to downgrade for testing.
:cl:
tweak: Smoke signals can be seen from anywhere except underground. You can …
> Tweaks Smoke Signals To Be Seen Indoors

- code/modules/clothing/under/f13.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
- modular_citadel/code/modules/client/loadout/kits.dm
Loincloths have a chest wrap, and should now cover ur boobs when the wrap is on. Also modifies custom loadout boxes to be normal sized, and made Jade's BE box hold a possible number of boobie bottles.
> loincloths hide boobs when toggled

- code/_onclick/drag_drop.dm
- code/modules/admin/admin_verbs.dm
With harm intent on, when you click, when you mouse-up, it clicks there. Simple as.
Comes with an admin killswitch in case it fucks everything up.
> Harm intend disables clickdragging

- code/modules/paperwork/pen.dm
Ports the ability to universally rename items with a pen by alt-clicking it from other versions of fallout 13 (In this particular instance, atom bomb.)
This should be a boon to RP, letting players customize their gear and do counterfeit shenanigans—the clear next step in the Stanford prison experiment that is Nash. 
:cl:
balance: rebalanced the pen
/:cl:
> Renaming Pens

- code/modules/projectiles/boxes_magazines/internal/revolver.dm
improvised762 was made into improvised308
improvised762/Initialize() was not made into improvised308/Initialize()
This caused the code that handled winchester reboring to do nothing, since it was attributed to a magazine type that no longer exists
1 line fix, not even that, a 3 letter fix
:cl:
fix: improvised762 is no more
/:cl:
> beeg thicc changes hotfix (reboring no longer broke)

- code/datums/components/crafting/recipes/recipes_primal.dm
No longer are the days of crafting blunt arrows as mid-air projectiles.
that's it
that's the whole thing.
You couldn't load them, the item was just broken since it wasn't an item at all, but the projectile held in your hand.
:cl:
fix: blunthead arrows.
/:cl:
> fixes blunt arrow crafting

- code/game/machinery/Sleeper.dm
Only one extra chemical per tier, and no straight healing chems putting more emphasis on chemistry stock.
> Autodocs the nerfening

- code/__DEFINES/mobs.dm
- code/_globalvars/lists/maintenance_loot.dm
- code/game/objects/effects/spawners/f13lootdrop.dm
- code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
- code/modules/mob/living/simple_animal/hostile/f13/raider.dm
- code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
Co-authored-by: Superlagg should make raiders, ghouls, and gelatinous cubes drop variable amounts of trash.
adds psycho to drug spawns, adds drug spawns to trash
:cl:
/:cl:
> HOPEFULLY WORKS

- code/game/objects/effects/spawners/f13lootdrop.dm
- code/game/objects/items/arrow_crafting.dm
- code/game/objects/items/stacks/sheets/sheet_types.dm
- code/game/objects/items/stacks/stack.dm
- code/modules/jobs/job_types/legion.dm
- code/modules/projectiles/ammunition/caseless/rocket.dm
- code/modules/projectiles/boxes_magazines/external/lmg.dm
- code/modules/projectiles/boxes_magazines/external/rifle.dm
- code/modules/research/designs/ammolathe_designs.dm
- modular_citadel/code/modules/projectiles/guns/ballistic/rifles.dm
Stacks can now spawn multiple things, in addition to stacks with stuff in them. Only really applies to arrow shafts right now.
Arrowheads should no longer mess with the CI.
Arrow shafts no longer need hay to make arrows.
Makes rockets visible.
> Stack tweaks and arrowhead fix

- code/datums/martial/rising_bass.dm
- code/game/objects/items/loadout_beacons.dm
The current listings are Sleeping Carp and Rising Bass.
Makes rising bass have 8 stamina cost in its dodge instead of sleeping carps 6 stamina cost. Reason being is rising bass is always active and pretty beefy in quality comparitivaley. That and sleeping has to have a specific action toggled to deflect.
> Martial Arts in Loadout roundstart!

- code/__DEFINES/dcs/signals.dm
- code/__HELPERS/unsorted.dm
- code/controllers/subsystem/radiation.dm
- code/controllers/subsystem/radturf.dm
- code/datums/components/radiation_turf.dm
- code/datums/weakrefs.dm
- code/game/objects/items/devices/geiger_counter.dm
- code/modules/admin/admin_verbs.dm
- code/modules/fallout/obj/decals.dm
- code/modules/power/singularity/collector.dm
- fortune13.dme
Radpuddles now assign a component to all the turfs it can see. Those components register their coordinates to SSradiation, and listens for anyone who enters the tile. On entry, they're added to a list, that SSradiation blasts with rad until they leave the tile.
Saves a fuckload of performance over spamming view checks, maybe.
> Reworks radpuddles into a low-impact mess

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Fixes a hole in the bank.
Fixes the Oasis being named the Heaven's Night on its doors.
:cl:
tweak: Changed names on a few doors in the Oasis
fix: Fixed a hole in the bank
/:cl:
> Minor Fixes to Nash

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Fixes a handful of issues, particularly
pile of radioactive waste was actually a pile of radioactive waste and not a decal, whoops
the junk gun spawners on the gun locker wouldn't go inside, left the gun locker for just the police revolvers and a handful of static junk spawns, left the junkgun spawners in their own locker. (Moved the radio locker to a crate in the upstairs)
Added a puddle, a rainwater collector and a sink to the cow-khamp (camp)
Added some clothing to the "dorms"
Added drinking glasses and a beer keg to the downstairs
Messed with the surgical crate so it's closeable (pixelshifted a bit up) and items can be thrown inside (no density)
Gave the oven 2 whole wood planks and a matchbox, zamn
poster spawner wouldn't pixelshift, leaving posters on the floor. Just stuck up some …
> Cowgang hotfix 2 electric boogaloo

- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/guns/energy/plasmaf13.dm
Once upon a time, all the pistols were given normal size, with concealable given small, life was in harmony.
Then one day, the contributors attacked, making all the pistols small- no longer would a lever action shotgun or folding stock m1 carbine take the same space as an m1911.
One class of weapon- hidden away in laser.dm and plasmaf13.dm, remained untouched, unloved, left with it's bulky weight.
No more.
Laser RCW's practically a las-uzi despite being described as an autopistol, it's staying normal size, same with the recharger pistol (solar scorcher's unique, it can be small tho) 🤓
:cl:
/:cl:
> Smallerizes the laser pistols

- code/modules/mob/living/simple_animal/hostile/f13/insects.dm
ye ye, I personally think they are a small creature enough to be friendly, makes it so you only have to worry about raiders and ghouls and many other creatures other than the ones close to nash.
> Makes bloatflies part of the beastfriendly perk

- code/modules/jobs/job_types/tribals.dm
- code/modules/jobs/job_types/wasteland.dm
- code/modules/mob/living/simple_animal/friendly/farm_animals.dm
Adds ability for Far-lands and normal tribals to get the mount kit!
Farlands can get it in the Farlands Mounted Warrior kit, and Sulphur Bottomites get it as Hunters
:cl:
/:cl:
> Mounts Pt 1a

- code/modules/cargo/exports/materials.dm
- code/modules/cargo/packs/misc.dm
Changing caps to be 1:10 Caps:Credits so that you can actually use caps in the train to buy things and sell things at reasonable rates.
Also fixes turning Credits into Caps so you're not longer doing that at a MASSIVE loss.
Pretty much the above. Just trying to hotfix cargo to be less of an utter mess and at least nominally viable.
:cl:
balance: Changed caps to have a Credit value of 10 per cap.
fix: Fixed the ordering of caps (converting credits to caps) to match the new value of caps so you're breaking even instead of trading at a loss.
/:cl:
> Credits and Caps Hotfix

- code/modules/cargo/exports/materials.dm
- code/modules/cargo/exports/misc_export.dm
- code/modules/cargo/packs/security.dm
Some changes done to make it so players can actually make a profit going out and doing things and selling crap to the shop, including trash guns.
Gonna need some watching, though, to make sure this doesn't break the economy. I'm kind of afraid to touch raw mats to be perfectly honest.
Basically what it says above. Shorthand to check for how many caps each thing is worth is to divide by ten. So an export value of 750 is 75 caps. It's expected traders will buy things from people at ~1/2 its value. Guns might legitimately sell for a little too much, though cargo depreciation keeps that from being an exploit at least.
Might need to go back and lower gun credit values to be lower depending on how things play out. But it just seems weird to sell a BAR or Sniper Rifle for less than a hundred …
> More Cargo Hotfixes

- code/modules/mob/living/carbon/emote.dm
Basically you can't spam the rocks/bricks, they still do the same damage without the trait, but the more you spam it the less damage it deals.
It takes all your stamina in order to take someone into crit with rocks.
With bricks you just have to have a quick breather before finishing them with one.
Real world performance will vary, however the variable is adjustable for the future. I found 2.2 to be the most... reasonable damage output when spammed.
> nerfs rocks + bricks to require all your stamina to put 'em to crit

- code/game/objects/items/loadout_toolkits.dm
Adds a merchant toolkit, bringing back the vending machine box from the old wastelander merchant loadout (contains every component for 1 (one) custom vending machine) and 75 caps, almost half of what you can get with the sellout loadout (200)
:cl:
/:cl:
> Adds merchant kit to worker tools

- code/modules/smithing/anvil.dm
- code/modules/smithing/finished_items.dm
As it says on the tin, All Smithing sounds reduced by about 30%.
:cl:
tweak: tweaked Smithing Sounds
/:cl:
> Reduces Smithing Sounds by a third

- code/datums/brain_damage/hypnosis.dm
- code/datums/traits/good.dm
- code/datums/traits/negative.dm
- code/game/machinery/firealarm.dm
- code/game/machinery/shieldgen.dm
- code/game/mecha/mecha_defense.dm
- code/game/objects/effects/effects.dm
- code/game/objects/items/devices/forcefieldprojector.dm
- code/game/objects/structures/fireaxe.dm
- code/game/objects/structures/grille.dm
- code/modules/antagonists/blob/blob/theblob.dm
- code/modules/antagonists/clockcult/clock_structures/ark_of_the_clockwork_justicar.dm
- code/modules/client/client_procs.dm
- code/modules/fallout/obj/trash_stack.dm
- code/modules/mob/living/carbon/alien/special/facehugger.dm
- code/modules/newscaster/newscaster_machine.dm
- code/modules/reagents/chemistry/reagents/food_reagents.dm
- code/modules/vending/brahminvendordm.dm
- strings/wounds/bone_scar_desc.json
Couldn't find the issue with the ladder so I thought I'd poke at some of the runtimes we have happening on the server.
So far the fixes:
- Sometimes canbrew reagents lack a holder. So I added a sanity check there. (reagents.dm)
- Some objects which are spawned from trash lack the variable to indicate it's from trash, sanity added (trash_stack.dm)
- Grilles and some other structures havent had their take_damage params up to date, leading to runtimes with running checking armor damage. (Whole bunch of .dms)
- Brahmin vendor tries to invoke a proc which doesn't exist globally, so I scoped it to src. (brahminvendordm.dm)
- Something about trying to delete a tongue on a mob when they are deleted, some reason they delete faster than the quirk, so we just check if the mob is deleted. (good.dm)
- …
> Fixes a bunch of runtimes

- code/game/objects/items/devices/flashlight.dm
- code/modules/WVM/wvm.dm
- code/modules/cargo/exports/materials.dm
- modular_citadel/code/modules/client/loadout/uniform.dm
Touched a few files to touch up the infini-vendors, added a few loadout items both for practice and because there's no reason for them to not be there, and lastly """fixed""" a bug with exporting certain things.
I mean, it wasn't even a bug. It was just a stupid text line that didn't check if there was any descriptor at all. Just a stupid generic line that applied if you didn't have message = "sample text" even though there's TWO KINDS OF DESCRIPTOR FUNCTIONS THAT WORK.
my brain hurts
:cl:
Wasteland Vendors: Added seclites, lanterns, welding tools, power tools, and welding goggles. Power tools are expensive enough you can't rush them, but they're mostly a luxury item anyway. Need to see how this works out and if it's alright, make the power tool order in cargo cheaper.
Seclite/Lanterns: …
> Bunch of general adjustments and things added

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Fixes an incorrectly placed mob (mistook gutsies for normal handies, whoops)
fixes all the skeleton mobspawns on the map, since some idiot (yours truly) mistook them for normal human remains. Might make the skeleton race choosable tho, people seem to be having fun with it.
Gives the convenience store a vendotron, he just vibes, he chill :3
Replaces some tent doors in hobotown with normal, blocky tent doors. Look ugly, but you can't lock the cool looking ones.
:cl:
/:cl:
> Halloween over go on home

- code/game/objects/items/loadout_beacons.dm
- code/modules/projectiles/ammunition/energy/laser.dm
- code/modules/projectiles/guns/energy/laser.dm
Adds the worn AEP-7
wattz 1k has 15 shots at 30 damage for a total of 450 damage per standard cell
aep7 has 30 shots at 24 damage for 720 damage per cell
worn aep gets 20 shots at 24 damage (480/cell) but a faster fire rate compared to the wattz 1k
it's drippy
bulky big gun
laser brick
:cl:
/:cl:
> big laser iron on his hip

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- code/datums/traits/negative.dm
- modular_citadel/code/modules/client/loadout/mask.dm
Due to unforseen consequences, it has appeared that masked mook is calling the wrong type of gas mask. I'm not adding additional clothing items here to be considered a gas mask as I added it to the loadout, aka, WYCI >:)
Needs to be tested and verified in a bit.
:cl:
fix: The funny perk.
add: loadout gas mask item
/:cl:
> Mask Mook fix & Loadout Item for LARP

- code/__DEFINES/traits.dm
- code/datums/traits/good.dm
- code/modules/mob/living/emote.dm
Adds 'Class Act', a 1-point trait that gives the user 10u ghoul powder on *deathgasp
Ghoul powder slows the user down considerably while also making them appear dead on examine, health hud, and health analyzer. (Though it doesn't fake the damage for it, so you can shoot someone, 'kill them', then look at them funny with your health anal-yzer says they died with only 20 damage)
Yes you could spam it to have it naturally since it lacks overdose, why would you? It's slow as shit and gives you no benefits against mobs, nor any against players if you're, you know, standing.
:cl:
add: Added new trait
/:cl:
> 'Class Act' trait (deathgasp buff?????)

- code/datums/traits/negative.dm
Makes the deaf trait pickable, why wasn't this a thing already? Trait_deaf already existed???
:cl:
/:cl:
> Deafens the wasteland

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
The following PR was made in order to combat cheesing from encounters involving Raiders and Deathclaws. Dclaws have the ability to destroy steel walls which can be used to grief other players AND mob skip extensively. The PR was made to fix that. In the area featured here: 
You will notice that Dclaw nests NEED to be cleared, as they will respond endlessly, and players are encouraged to work TOGETHER with this one.
4 extra puddles of goo were added to combat campers and make them prepare for this """bunker,"" and an additional weapon spawn was added to accommodate the spike in difficulty.
Also, mobs were fighting each other, making the bunker easier. I've since fixed that.
:cl:
balance: The bunker.
add: adds indestructible wall tiles to prevent grief.
/:cl:
> Dclaw bunker fix mine shaft

- code/datums/components/crafting/recipes/recipes_misc.dm
- code/datums/traits/good.dm
- code/modules/clothing/head/f13head.dm
- code/modules/clothing/suits/arfsuits.dm
Adds refurbished T45b (cheaper to make but requires salvaged T45 in the first place) and powered scrap PA (expensive, but can be made from just components and materials) to the technophreak trait.
These armors are no better then salvaged PA armor-wise. However, at the cost of all the downsides of PA (power management, the skill requirement, EMP vulnerability), you get the benefits of PA (stunimmune, recoil reduction, etc).
pa goes clunk clunk, who's to say the dungeon rushers get to have all the fun? Now normal players can use the PA trait as a generic heavy armor trait, with low tier garbage PA.
:cl:
/:cl:
> Proletarian Power Armor

- code/datums/materials/basemats.dm
- code/game/objects/items/stacks/sheets/mineral.dm
- code/modules/smithing/anvil.dm
- code/modules/smithing/finished_items.dm
- code/modules/smithing/smithed_items.dm
Ho boy, Here we go. Time for the big Smithing Revamp.
Things changed so far:
1. BUFFS all Materials to 1.15 modifier for more damage.
2. Does some more comments on the Anvil.
3. Gives the Waki a better force modifier.
4. Reduces the ingot light range and power.
:cl:
balance: buffs smithing weapon damage.
/:cl:
> Smithing Buff.

- code/modules/clothing/head/helmet.dm
- code/modules/clothing/suits/arfsuits.dm
- modular_citadel/code/modules/client/loadout/head.dm
- modular_citadel/code/modules/client/loadout/suit.dm
Changes light security vest and helm to be usable in loadout again (No job restrictions), and renames them to be a Vault-Sec armor set.
:cl:
edited loadout to remove job restrictions from light security head and vest to allow usage for loadouts again.
renamed the light security helm and vest to 'Vault-Tec security helmet' and 'Vault-Sec vest', respectively. 
/:cl:
> Light sec loadout change

- code/datums/traits/good.dm
goodbye rad immune for you non bots/ghouls
:cl:
Rad Immune is no longer selectable in the Trait menu.
The other two Rad Resist traits now explain exactly how much you're getting. Because people keep whining about that despite being confused when anyone explains how armor works to them. Seriously, percents aren't that hard people. You are literally complaining about it using a calculator.
:cl:
> Trait menu Rad Tweaks (good to go)

- code/game/objects/items/melee/f13onehanded.dm
- code/modules/cargo/exports/misc_export.dm
adds stuff I forgot earlier and updates knife toolspeeds after having tested it a bunch in game
:cl:
- salvage added to cargo exports so they can just directly sell it. When WVM buyer gets nibbled, gonna have it so you can sell salvage there too without cargo at worse prices. Good test for that.
- adjusted knife toolspeeds after having tested that for a week-ish. Higher speeds should make it much easier to skin critters before they explode
- adjusted descriptions to better reflect each knife's role (hunting knife = basic moneymaker, Bowie = middleground of combat and tool, survival knife = upgraded hunting knife)
:cl:
> toolspeed and sale stuff (should be good to merge)

- code/modules/WVM/wmv_buyer.dm
- code/modules/cargo/exports/misc_export.dm
Down with communism, one cap at a time. Part 2 will be done after the vendor is actually placed on the map so I can see how the prices work out and so I can test adding things like gunpowder and wood to the saleable list. Also, I need to chew on dan for what item is the dynamic research point blueprint.
:cl:
- Teeny cargo fix
- Big ol change to the wasteland buying vendor to bring it in line with the Bayou's available loot and such
:cl:
> Death of the commie pile, part 1 (should be good to merge)

- strings/insult.json
lol
:cl:
add: adds code-stealing as an insult
/:cl:
> adds 'code-stealing' as an insult_adjective

- code/datums/components/crafting/recipes/recipes_tailoring.dm
- code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
- code/datums/traits/good.dm
- code/modules/clothing/suits/arfsuits.dm
- code/modules/clothing/suits/utility.dm
Primarily adds a new Light hazard suit.
:cl:
- Hazard suit thing attached to Technophreak for future hazard armor crafting (its own trait later, maybe???)
- Gave the Security Biosuit a new name, a crafting recipe, and updated armor tokens
- Fixed regular radsuits being Bulky
- Reinforced hazard suit is INTENTIONALLY Bulky. It's basically peak Light Armor, even if the stats are sub par.
- Also a misc fix with enhanced cells 'cause they had extra commas
:cl:
> Hazard Armor MK2 (step 1) (Good to merge if it passes checks)

- code/controllers/subsystem/job.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/holiday/easter.dm
- code/modules/mob/dead/new_player/new_player.dm
- code/modules/mob/living/simple_animal/friendly/dog.dm
- code/modules/mob/living/simple_animal/friendly/drone/_drone.dm
- code/modules/mob/living/simple_animal/friendly/farm_animals.dm
- code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- code/modules/mob/mob.dm
- modular_coyote/code/_pmon_defines.dm
- modular_coyote/code/modules/examine_images.dm
- modular_coyote/code/pmon_mob.dm
Lets players customize a creature and spawn as them from the main menu.
All done, but some known issues that can be sorted out in near-future PRs include:
- Simple mobs who are resting can move at full speed and keep items in their hands
- Simple mobs with hands can't use unarmed interactions, including attacks/hugs/etc
- Simple mobs who wield two-handed items don't have the off-hand item removed correctly, although it can be dropped but it won't delete itself when it should
:cl:
add: You can now set your options and spawn in as Pokemon or similar creatures instead of a regular character. These are still a WIP, so expect bugs!
/:cl:
> Creature Spawning

- code/game/objects/items/cards_ids.dm
- code/modules/WVM/wmv_buyer.dm
- code/modules/cargo/exports/misc_export.dm
- code/modules/clothing/head/f13factionhead.dm
- code/modules/clothing/suits/arfsuits.dm
Mostly WVM stuff, but some other small tweaks
:cl:
- Since metal parts, high qual parts, and electronic parts seem to be scuffed, the commie killer now accepts metal, titanium, plasteel, and plastit instead. No gunpowder sheets for now.
- Lowered research papers to 25/paper to give the clinic a chance to buy them
- Popular opinion was the reinforced hazmat suit needed more armor, so it has 3 DT now. Makes it better against shotguns (it *is* a ballistic vest over a hazard suit) but otherwise doesn't actually do much.
- The bounty card vendor is now made using the old brotherhood gear-buying vendor because lol. Prices subject to change. Sprite subject to change by someone who is not me.
- Low booze got bumped to 1000 in cargo. Still feels too high, but it's not really in the loot pool afaik …
> Commie Killer, part 3 (Good to merge if passes checks)

- modular_coyote/code/_pmon_defines.dm
Hey did you know that you can get a type's initial vars without initializing an instance of them? Its true! I didnt know this! Woulda been really helpful when I was making lathed ammo have the right costs.
Also I swapped out the initialization stuff for building pokemon lists with this method, cus charmander kept trying to delete its genital hud before it existed and made runtimes.
> Fixes pokemon initialization runtimes

- code/modules/keybindings/keybind/human.dm
- modular_coyote/code/mobinventory.dm
- Lets creature characters store flashlights and similar accessories in their mask/head slot so they can see the mystery while doing the dungeon.
- Lets simple mobs use the E hotkey to quickly equip held items into an available slot or into a bag they're wearing.
> [ready] Creature Accessory Slot & E Hotkey

- code/datums/emotes.dm
- code/modules/mob/living/emote.dm
- code/modules/mob/say_vr.dm
Sat down with Dan and we mashed out a simple system for flirty emotes.
This includes such bangers as
-*flirt - vague initiation verb
-*flirtaccept - IC agreeing
-*flirtreject - IC rejecting
-*flirtlean - leaning on someone
-*flirtblush - blushing at someone, or something.
-*flirtbrush - brushing someone, or something.
-*flirtcaress - carressing someone or something.
-*flirtcoo - cooing at someone or something.
-*flirteyebrow - quirking an eyebrow at someone or something.
-*flirtgrope - getting a hold of someone or something
-*flirtkiss - kissing someone or something.
-*flirtkissdeep - deeply kissing someone or something.
-*flirtkisslight - lightly kissing someone or something.
-*flirtkissy - making a kissy face at someone or something.
-*flirtlookat - eyeying someone or something up. …
> Flirting 2.0

- code/modules/mob/dead/new_player/new_player.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- modular_coyote/code/pmon_actions.dm
- Fixes simple mobs ignoring their resting state. They now stop moving while resting. Crawling functionality may come later.
- Makes player controlled simple mobs slow down when their health gets low, just like carbons.
> [Ready if CI Passes] Simplemob movement balance

- modular_coyote/code/modules/regeneration/sleepingpart/regenerate_sleeping.dm
Synths can sleep to heal! It'll heal their robolimbs, but only if they are a synth. Sleeping as a non-synth wont heal your robolimbs.
Sleeping just checks for any beds on your turf. dont need to be tucked in to get the extra heals.
> Lets synths sleepheal, and you dont have to be buckled to a bed for their benefits

- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/mob.dm
- modular_coyote/code/modules/examine_images.dm
- Makes the profile picture preview image (the popup when you click on somebody's profile picture in their examine) 500x500 pixels big by default instead of being really small and forcing you to resize it manually.
- Also tells you that your image should be about 500 pixels big in the prompt when setting it up in character creation.
> [ready] Makes Profile Picture Preview Window Larger

- code/modules/clothing/suits/arfsuits.dm
- code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
loadout nonsense for a character of mine. hopefully this is all fine :)
- adds in a rename and re-desc battlecoat & eyebot (dog?)
- adds in the loadout box /w whitelist; 
| x2 44 ammo box (For the .44, ripped straight from a similar loadout) 
| x1 reskin .44 (Statistically identical to the one you can get on spawn, just looks better. Also ripped from a similar loadout) 
| x1 reskin self-assign ID (Just looks more akin to brotherhood / enclave holotags) 
| x1 red-tint PDA (Red warden pipboy, looks good and holds no other non-rp value outside of that really.)
| x1 sec glasses (Cool red glasses, sec-hud is useless here really.) 
| x1 Pvt. Eye (Rename, re-desc custom eyebot for character lore purposes and to save renaming every round) 
| x1 half gasmask (Sec gasmask. Holds no real function …
> Panzer's Custom Loadout Nonsense

- code/modules/projectiles/guns/ballistic/automatic.dm
A simple pull to more accurately reflect what ammo the sniper rifle actually uses.
:cl:
fix: Sniper Rifle description now properly states the type of ammo it uses.
/:cl:
> Sniper Description Fix

- modular_citadel/code/modules/client/loadout/__donator.dm
Combine LARPs a sad people. I am a sad person.
Adds a custom kit so I get faster to support slutting instead of loot rushing. As discussed within a ticket on discord this is mostly fine. Mask is the only one giving that combine larp feel that fits symmmchts. Didnt bother with the ultra lightly armored labcoat considering I usually only go out of town with escort with that character and the Wattz 1000 beam reskin should be a separate PR so everyone can access it via a radial menu or something.
Support pwayers want to have some fun too. LARPing as combine can be fun, albeit its dumb.
--> I ripped the format from another persons custom kit and changed it around that. It should work.
:cl:
add: Support slut kit for Irkallas symmmftchhh
/:cl:
> Adds Irkallas shitty custom loadout

- code/modules/cargo/packs/security.dm
- code/modules/mining/equipment/mining_tools.dm
Title. Apparently the stable pink slime core makes mobs not aggressive to you. All mobs. Including bosses like the SMB or Captain Arlem. This is a problem.
Also a shovel fix I meant to do earlier and forgot about it.
:cl:
- Removes the stabilized pink slime core from the buy list
- Changes the shovel to be Bulky to not outshine spears; double checked its damage to make sure it's equal to the T1 spear. It is.
- Slightly changes the description to make it obvious it's a passable weapon now.
:cl:
> Removes stabilized pink core (If it passes checks, it's good to go)

- code/datums/components/crafting/recipes/recipes_misc.dm
- code/modules/food_and_drinks/food/snacks_other.dm
- code/modules/mob/living/simple_animal/friendly/farm_animals.dm
adds a misc crafting recipe for "processed welding fuel" that requires 30u of welding fuel to make. "processed welding fuel" is now a snack item, you can eat it, but its main purpose is to be 'fed' to a motorbike mount. Changes the motorbike's accepted food to allow for the new snack to be "eaten" by it. Yes, you can still milk the bike, this just makes it so you can feed it now.
:cl:
add: "processed welding fuel" snack
add: "processed welding fuel" misc crafting recipe
tweak: motorbike now "eats" processed welding fuel.
/:cl:
> Motorbike mount food fix

- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
Gives Ashdown bar a facelift, adds a small poker room, break room, and re-adjusts the dressing room so not everyone has to walk through it to get to the bar.
:cl:
add: New poker room, outfits, autodrobe, staff lounge
del: Old workshop room by entrance
tweak: Cleaned the bathroom
/:cl:
Revamped bar image:
> Facelifts Ashdown Bar

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
Gives Nash clinic an ore silo and the medical book vendor inside instead of outside to incentivize people actually using the custom vendor. Moves the resupply vendor inside so people don't just empty it out in the lobby.
Puts Ashdown's bar curtains on the windows themselves instead of inside and pixel-shifted, which is dumb, but density=1 closed curtains are too.
:cl:
add: Ore silo, med vendor to Nash clinic
fix: Ashdown bar curtains.
/:cl:
> Nash clinic content pass, Ashdown curtain fix

- code/game/objects/effects/landmarks.dm
- code/modules/jobs/job_types/wasteland.dm
- code/modules/jobs/jobs.dm
To proper show what they are, citizens of the town of Ashdown.
:cl:
/:cl:
> Renames Ashdown Waster to Citizen

- code/modules/cargo/exports/materials.dm
Trade Union Scrip (NCR cash) used to give way too much in the cargo train. It no longer does this.
:cl:
- Changed the sale value of Trade Union Scrip from 15 per scrip to 6 per scrip. Still more profitable than exporting coins to encourage its use, but just barely. Definitely less exploitable now.
:cl:
> Fixes a cargo exploit (if it passes checks, it's good to go)

- _maps/map_files/Pahrump-Sunset/RedRiver-Upper.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
Due to a _Fun_ incident in-game today, turns the bar, with stripper poles, adult content, and a slew of outfits around it making it as obvious as it possibly can be that they're for sexual content, into something that- actually works to that design
Adds an alternative entrance/exit to Ashdown on the side of the bar without going directly through it and remaps the 'meeting hall' area to have proper seating. Also adds the Heaven's Night style pop-up warnings to avoid rule-based complaints.
:cl:
add: Heaven's Night warning to Ashdown bar (With different text, ofc.)
tweak: Shimmies around the Ashdown meeting hall.
/:cl:
Lower Floor:
Upper Floor:
> Ashdown Bar Nightification

- _maps/map_files/Pahrump-Sunset/RedRiver-Upper.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
Reverses the idea of a second Ashdown bar and, instead, takes option 2. Gives Ashdown's main bar an adult segment that's a bit more condensed while turning the *main* section into a 'family friendly' zone.
Note: May need a few more passes, but this _should_ be good.
:cl:
add: An additional top-side house
del: Second Bar in Ashdown I'd made and the alternate path up.
tweak: Drastically adjusts the Ashdown bar's Aesthetics
/:cl:
Bar in question: 
House:
> Ashdown - Reverse Course

- _maps/map_files/Pahrump-Sunset/RedRiver-Upper.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
Re-adds the forgotten dogs to the Ashdown bar, split by section. Makes the Adult section separated by a curtain with posters indicating its purpose along with a curtain instead of a plain broom-closet style door.
Adds lights to presently lightless house as well as rugs.
Removes the poles from the side booths. (As keeping them would require rotating the entire bar, several rooms, and disconnecting the staff hallways- which are meant to be connected for a reason.)
Also touches up the look of that section of the bar to match the 'feel'.
:cl:
add: Dogs, carpets, wood, lights, etc.
del: Side-table stripper poles
tweak: Floor tiles/tables
/:cl:
Meat of the edits:
> Ashdown Re-doggification, Small Fixes

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
While by no means perfect, the custodial staff have at least a little dignity when it comes to Nash's upkeep, and given Heaven's Night is a part of it, the disrepair of their lights and the plethora of frequently and unsightly stains day to day hasn't gone unnoticed. Though imperfect, especially considering more secretive back-rooms, the Night should at least have functional lights and far less 'dirt and grime' compared to its previous incarnation, making the establishment at least livable.
That and *finally*, restores the jukebox to working order.
:cl:
del: Removes a number of stains and grime for easy of set-up
tweak: Makes the broken lights operable with the usual chance to break, sets up folding chairs properly instead of littering the floor with them.
/:cl:
Cleaning:
> Hires a Janitor for Heaven's Night

- code/datums/martial/sleeping_carp.dm
- code/game/objects/items/implants/implant_misc.dm
Gives the no drugs trait to sleeping carp, as it was intended from the getgo. Halves adrenaline implant's reagents while also giving it only 1 use. You don't need 3. The only reason this ever even gets used is for sleeping carp, to instantly regain all of your stamina back-- 3 times.
For the same reasons I removed the slime cores, this is being nerfed. If it continues to be a problem, I will hit it again.
> Sleeping Carp fix and "nerf"

- code/game/objects/effects/spawners/masterlootdrop.dm
replaces the item path with the spawn bundle for T-45d and T-51b so they spawn with helmets... the colorful T-51b doesn't have a helmet so it's shit outta luck. Praise be to the big stompy suits.
> power armor helmet spawns

- code/modules/mob/living/carbon/human/species_types/ghoul.dm
Makes them a little less ridiculous. 1/5th of the stamina healing rate. And 1/2 of the HP healing rate. Also very slightly slower. I was told that before it wasn't even noticeable. If this is too much, I can pull it back.
> Ghoul nerf

- code/modules/projectiles/guns/ballistic/automatic.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
> Casey's Bad Mac10 knockoff

- code/game/objects/items/storage/bags.dm
Makes all quivers belt slot (since thats the only place they work)
:cl:
/:cl:
> "fixes" quivers

- code/datums/traits/neutral.dm
a mispelling in the code made everyone with the TRAIT_CAT in neutral quirks be actually TRAIT_RAT, this fixes that horrible crime.
Rin Pin :cl:
fix: cats are no longer rats
/:cl:
> Fixes cats being rats

- code/modules/clothing/suits/arfsuits.dm
the craftable hazard suit was meant to be normal sized, but due to an error, it ended up taking the original bulk of the biosuit, considering it was meant to be the light version of the wanderer / seva suit, this fixes that.
Rin Pin:cl:
fix: Reinforced Hazard Suit is now normal sized as it was meant to be.
/:cl:
> fixes reinforced hazard suits

- code/game/objects/items/loadout_beacons.dm
- code/game/objects/items/melee/f13onehanded.dm
- code/modules/clothing/glasses/_glasses.dm
Adds a new boomerang weapon to the weapon kit, a normal sized wooden boomerang that acts as a normal speed club while returning when thrown, it also "fixes" a current error in existing boomerang code which made it apply double damage to the target, this simply halves the throw damage in existing boomerang items it so now it should deal the damage it's meant to
RinPin :cl:
add: Adds  new boomerang weapon to the kit choice
fix: halves existing boomerang weapon damage so it applies correctly
/:cl:
> New boomerang weapon + "fixes" regarding boomerang code

- code/__DEFINES/armor.dm
- code/datums/components/crafting/recipes/recipes_misc.dm
- code/datums/traits/good.dm
- code/modules/clothing/head/f13heavy_helmets.dm
- code/modules/clothing/suits/arfsuits.dm
Adds a refurbished version of the hotrod armor + recipe locked behind technophreak, because the sprite is too awesome to be wasted in such terrible armor, it keeps the stats it had as salvaged, with just a slightly increase to DT, making it a laser focused counterpart to the regular refurbished, at the cost of melee
Rin Pin :cl:
add: Adds a refurbished version of the Hotrod PA + Recipe
/:cl:
> Hotrod Refurbished + Recipe

- code/__DEFINES/armor.dm
- code/modules/clothing/head/f13heavy_helmets.dm
- code/modules/clothing/suits/arfsuits.dm
adds a new armor speed category for refurbished power armor, so it's slightly slower than regular PA, (regular PA being a value of 1, same as heavy armor, while the refurbished armor will get a value of 1.2) and also nerfs the powered scrap armor, which turns out, is just identical to regular T45b with just a different sprite, it gives it a salvaged power armor value instead alongside the speed changes.
RinPin :cl:
add: New speed for refurbished power armor
balance: powered scrap armor is no longer free regular T45b, it's instead now salvaged tier.
/:cl:
> adds new speed for refurbished armor + nerfs powered scrap armor

- code/modules/jobs/job_types/oasis.dm
Adds the stock ss13 hardstun taser to Nash Sheriff and Deputy as well as the stunbaton in replacement of the sheriff's telescoping baton.
:cl:
add: Add /obj/item/gun/energy/taser to Sheriff and Deputy loadouts
add: Add /obj/item/melee/baton/loaded (stunbaton) to Sheriff loadout.
del: Removed /obj/item/melee/classic_baton from Sheriff loadout.
/:cl:
> Add Ballistic Stun Taser to Sheriff and Deputy

- code/modules/mob/living/blood.dm
- code/modules/mob/living/simple_animal/hostile/f13/insects.dm
- code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
Rattler venom now divides its blood loss by 2 for every 200 blood you lose, starting at 200 blood loss.
Also eased up a bit on bloodloss blurrification, so it actually uses the caps.
> Tweaks to the venoms

- code/controllers/subsystem/nightcycle.dm
> Slight uptick in light amount (except at night)

- code/controllers/subsystem/recoil.dm
- modular_coyote/eris/code/gun_firemode.dm
The firemode datum, which holds a gun's damage multiplier (why did I do that, again?), was always getting set to 1. So any gun that had a non-1 damage multiplier was getting set to 1. Mods worked, though. This is fix.
The recoil modifier proc was using a length value that was outdated. Used to expect 2 values, and it was since expanded to 4, so it always rejected every recoil list, good or otherwise. this is fix
> fixes recoil and damage forever

- code/controllers/subsystem/progress_bars.dm
Its long name kept making it jitter on my screen whenever it'd be queued. not an issue on widescreen or other resolutions than mine, but none of those are ones I use, so I'm changing it.
Also adds a var that could make all progress bars visible to everyone. Didnt test it, but maybe it works.
> makes the progbar ss not jitter so fuckin much

- code/game/objects/effects/spawners/masterlootdrop.dm
- code/modules/clothing/suits/arfsuits.dm
PA is now much rarer.
Rare items are more weighted toward guns than armor and mods. from 33% for each, now its 25% for armor/mods and 50% for guns.
Reduced PA's deflect damage cutoff to 20. it blocks handloaded 9mm!
Increased PA's deflection cooldown to 1 second.
Deflecting a shot now costs between damage*10 and damage*40, on average a bit more than it used to.
Refurbished PA is worse in terms of deflection. It uses between damage*40 to damage*120 per hit, has a damage cutoff of 16 (blocks .22), has a cooldown of 2 seconds, and can't deflect while blocking with a shield.
> Rebalances PA

- code/modules/projectiles/projectile/beams.dm
- code/modules/projectiles/projectile/energy/stun.dm
Should make stun weaponry hit a little harder. Non-Hitscan tasers given 75 Stam Damage. They already stun but they don't **stun** yet.
:cl:
tweak: Added Stamina Damage to the non-hitscan projectile Tasers.
tweak: Reduced chance for disabler beams to be reflected.
/:cl:
> Buffs Stun Weapons

- code/modules/projectiles/ammunition/energy/laser.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/guns/energy/plasma_cit.dm
- code/modules/projectiles/guns/energy/plasmaf13.dm
trying some fixes, this should probably work
> gun fixes, jaggachi and aldric

- _maps/map_files/Pahrump-Sunset/Dungeons.dmm
- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
- _maps/map_files/Pahrump-Sunset/Westlands.dmm
- _maps/map_files/Pahrump-Sunset/chromata_en_res.dmm
- code/controllers/subsystem/atoms.dm
- code/datums/explosion.dm
- code/game/machinery/obstacles_barricades.dm
- code/game/objects/effects/spawners/lootdrop.dm
- code/game/objects/effects/spawners/masterlootdrop.dm
- code/game/objects/items/stacks/sheets/mineral.dm
- code/game/objects/items/stacks/stack.dm
- config/game_options.txt
Augh, attempts to fix linters cause I hate seeing red X's
For future reference:
Do not put mobs near other mobs not in the same faction, this leads to lots of errors.
> Linter fix

- code/game/objects/items/melee/f13powerfist.dm
Makes power fists actually worth using, giving them a proper unarmed damage while upping their regular melee damage, considering how rare they are, they are very weak to the point that most players ignore them.
regular power fist 
45 unarmed / 45 melee
Goliath (Legendary weapon)
50 unarmed / 55 melee
Mole Gauntlet 
30 unarmed / 38 melee 
RinPin :cl:
Balance: makes power fists not worthless
/:cl:
> Powerful fists!

- code/modules/mob/living/carbon/life.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
> MORE linter fixes!!

- code/modules/clothing/head/f13head.dm
- code/modules/clothing/suits/arfsuits.dm
Gives Excavator PA the same laser armor the helmet offers, which is meant to be bad rather than non existent.
Also gives it a flashlight like the other PA helmets (it's a mining tool after all)
Rinpin :cl:
fix: Excavator PA has laser armor
/:cl:
> Fixes Excavator PA

- code/game/objects/items/melee/f13powerfist.dm
- code/game/objects/items/powerfist.dm
removes the code that gave it a power based on setting via wrench, which also happens to control things doing 4-5x the damage it was meant to, should be dealing the proper damage now.
RinPin :cl:
fix: powerfists are no longer so powerful
/:cl:
> Fixes power fists dealing 200 damage

- code/__DEFINES/inventory.dm
- code/datums/components/melee_special.dm
- code/modules/antagonists/cult/cult_items.dm
- code/modules/mining/lavaland/necropolis_chests.dm
Adds a reworked cult bastard sword to the chest bubblegum drops,  that when two handed dealing 69 damage, 40 block alongside some other special effects, but can't be stowed away inside a sheath, and takes up your back or main slot.
replaces the broken inquisitor hardsuit with a modified cultist robe, which is slightly better than reinforced combat armor when dealing with melee, but less against lasers.
also adds a custom special melee component to it so it can do turf based attacks like the other weapons.
RinPin :cl:
add: Replaces bubblegum loot with a reworked cult sword + robes
/:cl:
> Bubblegum loot overhaul

- code/modules/mob/living/carbon/human/species_types/synthliz.dm
Title says it all, I literally just changed the name since you can choose sprites other than lizard now.
Not tested yet.
- [✓] You tested this on a local server.
- [✓] This code did not runtime during testing.
- [✓] You documented all of your changes.
:cl:
tweak: Changed the name of the synth race from "Synthetic Lizardperson" to "Synthetic Anthropomorph".
/:cl:
> Changes "Synthetic Lizardperson" to "Synthetic Anthropomorph" because the name is misleading now.

- code/__HELPERS/areas.dm
Before, areas would be depowered and required APCs, which could not be built. Also removes the redundant text from creating a new area that mentions APCs.
> Fixes Player-Made Areas Being Depowered

- licenses/README.md
Basically, it stops us from getting DMCA'd even though we have all rights to use other codebases we've been using.
Mostly because the CC by SA license requires crediting, even if we are under fair use for using the sprites, I don't think any of us wants to bother disputing it if we do get an abusive DMCA.
This makes it so
1: The license is valid.
2: We don't get DMCA'd
3: We at least show where we source some assets from.
Feel free to add more codebases onto it, I just did the ones I know we've definitely sourced from.
Basically addresses and solve the little unnecessary drama #2707 gave to us. We actually don't have to strictly follow those guidelines due to fair use.
> Adds appropriate credits to our codebase

- code/modules/reagents/chemistry/machinery/smoke_machine.dm
- modular_citadel/code/modules/reagents/chemistry/reagents/eigentstasium.dm
Restores eigenstatsium's locker fast travel functionality.
Also massively reduces the volume capacity of smoke machines to reduce the likelihood and effectiveness of chemistry grief.
> Re-Adds Eigenstasium Locker Functionality

- code/__DEFINES/inventory.dm
- code/game/objects/items/stacks/sheets/leather.dm
Changes large survival pouches to be able to contain small items, which includes ammo, tools, hand sized items.
The change includes reducing its max capacity from 21 items to 14, which is slightly better than two pocket pouches.
Now costs 150% more than just making two pocket pouches, convenience tax. Situationally useful, as it can only be stores on the suit slot. Not the most desirable storage method, as there are better options that dont take up your suit slot.
> Large Survival Pouch Change

- code/__DEFINES/ammo.dm
- code/game/objects/items/loadout_beacons.dm
- code/game/objects/items/storage/_storage.dm
- code/modules/projectiles/ammunition/ballistic/rifle.dm
- code/modules/projectiles/boxes_magazines/ammo_boxes.dm
- code/modules/projectiles/boxes_magazines/external/rifle.dm
- code/modules/projectiles/boxes_magazines/external/sniper.dm
- code/modules/research/designs/ammolathe_designs.dm
The gauss mag in the ammolathe comes empty.
You can print out racks of 5 gauss shots from the lathe, as well as blender rounds. Dunno if they're the same price, should be a bit cheaper?
Ammo that comes from a loadout beacon will be fully filled.
> Touches up ammolathed gauss and guarantees full ammo for loadouts

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper-2.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
replaces heavens night in the sewer with a large and very full warehouse to pick over (mostly just as filler for right now). This has been done because Heavens Night now exists on top of the bar in Nash, all the way up, like a penthouse of degeneracy. Actually, not like, thats exactly what it is.
:cl:
add: penthouse Heavens Night on top of the bar in Nash
add: warehouse in place of old heavens night location
del: sewer based Heavens Night is DEAD
tweak: minor tweaks and additions to the space around the bar in Nash to facilitate Heavens Night
/:cl:
> the penthouse hoehouse

- code/datums/components/storage/concrete/boxes.dm
Blindfold can now fit back inside the synth repair kit.
It allows the player to fit blindfolds in the synth repair kit.
:cl:
fix: blindfold can rightfully fit repair kits now.
/:cl:
> blindfold-and-repair-kits

- code/modules/cargo/exports/misc_export.dm
- code/modules/cargo/packs/emergency.dm
- code/modules/cargo/packs/medical.dm
- code/modules/cargo/packs/security.dm
Makes toys lose value after 100 sales, as there was a way to print thousands of them endlessly round start as shopkeep
Also fixes some packs from medical and moves a pack from security to emergency, the latter of which is renamed to Kits because everything in it is just that.
> Nerfs Toys and Fixes Some Cargo Packs

- code/modules/clothing/suits/arfsuits.dm
- modular_citadel/code/modules/clothing/suits/suits.dm
Some hooded suits are in my personal and humble opinion fine with digilegs.
Simply changing one variable to show digitigrade legs on some suits. If you're asking why, it's because I have OCDs and that one stray pixel bothers me (I know I hate myself too). Here's an example:
:cl:
fix: Shows digilegs on cloaks.
/:cl:
> I think hooded suits look cool on digilegs tribals, yes I'm biased, so what?

- code/game/atoms_movable.dm
- code/game/turfs/simulated/walls.dm
- code/modules/mob/dead/dead.dm
- code/modules/mob/living/living_movement.dm
Swear on me mum, yeah, that that bug didnt exist when I made it, cause I recall testing it 'n all, roight? Must be some other code which caused it m8
Either way, fixed, and the mobs system finally remembers to keep track of the mobs when moving between z levels. <3
Please can someone verify that the sounds work on their end too because I don't know what the *exact* issue is. All I know is that you only heard mobs from a specific z level and that's it.
> *augh Fixed sounds not working between z levels & that freeclimbing oopsie.

- code/game/atoms_movement.dm
ebic, does exactly as the title says.
Problem was that update_z didn't call on ghosts when going "move_up" or "move_down" originally, fixed that,  but orbiting and such doesnt trigger update_z.
Sound works on this code by checking the z level for clients, it refers to a list, where the first entry is z level 1, and that contains all clients on z level 1. The problem was is that orbitting didn't update that list, so if you moved to a different z level, that list stayed the same, so you could only hear sound on the z level you teleported from.
This fixes that, it forces every "forcemove" call to call "update_z", forcemove shouldn't be used willynilly as it's a forceful move, this bypasses safety checks and sanity checks because it's a forceful action, not a graceful one. So ye, it be fixed …
> Fixes all cases where a forcemove desyncs the listening z level of ghosts/objects/anything.

- code/__DEFINES/economy.dm
- code/modules/vending/medical.dm
Makes the research grants vendor indestructible, and swaps some numbers around in its prices.
> Destructible Research Vendor Fix

- code/modules/arousal/genitals_sprite_accessories.dm
- code/modules/arousal/organs/vagina.dm
Simply adds the option to have an inconspicuous pair of testicles or vagina. (what has my life become...) Basically a friend brought an issue up with taur sprites and exposed genitals, it makes sense that some of these bits are- exposed on the lower half of the taur. Spriting them wouldn't really be worth it as they may as well be hidden by thighs, tail etc...
So.. these are two invisible bits that simply give the examiner some flavour text but cannot be seen.
:cl:
add: two new lewd genital options.
/:cl:
> Invisible genitals for taurs, for hermaphrodites, for everyone (I swear I'm doing this for my best friend)

- code/modules/surgery/surgery.dm
Adjust failure chances for surgery performed in non-ideal locations.
Normal Tables - %20 -> %10
Beds - %30 -> %20
Anywhere - %50 -> %25
:cl:
balance: Adjusted failure chances for normal tables (%10), Beds (%20), and anywhere else (%25)
/:cl:
> Slight buff to locations for Ghetto Surgery

- code/controllers/subsystem/events.dm
Turns off the respanwing mob nests, but what must be done for gameplay must be done.
:cl:
/:cl:
> Temp tidi lowering

- code/modules/clothing/neck/_neck.dm
It's now possible to wear some simple necklaces and collars on the mask slot. I think this could be interesting not only from an aesthetical point of view, but it could also incentivize players to get the 'masked mook perk'. Like for example, a mercenary that is deeply attached to their dog-tags.
On a side note, it's not possible to activate mood debuffs/buffs when wearing collars as a mask. Meaning that is not possible to stack two positive buffs using two collars. One of them simply becomes cosmetical. 
:cl:
add: This new cool thing that allows YOU to wear collars on the mask slot.
/:cl:
> You can now wear collars and necklaces on the mask slot!

- code/modules/smithing/finished_items.dm
There was a bug that made whetstones set dmg to 5 if the weapon didnt have a force_wielded or force_unwielded value
Adds these to smithed weapons to unfuck them.
> Whetstone Bugfix

- code/modules/mob/living/carbon/human/human.dm
- code/modules/mob/living/living.dm
Adds a new button called "Sleep Toggle" in the IC tab, as the name states, toggles the sleeping status. In order to wake this button needs to be used again, it will then make you sleep for a set amount of time (depending on the heavy sleeper trait) after that you'll up. This decision was taken in order to avoid exploits of this button. (in reality this button is a lie, it makes the player sleep for 30 minutes with the option of waking up after 40 seconds if toggled back again, so if something bad happens in the code I guess they won't sleep forever).
:cl:
add: "Sleep Toggle" button
/:cl:
> "Sleep Toggle" button, to sleep for much longer.

- code/modules/hydroponics/grown/towercap.dm
Makes the color of smoke signals orange.
:cl:
tweak: Makes the smoke signal text color different.
/:cl:
> Adds color to Smoke signals

- code/modules/mob/living/carbon/human/examine.dm
Redundant to have it mention any health changes because that's already in examine code for everyone, makes it spammy.
I made the whole 'something nice' message show up in green like moodlet text that is good. I also added a pronoun note so that it will show proper pronoun. This should make Empath worth taking for those that want the trait. It's still neutral and still offers little benefit with the fact that the health show is redundant.
:cl:
code: changed some …
> Empath Edit

- code/datums/components/crafting/recipes/recipes_tribal.dm
- code/datums/traits/good.dm
I added a global init to the Bone Dancer tribe. This means that people can actually get the crafts for selecting the neutral quirk Bone Dancer traditions.
:cl:
/:cl:
> Bone Dancer Equipment (MERGE Ready)

- code/game/objects/hand_items.dm
- code/modules/mob/living/carbon/emote.dm
This is just an academic exercise, it can be approved or denied, especially if it's game-breaking. What this PR does is simply discriminating between human and creatures. The emotes *bite and *claw are buffed ONLY if the user is a creature, if a human or any sub-specie runs the same emote it will return the untouched regular values.
Why I did this... well because whenever I see a creature running around on the server defending itself with a knife it makes me a little sad and makes me think: "wouldn't it be cool if the creature could actually use claws or bite?".
I'm not a game designer, so... if the strength values of this is too high just tell me and I'll tune it down.
:cl:
add: Adds nastier claws and bites for creatures.
/:cl:
> Makes claws and bites nastier ONLY for creatures, not humans [can be merged IF you want]

- code/__DEFINES/misc.dm
- code/__HELPERS/mobs.dm
- code/controllers/configuration/entries/game_options.dm
- code/datums/dna.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- config/game_options.txt
Allow me to explain everything with a single picture:
just kidding have more:
Basically this adds a way to modify a charater's body width, this is... supposed to be used as a tool to counter distortion, but I already know I'll regret it. Here's an example, note the eyes:
:cl:
add: Adds character width.
/:cl:
> W I D E (character width slider)

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
Just turns this
Into this
There's already a roof over it, so, why not?
> Smol Map Fix

- code/game/objects/structures/memorial.dm
Apparently a while back someone upstream modified a memorial file that was put in for two upstream coders' deaths. This undoes that, because that's just not okay.
> Fixes An Old Code Defacement

- code/modules/surgery/bodyparts/robot_bodyparts.dm
Right now normal bodyparts have a dmg threshold of 50 hp
This seems to only affect wounds
Prosthetics cant be wounded, so when they reach their dmg threshold, it cripples the limb until replaced or fixed
Surplus prosthetics had 20 max dmg, which meant a gecko could cripple you with a single, solitary nibble.
Now prosthetics start off with 50 max, with enhanced prosthetics having 70 with a little dmg negation
Makes you able to take more than two hits from a gecko on a single prosthetic, now.
> Makes Prosthetics Not A Death Sentence

- code/modules/WVM/wvm.dm
- code/modules/cargo/exports/misc_export.dm
- code/modules/fallout/obj/stack/f13Cash.dm
Title. Touches WVM buyer and the cargo sell list.
:cl:
- Added more money denominations to the money exchange vendors as requested
- Upped Power Armor sale prices to 7500 for chests/helmets
- Crates now have a sale value
- Adjusted the medical infinivendor (stims cost 100, mid surgery costs 750, chemistry costs 1500) so things actually reflect their real value and the state of the economy
:cl:
> Economy Touches Part Whatthefuck

- code/__DEFINES/lighting.dm
- code/__DEFINES/traits.dm
- code/datums/traits/good.dm
- code/game/objects/items/grenades/f13grenade.dm
- code/modules/mob/living/carbon/carbon.dm
makes dynamite tiny sized items
does 30 dmg, so the only way this can kill is if you piss off the whole tribe.
Will need a timer on sending birds, maybe five minutes, if this is used too much.
Also changes night vision to two perks
Dark vision - minor
dark vision - greater
2 and 4 tiles dark vision range, 22 and 44 point cost respectively
> dark vision and tribal carpet bombing

- code/datums/traits/negative.dm
Makes it to where wearing sunglasses makes you not take the negative moodlet, as otherwise it spams you with the moodlet if you walk down a partially illuminated corridor.
Also adds info about sunglasses to its mechanics too.
> Tweaks Light Sensitivity

- code/game/atoms_movable.dm
- code/game/objects/items/stacks/crafting.dm
- code/game/objects/items/stacks/rods.dm
- code/game/objects/items/stacks/sheets/sheet_types.dm
- code/game/objects/items/stacks/sheets/sheets.dm
- code/game/objects/items/stacks/stack.dm
- code/game/objects/items/stacks/telecrystal.dm
- code/modules/plumbing/ducts.dm
- code/modules/spells/spell_types/shapeshift.dm
Makes all stackable materials have a max amount of 100, bumped from 200 and raised from 50 for everything.
Also makes it to where wild shape now maintains your name and languages when transforming back and forth.
> Wild Shape and Stack Sizes Fix

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- code/__DEFINES/access.dm
- code/modules/jobs/job_types/wasteland.dm
Gives Radio Operator two slots
Gives Radio Operator a way to leave their bunker without going through the attached dungeon
Gives Radio Operator an ID card with access to their post.
Adds red lights to the MF dungeon, apparently didnt have them even before I touched it.
Adjusts spawner positions and adds a bit more loot to account for difficulty and dungeon timer.
Makes shutters in the dungeon have more hp, to incentivize using the buttons for the intended linear path.
Also makes radio operator's room unable to access the dungeon early. Gotta do the dungeon to open that path up.
Also adds the window bearing bars to the clinic and sci post, because it bugged me.
> Modifies Radio Operator and MF Dungeon

- modular_coyote/code/modules/verbies/whocares.dm
Blind change to set a silly default status message
:cl:
/:cl:
> Set a default silly status message

- code/datums/brain_damage/phobia.dm
- code/datums/traits/good.dm
- code/datums/traits/negative.dm
- code/modules/mob/living/emote.dm
Makes phobias not cause a 7 second stun, but adds two new debilitating effects to make up for the vaccum.
Can synergize with heavy sleeper with a new faint mechanic, making it even more severe.
Increases all phobias besides darkness, as they all take from the above mechanics. Comments attached to their values with my thought process. Feel free to change if it tastes funny.
Also tweaks some other negative quirks' values to make more sense for how they will affect the player in regards to combat.
Also makes a new weaponsmith category under quirk packages, combining both basic and masterwork (cost of 42) for a total of 55
> Adjusts Phobia Mechanics and Values

- code/game/objects/items/melee/f13twohanded.dm
So I was investigating the source of the proton axe's log spam, hoping I could come to some sort of solution to make it chill a little, but I found out that the effect was actually massively broken. The EMP effect did not check for proximity or attack speed, meaning you could spam a targeted, one-tile EMP attack on anything you could see as fast as you could click. I don't really want to go through the effort of fixing this, but it's obviously not okay in it's current state
So now the shitty fireaxe clone is a little faster
> axes the proton axe

- code/modules/awaymissions/mission_code/challenge.dm
- code/modules/power/singularity/emitter.dm
Only easy optimisation possible rn, otherwise I cba aha.
Possible things to look into is the sound loop, possible items/systems causing this is:
- vore sounds
- /obj/item/storage/battery_box
- /obj/item/storage/blender_belt
- /obj/machinery/shower
- /obj/structure/bonfire
- /obj/machinery/mineral/wasteland_trader
- /obj/item/geiger_counter
> stops emitters from being auto-on draining server resources

- code/datums/martial/berserker.dm
a typo in the code made the extra crit damage / regular hard punch damage be only a +3.5 increase rather than the intended multiplier, which unironically, made regular punches WEAKER than just punching them with no martial arts, somehow, this hopefully fixes the issue.
What the title says.
> Makes berserker crits work as intended

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Upper.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- code/modules/food_and_drinks/recipes/tablecraft/recipes_donut.dm
- code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
- code/modules/hydroponics/grown/towercap.dm
- modular_coyote/code/mailbird.dm
Implements a bunch of very much non-atomized changes. Sue me, I guess. If any of the following changes are contentious, I don't mind removing them!
- The Tribal mailbird's weight limit has been increased to `WEIGHT_CLASS_SMALL` from `WEIGHT_CLASS_TINY`, significantly increasing its usability. This can potentially have negative consequences, so I expect this to be the most contentious change!
- The recipe for Hot Cross Buns now uses buns instead of entire loaves of bread to produce a single serving bun.
- The bonfires in the tribe are no longer set on top of tables, and instead use a new subtype that leverages the pre-existing way of making bonfires dense. There is an additional subtype used to give the tribe kitchen a pre-existing grill.
- The barrels in the tribe garden are no longer …
> Increases Mailbird Weight Limit, Misc. Fixes and Changes

- code/datums/martial/berserker.dm
Reduces the crit multi from 3.5 to 2, making it still quite nasty but no longer absolutely insane, reduces the regular hard punch multiplier to 1.3, which is still a nice damage increase without being literally more than double for free.
, has the NO DRUGS trait removed to be compatible with the current test merge (i hope)
> berserker rebalance

- code/game/objects/hand_items.dm
Gives the *claw item and children proper unarmed tags and glove slots, so it becomes compatible with unarmed quirks / martial arts, while still keeping the versatile melee nature for big leagues and other quirks, also replaces the wielded damage by just regular force damage, since they are all quite low and weak to begin with. (plus makes it less of a headache to work with the current unarmed system)
> Turns the *claw emote and variants into wearable gloves.

- code/datums/components/storage/concrete/pockets.dm
Literally turning a false in a true to make shoes behave like the rest of the equipment.
Now it's not possible to take off your shoes while trying to unsheathe your favourite boot knife in a panic situation.
Alt clicking to unsheathe still works, Though now to remove the shoes you have to click drag them to your hand.
:cl:
tweak: Shoes behave like the rest of the wearable equipment that have a strorage
/:cl:
> Makes shoes behave like all the rest of the wearable equipment that have a storage slot [ready to merge]

- code/game/objects/items/holy_weapons.dm
Makes Nullrods (supposedly one of a kind / very rare weapons) a little more viable, by giving them a damage buff akin to mid-higher end but not top tier one handed melee weapons, which (hopefully) will be balanced.
> Buffs Nullrods

- code/game/objects/items/devices/radio/encryptionkey.dm
- code/game/objects/items/devices/radio/headset.dm
gives the hell's nomads access to the ashdown radio, which for some reason, they don't.
> Hell Nomad's radio

- code/datums/martial/raging_boar.dm
as it stands, raging boar is very weak compared to the other martial arts, this gives it a buff to make it more viable, by adding a flat damage boost to the punches, while making it scale worse than the beserker's multipliers, reduces slightly the stamina cost of the tackles, and gives it a weaker stamina/ stun modifier than the other martial arts (which was previously lacking)
> Makes raging boar ANGRIER

- code/game/objects/hand_items.dm
makes all natural weapons and quirks deal the same damage per tier, only changing the damage type (sharp, pierce, blunt), allows biting to be used as an unarmed weapon, and increases the damage from 15 for basic, 18 for fast, 25 for big, 30 for max tier. to compensate
:cl: …
> Buffs natural weapons

- code/modules/mob/living/living.dm
- code/modules/mob/mob.dm
This is a simple change to the pixel shifting system, what this basically does, is to allow a player to enter someone else's tile without the need to flop on the floor. There are a lot of rules and checks to this, such as the other person needs to be in help intent and more! Should be unexploitable now, but before this point, unlimited speed and the ability to phase through bunker walls thanks to your erp buddy was an actual threat.
:cl:
add: Adds pixel sliding to another tile.
/:cl:
> Pixel sliding iteration I [ready to merge]

- code/modules/projectiles/guns/ballistic/automatic.dm
- code/modules/projectiles/guns/magic/wand.dm
Title
:cl:
- P90 is now normal sized due to being outclassed despite the 50rnd mag. May need to revert in the future, or disable it being used akimbo down the line
- Decreased Firebolt wand charges (outshone literally every high cal secondary, whoops)
- Sparks wand has decreased charges and slightly increased charge time per shot (still good v swarms, less good v tougher mobs now)
- Wand of Magic Missile slightly nerfed (intended to be just barely worse than Firebolt/Sparks, adjusted to stay there)
:cl:
> Tweaks magic (and the p90) (good to go if it passes checks)

- code/__HELPERS/unsorted.dm
If you're a New Player (ghost mob that you are before you join the actual game) or your name contains your ckey, it'll replace the ghost name thing with a random cow name. Might make Aldric show up as Tux (short for Tuxedo), but that's  a risk I'm willing to take.
> Hides players' ckeys from the orbit list

- code/modules/mob/living/carbon/human/human.dm
If your mount is a taur, then the rider only needs one hand to hold onto the taur. The taur itself doesn't need to use any hand at all to have a passenger! If this is poorly worded, it's because I'm about to have a minor stroke.
:cl:
tweak: Taurs and riders use one less hand to ride.
/:cl:
> Piggyback riding! [ready to merge]

- code/modules/mob/living/carbon/human/human_defense.dm
As the name states, no more loosing limbs due to big explosions, as requested.
:cl:
del: Removed limb loss by explosions
/:cl:
> No more limb loss by big explosions [ready to merge]

- code/__DEFINES/dcs/signals.dm
- code/controllers/subsystem/processing/mob_spawner.dm
- code/datums/components/spawner.dm
- code/modules/mob/living/simple_animal/hostile/hostile.dm
Dunno if it works, keeps crashing, gonna try it on the test server.
> Maybe performances up spawners

- code/game/objects/items/loadout_toolkits.dm
adds a capture device to the rider kit, so it's a lot easier to have your own pet chocobo / motorcycle without them constantly dying due to ghouls attacking them or getting stolen due to the lack of keys, buffs beastmaster by adding an additional capture egg to the kit, to hopefully encourage more diversity in battle pets, (i'll probably make an eggless version of the rider kit for cargo if people abuse this)
> Shameless rider kit buff (and to some degree, beastmaster buff)

- code/datums/components/crafting/recipes/recipes_tribal.dm
Title. Accidentally made it so the Wand of Firebolt and Staff of Fireball had the same output.
Wand of Firebolt now *actually* gives you a Wand of Firebolt.
:cl:
/:cl:
> Fixes the Wand of Firebolt craft (Good to go if it passes checks)

- code/__DEFINES/traits.dm
- code/datums/traits/good.dm
- code/modules/projectiles/gun.dm
- code/modules/projectiles/guns/magic/wand.dm
I do as the kelpmaster commands.
Quirk for wands! Now you need to be proficient to use wands. Wands and martial arts can't be used together. Creatures on the other hand, can use all wands.
The bone one can be used by everyone, quirk or not, as long as they don't know a martial art.
:cl:
add: Added TRAIT_WAND_PROFICIENT
/:cl:
> WANDerful: Quirk to use wands, creatures don't need the quirk to use them [ready to merge]

- _maps/map_files/Pahrump-Sunset/RedRiver.dmm
- code/_compile_options.dm
- code/datums/components/mood.dm
- code/datums/components/spawner.dm
- code/datums/components/swarming.dm
- code/modules/mob/living/simple_animal/hostile/giant_spider.dm
- code/modules/mob/living/simple_animal/hostile/regalrat.dm
> Fenny, Dan & Andy eat the code like vultures supping on roadkill

- code/datums/traits/good.dm
Title
:cl:
- Changes some text regarding the Wand trait and makes it more obvious that it'll affect more than just wands/staves down the line. NOTE FOR FUTURE DEVS: This ONLY affects kelpmagic items. Standard TG magic items should be unaffected so they're still usable in events.
:cl:
> Tweaks the Wand trait (Good to go if it passes checks)

- code/game/objects/items/stacks/sheets/sheet_types.dm
Changes crafting costs of crates to stop an exploit where people could make way too much money by spamming crates. Seriously, why the fuck are people addicted to exploiting 200k credits when you can do it legit like super fucking easy I s2fg these people fr fr
:cl:
- Wood crates to 25 (affordable, but piss people off using that much wood
- Metal crates to 40 (good fucking luck getting more than 2 or 3)
- Plasteel crates to 30 (vaguely affordable, but just sell plasma my man)
:cl:
> Hotfixes crates to cost more in crafting (Good to go if it passes checks)

- code/__HELPERS/_cit_helpers.dm
Reverts a change of #448 that broke a lot of clothing items.
What it did was make it so the game stops looking at what parts of your body your clothes cover up, and instead look at a new variable that _should_ do the same thing, but still allow you 'female body armor™'. This new variable, however, is not set on a lot of clothing items, thus breaking them.
It this works, we can re-implant the changes of #448 as a simple "show-it-anyway" override. So instead, we still check at what parts are covered up, but we also check for this override that'll be set to no by default.
:cl:
fix: Fixes a lot of clothing items to only show your off your enterprise resource planning assets when they should be.
/:cl:
> [Testmerge ONLY!!] Fixes chest-mounted equipment from displaying on top of clothes when they shouldn't.

- code/datums/soullink.dm
- code/modules/mob/living/living.dm
Try combining destroy() to see if that fixes some of the code.
:cl:
/:cl:
> Nothing like testing in prod!

- code/game/objects/items/devices/PDA/PDA_types.dm
PDAs for security law jobs will no longer have cartridges. This will keep them from informing people of the entire region's population and also having a way to check on DNA and fingerprints. These are SS13 features that aren't really productive to wasteland roleplay. Mostly because there is no way they have a record of each Wastelander and non citizen that will come by.
:cl:
config: changed some config …
> No More Manifest

- code/modules/projectiles/ammunition/energy/stun.dm
- code/modules/projectiles/guns/energy/stun.dm
Title
:cl:
- Taser uses ECP cells like other normal-sized energy guns usually do
- Taser projectile now drains properly (10 shots, disablers have 16 so that's a decent gap imo)
:cl:
> Hotfixes the taser to not have 150 shots (Good to go if it passes checks)

- code/modules/clothing/suits/miscellaneous.dm
- modular_citadel/code/modules/client/loadout/suit.dm
makes the loadout grey and brown robes be equivalent to medium loadout armor, 2 point cost, same as the other armors.
> Minor robes buff for cult event

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
Turns out the inner gatehouse buttons rested on the exact same square as the outer buttons, making them redundant. Also changed gatecodes to be numeric only so if some chucklefuck nukes the controllers it may be actually FIXABLE
:cl:
/:cl:
> Rejiggered Nash gate and Buttons

- code/modules/reagents/chemistry/reagents/other_reagents.dm
- code/modules/reagents/reagent_containers/bottle.dm
- code/modules/research/designs/autolathe_desings/autolathe_designs_medical_and_dinnerware.dm
- code/modules/research/designs/autolathe_desings/autolathe_designs_tools.dm
Fixes the synth repair gel to, y'know, actually heal synths and makes it obtainable.
Personal note: This is largely a temporary setup. How temporary depends on how long it takes me to figure out how autocycling works and how to apply it to stuff like welders and cables. May end up moving the healjuice to the crafting tab down the line. Might even make a proper chem recipe, if I'm feeling insane.
:cl:
- Synth repair gel added to autolathe for 500/500/500 gold/silv/glass
- Synth repair gel now heals synthetics properly, and has a description reflecting this; has 2x the power of welding fuel but requires two in-demand materials and glass which can be hard to get (mostly because people forget about the materials vendor)
:cl:
> Synthjuice (Good to go if it passes checks)

- code/__HELPERS/unsorted.dm
- code/controllers/subsystem/second_wind.dm
- code/datums/components/plumbing/_plumbing.dm
- code/datums/components/storage/ui.dm
- code/datums/components/swarming.dm
- code/datums/components/tackle.dm
- code/datums/emotes.dm
- code/datums/mood_events/generic_positive_events.dm
- code/game/atoms_movement.dm
- code/game/objects/hand_items.dm
- code/modules/client/preferences_savefile.dm
- code/modules/clothing/suits/arfsuits.dm
- code/modules/food_and_drinks/food/snacks.dm
- code/modules/mob/camera/camera.dm
- code/modules/mob/living/carbon/human/emote.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/carbon/life.dm
- code/modules/mob/living/simple_animal/hostile/hostile.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- code/modules/mob/logout.dm
- code/modules/reagents/chemistry/holder.dm
- config/maps.txt
- modular_coyote/code/modules/say/soundbubbles.dm
More runtime fixes!
:cl:
/:cl:
> Fix some runtimes!

- code/datums/components/tackle.dm
- code/datums/martial/raging_boar.dm
- code/datums/traits/good.dm
Changes how the current in game tackles obtainable through the quirks + raging boar work, by adding a "strong" variant of the simple tackles that boar uses, turns out, the original code for the simple tackles has some strange errors in the calculation, and none of it actually applies, so the damage ends up being just a flat 5 every time, not taking into account distance or any of the different multipliers.
Simple tackles cannot knockdown enemies, it only deals some damage and knockback.
This replaces the raging boar tackle and max level tackle quirk with the "strong" version of the tackle, which deals 10 / 20 / 30 damage depending if you have no unarmed quirk / fists of iron / fists of steel, and can't be increased in any shape or form, and is also affected by armor, it also has some …
> Tackle tweaks (TEST PR)

- code/game/objects/items/devices/radio/encryptionkey.dm
Gives Hell Nomads access to the ashdown radio again, hopefully without any bizarre lighting related runtimes.
> gives nomads their radio back.

- code/modules/mob/dead/new_player/new_player.dm
adds civ weapon kit, duffelbag, coin stash, and pda (with idcard) to the creature loadout
this should reduce the time spent gearing up and increase the time they can spend actually having fun
:cl:
/:cl:
> makes the creature loadout less terrible

- code/game/objects/items/RCD.dm
- code/modules/plumbing/plumbers/_plumb_machinery.dm
- code/modules/research/designs/medical_designs.dm
This soft-removes the plumbing system by removing the ability to make plumbing devices with the (now-broken) rapid plumbing device. It also removes the ability to make the device in the first place so nobody will be losing materials by making it while it's disabled. Once someone fixes the plumbing runtime errors, they can have it back by reverting this PR.
> fixes plumbing lagging the server (soft removal)

- code/datums/components/crafting/recipes/recipes_tribal.dm
- code/modules/WVM/wvm.dm
- code/modules/cargo/exports/materials.dm
- code/modules/cargo/packs/materials.dm
Fixes some WVM stuff, fixes a crafting menu whoops, adjusts prices of materials.
:cl:
- Adds Red Paint to the WVM attachment vendor due to excessive demand (and reasonable complaints)
- Adds Rose Ingots to the export list
- Fixes an infinite money exploit
- Greatly increases prices of raw material exports so it's worth it to buy materials from miners; may as well give raw mats some use due to their lack of role right now (and opens up using raw mats as dungeon loot)
- Fixes the Improvised Shock Wand name in the crafting menu so you don't accidentally craft the T0 wand instead of a T1
:cl:
> Various fixes (Good to go if it passes checks)

- code/_onclick/hud/screen_objects.dm
removes the green/red ghost thing when you click on an inventory slot instead of only when your mouse leaves the inventory slot
> fixes inventory ghosting

- code/__DEFINES/inventory.dm
currently, if you sheath your sword before your shield it will go into the belt slot and then your shield can't be sheathed in your suit storage so you just have your shield chilling in your hand awkwardly
> allows shields to fit into suit storage

- code/game/objects/items.dm
- code/modules/WVM/wmv_buyer.dm
When you examine an item, it will now tell you if the scrapper accepts it and for vaguely how much (i.e. "This would sell for a few copper coins.").
this streamlines the process of looting items that sell well without revealing their exact cost. good players won't really need this, but newer ones will appreciate not wasting half of their bag's space with unsellable junk
> lets you know if an item is worth selling

- code/modules/keybindings/keybind/human.dm
- code/modules/mob/inventory.dm
- code/modules/mob/living/carbon/human/inventory.dm
- code/modules/projectiles/gun.dm
Stupidly complicated smart equip/unequip, what is this supposed to do:
If the user is empty handed and triggers this function, then unholster an item with priority and with exceptions in the following order:
1-Backpack slot;
2-Armor slot;
3-Belt slot;
4-Holster contents, return ONLY firearms, all other items will be ignored;
5-Boot contents.
It also ignores people who wear their flashlights on these slots, it's smart, smarter than me.
There's one more twist to this, for example, if the user had previously unsheathed a revolver from a shoulder holster,
we clearly want the revolver to be re-sheathed in the previous location, this is why memory of item and origin of said item have been added.
There's one edit of this, if using quick equip with shoulder holsters, the cocking delay of the gun …
> Smart inventory slot unsheathing [ready to merge]

- code/datums/traits/negative.dm
Noticed you can stack all three 'bad eyes' quirks for points and free glasses, kinda lame so I made them conflict.
Also tacked on blindness to conflicts because you can stack those all with blindness too
:cl:
balance: Vision loss (bad vision, blindness) quirks now all conflict with each other
/:cl:
> Vision loss quirks conflict with each other

- code/datums/hud.dm
- code/modules/mob/dead/observer/observer.dm
Fixes GC for observer and new players
EAT A DICK FALLOUT 13, YOUR DEVS ARE TRASH FOR NOT PORTING THIS TWO YEARS AGO.
https://github.com/tgstation/tgstation/pull/55563
BLESSED TG CAN STILL SAVE US
:cl:
/:cl:
> Attempts to port tgs pr 55563

- code/modules/WVM/wmv_buyer.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/damage_procs.dm
- modular_coyote/code/mob.dm
- While roleplaying in one spot for a while, your hunger will stop draining.
- Stackable materials will no longer say that they're worth more than they are when you examine them.
- Radiation damage now has a ceiling of `very high` to prevent players from accumulating so much that they're forced to get cloned or respawn.
> Freshest PR u ever seen

- code/game/objects/items/granters.dm
I broke the recipe for my own donator item, currently disabling until I can be bothered to fix it.
:cl:
fix: No more NTOS error crafting menu upon reading the book.
/:cl:
> Disabling broken recipes

- code/modules/projectiles/guns/ballistic/rifle.dm
Doubles the fire rate of the .22 repeaters. The full sized rifle when two handed, even when fired at its fastest possible fire rate with bolt worker, is basically unaffected by bloom, as a lever action .22 probably should be. The mares leg version, when one handed, can bloom very rapidly, as you'd expect given you have to twirl that thing around like you're some sort of exterminator.
> Tweak to buff the .22 repeaters fire rate

- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset-Lower.dmm
- _maps/map_files/Pahrump-Sunset/Pahrump-Sunset.dmm
- code/game/machinery/telecomms/machines/allinone.dm
- code/game/machinery/telecomms/machines/broadcaster.dm
- code/game/machinery/telecomms/machines/bus.dm
- code/game/machinery/telecomms/machines/hub.dm
- code/game/machinery/telecomms/machines/message_server.dm
- code/game/machinery/telecomms/machines/processor.dm
- code/game/machinery/telecomms/machines/receiver.dm
- code/game/machinery/telecomms/machines/relay.dm
- code/game/machinery/telecomms/machines/server.dm
Separates the comms lounge a bit from the adjacent dungeon. Also adds an ooc warning to the entrance to it that clarifies its not part of the nearby dungeon.
Also makes the machines unmodifiable and indestructible. That way comms griefing can be curated, to prevent dick-moves.
> Comms Station Tweak

- code/datums/components/crafting/recipes/recipes_primal.dm
- code/modules/jobs/job_types/tribals.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
Adds wicker doll crafting recipe to shaman, druid, and chieftan. Craftable with 25 hay. Negligibly abusable. If we get bad actors, can increase the use delay.
Also adds a custom kit.
> wicker? hardly know 'er

- code/datums/traits/_quirk.dm
- code/datums/world_topic.dm
- code/modules/mob/living/carbon/carbon.dm
- code/modules/mob/living/living.dm
- code/modules/mob/mob.dm
- code/modules/reagents/chemistry/holder.dm
Mobs runtime in nullspace, who knew.
:cl:
/:cl:
> Try to un-runtime the runtimes

- code/modules/projectiles/ammunition/energy/laser.dm
- code/modules/projectiles/guns/energy/laser.dm
Just a hotfix
:cl:
- Changes the Wattz 2k Sport to use the Microfusion Breeder
- Changes the Wattz 2k Sport to be unable to eject the cell
:cl:
> Wattz 2k Sport fix (good to go if it passes checks)

- code/controllers/subsystem/npcpool.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
I am going to beat jon with a shovel until he is a deer pudding.
Doesn't quite port it completely, specifically it still uses our version of mob transformation.  But it compiles, mother fucker.
@GremlingSS you are in danger, run
:cl:
/:cl:
> Ports the last 2/3rd of tg 67273

- code/game/turfs/simulated/floor.dm
->attemt to channel your inner theoretical physicist
->remove the entire buildings floor tiles chasing down your enemies
->bury yourself in shame; you tarnished something beautiful
:cl:
add: Added harm intent checker to prevent plying tiles mid combat
/:cl:
> Makes floors unplyable on harm intent

- code/_onclick/hud/screen_objects.dm
also fixes your active hand indicator thing disappearing sometimes
:cl:
/:cl:
> another green ghost fix

- code/datums/traits/good.dm
Adds the crafting recipes from Chem Whiz to General Medical Practitioner and adds the crafting recipes from Weaponsmith (basic) to Weaponsmith (Legendary).
:cl:
add: See desc.
/:cl:
> Add crafting recipes to quirk packages

- code/modules/projectiles/ammunition/energy/laser.dm
- code/modules/projectiles/boxes_magazines/external/lmg.dm
- code/modules/projectiles/guns/ballistic/automatic.dm
- code/modules/projectiles/guns/energy/plasma_cit.dm
Makes the ratling (an easily craftable, black powder makeshift minigun) no longer be a better weapon in almost every way compared to the minigun and other high tier legendaries, considering how easy it is to craft.
20 damage per bullet down from 60 (while still using the flintlock damage table which can roll for 200 damage), 50 round mags from 200, reduced the RPM from 300 (which in reality was 600) to 100, made it far more innacurate.
unfucked the laser AK cells to hold the 30'ish shots it was meant to have rather than the 8 it currently does, slightly increases the recharge rate.
> salt ratling nerf PR + fixes the ammo count for the laser AK

- code/controllers/subsystem/ticker.dm
Changes the STATION_EVACUATED Ticker message
:cl:
tweak: changes time to be more ambiguous.
/:cl:
> Finally removes "Week" From the end of round display.

- code/modules/projectiles/guns/ballistic/automatic.dm
Allows the 10mm SMG and every SMG below it such as the rockwell, uzi, etc to be normal sized, thus allowing them to be backpackable and holsterable, at the downside of receiving a T1 damage malus (.22 is unaffected, it's pitiful damage enough as it is) 
Regular full sized SMG's remain unnafected (grease gun, 10mm upgrades, etc)
Also allow them to be surpressed cuz why not.
> (TEST PR) Allows certain SMG's to fit in bags/holsters

- code/game/objects/items/stacks/medical.dm
It should now take 5 seconds per use on yourself, instead of 2. Using it on others is still 1 second. This does mean you can't stamcrit yourself using the basic stuff. Also swapped the icons around since I actually got them mixed up. Horsenettles are pink, datura is white.
> A "quick" nerf to the horsenettle creams that actually slows them down

- code/datums/components/storage/storage_mode_switch.dm
- code/game/objects/items/storage/_storage.dm
- config/maps.txt
- fortune13.dme
Allows players to choose how to pick up items out from their storages, by simply right clicking on a certain storage and clicking on the right verb.
The mode we added in:
- STORAGE MODE 0: default
- STORAGE MODE 1: take out the FIRST placed item when simply CLICKING on storage
- STORAGE MODE 2: take out the LAST placed item when simply CLICKING on storage
- STORAGE MODE 3: take out the FIRST placed item when ALT-CLICKING on storage
- STORAGE MODE 4: take out the LAST placed item when ALT-CLICKING on storage
- STORAGE MODE 5: take out the FIRST placed item when CTRL-CLICKING on storage
- STORAGE MODE 6: take out the LAST placed item when CTRL-CLICKING on storage
:cl:
add: Adds a verb that lets you choose how to pick items up from a storage.
/:cl:
> Fuzzy's storage equip/unequip QoL [ready to merge]

- code/game/objects/objs.dm
- code/game/objects/objs_set_vars_verbs.dm
- fortune13.dme
Eki and I are up to no good.
Allows players to edit some objects variables, such as pixel offset, rotation and layer.
https://github.com/ARF-SS13/coyote-bayou/assets/64517916/83eb0921-723e-4ddf-b4da-ab285ebc745a
:cl:
add: Adds the ability to edit variables for some objects.
/:cl:
> Objects variable edit [ready to merge]

- code/game/objects/effects/spawners/masterlootdrop.dm
- code/modules/projectiles/ammunition/energy/laser.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/projectile/beams.dm
Title, basically. Ultracite rifle is ugly, but the energy loot lists are both anemic and unrewarding. It'll do for now.
:cl:
- Adjusted the Ultracite rifle to a radioactive 40 shot AER-9. Ultracite ammo cells are stupid rare and can't be made, so it's basically an ugly TG blaster
- Adjusted some irradiate damage on weapons because radarmor is so easy to get and stack
- Adjusted the loot lists to include kelpmagic items
- Adjusted the rarity of Solar Scorchers so finding a safe, self-charging gun is no longer incredibly common
- Adjusted energy loot lists in general to account for new items and to make some items more reasonably common, uncommon, or rare
:cl:
> Ultracite Rifle and Loot Adjustments (Good to go if it passes checks!)

- code/datums/traits/good.dm
Title- 
Many mobs that you can transform into through wildshape have issues associated with them, and this PR will disable the quirk for now until those issues are fixed.
> Makes wildshape innacessible to players until the bugs and exploits are ironed out.

- _maps/map_files/coyote_bayou/Ashdown-Upper.dmm
- code/__HELPERS/unsorted.dm
- code/datums/traits/good.dm
- code/game/objects/effects/landmarks.dm
- code/modules/spells/spell_types/shapeshift.dm
- modular_coyote/code/_pmon_defines.dm
- modular_coyote/code/drakeborgs/drakeborg.dm
- modular_coyote/code/mob.dm
- modular_coyote/code/pmon_actions.dm
- modular_coyote/code/pmon_mob.dm
> Wildshape bug fix and balance palooza

- code/game/objects/effects/spawners/masterlootdrop.dm
- code/modules/projectiles/ammunition/energy/laser.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/guns/energy/plasma_cit.dm
Title. The laser AK (470 and 470M) were both just utterly whack. The 470M still had the original 600 RPM despite being the worn / loadout version, and neither AK used the AK470's unique casing or projectile. TL;DR, I just brought it in line with other self-charging guns and made it use its actual casing/projectile
:cl:
- Fixed the AK470 and M to use their unique casing/projectile
- Fixed the Laser 470M using a vanilla MFC, allowing an exploit to reload it despite can_remove = 0
- Adjusted the rechargerate of the laser AK to 30 (Read: 60 seconds) because it's a fully automatic self-charging gun. May be too harsh considering it does AEP damage, might adjust rate or damage later
- Added the AK470 as a rare loot because it was originally a hardspawn only and hardspawns icky
- Gave the AK470 …
> Tweaks the Laser AK to meet Bayou standards (Good to go if it passes checks)

- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/guns/energy/plasma_cit.dm
- code/modules/vending/sovietvend.dm
Title
:cl:
- Replaces vendor Laser AK470 with worn variant
- Removes -10% damage nerf to AK470M (worn)
- Adds +20% damage to AK470 (normal)
- Increases 2-handed handling of the AK470 and 470M
:cl:
> Rebalances the Laser AK yet again (Good to go if it passes checks)

- code/modules/projectiles/guns/energy/laser.dm
As it says on the tin, removes the ability to mod the x-com laser.
:cl:
tweak: Removed abilitiy to mod a special laser rifle
/:cl:
> The X-COM laser can't be modded

- code/modules/projectiles/ammunition/caseless/arrow.dm
It used the wrong projectile.
:cl:
fix: Titanium arrows now fire titanium arrows.
/:cl:
> Fixes titanium arrows turning to regular arrows

- code/datums/components/crafting/recipes/recipes_tribal.dm
- code/modules/projectiles/guns/ballistic/automatic.dm
- code/modules/projectiles/guns/magic/staff.dm
- code/modules/projectiles/projectile/beams.dm
Title, basically. Phase 3 of magic didn't work out, so some random small stuff was done instead.
:cl:
- Added the Perfected Staff of Healing; literally just a medbeam but with Staff of Healing properties outside of the healbeam effect
- Added the Perfected Staff of Healing to the crafting list
- Tweaked a bunch of Magic crafting things to be more forgiving and less heavy on parts, also changed the staff of acid to uranium because green is green
- Fixed the Oststrauss LMG's name and description. Tox is probably going to re-expand the desc again but the core issues are fixed with it so I can just clean that up when done
- Made it so the Particle Cannon's crit doesn't basically Round Remove someone, but it still does screw you over no matter what you're wearing or doing
:cl:
> Magic stuff, gun name fix, and particle cannon nerf (Good to go if it passes checks)

- code/__DEFINES/traits.dm
- code/datums/traits/good.dm
- code/game/objects/hand_items.dm
- code/modules/mining/equipment/kinetic_crusher.dm
- code/modules/mob/living/carbon/emote.dm
Adds 2 cantrips to work as the foundation for a more interesting magic system, being quirks you can pick as a more unique alternative to the regular claws / bites / unarmed ones.
The current ones are - Shocking grasp - a fast melee based cantrip that deals burn damage
-Booming blade - effectively a weaker kinetic crusher, able to mark targets with a projectile to deal extra melee on the next hit.
> a wizard did it (cantrip PR)

- code/__DEFINES/armor.dm
- code/datums/components/crafting/recipes/recipes_tribal.dm
- code/modules/clothing/spacesuits/hardsuit.dm
Title. Fixes an issue in defines, the cydonian powersuit, and a naming error in crafting.
:cl:
- Energy armor in defines now adds instead of multiplies. This should fix *several* issues regarding energy armor
- The Cydonian Powersuit is now +1 Laser/Bullet/Plasma and +3 Speed at the cost of -3 Melee. It's about as common as regular combat armor, so it might be fine? Seeing comments, I may need to make it 1:1 of combat armor because I want people to have the funny RGB armor but I don't want it being OP and that +3 speed is strong if you know how to balance your mood
- Fixed the Perfected Staff of Healing having the wrong name in the crafting menu
:cl:
> Trio of fixes (Good to go if it passes checks)

- code/datums/components/crafting/recipes/recipes_tribal.dm
- code/game/objects/effects/spawners/masterlootdrop.dm
- code/modules/cargo/packs/security.dm
- code/modules/projectiles/guns/magic/staff.dm
Title. Magic Missile Staff turbofucked and Lightning Staff was doing Plasma damage.
:cl:
- Lightning Staff now does Laser damage as intended; spark wand stays energy (plasma) because it underperforms as far as I understand things. Might change in the future
- Magic Missile Staff is commented out of crafting/loot because it's super bugged and has literally infinite shots, no need to wait for recharge
:cl:
> Urgent fixes, kind of (Good to go if it passes checks)

- modular_coyote/eris/code/wielding.dm
fixed dual wielding being procced when attempting to unwield a two-handed weapon
simple bugfix
- [ x] You tested this on a local server.
- [ x] This code did not runtime during testing.
- [ x] You documented all of your changes.
:cl:
fix: unwielding two-handed weapons works again.
/:cl:
> fixed dual wielding being procced when attempting to unwield a two-ha

- code/__DEFINES/traits.dm
- code/datums/martial/raging_boar.dm
- code/datums/traits/good.dm
- code/modules/mining/equipment/kinetic_crusher.dm
- code/modules/mob/living/carbon/emote.dm
- code/modules/projectiles/guns/magic/staff.dm
due to TIDI issues, booming blade is commented out, raging boar had it's damage bonus reduced from 15 to 5 (it's insane)
- [X ] You tested this on a local server.
- [X ] This code did not runtime during testing.
- [ X] You documented all of your changes.
:cl:
/:cl:
> Comments out booming blade related code, nerfs raging boar.

- code/game/atoms_movable.dm
- code/game/objects/items.dm
- code/game/objects/items/his_grace.dm
- code/game/objects/objs.dm
- code/modules/smithing/finished_items.dm
- code/modules/smithing/smithed_items.dm
- fixed a bug that made all smithing effects on weapons disappear if the player two-hand wielded it and then unwielded it (how long has this been the case lmfao)
-  fixed the DPS calculator so it takes extra damage from smithing and sharpening into account (the original scope of the PR)
:cl:
/:cl:
> fixes smithing and damage estimate bugs

- code/__HELPERS/areas.dm
Resolves #429 by adding mineral doors and vault doors to the list of things that count as blockers when checking for sealed areas.
:cl:
tweak: Added mineral doors and vault doors to the list of room sealing objects.
/:cl:
> Expands room_sealers to include more doors

- code/datums/chatmessage.dm
This increases the size of runechat messages to 200, and lengthens how long they're visible.  Yes, this does mean we could have someone spam them, but its a risk I think is worth taking for QOL.
I am also trying to make it so that it checks for the Trait ERPBOTTOM and places the runechat messages BELOW you, but haven't quite got that working yet.  Could use a real coder
@TalkingCactus
@Superlagg
@OverDriveZ
https://gyazo.com/a6117d31c916fcd37bdbb7a9a53c43d6
:cl: …
> Adjusts the Runechat timers/size and adds Bottom Text :tm:

- code/datums/looping_sounds/_looping_sound.dm
- code/modules/projectiles/projectile.dm
-Resolves a runtime involving multiple looping sounds attempting to register to the same signal upon starting. `RegisterSignal` has an `override` param specifically for this.
-Resolves a runtime involving projectiles having their location and trajectory nulled before attempting to run checks based on those two variables by running null checks at relevant times.
:cl:
fix: Fixed a runtime in looping sounds and one in projectile movement.
/:cl:
> resolves two runtimes: looping sounds and projectiles

- code/modules/mob/living/carbon/carbon_sprint.dm
stamina now properly only drains when your sprint buffer is depleted
:cl:
/:cl:
> sprinting bugfix

- _maps/map_files/coyote_bayou/Ashdown-Upper.dmm
So what this PR basically does is maps in the armory a bit more life instead of having everyone pushed up towards the north. So that way if you are a ballistics user you arent crowded in the back of the area but instead crowded around the main parts. I also added five sheets of plastic into the armory. Also now Ashdown has chikens so bakers can get eggs if one of the ashdown / nomads want to do baking week without having to get a biogenerator. Also put sunflower in the pen instead of sunflower speedrunning into the recycler. Below is photos on the details. 
:cl:
tweak: ashdown armory + animal pen
/:cl:
> Map Tweak: Ashdown Armory + Dog + Chikens

- _maps/map_files/coyote_bayou/Ashdown-Upper.dmm
- code/datums/tattoo.dm
- code/modules/mob/living/carbon/human/human_helpers.dm
- code/modules/vending/autodrobe.dm
- code/modules/vending/brahminvendordm.dm
- code/modules/vending/clothesmate.dm
- code/modules/vending/games.dm
- code/modules/vending/toys.dm
- puts tattoo removal functionality into the tattoo gun itself to reduce clutter and adjusts its examine to reflect the change
- adds damage and a chance to scream on removal of a tattoo in order to make it feel more in line with tattoo application
- fixes two small errors with the code that was merged last night.
:cl:
tweak: Tattoo removal is done with the tattoo gun
code: minor error correction with my previous tattoo code
/:cl:
> minor fixes and adjustments to permanent tattoos

- code/modules/mob/mob.dm
adds a slew of new flirt options and helps define this system as being semi-physical. adds text back to the user to know what you did
- Bite your own lower lip fixed
- ear bite
- nuzzle neck
- bite neck
- hold hands (awful, I know)
- fondle chest
- touch crotch
- petting of the heavy variety
- stare at em
- try hard not to look at em
- opnely oogle
- fail pickpocketing
- eyebrowboom but sexual
- kabedon
:cl: …
> Flirt Update - Flirt Harder

- code/modules/mob/mob.dm
More coy flirt verbs.
"Whine needily.",
"Tongue in cheek.",
"Mouth an object.",
"Play with your nipples openly.",
"Play with your nipples sneakily.",
"Draw attention to your breasts.",
"Fold your arms under your breasts.",
"Squish your breasts together.",
:cl:
/:cl:
> Would you believe I can just make these all fucking day?

- code/modules/clothing/head/helmet.dm
- modular_citadel/code/modules/client/loadout/shoes.dm
fixes an issue with the files of the psycho mask + makes regular shoes (not boots) cost nothing since they are cosmetic and offer no benefit or armor.
:cl:
/:cl:
> Mask DMI fix + minor tweak

- _maps/map_files/coyote_bayou/Ashdown.dmm
What this PR does it basically expands the ashdown bar by a singular tile and making it where the potluck doesnt destory the wall anymore that leads to the mirelurk cave plus it also allows more walkroom on the back just incase if someone is rping in the middle and also this PR adds a salt and pepper to the Ashdown bar kitchen fridge.
Salt and pepper in the fridge
:cl:
tweak: Ashdown Bar
/:cl:
> Map Bugfix: Ashdown Bar

- _maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
- _maps/map_files/coyote_bayou/Texarkana_underground.dmm
A, purposefully, very incomplete mapping of a camera system to the Nash and Texarkana map for cameras that the 'radio operator' can use to see what's going on up top.  The gaps are mostly intentional, to stop it from being raw powergaming the job.
:cl:
/:cl:
> Texarkana Traffic Network Pass 1

- code/game/machinery/cell_charger.dm
- code/game/machinery/recharger.dm
Simply put, you can still smack wrenches against rechargers, but they don't unanchor them anymore, to move them you now have to fully disassemble them. Workaround for FIAT power and TG styled recharging guns with non-replacable cells
PS. Staff requested the WHOLE energy weapons idea get kneecapped instead of the 'replaceless cells' TG guns, sorry folks!
- [ X] You tested this on a local server.
- [ X] This code did not runtime during testing.
- [ X] You documented all of your changes.
:cl:
/:cl:
> Applying Superglue to the bottom of Rechargers

- code/game/objects/items.dm
Doesn't work with Dans directional melee system, but does allow anything that can do force and is one handed (ie, not using wielded force) to have a backstab multiplier that we can dial in.
Backstabs only render their bonus damage when DIRECTLY behind the target.
Thanks Cactus!
:cl:
/:cl:
> Adds Backstab Multiplier for one handed attacks

- code/modules/mob/mob.dm
"React - Lose your breath.",
"React - Heave your bosom.",
"Leer - Grin deviously.",
"Leer - Stare at their crotch.",
"React - Lick your lips.",
"React - Purse your lips.",
"React - Shake from their touch.",
"React - Shudder from overstimulation.",
"React - Gasp from something they did.",
"React - Moan at them.",
"Leer - Lid your eyes and watch them.",
"Leer - Sneak a peak at their assets.",
"Touch - Put their HAND between your breasts.",
"Touch - Put their HEAD between your breasts.",
"Touch - Put YOUR HAND between their breasts.",
"Touch - Put YOUR HEAD between their breasts.",
"Touch - Lay a hand on their shoulder.",
Can you tell this was made by a boobman?  Is it obvious?  MMMMM, I WONDER
:cl:
tweak: tweaked a few …
> More flirts

- code/game/objects/items/loadout_beacons.dm
- code/modules/projectiles/guns/magic/staff.dm
- code/modules/projectiles/guns/magic/wand.dm
- code/modules/projectiles/projectile/magic.dm
Adds a new staff to the spawn loadouts per fenny's request and some minor balance tweaks with magic things.
:cl:
- Added the triheal staff to loadout
- Changed the triheal staff to basically be a healing RCW
- Buffed the healing wand/staff so that the triheal staff isn't just outright better. May need to go back and raise their recharge time a little in the future?
:cl:
> Loadout Healstaff and some minor heal magic balances (Good to go if it passes checks)

- code/modules/projectiles/projectile/beams.dm
- code/modules/projectiles/projectile/plasma.dm
- code/modules/surgery/bodyparts/_bodyparts.dm
Title. Makes it so laser/plasma projectiles are considered 'sharp' and can cause bleeding. Temporary fix for lasers/plasma weapons not actually doing anything at high Wound levels. Should also indirectly fix some Wound issues with melee too.
:cl:
- Lasers are now sharp and pointy
- Plasma is now sharp and pointy
- Something changed in _bodyparts to make it so that burn-damage weapons can cut and bleed you
:cl:
> HOTFIX - Energy Weapon Wounding (Good to go if it passes checks)

- code/datums/traits/good.dm
- code/modules/mob/living/simple_animal/simple_animal.dm
- Removed smithing quirks from creatures since they weren't working correctly.
- Fixed lazarus injected mobs and second-winded creature players not being able to move until they used the rest command.
> couple bug fixes

- code/game/objects/items/arrow_crafting.dm
bodkin arrows were making broadheads
:cl:
fix: arrow crafting should be okay again
/:cl:
> silly little arrow crafting bug

- code/__DEFINES/mobs.dm
- code/__DEFINES/traits.dm
- code/controllers/subsystem/traumas.dm
- code/datums/brain_damage/phobia.dm
- code/datums/traits/negative.dm
- code/modules/surgery/bodyparts/_bodyparts.dm
People very rarely take negative quirks. Clean veins gave you more points than a literal brain tumor.
This should make negative quirks still a debuff that you feel, but they aren't all debilitating. 
• Blood regeneration can no longer be cheesed _as much_ by making people fat.
• Blood Deficiency is no longer fatal and will cap at 30% volume.
• Glass bones and paper skin combined into one 'easily wounded' quirk.
• A bunch of point changes, spawning without prescription glasses and being near-sighted gives less bonus points than being near-sighted and spawning with them.
• Brain tumours are now -30 points due to the removal of plumbing and chem dispenser changes making mannitol a bigger pain the butt to produce for the entire round.
• Deaf and Paraplegic now give you a lot more points. …
> Negative Quirk rebalancing & QoL

- _maps/map_files/coyote_bayou/Redwater.dmm
There was a few rogue tiles they are gone now.
:cl:
tweak: redwoter z level
/:cl:
> Map Bugfix: Redwater Z Level

- code/modules/fallout/turf/house_wall.dm
- code/modules/fallout/turf/walls.dm
Allows you to apply a new paint to pre-war house walls to make it look brand new.
turn /turf/closed/wall/f13/wood/house to /turf/closed/wall/f13/wood/house/clean using "5 use" of spraycan.
also makes the wall use new smoothing because why not.
puts the house walls in it's own .dm to make wall.dm less cluttered.
> House Wall Restoration

- code/modules/clothing/neck/_neck.dm
- modular_citadel/code/modules/client/loadout/neck.dm
scarf-capes are unselectable because they have `+` in the name. i changed them all to `w/` and now they work.
:cl:
/:cl:
> fixes scarf-cape loadout names

- code/modules/fallout/turf/ground.dm
- modular_coyote/code/modules/turf_changes/PlantGrass.dm
makes foragables spawn more reliably
the chance can be edited by changing the MEDICINAL_PLANT_CHANCE define
:cl:
/:cl:
> increases foraging dopamine

- code/game/objects/structures/flora.dm
- code/modules/fallout/obj/structures/wasteplants.dm
- modular_coyote/code/flora_coyote.dm
Any flora object will now automatically generate a (roughly) correctly sized transparency zone so you can add as many trees as you want and we can still see.
:cl:
/:cl:
> automatic flora transparency

- code/__DEFINES/armor.dm
Funkles with armor defines to help flesh things out. Mostly makes heavy+ armor better as well as some other small tweaks.
:cl:
- Buffed Heavy armor from 40 EHP to 60
- Buffed SPA to +110 and +130 EHP
- Buffed PA to +140 and +160 EHP
- Buffed Light Armor's Wound protection barely
- Gave clothing pity melee armor (mostly for RP flavor, tbh)
- Increased real PA rad protection to 60
- Increased Light armor slowdown to 0.15 to give you an actual reason to go naked, and to make the few less_slowdown Light armors actually have a reason to have that token
- Decreased Medium slowdown from 0.5 to 0.40
- Decreased Heavy slowdown from 1 to .80 because it's weird that it's as slow as PA but worse in literally every way; It's almost effectively half as good as SPA as well, meaning the difference in …
> Armor Tweaks and Adjustments (Needs vulpine approval but otherwise good to go)

- code/modules/projectiles/projectile/magic.dm
Title
:cl:
- Fireball staff now checks Bomb-type armor, not Magic
- Fireball staff now does 40+10 to 90+10 damage vs players
- Fireball staff now has 200 base bane damage instead of 169 (200 to 250 NPC damage, except against Enclave)
- Fireball staff now has a more impressive fireball effect when it impacts
:cl:
> Fixes the fireball staff (Good to go if it passes checks)

- code/_onclick/item_attack.dm
- code/modules/projectiles/projectile.dm
Fixes some issues that came with pacifism lesser, now it's possible to bap people with items that are harmless (such as "play claws" or plushies) and it's also possible to use healing wands without getting traumatized and of course all other projectiles that are considered harmless.
:cl:
tweak: tweaks lesser pacifism.
/:cl:
> Tweaks Pacifism Lesser [ready to merge]

- code/modules/projectiles/ammunition/caseless/_caseless.dm
- code/modules/projectiles/boxes_magazines/internal/rifle.dm
- code/modules/projectiles/guns/ballistic/automatic.dm
- code/modules/projectiles/projectile/bullets/pistol.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
Buffs wounding of the needler projectile.  Adds two custom loadouts. Needler projectile can embed at a 25 percent chance, subject to change. Needler now has 10mm wounding, making it more dangerous to be shot by despite having very low damage.
:cl:
/:cl:
> (MERGE WHEN POSSIBLE) Loadouts + Needler buff

- code/modules/vore/eating/belly_obj.dm
Having mobs in your guts no longer slows you down.
However, any mobs who are horked up will be hard stunned for around 10 seconds.
> Removes vored mob based slowdown

- code/modules/clothing/suits/arfsuits.dm
- modular_citadel/code/modules/client/loadout/__donator.dm
Removes the aug and changes the armor to a custom medium armor.
Can probably just have the populate contents block change the name and desc to not make an entirely new subtype of the armor, but I cant remember how to do that right now.
> Tweaks Aldric's Loadout

- _maps/map_files/coyote_bayou/Garland-City.dmm
What this PR does is basically makes the diner in garland relevant. It has cleaned up into more of a modern style instead of what it used to be and expands it a little bit so you have more room and gives it food inside so you can already eat. Also there has been added upgraded drink machines. This feels like it brings more of that classy diner vibe and some candles in the freezer area just incase if someone wants to buy out the diner for a romantic dinner or two. Below photo is how it looks now
Also what else is added is a seed extractor with a little tweak of moving the compost off to the side
Also most of the railing has been fixed and deadbolts so people can actually walk by the railing instead of avoiding it completely. 
:cl:
Tweak: Gaaarland Texarkana
/:cl:
> Map Tweak + Bugfix: Garland

- code/datums/components/spawner.dm
Check only against player mobs on the spawner's Z to save cycles
:cl:
/:cl:
> Only compare against player mobs on their own Z

- code/datums/components/crafting/recipes/recipes_medicine.dm
Adds normal lunchbox to be useable for the improvised defib recipe.
Felt silly that the recipe requires the custom lunchbox that fallout has while the base ss13 lunchboxes are useless
:cl:
add: Normal lunchbox to defib recipe
/:cl:
> Adds normal lunchbox to defib recipe

- code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
Peanut butter brownies required 5 of lower case peanut butter JARS instead of the reagent. Now it's happy with 5u of actual peanut butter.
:cl:
fix: Peanut butter brownie now makeable
/:cl:
> Fixes peanut butter brownie recipe

- code/game/objects/structures/bedsheet_bin.dm
• Adds the code-block for setting down 
• Changes desc of blankets and bedsheets to inform players how to tuck in.
:cl:
qol: You can now tuck yourself into bed by using the bedsheets in your hand.
/:cl:
> Lets you tuck yourself in underneath blankets, because blankets exist separately from bedsheets for some reason

- modular_citadel/code/modules/client/loadout/__donator.dm
Switches the handle of the four loadout items to ckey 'prismaticnova'. Nothing fancy. 🐺
> Loadout Stuff Ckey Migrate

- code/modules/food_and_drinks/recipes/tablecraft/recipes_burger.dm
Craft the pizza instead of pizza slices.
:cl:
fix: When you make a pizza, 80% of it doesn't instantly vanish.
/:cl:
> Fixes those modular pizza crafting recipes

- code/modules/reagents/chemistry/machinery/chem_dispenser.dm
This is basically adding cucumber juice to the drink dispenser, as it was forgotten long ago, so now you can come up to bar and ask for a cucumber lemonade or cucumber related drinks without waiting a year to get it. More for the roleplayers of the server instead of waiting a year for a singular drink. 😋 
:cl:
add: Cucumber lemonade drink machine
/:cl:
> Drink Machine Addition: Cucumber Juice & Amaretto

- code/modules/mob/mob_transformation_simple.dm
Unironically the first bug I've been really impressed by on this codebase, *hopefully* prevents this from happening again. 
Love it. Simple basic network replication issues I encountered during all my uni work this semester simply showing up with BYOND's netcode! Though, it's not their code which is the issue, it's our codebase not being safe for concurrent issues such as that.
If anyone's wondering, basically when a observer leaves the game, the ghost they have is deleted. However with our changes to garbage collection, Fenny nullspaces it, so on that same tick now after the player disconnected on the same frame the spawn mob proc is called, that ghost is in nullspace, and it's src.loc is `null`, so that mob is now instantiated into nullspace.
Simple one line of code to make sure src.loc …
> Prevents ghosts from spawning mobs in nullspace mid-disconnect.

- code/game/objects/hand_items.dm
Makes the strongest variants of the biter, tailer, and clawer trait items do 40 force instead of 30, as the armblader did 40 already yet cost the same.
Also changes sabre toothed biter cooldown mod from 0.7 to 0.8, since that seemed like a typo, given the other two had 0.8
> Equalizes Biter, Tailer, Clawer To Match Armblader

- code/modules/projectiles/guns/energy/plasmaf13.dm
Fixes the guns in the loadout that're supposed to have self charging.
Covpistol and Covrifle are the two guns! Original creator of the guns is Tox.
> Self Charging holdout guns

- code/game/objects/items/stacks/sheets/sheet_types.dm
- modular_coyote/code/objects.dm
Title, basically. I just added a list to the cloth stack-craft menu to make the rugs.
You can also deconstruct them the same way as clothes (Knives, wirecutters, etc.)
:cl:
add: Added the ability to craft rugs
/:cl:
> Makes rugs and mats craftable

- code/modules/mob/dead/new_player/preferences_setup.dm
Fixes the character creator button to change background from complete void and black:
:cl:
fix: fixed character setup "change background" button
/:cl:
> Fixing the character setup background not showing [ready to merge]

- code/modules/jobs/job_types/hells_nomads.dm
What this PR does is adds sunnies and datapal to the most baddest toughest biker gang that eats nails for breakfast, and now they just gotten cooler then what they were before. Finally coming in with sunnies and datapal in the beginning as it seemed like everyone else gotten one but them. 😎 
:cl:
add: sunglasses + datapal to Nomads 
/:cl:
> Job Equipment Tweak: Nomad Sunnies + Datapal

- modular_citadel/code/modules/client/loadout/__donator.dm
Fixed the ID description to remove mention of the BoS, as well as removing the BoS gun.
Also yeeted the prism glasses. A bit too OP considering what you usually have to go length wise to get. ._.
> Loadout final loose ends (prism saga)

- code/modules/food_and_drinks/recipes/tablecraft/recipes_cake.dm
- code/modules/food_and_drinks/recipes/tablecraft/recipes_donut.dm
- code/modules/food_and_drinks/recipes/tablecraft/recipes_pie.dm
What this PR does is finally readds vanilla cake, clown cake, chocolate lava tart and berry tart. Which was disabled for some reason I believe it was dr2 code back in the day. :D
:cl:
tweak: a few food code that was always avaliable.
/:cl:
> Food Readdition: Cakes and Tarts

- code/datums/brain_damage/severe.dm
- code/datums/elements/mob_holder.dm
- code/modules/mob/living/simple_animal/animal_defense.dm
- code/modules/mob/living/simple_animal/friendly/farm_animals.dm
- config/maps.txt
Monophobia, technically classified as severe brain injury in the code, actually gave me severe brain injury as well, while I was trying to fix it.
Now monophobia checks hands content and backpack contents as well! Meaning, you can carry your beloved pet in your bag and still feel their presence!
Edit: as someone pointed me out, pet animals were laying dead after being released on the ground, so I understood where the issue was and fixed it.
:cl:
tweak: tweaked monophobia to behave in a less dumb way.
fix: pet animals don't lay dead after being released.
/:cl:
> Monophobia checks hands and backpack too; Animals can get up on their feet after getting tipped [ready to merge]

- _maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
- _maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
Adds a few quality of life bits to the Den, reworks a few of the parts of the map, and adds some materials to bring it up to basic par with a few other settlements.
Behold, grassification and a central park with benches:
Adds a blender and a primitive defib instead of a regular defib to the Den clinic: 
Reorganzies the garden, adds a compost bin, harvest bin, seed extractor and seed bin, as well as an animal pen and tools! (And fixes the bridge having collision):
Adds 50 metal, 50 glass, and 50 blackpowder, and a toolbox to the workshop, as well as a sledge and a set of smithing gloves to the anvil room to bring the Den up to par with other map-spawn workshops:
Adds a boxing ring to the upper floor, complete with a pair of gloves for good old fashioned fisticuffs: 
Adds benches to the …
> Den QoL and Beautification

- code/datums/traits/good.dm
- code/modules/projectiles/multichance_projectile_hit_behaviour.dm
- config/maps.txt
Headshot:
-50% prob of landing a headshot --> +50% raw damage on the projectile;
-25% prob of dealing regular damage and not triggering any gimmick;
-25% prob of completely missing the shot.
Shoulders hit:
-75% prob of landing the shot --> mob deals -25% damage for 3 seconds;
-25% prob of dealing regular damage and not triggering any gimmick;
-Bullet always deals -15% damage, no matter what;
-If the hit is successful then timeout of 6 seconds total, in which this gimmick can't be triggered again (so it can't be stacked more than once at the same time).
-If the hit is successful, a chance of stunning the mob will be calculated, the percentage of this event triggering is function of projectile damage and damage threshold of the mob. (Basically, high damage projectiles have higher chances of …
> Multichance projectile hit behaviour v1 (MCPHB v1) [ready to merge]

- code/_globalvars/lists/maintenance_loot.dm
- code/game/objects/effects/spawners/masterlootdrop.dm
- modular_coyote/eris/code/mods/mod_types.dm
Thanks to other devs, this actually works how it should now!
Random stats from -35% to 45%. Might get the best mod or trash, good luck!
Also removed the second bluespace paint. It was brought to my attention that two separate ones were unneeded due to the random variety. They can go on any gun, but some might be better on a specific gun type (for obvious reasons).
> Fixes the bluespace paint stats

- code/game/machinery/autolathe.dm
This PR aims to fix a fundamental logic error in the auto lathe. When attempting to capture the largest quantity of an object that it can print, the lathe experiences two different types of mathematical error:
1. The lathe does not handle if any materials in the recipe require a zero quantity. Due to a bug that I cannot find, some materials list a requirement of 0 black powder, which causes a divide by zero error and breaks the UI.
2. The lathe incorrectly shows the total quantity that can be printed as limited by only the last material checked. Therefore, it may display a number that is impossible to print with the provided materials.
:cl: …
> Attempt to fix autolathe logic

- code/modules/WVM/wvm.dm
Might as well do this. 
Gold paint is 20 coins more cause better than red paint. 
Bluespace paint is only 50 but you arent guaranteed a good mod out of it cause of its randomized nature.
> Bluespace and Gold paint buyable at shop

- _maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
- _maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
- _maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
Completely and utterly changes every part of the Den, adds 2 new ruins and a bunch of mineable rock to the uppermost Nash z-level, with barrier walls between dungeons obviously left intact.
New Den Z-2: 
New Den Z-3: 
New Ruin 1, Raider Cabin:
New Ruin 2, Machine Shop:
Post Machine-Shop Reward, isolated mountain house, figured a livable area instead of a ton of loot might be cool as a prize:
:cl:
add: Two new ruins, mineable rock added to upper Tex-Arkana.
del: Removed Old Den
tweak: Entirely New Den
/:cl:
> Den and Nash Upper 2 Facelift

- _maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
- _maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
Fixed the bolts in all the Den's doors so they no longer all face South. Used the opportunity to put carpets and rugs in more of the rooms, added glass floors so you can ogle things, and, most importantly, re-adds the soul.
Bolts: 
New Rugs and Carpets: 
And of course, the Soul, which I was confused about before, but now understand, at least so I think: 
:cl:
add: New carpets and rugs
fix: Missing roof and 'soul' from the protectron trader, bolt directions.
/:cl:
> Fixes Den Bolts, Adds Carpet, Re-adds Soul

- code/controllers/subsystem/second_wind.dm
- code/modules/reagents/chemistry/reagents/medicine_reagents.dm
-stop re-init'ing second wind lives when a new mob is found
-no more `nods along to` when at full health
:cl:
/:cl:
> second wind and toe tapping fixes

- code/game/objects/items/melee/coyotemelee.dm
We hear you.
:cl:
fix: Old Bokken can no longer be abused to insta stamcrit people.
/:cl:
> Old Bokken no longer applies stamina damage on click regardless of click cooldown

- code/modules/mob/living/living.dm
ALT+Clicking with HELP intent on a carbon retrieves one of the 3 healing emotes (lick, touch, tend with this order) and autoheals them without the need for a keybind for the "triages".
:cl:
add: Adds Autotriage
/:cl:
> Autotriage [ready to merge]

- _maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
- _maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
Adds the Garland vendors to the Den as per request from Fenny. The guns, ammo, armor, and trading machines are in a new building out the East exit, with a mining vendor next to the ORM and a smart-fridge now placed in the chemistry lab.
Also adds an art room and lounge above the new vendor room, because why not?
Vendor room:
Mining vendor: 
Smartfridge (Becoming Nook and other vendor now added to storage closet):
Art room/Lounge: 
:cl:
add: Den vendors, art room, smart-fridge
/:cl:
> Den Vendorification

- modular_citadel/code/modules/client/loadout/__donator.dm
Kilmented gave my loadout the wrong coat. Fixing it myself to make it faster, look at my ticket if you need context.
:cl:
fix: Changes the light-armour duster to the medium-armour variant
/:cl:
> Fixes the loadout again

- _maps/map_files/coyote_bayou/Ashdown.dmm
What this PR does is fix the booths of Ashdown and adds a bit more lights inside.
:cl:
bugfix: ashdown
/:cl:
> Map Bugfix: Ashdown Booths

- code/modules/mob/living/carbon/emote.dm
Basically, Fenny asked me to make the double click function of the autotriage button bound to a shortcut on the keyboard.
To which I thought.... what if simply calling the triage emote twice using the same key on the keyboard, would also start healing yourself?
I played with this little logic a little bit and it honestly feels quite good
tl;dr: doublepressing the key that calls one of the triage emotes initiates healing automatically.
:cl:
tweak: tweaked autotriage
/:cl:
> Autotriage III [ready to merge but evaluate yourself first]

- _maps/map_files/coyote_bayou/Newboston-Upper.dmm
- _maps/map_files/coyote_bayou/Newboston.dmm
- _maps/map_files/coyote_bayou/Redwater.dmm
This should be removing most of the Ave and Doogmen doors that were access locked and also fixes the Rangerdangers garage up a tad bit including the garage door finally opens.
:cl:
remove: faction doors
/:cl:
> Map Fix: New Booston + Redwater 'faction' doors removed

- code/modules/cargo/exports/materials.dm
Title
:cl:
- Adamantine / Pre-War Steel Ingots have had their value per 2000 units lowered so their value isn't 6x what it should be
- Mythril / Rose Steel Ingots have had their value per 2000 units lowered so their value isn't 6x what it should be
:cl:
> Fixes a pair of infinite money glitched (good to go if it passes checks)

- code/game/objects/items/stacks/medical.dm
Allows people to move while healing using one of the 3 healing emotes, but everything else still requires to stand still.
For example, the player can't use sutures while moving, but can lick their own butt on the go.
:cl:
tweak: tweaks how licking butts works
/:cl:
> Allows people to move only when using the tend emotes [ready to merge]

- code/game/objects/effects/spawners/masterlootdrop.dm
- code/game/objects/items/loadout_beacons.dm
Makes the needler pistol the roundstart get item instead of the two 'rifles'.
The two 'rifle' needler were moved to the master loot system
> Needler loadout roundstart changes

- code/datums/components/reskin.dm
- code/modules/projectiles/guns/magic/staff.dm
- config/maps.txt
Adding the component we already have to make kelpmagic staves reskinnable.
Staves can be reskinned in "shaman staves" now.
I also modified the reskinnable component to fetch the lefthand and righthand files, this way it's possible to give unique sprites to weapon that require it!
:cl:
add: Adds reskinnable component to staves.
tweak: Modified the reskinnable component to accept lefthand and righthand files as well.
/:cl:
> Reskinnable Kelpmagic Staves [ready to merge]

- code/game/machinery/computer/dna_console.dm
Since research is already boring, might as well make genetics less slow so it can be finished early, just like the rest of the time-gates research stuff. Basically just cuts joker timer in half, which allows for faster goofing off with genetics. Doesnt make the powers any more useless than they already are tho. |D
> Makes Genetics Less Tedious

- code/modules/projectiles/guns/ballistic/automatic.dm
Because 800 rounds a minute with an average of +25% from a single mod (1000 rpm) and then maybe, say 33% boost from gold paint is 1330 rpm on a weapon that has high wounding (while most folks wear light armor) and insane bane.
This ACTUALLY brings it down to NORMAL LMG rate of fires.  I'm biting Tox on the b-tooty
:cl:
server: something server …
> Halfs the needler lmg rof

- code/game/objects/items/stacks/sheets/sheet_types.dm
:cl:
add: Made metal tins craftable with metal instead of cloth
add: Made coin purses craftable
/:cl:
> Made cloth create coinpouches and metal create metal tins

- code/datums/elements/flavor_text.dm
- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/mob/living/carbon/human/human.dm
- interface/interface.dm
Adds a box inside the character editor where people can copy-paste their F-list.
The system asks people if they want to open up said link on the browser before actually doing so and as an addendum it also shows what link is about to open in the alert box.
This little logic is also capable of recognizing if the link placed in doesn't belong to "https://www.f-list.net", in case people put other (maybe malicious) links in.
If people don't put any link in this box, it won't even show the [F-list link] option in their examine text.
:cl:
add: Adds F-list link
/:cl:
> F-list hyperlink as flavour text option [ready to merge]

- code/game/objects/items/shields.dm
So, this doesn't touch the loot shields for the most part (at least, not their armor amount)
What this does do is lower them all to be 20-15-15-0.  Then it adds a force of 12, wielded 20.  Then it lets you also use them as melee weapons directly.
This means you can dual wield with your shield, using it with a single handed melee weapon.  It also adds directional melee attacks to them.
It also means you can't round start scoop up to 90 fucking melee armor, lmao
:cl:
spellcheck: fixed a few …
> Shields Adjusted & Expanded

- code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
- modular_coyote/eris/code/mods/mod_types.dm
Adds crafting recipes to reroll orange, purple, and green paint.
Fixes the black paint to require orange, purple, and green paint.
Adjusts the move delay for the paint to always be positive and quite high. It only seems to affect guns that slow you down like antimaterial rifles anywho.
> Paint, and Propaint accessories

- code/datums/components/crafting/recipes/recipes_primal.dm
- code/modules/clothing/suits/arfsuits.dm
Makes the Light and Heavy Tribal armor easier to craft with materials more fitting their descriptions.
Reduces the material cost of the Light Tribal Cloak.
:cl:
tweak: tweaks some armor recipies for tribals
/:cl:
> Makes some tribal armors easier to craft. [READY TO MERGE]

- modular_citadel/code/modules/client/loadout/backpack.dm
- modular_sunset/code/modules/clothing/head/f13head.dm
- modular_sunset/code/modules/clothing/under/accessories.dm
Adds flavored text descriptions for the GWTB helmets and caps.
But honestly I just wanted to make chest and arm patches free in loadout, I don't know why I did that too.
:cl: Anonymous
tweak: Additional (poor) flavor descriptors for Blastwave helmets and peaked caps.
tweak: Generic chest and arm patches in loadout are now available for free.
spellcheck: Generic chest and arm patches default description: "six-pointed" -> "eight-pointed" (it is more close to the sprite look).
/:cl:
> Generic chest/arm patches are made free, plus GWTB afterthought (why)

- code/modules/mob/living/emote.dm
Potentially makes the faint emote work by commenting out a duplicate datum
:cl:
tweak: potentially made faint emote work
/:cl:
> Potentially makes the faint emote work

- _maps/map_files/coyote_bayou/Newboston-Upper.dmm
- _maps/map_files/coyote_bayou/Newboston.dmm
- _maps/map_files/coyote_bayou/Texarkana_underground.dmm
This is my final attempt at making townie jobs work.
For the sake of not having to repeat myself for the 700th time this is why I've made this map change that smushes the bar, the clinic, the shopkeep, and the banker together.
Every single stationary job that we have that relies on players working out of a single location is a newb trap.  I have watched, for a year and a half as players who are new take these jobs (as well as preacher, librarian and a few others) and basically lock themselves into their 'department' and hope for the best when it comes to finding roleplay.  It does not work. It has never worked.  Even a particularly vocal shopkeeper, bartender, or banker, can often be completely excluded from roleplay (or its child object, erotic roleplay) entirely because they exist in a …
> One final hurrah for the stationary jobs

- code/modules/cargo/packs/security.dm
Adds the first pass of weapons into the shop to be bought without randomization.  Using cactus's gun proc it only includes some of the guns from the first 100.
We have 500 guns+ to add to this list, and we shouldn't add all of them.
:cl:
/:cl:
> The Gun cargo-ening part 1

- code/datums/components/crafting/recipes/recipes_misc.dm
Makes picket signs require wood instead of the ever elusive cardboard
:cl:
/:cl:
> make picket signs require wood

- code/datums/traits/neutral.dm
Hydra head is heavily flavored to use language heavily implying the existence of multiple on your body, obviously, but also mentions this ability can be used to have multiple personalities, all I did was flip this around, now its a trait that heavily implies multiple identities, but mentions this ability can be used to have multiple heads
:cl: …
> Make hydrahead more open ended of a trait

- code/modules/mining/lavaland/necropolis_chests.dm
It shouldn't have been in the loot pool in the first place.
> Godeye and Cult Teleport Sword Removal

- code/game/objects/effects/spawners/masterlootdrop.dm
- code/modules/WVM/wvm.dm
Tweaks the medical WVM to only sell low-quality supplies at a high price, adds a machine for the clinic interior to promote them actually selling stuff, and largely axes stimpaks from loot.
:cl:
- Standard medical WVM lost the medkit, replaced standard bandages/sutures with improvised versions, and generally increased prices.
- New clinic-specific WVM for medical supplies that sells bulk meds, standard bandages/sutures, and is generally cheaper.
- Removed Stimpaks from the Common medicine loot pool.
- Replaced Stimpaks with Bitter Drinks (Bitters are like ~40%? better than Poultice, while Stims are almost flatly 100% better) in the Uncommon medicine loot pool.
- Lowered Stimpaks to '4' weight in the Rare medicine loot pool and Super Stims to '1' in the same tier.
:cl:
> Overhauling Medical Vendors (DRAFT, DO NOT MERGE)

- code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
Should fix the issue of it dropping wood instead of metal, its construction material
:cl:
/:cl:
> Makes craftable shelf drop metal instead of wood

- code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm
for real this time
(For real this time), should remove the thing that makes all the child objects call the parent object, and therefor, make them drop wood. Stupid wood. I should have just made the recipe 10 wood
:cl:
/:cl:
> Makes craftable shop shelves not drop wood

- _maps/map_files/coyote_bayou/Newboston-Upper.dmm
- _maps/map_files/coyote_bayou/Newboston.dmm
- code/__DEFINES/access.dm
- code/__DEFINES/jobs.dm
- code/datums/datacore.dm
- code/game/machinery/computer/communications.dm
- code/modules/jobs/job_types/oasis.dm
- code/modules/jobs/jobs.dm
- code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
- Integrates Clinic into Guild Space
- Integrates Clinic upstairs into Guild Space
- Re-enlarges the Bank space slightly, but should make it more streamlined
- Integrates Bar into Guild Space
- Integrates Library into Guild Space
- Moves Farm to where Clinic was
- Overhauls main area of Heavens Night (not the park)
- Moves Well of Souls into the Dump (lol)
- More Green space in New Boston
Needs some things done, hopefully @PrettyPsychoForAWolf can do me some stuff today and we can roll this out this afternoon.
To do
> New Boston Update - The Guildening & Heavens Night Overhaul

- code/modules/WVM/wvm.dm
due to the laws of supply and demand
no one wants to buy them when there's loads on the sand
> but the value of those MF C cells will fall

- code/datums/components/storage/concrete/pockets.dm
- code/modules/clothing/suits/arfsuits.dm
Saddles can now actually hold items. They can hold about as much as a belt, which feels fitting for saddlebags.
:cl:
add: a new pocket type for "saddlebags"
tweak: gave all taur-saddles the new "saddlebag" pocket type
/:cl:
> Saddle Storage Fixes

- code/modules/arousal/genitals_sprite_accessories.dm
- code/modules/arousal/organs/breasts.dm
Fixes the description for the new "Pair(round)" breast shape to display the same description for a regular pair of breasts rather than "exotic"
:cl:
fix: breast descriptions for new breast shape
/:cl:
> Bazonger fix

- code/__DEFINES/radio.dm
- code/game/objects/items/devices/radio/encryptionkey.dm
redefines the "changeling" mode keys so that it's no longer conflicting with the guild key, letting the radio now work.
:cl:
fix: guild radio key and changeling mode key conflict
/:cl:
> Guild radio fix

- _maps/map_files/coyote_bayou/Dungeons.dmm
- _maps/map_files/coyote_bayou/Newboston-Upper.dmm
- _maps/map_files/coyote_bayou/Newboston.dmm
The extract room as 8 total different handpicked crossbreeds. They aren't as op as say xenobotany though.
infinite use: (requires specific numbers of plasma per use)
Industrial Red = Blood orb
Industrial Cerulean = Extract enhancer
Industrial Purple = Regen jelly autoinjector (slightly stronger than tricord)
Industrial Light pink = free chocolate!
One time use: (one time of 10 plasma)
Chilling silver = ration packs
Chilling grey = barrier cubes
Chilling pyrite = prism glasses
chilling darkblue = wow mages ice block spell
> Makes Xenobio's Pens Slightly bigger and Adds a special extract room

- modular_coyote/code/creature_species.dm
This should fix toxins processing and hunger on mechs. The reason why I added easy dismember instead of nodismember is that I don't think its possible to dismember people regardless of the traits, and I wanted to make it as close as possible to synthliz.dm so that sleep healing hopefully works on mechs. 
!! I cannot test these changes, because my test server really hates the adapted species, and they do not appear regardless of what I do !!
:cl:
code: changed …
> Fixing toxins hunger processing on mechs

- code/modules/cargo/console.dm
Makes the supply shuttle console confused, and call it a train instead, which is what we want it to do. Admins have to suffer as the logs still call it a train
:cl:
/:cl:
> um aktualli, its a train, not a shuttle 

- code/datums/components/crafting/recipes/recipes_misc.dm
- code/game/objects/items/stacks/sheets/sheet_types.dm
See title, makes cardboard craftable, 5 sheets per crafting. This is roughly equivalent with paper crafting if you were solely using it for paper sacks. 
:cl:
/:cl:
> Makes cardboard craftable

- code/modules/projectiles/boxes_magazines/internal/misc.dm
The brick launcher can (supposedly) hold 3 bricks instead of 1, each brick is about 60 damage, compared to many other options, I think this is balanced and make it a weapon instead of a gimmick
:cl:
/:cl:
> Makes experienced builders atleast 6900% more powerful

- code/modules/research/designs/weapon_designs.dm
Makes /obj/item/shield/riot for the tele shield be /obj/item/shield/riot/tele. It was giving a regular ol riot shield instead of the telescopic one.
> RnD Telescopic Riot Shield design fix

- code/datums/traits/good.dm
- code/modules/mob/living/carbon/human/human.dm
This is just a fancy way of saying that I added a trait that shoves a workbench/alchemy table up your ass and comments out all the code that gives ferals/taurs an advantage on buckling over other people, now you can carry your bottoms on your back without having to be a pokemon and still use your guns
:cl:
server: something server ops should …
> Adds crafty and tinkerer traits, and standardizes mob buckling

- _maps/map_files/Pahrump-Sunset - Backup/RedRiver.dmm
- _maps/map_files/Pahrump-Sunset - Backup/RockSprings.dmm
- _maps/map_files/coyote_bayou/Ashdown.dmm
- _maps/map_files/coyote_bayou/Redwater.dmm
- code/datums/components/artifacts.dm
- code/datums/components/remote_materials.dm
- code/datums/materials/basemats.dm
- code/game/objects/effects/spawners/f13lootdrop.dm
- code/game/objects/effects/spawners/masterlootdrop.dm
- code/game/objects/items/stacks/rods.dm
- code/game/objects/items/stacks/sheets/sheet_types.dm
- code/game/objects/structures/icemoon/cave_entrance.dm
- code/game/turfs/simulated/minerals.dm
- code/modules/mining/machine_redemption.dm
- code/modules/mining/ores_coins.dm
- code/modules/reagents/chemistry/reagents/other_reagents.dm
- code/modules/research/designs/autolathe_designs.dm
- code/modules/research/designs/smelting_designs.dm
Removes the material and reagent known as 'lead'(leadacetate is unaffected as it is actually not lead). Unlike other materials that are properly interspersed throughout the proto and autolathe fab list, lead is entirely useless due to being a vestigial material no longer in use. Even for the alloy recipe(changed to iron) it doesn't work due to some unknown bug, and lead cannot be put back into the ORM. ATM lead just serves to be an annoyance with no real purpose outside of the niche use of what anomalous cubes are pathed from and reducing mining yields by roughly 10% or so(im not doing the full math im sick of stats). However they have been changed to instead default metal (will never actually happen due to them only being made by players, and metal already existing). 
Private server …
> Removes vestigial lead

- code/modules/projectiles/guns/magic/staff.dm
- code/modules/projectiles/guns/magic/wand.dm
legalize nuclear bombs
Wands changed to a concept of low mag cap with quickish recharge.  Thusly high burst damage but poor sustain.
Staffs buffed to not be dogshit, oh and I fixed the low power fireball staff.  It was accidently using the actual fireball not the lower power one 😩 
https://www.youtube.com/watch?v=Tq1Kl1luIjA
:cl:
server: …
> Shadow wizard money gang (buffs wands and adjusts staffs)

- code/game/objects/items/holy_weapons.dm
- code/modules/projectiles/guns/magic/staff.dm
- code/modules/supplykit/supplykit_items/supplykit_magic.dm
The acid staff now has super-effective, meaning it will always deal atleast more than 5 damage to the target, also you basically cant run out of charge with it, it recharges almost as fast as you use it, should now be a super sustainable weapon for wizards, instead of having to use 3 shots to kill a rat.
Also, the nullrod is now selectable, I buffed the prayer beads to be better than just normal tending, tested alongside methods that boost your progress bars, like the utility hunting horn, I think its in a good balanced spot right now, It doesnt nullify other healing items but it does supplement if you have them. (Its brute/burn healing is about double the effectiveness of normal tending, works on robots, and applies minor blood regen, and good radiation healing)
:cl:
add: Added new …
> Improves the nullrod and makes it choosable, also buffs the acid staff

- code/modules/projectiles/guns/magic/wand.dm
The damage is in a good spot if it didnt have so many charges. It can one shot most trash mobs like ghouls, rats, pillbugs, bloatflies, and two shot most mid-tier trash mobs withheadshots, like handies. This makes it so you should really be carrying more than one spark wand, instead of one being all you need
:cl:
server: something server ops …
> Nerfs the spark wand a little

- code/modules/projectiles/boxes_magazines/ammo_boxes.dm
Turns out, a change from a year ago swapped the icon .dmi location from icons/fallout/objects/guns/ammo.dmi to just /obj/ammo.dmi . This will fix it,  nya.
:cl:
/:cl:
> (MERGE) Finally fixed

- code/modules/projectiles/guns/magic/wand.dm
- code/modules/projectiles/projectile/magic.dm
Made shotgun be the magic missiles gimmick, instead of just the improvised spark wands gimmick. For the absolute life of me, this code CANNOT have a shotgun with an initial spread higher than 1 degree, I've beat my head into a wall for 4 hours messing with added_spread, variation, distro, all that, nothing worked, my head broke, not the wall
Magic wands just shoot 6 projectiles and have long recharge times now, being a shotgun is their gimmick. The improv spark wand was changed to be an anti-trash wand that SHOULD be less capable of fighting mobs mid-tier or above now, but has the fastest recharge in the came, if the least capacity
:cl: …
> Adjusts wands, also justifies toxinlover negative traits cost

- code/modules/mob/living/carbon/human/damage_procs.dm
For humans, at least.
So, turns out if something tries to change your health really really *really* soon after something else tries to, it'll be dropped. This meant artifacts would keep blocking sleep healing. Should no longer be the case.
> Fixes iframes

- code/modules/mob/living/simple_animal/hostile/megafauna/captainarlem.dm
Ahem. one, the keycard is for the enclave PA Arlem guards. two; ARLEM MAKES A HARD-DEL EXPLOSION ON DEATH, this removes any loot spawned unless it is indestructable.
(test not needed, revert of a small section of pr 4771)
fix: Arlem now drops the golden key again
/:cl:
> Fixes Arlem

- arfsuits.dm
- code/datums/components/crafting/recipes/recipes_assemblies.dm
- code/datums/components/crafting/recipes/recipes_misc.dm
- code/datums/components/crafting/recipes/recipes_tailoring.dm
- code/datums/components/crafting/recipes/recipes_tribal.dm
- code/game/gamemodes/objective.dm
- code/game/objects/items/stacks/crafting.dm
- code/game/objects/items/stacks/sheets/leather.dm
- code/game/objects/items/stacks/sheets/sheet_types.dm
- code/modules/clothing/chameleon.dm
- code/modules/clothing/suits/arfsuits.dm
- code/modules/mining/ores_coins.dm
- modular_citadel/code/modules/client/loadout/glasses.dm
- modular_citadel/code/modules/client/loadout/gloves.dm
- modular_citadel/code/modules/client/loadout/head.dm
- modular_citadel/code/modules/client/loadout/mask.dm
- modular_citadel/code/modules/client/loadout/neck.dm
- modular_citadel/code/modules/client/loadout/shoes.dm
- modular_citadel/code/modules/client/loadout/suit.dm
- modular_citadel/code/modules/client/loadout/uniform.dm
Makes chameleon clothing craftable to replace peoples unobtainable loadout items in the event they step on a mald mine or get set on fire while in crit + makes them selectable in the loadout for free
Makes the well crafting recipe not nearly as bad as it was. You can carry around like, 5 metal parts and 5 metal and make a sink literally anywhere, it doesnt need an entire towns assistance to make a small well. Now it just takes time + wood in various forms, instead of requiring the ever elusive sand.
Makes sand less elusive by letting people craft 3 at a time by bashing rocks together. Side effects include monkey glass production industry and crafting soil literally anywhere and adding fun to the game
:cl:
tweak: tweaked …
> Makes the chameleon clothing craftable

- AAADevTool/AAA_DEVELOPMENT_CONFIG.dm
- _maps/pahrump-just_new_boston_only.json
- fortune13.dme
Adds in a define that makes only the newboston Z load.
HOW 2 USE:
Open AAADevTool/AAA_DEVELOPMENT_CONFIG.dm
Set SANIC_SPEED to 1
Done. Try not to commit this file with SANIC_SPEED set to 1, though im like 30% sure I can make TGS overwrite it. It'll be our little dirty secret =3
> Deletes 90% of the world to speed up init

- code/datums/mutations/telekinesis.dm
I forgot that telekinesis is a mutation, and "KILL ALL MUTATIONS" chem exists, making it so you can never eat mutadone. There are probably other chems that like to pretend to be mutadone which would need to be fixed later
:cl:
/:cl:
> Makes telekinesis no longer curable

- modular_citadel/code/modules/client/loadout/__donator.dm
Condensed the two kits into one, removed clothes and Stealth Boy from both and added a resize cartridge (thx Andy!)
:cl:
add: Added ZeroNetTwo as a valid Ckey to ZeroNetAlpha's kit.
add: Added a resize cartridge to ZeroNetAlpha's kit.
del: Removed custom kit clothes, Foam force X9, and Stealthboy from ZeroNetAlpha's Kits.
tweak: Condensed ZeroNetAlpha's Kits into one.
/:cl:
> Tweak Zero's Custom Kits

- _maps/map_files/coyote_bayou/Ashdown-Upper.dmm
- _maps/map_files/coyote_bayou/Ashdown.dmm
- _maps/map_files/coyote_bayou/Backup Nash/Nash_and_Texarkana-Upper-2.dmm
- _maps/map_files/coyote_bayou/Backup Nash/Nash_and_Texarkana-Upper.dmm
- _maps/map_files/coyote_bayou/Backup Nash/Nash_and_Texarkana.dmm
- _maps/map_files/coyote_bayou/Backup Nash/Newboston-Upper.dmm
- _maps/map_files/coyote_bayou/Backup Nash/Newboston.dmm
- _maps/map_files/coyote_bayou/Dungeons.dmm
- _maps/map_files/coyote_bayou/Garland-City.dmm
- _maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
- _maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
- _maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
- _maps/map_files/coyote_bayou/Newboston-Upper.dmm
- _maps/map_files/coyote_bayou/Newboston.dmm
- _maps/map_files/coyote_bayou/Redwater-Upper.dmm
- _maps/map_files/coyote_bayou/Redwater.dmm
- _maps/map_files/coyote_bayou/Texarkana_underground.dmm
- code/game/objects/structures/tables_racks.dm
- code/modules/food_and_drinks/kitchen_machinery/microwave.dm
- modular_coyote/code/objects.dm
Fixes the White Stove Microwave so it doesn't break upon interacting with.
Makes Wooden Counters and Crafted Counters actual tables.
None of them are craftable. Yet.
:cl:
/:cl:
> Fixes White Stove and Counters

- code/datums/traits/negative.dm
- code/modules/admin/verbs/playsound.dm
Adds pain tolerance traits, these change when you go into soft crit, not hardcrit/death. With "Pain Tolerance - Total Wimp", any damage above 1 will put you into soft crit, but you will still require another 199 damage to die, and about 130 damage to enter hard crit. same logic applies to all other wimp traits
:cl:
server: something server ops …
> Adds pain tolerance traits (For bottoms)

- code/controllers/subsystem/who.dm
Turns out the proc returned minutes, which meant you needed around 2400 days of playtime to stop being a newbie. Which, honestly, yeah.
> Makes it so everyone isnt a noob

- code/__DEFINES/span.dm
- code/modules/admin/admin_verbs.dm
- tgui/packages/tgui-panel/styles/goon/chat-dark.scss
- tgui/packages/tgui-panel/styles/goon/chat-light.scss
Adds in a flashing colorful text thats ment to be used in a private player to player DM system in the future. This flashes the message 2 times, and then becomes a solid singular color, intended to be eye catching, but not straining to read, as the animation is done in about 1 second
:cl:
/:cl:
> Adds the private flashing text span for later use

- code/modules/projectiles/guns/energy/laser_crank.dm
CrankLaser weapons can be cranked while moving.
This may need a weapon variable in the proc to let it be defined on a weapon per weapon basis
:cl:
/:cl:
> Lets you crank that soldja boy while moving

- code/modules/projectiles/guns/energy/laser_crank.dm
- modular_coyote/code/creature_species.dm
Crankable lasers are pretty overpowered so I took it apon myself to nerf them a bit (Since I added them)
Generally;
Laser weapons should require alot of charge time, stamina, but you gain more than 1 power per charge. 
Adds a variable to influence how much charge you get per crank
Checks if you have stamina before cranking, so you cant crank that soldja boy into your grave
Increases how much charge laser weapons have, so cranking is a last resort option, or you can slowly crank that bad to full power. Take some jet, faint, or have people help you.
Basically; 
Makes energy weapons not literally infinite ammo and literally free by doing meth
:cl:
fix: fixed a few …
> Crankable laser fixes + Nerfs

- _maps/map_files/coyote_bayou/Dungeons.dmm
Bloodorbs 1: give you a broken chainsaw that cannot do damage or be dropped until the effect ends. but 2: the 'see demons' trauma is round-permanent, aka cringe. If hazards are wanted in the dungeons, don't use ones that are 5*5 square radius mines that permanently make you unable to see most sprites.
Revert PR, untested. minor map edits at most
:cl:
del: bloodorbs
/:cl:
> Permanent trait-trauma is cringe.

- code/modules/hydroponics/hydroponics.dm
makes hydro trays not reset their numbers when they're built or have their parts replaced. heavily lowers the health penalty for plants past their lifespan. removes probably all lines where pests and weeds are added to trays with crops in them.
:cl:
/:cl:
> plants last a long time, lower weeds and pests

- code/game/objects/items/sharpener.dm
…at when you craft a whetstone you get a whetstone
not a nebulously named melee weapon enhancement kit
:cl:
/:cl:
> Renames the nebulous melee weapon enhancement kit to Whetstone, so th

- _maps/map_files/coyote_bayou/Newboston.dmm
- code/modules/hydroponics/hydroponics.dm
Finally fixes the damn trays not having a max of 100, total and max are not actually the same, which max is what was altered during the previous time of parts actually working on trays. Now instead of defaulting to 20 it will properly stay stuck at 100, with a bonus of 100 nutrient roundstart. Also removes bugged trays from NB, and adds the vendor closer to the ORM that fenny forgor. Unsure if the drain is still horrid, but maybe it will be better now, perhaps a botanist thread on the discord can help with keeping track of times, for now everyone gets to keep rushing gaia.
fix: reagents.max_volume null refrence
add: mining vendor next to the orm like a sane person
fix: building south of NB no longer spawns bugged circ boards
/:cl:
> BOTANY BROS WE ARE SO BACK

- code/modules/fallout/turf/ground.dm
- code/modules/mob/living/simple_animal/friendly/pet.dm
- modular_coyote/code/modules/turf_changes/PlantGrass.dm
should be about half as many nests on roads, but more other stuffs
fixed nests spawning anywhere that trees could, instead they are bundled with other junk and non-plants and will spawn anywhere plants didn't so long as it's not in a safe zone
> Adjusts Mob Nest Frequency

- code/modules/cargo/packs/medical.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/guns/energy/laser_crank.dm
- code/modules/projectiles/guns/energy/special.dm
Fixes some weapon stuff that shoulda been fixed a while ago, slightly buffs the ebows to make them more competitive, and adds something to the train so refilling medkits / medical pouches isn't a total pain.
:cl:
- Wattz 1k-sport pistol now has actual pistol handling, but slightly better than other pistols due to rarity and the fact it has a projectile
- Adjusted various TG Blaster recoil per player feedback (generally made better baseline, but still encourages slow and precise shooting over holding down the trigger)
- Increased the ebow mod slots from 1 to 2, fixes the mini-ebow's shot sound so it no longer sounds like a silenced gun
- Adds a medical pouch refill to the train consisting of quality bandages, regular sutures, and a spray of brute or burn meds (costs about the same as a …
> General Tweaks/Fixes and a small shop expansion (Good to go if it passes checks)

- code/_onclick/hud/screen_objects/character_actions.dm
- code/modules/keybindings/keybind/combat.dm
- code/modules/mob/inventory.dm
- code/modules/projectiles/gun.dm
- code/modules/projectiles/guns/ballistic.dm
Press 1 button to reload the gun in your active hand, assuming it uses external magazines. Can be adapted later to work with toploaders/shotguns/energy weapons/etc. It will search 1 layer deep into any pockets, bags, rigs, armor, shoes, helmets, etc that you might be wearing. Has trouble with magazines that are stored in your pockets and stuff but aren't in another item.
Takes 1 second to reload by default, but it can be altered on a gun-by-gun basis with a single variable. A variable on magazines would be a good idea too, but that can come later if we feel we need it for balance.
When you use it, it will replace the magazine that you pulled out with the empty one you just ejected if possible. Otherwise, it's ejected to the floor.
> Reload Gun Hotkey

- code/datums/martial/berserker.dm
- code/modules/supplykit/supplykit_items/supplykit_magic.dm
Hehehe ohoho funny unarmed changes - 
TLDR with the advent of melee becoming stronger under recent changes, and the ability for backstabbing, as well as sleeping carp now being compatible with guns, i made this PR to give unarmed some more well defined roles in the form of offense with berserker and  and defense  with rising bass.
Changes - Berserker has some damage increases that are below the original ones, but still equivalent to what a melee weapon would get with backstabs when the correct combos are performed, it also received a no slip trait to really encourage the aggressive nature, as the oil that seems to be everywhere on the floor really punishes melee players when they're aggressive.
Rising bass was now added to the round start supply kit, as a more defensive focused …
> Berserker overhaul / Rising bass added.

- code/game/objects/effects/spawners/masterlootdrop.dm
- code/modules/cargo/exports/misc_export.dm
- code/modules/projectiles/guns/energy/laser.dm
- code/modules/projectiles/guns/energy/laser_crank.dm
- code/modules/projectiles/projectile/beams.dm
Title, basically.
Also tried to give each of the TG blasters a unique role. We'll see how that goes, eh?
Scraplaser: Shitty T0 weapon, but decent crankability
TG Minipistol: T0.5, shitty pistol that you're meant to have 4+ of at any time. Easy enough to crank and has a hidden use in the portable recharger.
TG Carbine: T1, almost a straight upgrade to the scraplaser. "Beats" the Repeating Blaster/Shocker in the sense you can carry two Carbines, or more if you use a bag
TG Autoblaster: T1, easy to crank anti-rodent gun. The best of the T1 weapons in terms of scaling.
TG Shocker: T1, hitscan and hits a little harder than the AB. The best T1 on its own and out of the box. Best used and discarded for pretty much any upgrade but still viable to upgrade.
TG Laser Rifle: T2, basically just an …
> Fixes and adjusts the TG Blasters for fun and balance (Good to go if it passes checks)

- code/modules/keybindings/keybind/combat.dm
- code/modules/mob/dead/new_player/new_player.dm
- code/modules/projectiles/gun.dm
- code/modules/projectiles/guns/ballistic.dm
- code/modules/projectiles/guns/ballistic/revolver.dm
- code/modules/projectiles/guns/ballistic/rifle.dm
- code/modules/projectiles/guns/ballistic/shotgun.dm
- Added another hotkey which will reload if your active hand has a gun in it, or toggle your throw mode otherwise.
- Reloading now works with bolt action rifles, shotguns, and revolvers. ( doesn't work with the widowmaker shotgun for some reason but you'll never notice that because nobody uses it :] )
- When you use the reload hotkey with these weapons it will try to load from any ammo boxes, stripper clips, or magazines you have, but will fall back to loading single bullets/shells if necessary. Will continue to loop through the reloading process until your weapon is full or there's no more ammo left.
- Fixed the search algorithm so it will correctly check your accessory slot for magazines, boxes, and bullets.
- You can now akimbo reload if you're wielding two guns
- Fixed odd behavior …
> Reloading Hotkey Part 2

- _maps/map_files/coyote_bayou/Newboston.dmm
Remodels the bar kitchen into something not akin to a third world country.
namely this contains all standard ss13 amenities such as actual fucking milk and eggs, but also gives bonuses of meat variety, bowls, condiments, chef uniform, cleaner floors, and numerous baking supplies.
Also I know you nerds discussed a nutrient thing for autolathes to like, cut down on difficulty for cooking/baking, one of the reasons it is hard in the first place is that the kitchens have not been stocked at all, or only stocked with randomspawn fallout stuff. This will heavily alleviate such stresses and concerns.
(entirely untested gem, but it did build without errors so its good enough)
fix: heavens night starving to death
/:cl:
> Heavens night starvation solution

- _maps/map_files/coyote_bayou/Newboston.dmm
- code/__DEFINES/inventory.dm
Changes the size of trash, botany, and salvage bags to 50 instead of 38 and 34 respectively
This also allows plant disks to be moved with produce bags, and fixes the fridges my dumbass forgot to anchor in my last kitchen PR (oopsies)
:cl:
tweak: bags store 50 items
/:cl:
> Increases bag sizes

- code/datums/martial/rising_bass.dm
As requested by Jaeger, comments out deft switch, also replaces the auto dodge for an auto reflect function, to provide a proper defensive function to the martial arts (as shots before just went through you and killed your friends).
:cl: …
> Rising bass rebalance P1

- code/modules/mob/living/simple_animal/hostile/giant_spider.dm
also makes them not move at sonic speed *and* kill you in two hits; now they just kill you in two hits
> fixes strong spiders permakilling people with broken overdose code

- code/modules/fallout/obj/food_and_drinks/food.dm
Adds cutlet variations for all the wasteland meats, so now you can whack your friends with deathclaw sausages.
Tried to keep the cutlet subtypes thematically correct with their existing meat slabs, so they're mostly just standard cutlets, but the geckos use the chicken cutlets and the rats and deathclaws use the bear cutlets, since the rats use the bear steak sprite and deathclaws just seem pretty bear-y to me. Shouldn't have any effect on the actual meat itself beyond looks since the cutlets inherit all their info from the parent slabs.
:cl:
add: Added cutlets for all the wasteland meats.
:cl:
> Cutlet Equality

- code/modules/reagents/chemistry/reagents/medicine_reagents.dm
makes nanites safe for toxinlovers, 1: Rare as fuck chem to get 2: it is buried under a long series of dead forums, but nukie chems are balanced strange as fuck. One of these balances was for when xenobio was actually decent, given xenobio is fucked here, and not exclusive for the toxinlover trait this balance does not work anymore.
Logically nanites that can cure your fucking dna should also ya know... not be stupid enough to kill you with toxins.
Devils advocate incoming; Magic users do still exist and can easily outpace the rate for toxinhaters, this just serves to add a small bit of extra option to act as a stepping stool to a ladder. 
Entirely untested gem, because it is 1 var being changed and it builds fine
:cl:
balance: IM SLIME STIMMINNGGG!!!!!
/:cl:
> Solves toxinlover-ism

- code/controllers/subsystem/economy.dm
This pull request fixes the condition for checking the QR type in the economy subsystem. Previously, the condition was incorrect and resulted in incorrect behavior. This fix ensures that the correct condition is used, allowing the system to function as intended.
> Fix condition for checking QR type in economy subsystem

- code/datums/traits/clams.dm
- code/modules/projectiles/gun.dm
- code/modules/projectiles/guns/ballistic.dm
- code/modules/projectiles/guns/ballistic/flintlock.dm
- code/modules/projectiles/guns/energy.dm
- code/modules/projectiles/guns/magic.dm
This pull request updates the ammo count overlay for magic, ballistic, and energy guns. The overlay now displays the remaining ammo in a more visually appealing and informative way. It uses different colors to indicate the ammo level, and the text shows the remaining ammo count out of the maximum capacity. This improvement enhances the user experience and makes it easier to track ammo usage during gameplay.
that and it makes clamparts tiny
> Update ammo count overlay for guns

- code/modules/client/preferences.dm
- code/modules/client/preferences_savefile.dm
- code/modules/mob/dead/new_player/preferences_setup.dm
So, you make a new character, and they look like a gray human. Turns out beneath the skin, they're your previous character, but jacked up in the vars, causing, among other many things, wierd questbook corruption nonsense. Now, the character vars are properly initialized!
Also makes the default new character a furry, cus we're a furry server full of furries, you're gonna have a better time if you play a furry instead of some wierd human everyone just assumes is either a jerk or a grieftider.
Also adds in a button to delete the currently selected character. Do note that when you delete your character, it is gone forever, utterly impossible to recover, like seriously, there are no backups, no secret saves, once deleted, your character is *gone*. And it says so too!
> Fixes new character creation making a wierd half-clone of yourself

- _maps/map_files/coyote_bayou/Newboston.dmm
(Remade on new branch due to conflict) ; Attempts to make the reclaimers botany lab less cluttered by using the large portion of rock and empty space on the west side. It also just serves to give botanists something to look out at and socialize to when working, which was the main point of giving an outside-facing wall like all other proper servers have hydroponics. As a side affect of the new empty space of where botany previously was and now replaces the two mech chargers, a robotics lab has been thrown in due to players still using mechs. However a common area/breakroom could always be slapped in place, even if the previous was never used. Alternatively, even moving the nanite lab to get it off of the dungeon z level.
Tweaks: Most of the west wing of the reclaimers  remodeled
/:cl:
> Reclaimers botanical and west wing alterations

- code/controllers/subsystem/economy.dm
- code/modules/projectiles/projectile.dm
This pull request fixes an issue with broken quests and improves the rounding of projectile damage.
The broken quests were caused by an invalid save chunk encountered during quest loading. This PR removes the invalid save chunks and prevents the generation of new quests that could cause further issues.
Additionally, the rounding of projectile damage has been improved to round to the nearest 0.5 instead of rounding down to the nearest whole number. This ensures more accurate and precise damage calculations for projectiles.
> Fix broken quests and projectile damage rounding

- code/modules/hydroponics/hydroponics.dm
Reduces the amount of ambrosia gaia needed to achieve self sufficient hydroponics to 1 instead of 7, because I'll be honest, if you have ambrosia gaia, you already have a supply of it. Having 7 just delays and makes tedious the process of getting like 15 soilbeds to be self sufficient. (105 branches of ambrosia gaia to make 15 trays self sufficient)
:cl:
admin: messed with …
> Makes hydroponics self sustaining easier to achieve

- code/modules/mob/living/simple_animal/hostile/hostile.dm
- code/modules/projectiles/ammunition/_firing.dm
This pull request adds a new `spread` parameter to the `Shoot` function in the `hostile.dm` file. The `spread` parameter allows for controlling the spread of the mob's ranged attacks. The `Shoot` function now accepts an optional `spread` argument, which defaults to 0 if not provided. The spread value is used to calculate the true spread of the projectile, taking into account the base spread, extra spread per shot, and the maximum spread allowed.
> Makes ranged mobs not 100% accurate

- code/modules/reagents/chemistry/machinery/chem_cartridge.dm
see title
- [NOPE] You tested this on a local server.
basically
tl;dr
we have made it where you can grow 1750hp healing healing powders per broc and xander plant
you can easily scale this up to 7000 with just four of each in a 2x4 area
for every eight tiles you can get 7000 hp healing resources
chemistry cannot even remotely compare
there's also more fun uses of chemistry that isn't healing, and generally people who want to play doctor who also want to play chemist don't want to deal with the system, so I soft removed it
> buffed the shit out of chemical cartridges

- code/modules/WVM/wmv_buyer.dm
Fixes a double convert oversight that makes the workshop scrapper tell you the coins in silver instead of copper
:cl:
fix: Workshop scrapper now tells you the correct price
/:cl:
> Fixes double convert bug

- _maps/map_files/coyote_bayou/Texarkana_underground.dmm
- code/datums/datacore.dm
- code/modules/jobs/jobs.dm
Turning them off because I only turned them on in vague hopes of leaving something of them for people, but if I want to *fix* CB at all they *have* to go.
We are now in the placeholder map era.
:cl:
/:cl:
> Turns off the needless jobs and towns

- code/datums/traits/negative.dm
- code/modules/mob/living/simple_animal/hostile/hostile.dm
- [maybe] You documented all of your changes.
> random mob firing

- code/modules/mob/living/life.dm
SEE title
For my GitHub divers,
This PR makes it where you (basically) cannot regenerate your triage without food OR water
It also ups the reservoir by five points, bringing the total amount of healing from `25 -> 50`  for basic, and `125 -> 150` for advanced triage
Additionally, it removes the ability to find medicinal wasteland plants.
> soup is for sick people (which is you)

- code/datums/components/storage/concrete/belts.dm
- code/datums/components/storage/concrete/necks.dm
- code/datums/components/storage/concrete/pockets.dm
- code/game/objects/items/crayons.dm
- code/game/objects/items/devices/battery_box.dm
- code/game/objects/items/devices/portable_chem_blenderbelt.dm
- code/game/objects/items/plushes.dm
- code/game/objects/items/storage/belt.dm
- code/game/objects/items/storage/firstaid.dm
- code/game/objects/items/storage/toolbox.dm
- code/modules/fallout/obj/krotchy.dm
- modular_splurt/code/modules/research/xenoarch/tools.dm
Removes storage restrictions on some items. Notable exceptions are:
- Bags and other containers that have a "gather all" option. This leaves them with their intended function and prevents annoyingly picking up everything all the time.
- Special boxes like cigarette and match boxes. Removing the restrictions gives them the same functional capacity as a normal box
- Back Sheath. The special storage is intended to allow storing a weapon without giving up your backpack inventory. Removing the restriction just makes it a backpack within a backpack.
- Sturdy Quiver. The storage capacity of the quiver is massive to accommodate the bulky spears and javelins
- Everything in the Fancy storage. These have special icon states to indicate how full they are. Unchanged to maintain clarity. The easter …
> Removes storage restrictions on several items

- code/datums/components/crafting/recipes/recipes_misc.dm
- code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
Hivebots have had their costs increased, especially for ranged units, to the point that reclaimers are the only ones who can feasibly produce large amounts of them. As a flipside, these bots have been generally improved in their survivability, with tier 3 ranged hivebots able to survive several shots of 9mm in one life.
Melee hivebots now have way more health to fully serve their purpose as generally aggressive hivebots that distract opponents from real threats, and so also have slightly reduced damage and DPS
tl;dr you can no longer make large amounts of ranged hivebots simply by buying components at the vendor anymore, go salvaging and looking for components, or be a reclaimer for that robot swarm fantasy!
:cl:
tweak: …
> Hivebot cost and power adjustments

- _maps/map_files/coyote_bayou/Newboston-Upper.dmm
- _maps/map_files/coyote_bayou/Newboston.dmm
Removes two windows facing a wall and replaces them with a corner and window on the lower z, then fixes xenobiology's doors to actually be 1-5 and each be independent and have their buttons aligned. Also tries out a more open floorplan with a railing and less walls near the stairs.
Built fine for me, but private server upper z would not load, don't have the knowledge of how to fix
:cl:
add: Added expanded corner for reclaimers protolathe lab, new balcony for xenobiology
del: Removed small portion of lower z walls and upper z stairwell
/:cl:
> Small reclaimers fixes/changes

- code/controllers/subsystem/datumrentals.dm
- code/datums/beam.dm
- code/datums/chatmessage.dm
- code/game/say.dm
- code/modules/mob/living/say.dm
Objects that can speak can now speak.
Claire's runechat appears over your head.
Runechat is moved up a bit to make room for a progress bar.
Offscreen chat should (should) stick on the turf it should, and not move with the speaker.
Beams should work once more.
> Lets things talk again, also other stuff

- code/modules/mob/living/simple_animal/simple_animal.dm
- code/modules/projectiles/guns/energy/laser_crank.dm
- modular_coyote/code/modules/znuguns/code/guns/zloadout.dm
Heavily overhauls how crank weapons feel.  They are now
- Low cell size (small mag)
- low recharge rate (often one shot per crank)
- low-ish stamina cost (you only stamcrit if going insane)
- very low accuracy
- very fast recharge rate
This makes a weapon that is a crapshoot on every trigger pull, has functionally unlimited ammo but can stamcrit you if you go too hard with and is ultimately outdone entirely by a normal firearm.  You trade all that inventory space for a coin flip if you hit at all, basically.
Adds loadout versions of
Pistol 
Carbine (
Rifle
Heavy Rifle
:cl:
sounddel: removed an old sound …
> Adjusts and re-adds 4 crank laser weapons
