code/modules/mob/living/simple_animal/hostile/f13/raider.dm
code/modules/mob/living/simple_animal/hostile/giant_spider.dm
code/modules/projectiles/projectile/energy/nuclear_particle.dm

One bite from a viper = ded.
three shots from a cultist = mutated with a second head singing 'its a small world'.
None of that lol

Viper and Cultist Nerf

---

code/controllers/subsystem/who.dm
code/datums/datacore.dm
code/game/objects/effects/landmarks.dm
code/modules/jobs/access.dm
code/modules/jobs/job_types/khan.dm
code/modules/jobs/job_types/tribals.dm
code/modules/jobs/jobs.dm
tgui/packages/tgui/interfaces/CharacterDirectory.js

Renames some jobs and messes around some categories, also the manifest
Also touches a description in who, and switches are purple

Fixes various jobs

---

code/modules/jobs/job_types/oasis.dm

Technophreak from jobs is just broken. No identifiable cause. This'll be a bandaid fix

Shopkeeper has better cells

---

_maps/map_files/coyote_bayou/Ashdown.dmm
_maps/map_files/coyote_bayou/Dungeons.dmm
_maps/map_files/coyote_bayou/Garland-City.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

Adds more parts loot

---

code/modules/jobs/job_types/oasis.dm

Removes Quartermaster
Adds an extra slot to science, doctor, and trade worker

Job number fixes

---

code/modules/hydroponics/biogenerator.dm
code/modules/research/designs/biogenerator_designs.dm
code/modules/research/designs/medical_designs.dm
code/modules/research/techweb/nodes/biotech_nodes.dm

Adds DNA Disks to Research, Adds Strange Seeds to Biogenerator

---

code/modules/projectiles/guns/ballistic/bow.dm

Makes it so all bows can fit in your belt and backpack slot. Suit-storage can hold all guns, and bows are guns.
:cl:
fix: Bows should fit on your back again?
/:cl:

Bows should fit in back slots.

---

modular_citadel/code/modules/client/loadout/__donator.dm

Changes a certain loadout from stimki to stimki:2
:cl:
/:cl:

(MERGE SPLURG PLS) Loadout change

---

_maps/map_files/coyote_bayou/Newboston.dmm

Replaces the miester because he refuses to var edit his projectiles A

---

code/game/objects/effects/landmarks.dm

Should fix Den and Garland spawns

---

code/__DEFINES/random_mob_spawner.dm
code/modules/fallout/obj/structures/mob_spawners.dm

OP mobs, so are now high level slots.

Moves Emperors to their own nest

---

code/controllers/subsystem/artifacts.dm
code/datums/components/artifacts.dm

Fixes stamina healing artifacts actually hurting your stamina

---

_maps/map_files/coyote_bayou/Ashdown.dmm
_maps/map_files/coyote_bayou/Dungeons.dmm
_maps/map_files/coyote_bayou/Garland-City.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

More Vertibird Landing Spots!

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm

Was not supposed to be there, my bad...I should have communicated with fenny about that better.

Removes the Mass Fusion Second Floor virtibird Spot

---

_maps/map_files/coyote_bayou/Ashdown.dmm
_maps/map_files/coyote_bayou/Dungeons.dmm
_maps/map_files/coyote_bayou/Garland-City.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Naming is important, not only ID...welp.

Fixes the Vertibird landmark names

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm

Some shotguns and chargers for the nash sec guys

---

code/modules/client/client_procs.dm

This makes the newbie join message take a lil longer so the nerd can actually god damn connect first god damn
:cl:
/:cl:

Adds a cooldown to the chat message thing

---

code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm
code/modules/projectiles/projectile/bullets/pistol.dm

experimenting.  Lowers their projectiles to 1 extra and slows the bullet down some
:cl:
/:cl:

Securitron changes

---

code/__HELPERS/unsorted.dm
code/game/objects/items/devices/battery_box.dm
code/modules/WVM/wvm.dm
code/modules/projectiles/guns/energy.dm
code/modules/research/designs.dm
code/modules/research/designs/autolathe_designs.dm

Fixes the charger box thing

---

code/controllers/subsystem/artifacts.dm
code/datums/components/artifacts.dm

Fixes artifacts being dozens of times more powerful than they should

---

_maps/map_files/coyote_bayou/Texarkana_underground.dmm

I went down and poked it but poke no work so moved machines and now poke machine will work.
:cl:
add: wall light
del: floor light
fix: moved chemical heater
/:cl:

moving things in Nash Science Chemistry to make them accessible

---

code/game/objects/items/devices/battery_box.dm

It should now charge, even when itself is full.

Fixes the battery box, again

---

code/modules/reagents/reagent_containers/pill.dm

Changes anti-venoms color to reddishorange

---

code/__DEFINES/maths.dm
code/__HELPERS/_lists.dm
code/__HELPERS/unsorted.dm
code/controllers/subsystem/statpanel.dm
code/modules/mob/living/carbon/human/species.dm
code/modules/mob/login.dm
code/modules/mob/logout.dm

Tells you who to play if you wanna get laid

---

_maps/map_files/coyote_bayou/Newboston.dmm

FIxes a rogue textured tile

---

code/__DEFINES/dcs/signals.dm
code/datums/elements/flavor_text.dm
code/modules/mob/living/login.dm
code/modules/mob/living/logout.dm
code/modules/mob/login.dm
code/modules/mob/logout.dm
code/modules/projectiles/guns/ballistic/rifle.dm
modular_splurt/code/datums/modules/client/verbs/character_directory.dm
tgui/packages/tgui/interfaces/CharacterDirectory.js

Adds flist linking to the character directory. You can set it there too!
Reorganizes the settings panel for it to be more zwah.

Makes flist more accessible

---

code/modules/jobs/job_types/oasis.dm

Scientist = 10
Doctor = 6
(up from both being 4)

Increases Scientist and Doctor slot numbers

---

code/datums/traits/good.dm

Switches prices on quick and quicker carry

---

code/modules/mob/dead/observer/observer.dm

Its now logged when non-admins ghost, and anyone orbits a mob. the former prints a message for admins, the latter just quietly logs it cus we dont need thaaaat much spum.

Logs paranormal activity

---

code/game/machinery/camera/camera.dm
code/game/machinery/computer/camera_advanced.dm
code/modules/admin/admin_verbs.dm
code/modules/admin/holder2.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/silicon/ai/life.dm
code/modules/mob/living/silicon/robot/robot.dm
code/modules/mob/living/simple_animal/simple_animal.dm

if you're an admin that is!
click Toggle Seeing Ghosts at the bottom of the Admin panel to toggle seeing ghosts.

Lets you see dead people

---

code/controllers/configuration/entries/general.dm

Very complicated pr for andy

---

code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
code/modules/projectiles/guns/mods/mods.dm
modular_coyote/eris/code/mods/mod_types.dm

Fixes mess ups I made.
Removes the gun magazine modification. It outright makes a gun invisible or hard deletes the stored magazine.

Fixes mess ups with Paint PR

---

code/game/turfs/simulated/floor/f13_floors.dm

Fixes the crossroads sounding like plating. Which they are. Techincally.
:cl:
fix: fixed crossroads sounding like plating.
/:cl:

Fixes a road sounding like a plate

---

code/__DEFINES/say.dm
code/datums/elements/flavor_text.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/mob/living/carbon/human/human.dm
config/maps.txt

Adds a new OOC set of notes called "Background Info Notes". Worry not, it's clever enough to recognize if the player has actually set anything in it, so it doesn't clutter the examine text in case people didn't set it up.
I do as the Fenny commands.
:cl:
add: Adds "Background Info Notes", for people who want it!
/:cl:

Background Info [ready to merge]

---

code/game/objects/items/loadout_toolkits.dm

Contains hunting, horn, and hunting horn

Adds hunting horn to the toolkit loadout thing

---

code/game/objects/items/loadout_toolkits.dm

thanks git, didnt update, GOOD TO MERGE FENNY

makes the loadout thing have the actual good horns

---

code/controllers/subsystem/dummies.dm

worst subsystem ever

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm

Fenny said it was okay to ages ago but it was never added and now I'm adding it :3
:cl:
add: Mining Points Vendor
/:cl:

Add Mining Points Vendor to the Den

---

code/modules/WVM/wvm.dm

puts the portable charger in more vendors

---

code/datums/elements/mob_holder.dm

LETS FUCKING GOOOOOOOOOOOOOOOOOOO!!
:cl:
/:cl:

MAKES SMOLS HAVE FORCE WHEN CARRIED

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm

Reverts ARF-SS13/coyote-bayou#4377

Revert "Add Mining Points Vendor to the Den"

---

code/game/objects/items/melee/huntinghorn.dm

hard to test solo but we'll see
:cl:
/:cl:

maybe fix hunting horn song performing

---

code/modules/fallout/turf/walls.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/living.dm

No, i don't need to know what size balls you had just because you decided you wanted to matrix
:cl:
/:cl:

Cleans up despawn information

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Some community suggestions to map

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

just trying a thing
:cl:
/:cl:

Let me cook - New Boston Road recoloring

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Adds a few more Tribe stuff
Removes some Kilts

MoreTribeSTuff

---

code/modules/jobs/job_types/heavensnight.dm
code/modules/jobs/job_types/hells_nomads.dm
code/modules/jobs/job_types/oasis.dm
code/modules/jobs/job_types/tribals.dm
code/modules/jobs/job_types/wasteland.dm

Do note that some jobs aren't unlimited for a reason.
Turns off nash librarian.

Unlimited Jobs

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm

Fixes a Decal

---

code/modules/mob/dead/new_player/new_player.dm

removes some dialogs when you click to observe.

Lless checks when u obrsrve

---

code/modules/clothing/suits/trait_no_med_hvy_armor.dm
code/modules/mob/dead/new_player/new_player.dm

The three main protections set to max limit of 35.
The damage threshold max is 2. Since all light armor uses that essentially.

Fixes Armor Aversion

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Moves Tox's Hideout to New Boston

---

code/datums/components/twohanded.dm
code/game/objects/items/melee/huntinghorn.dm

not sure why suitstorage slot isnt working but at least those two do
:cl:
/:cl:

HHs fit on belt and back

---

code/__DEFINES/inventory.dm
code/_onclick/item_attack.dm
code/datums/components/melee_special.dm
code/game/objects/items/melee/huntinghorn.dm

they fit in suitstore instead of belt, and run HH procs in pre_attack. also pre_attack actually fucking runs more often. clicking farther from your target than you need to and hitting them no longer stops the entire attack chain.
:cl:
/:cl:

hunting horns work better

---

code/game/objects/effects/landmarks.dm

Fixes the Harvest Leader Landmark
:cl:
fix: fixed a tribal landmark
/:cl:

Fixes Harvest Leader landmark

---

code/__DEFINES/combat.dm
code/controllers/subsystem/second_wind.dm
code/modules/mob/living/carbon/alien/damage_procs.dm
code/modules/mob/living/carbon/damage_procs.dm
code/modules/mob/living/damage_procs.dm
code/modules/mob/living/silicon/damage_procs.dm
code/modules/mob/living/silicon/pai/pai_defense.dm
code/modules/mob/living/simple_animal/damage_procs.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/guns/magic.dm
code/modules/projectiles/guns/magic/staff.dm
code/modules/projectiles/guns/magic/wand.dm
code/modules/surgery/organs/soda_organ.dm

Magic weapons now demand a price to charge! A price of BLOOD! and hunger, mostly hunger

Power, at a cost

---

code/datums/components/melee_special.dm

i mean, if there was anything that fucked up in any weapon's `afterattack` someone who clicks on mobs would've noticed already right
:cl:
/:cl:

weapon_special runs the weapon's afterattack

---

code/modules/mob/living/carbon/human/species_types/ghoul.dm

I put on my robe and wizard hat and cat level 69 domination.

Sussy Ghussy Fever

---

code/game/objects/hand_items.dm
code/game/objects/items/melee/coyotemelee.dm
code/game/objects/items/melee/f13onehanded.dm
code/game/objects/items/melee/f13twohanded.dm

Finally got around to doing this, we can dial them in better over time.
:cl:
/:cl:

Melee weapon backstab multiplier overhaul

---

code/modules/mob/living/simple_animal/hostile/abilities_common.dm

Poorly fixes the mob commands not working anymore. Hopefully a proper fix could be done at later time, as for now commanded mobs no longer follow you or stick to the moved area anymore.
:cl: Anonymous
fix: Fixes mob commands not working. Although it is not a proper fix, I think.
/:cl:

Band-aid-fixes mobs not listening to commands

---

code/__DEFINES/combat.dm
code/controllers/subsystem/second_wind.dm
code/modules/mob/living/carbon/alien/damage_procs.dm
code/modules/mob/living/carbon/damage_procs.dm
code/modules/mob/living/damage_procs.dm
code/modules/mob/living/silicon/damage_procs.dm
code/modules/mob/living/silicon/pai/pai_defense.dm
code/modules/mob/living/simple_animal/damage_procs.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/guns/magic.dm
code/modules/projectiles/guns/magic/staff.dm
code/modules/projectiles/guns/magic/wand.dm
code/modules/surgery/organs/soda_organ.dm

Reverts ARF-SS13/coyote-bayou#4406

Revert "Power, at a cost"

---

code/modules/jobs/job_types/oasis.dm
code/modules/jobs/job_types/tribals.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Adds a new weredoggo kit. Also organizes their kits into the W's. It world war 3 right here with my OCD </3
adds tool kit spawners to all jobs that dont have em. If I missed any, ping fenny on discord.
Removes prismatics 4th loadout. Not used anymore.

Loadout Starter Stuff!

---

_maps/map_files/coyote_bayou/Newboston.dmm

betalborking bornch bo bew bewston blease

---

_maps/map_files/coyote_bayou/Newboston.dmm

Ticket Puncher for shop

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm

Fixes some stairs

---

code/modules/jobs/job_types/wasteland.dm

Dunno why they didn't before...

Radio Operator has a headset now

---

_maps/map_files/coyote_bayou/Newboston.dmm

Also removes the one in the matrix, and on the track. How did he manage this lol

Correct Shop Bounty Ticket Machine added

---

code/controllers/subsystem/research.dm

The strange rock from xenoarch will give about 3750 points. Makes research far easier.

Strangerock = Research

---

code/controllers/subsystem/research.dm

Reverts ARF-SS13/coyote-bayou#4433
This may have fucked it hard.

Revert "Strangerock = Research"

---

code/datums/components/artifacts.dm

stamina buffer is a scam
Also heal artifacts will heal you in crit, but at a greatly reduced rate.

Fixes artifacts, again, maybe

---

code/modules/mob/living/simple_animal/simple_animal.dm

lets you RP as a horde of molerats

---

modular_splurt/code/modules/research/xenoarch/artifact_list.dm

Upgrades strange rocks to be a bit better

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Adds more buildings to the new boston z, including a few little livable points of interest.
closes of the road from the depot from the nash z, lol
:cl:
/:cl:

I will never stop mapping you can't make me

---

code/modules/mining/equipment/mining_tools.dm

Makes Pickaxes normal size for now.
:cl:
/:cl:

Makes Pickaxes Smaller

---

code/modules/projectiles/guns/energy.dm

8 seconds is usable, but stressful.  One minute is torture.
:cl:
/:cl:

Really ramps up recharging weapons time

---

code/modules/holiday/party_time.dm

potluck fix

---

code/game/objects/items/balls.dm

I miss Geoff Peterson

---

code/modules/clothing/suits/arfsuits.dm

literally just the title
:cl:
/:cl:

Fixes the gear harness again maybe (good to go if it passes checks)

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

mo changes

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

map fixing never stops

---

_maps/map_files/coyote_bayou/Dungeons.dmm
_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm
code/modules/research/techweb/nodes/nanites_nodes.dm

Small custom 2 minute lab put together holding all you need. Have fun!
Also fixed a few map erorrs with lights/vents too as requested.

Add Nanites to Science

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

More NB overhauling
:cl:
/:cl:

I will NOT stop mapping

---

code/modules/clothing/suits/arfsuits.dm

Reverts ARF-SS13/coyote-bayou#4457

Revert "Fixes the gear harness again maybe (good to go if it passes checks)"

---

_maps/map_files/coyote_bayou/Ashdown.dmm
_maps/map_files/coyote_bayou/Garland-City.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Newboston.dmm
_maps/map_files/coyote_bayou/Redwater.dmm

Adds various more cell characters on the first floor of the maps. Not many, but enough to make things somewhat easier for the egun users.

More Cell Chargers around? Maybe

---

code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
code/game/objects/effects/spawners/masterlootdrop.dm
code/modules/projectiles/guns/mods/mods.dm

Adds a black paint re-roll recipe.
Removes gold paint from the mods/loot pool.

Paint Edits!

---

code/datums/components/nanites.dm
code/modules/research/designs/nanite_designs.dm
code/modules/research/nanites/nanite_programs/protocols.dm
code/modules/research/nanites/nanite_programs/utility.dm
code/modules/research/nanites/program_disks.dm
code/modules/research/techweb/nodes/nanites_nodes.dm

- Adds Protocols
- Diagnostics Program added (required to see status of nanites)
- Makes base max nanites to 500 to make up for the new additions

Nanite ports from TG

---

code/modules/mob/living/emote.dm

Simply adds *tilt emote to tilt your head... And also makes my previously added emotes to be of audible type.
:cl: Anonymous
add: *tilt (headtilt).
/:cl:
~~no cocks~~
~~also good god i wanted to pretty up other emotes here as well code-wise what with indentations~~

Added head tilting emote

---

code/modules/projectiles/guns/mods/mods.dm
modular_coyote/eris/code/mods/mod_types.dm

Forgot to bring the battery shunt in the mix. Also, it among other things have charge cost increase now. Its a *battery shunt*. No shunting was done originally.

Re-enables charge cost reduction/increase in mods and Adjusts Damage Numbers

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm

See title. I forgot to take screenshots, ma bad.

Ody licks the den

---

code/datums/traits/good.dm
code/modules/mob/living/simple_animal/hostile/abilities_common.dm
code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm

Makes Giant Rats to be docile with rat-friends, and also tame-able for Rat Beast Masters, but not controllable.
:cl: Anonymous
tweak: Makes giant rats docile toward Rat Beast Masters/Friends.
tweak: Allows Rat Beast Masters to tame giant rats, but not control them.
spellcheck: Changes desc for small critter beast master - molerat -> giant rat.
/:cl:

Tweaks rat and critter lords a little

---

code/modules/mob/living/simple_animal/hostile/hostile.dm

I am evil and fucked up.
:cl:
/:cl:

Robust Searching

---

code/modules/reagents/chemistry/reagents/other_reagents.dm

or just stopping them from slurping oil off the ground and going insanely fast.
You decide.
:cl:
/:cl:

Synths nerfed to be basically unplayable

---

code/game/objects/effects/spawners/masterlootdrop.dm
code/modules/cargo/packs/security.dm
code/modules/cargo/packs/skillbooks.dm
code/modules/projectiles/guns/energy/laser.dm

Title.
Quick note is that eguns don't _quite_ follow the (DPS * 2 * 10) formula as, unlike ballistics, they have weird quirks that'd make some items outright obsolete. Namely things like not being able to be reloaded in the field, certain guns being objectively better than others despite using the same ammo, or having special effects such as massive bonus damage to robots. Honestly, the tweaks probably won't do much but it should at least provide a _feeling_ of it being 'balanced.' Whatever the fuck that actually means.
:cl:
- Adds a bunch (though not all) energy weapons to the shop's buy list.
- Fixes a naming issue with a blueprint.
- Fixes a spacing issue in the code.
:cl:

Adds a bunch of e-guns to the shop (and some small fixes) (good to go if it passes checks)

---

code/modules/research/designs/nanite_designs.dm
code/modules/research/nanites/nanite_programs/utility.dm
code/modules/research/techweb/nodes/nanites_nodes.dm

Sting and Infective Ex-locomotion go bye bye

Removes the Spreading Infection Nanites

---

code/modules/clothing/suits/arfsuits.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Hotfixes and nerfs armor of a player under request. Snelly
:cl:
/:cl:

(SNERGE SNAGAIN) Hotfixes

---

code/__DEFINES/traits.dm
code/datums/components/crafting/recipes/recipes_assemblies.dm
code/datums/traits/good.dm

Adds in the treasure hunting trait, which allows players to dig up lootspawners
:cl:
/:cl:

Adds treasure hunter trait

---

code/datums/traits/good.dm

title
:cl: anonymous
spellcheck: beast master/friend -- radroaches -> pillbugs.
/:cl:

Changes beast friend/master description about roaches into pillbugs

---

code/datums/components/crafting/crafting.dm
code/datums/components/crafting/recipes.dm
code/datums/components/crafting/recipes/recipes_assemblies.dm

Fixes up treasure hunter, thank you so much superlagg and certified hyper idiot for the help
:cl:
/:cl:

Hopefully fixes trash- I mean treasure hunter and makes it balanced

---

code/modules/cargo/packs/security.dm

AER 14 shop fix

---

_maps/map_files/coyote_bayou/Newboston.dmm

Science RnD Public Access

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm

Shifts a few things around the tribal camp.

---

_maps/map_files/coyote_bayou/Newboston.dmm

Swaps a Fake stair with a real one.

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Moves Heavens Night into New Boston

---

_maps/map_files/coyote_bayou/Newboston.dmm

oops fake stairs

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

I literally can't stop myself please help me
:cl:
/:cl:

More New Boston Overhauling

---

_maps/map_files/coyote_bayou/Newboston.dmm

Fixes a house

---

code/modules/clothing/suits/arfsuits.dm
modular_citadel/code/modules/client/loadout/suit.dm

Tox's request! It happens now. :p

Warhammer clothing given the light armor tag

---

code/__HELPERS/mobs.dm
code/game/atoms.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/mob/living/blood.dm

should work. no rainbow yet
:cl:
/:cl:

custom blood color

---

code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm

Craftable shelves no longer drop wood

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Cleans up some tribe coloring.

---

_maps/map_files/coyote_bayou/Newboston.dmm

This is why we can't have good things.

Science access re-enabled

---

_maps/map_files/coyote_bayou/Newboston.dmm

A few spawns of it roundstart. Like 30

Gives Science roundstart Plastic

---

code/modules/mob/living/carbon/human/examine.dm

Adds every perception trait to these traits, so if you have atleast one of them, you will see someones PVP preferences. More of a bandaid fix for lack of better alternatives.
:cl:
/:cl:

Makes PVP preferences actually visible

---

_maps/map_files/coyote_bayou/Backup Nash/Texarkana_underground.dmm
_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Weeee Makes it nicer

---

code/__DEFINES/construction.dm
code/datums/components/crafting/recipes/recipes_tailoring.dm
code/modules/clothing/head/f13head.dm
code/modules/clothing/suits/arfsuits.dm

Power Armor Crafting Final Touch up

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm

Fixes a Hole

---

code/game/objects/effects/effect_system/effect_system.dm
code/modules/mob/living/emote.dm

I saw it in the discord good idea zone, it was something I've been meaning to add but just never got around to
:cl:
/:cl:

Adds the spark emote

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm
code/game/objects/effects/decals/misc.dm

Fixes the Pointer arrow rendering under everything.

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm

Moves some fire into walls in the tribal camp

---

code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm

Tried adding a banned list variable to it and making this more efficient but in testing it didn't work, this however is guaranteed to work... I hope
:cl:
/:cl:

Makes craftable shop shelves paintable/writable

---

code/game/objects/items/storage/survivalkit.dm
code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm

Removes the confusion on rattle venom
:cl:
/:cl:

No more confusion

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
modular_roguetown/code/objects/lightening.dm

Fixes the Wall candles so they are not Campfires
:cl:
/:cl:

Fixes wall candles

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm
code/modules/fallout/turf/ground.dm

Ody does too much in one pr again V2

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm

Adjusts some tribal stuff.

---

_maps/map_files/coyote_bayou/Newboston.dmm

More soda vendors on the new boston z

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm
code/game/objects/structures/railings.dm
code/game/objects/structures/tribal_torch.dm
code/modules/power/lighting.dm

Some wall lights were on the wrong plane, they should be on the MOB plane. Not the OBJ plane.
:cl:
/:cl:

Fixes some layer issues with ON_WALL lights.

---

code/__HELPERS/unsorted.dm
code/game/atoms.dm

allows for `#000000` blood
:cl:
/:cl:

blood (dark)

---

code/modules/cargo/packs/security.dm

- Compact 14mm Rifle
- ALR-15
- AK-74U
- Colt Buntline
:cl:
/:cl:

Adds 4 more guns to the shop

---

code/modules/hydroponics/grown/ambrosia.dm

Makes Ambrosia Gaia a little bit less cancerous to take care of

---

code/modules/mob/living/simple_animal/friendly/farm_animals.dm

Makes cows half sized, instead of .85 size lol

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

I made booboo and am trying to fix said booboos

Quick Patch

---

code/modules/mob/living/simple_animal/friendly/farm_animals.dm

Upsizes cows to 70% size from 50

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm

Anchors some fuckin clotheslines lol

---

_maps/map_files/coyote_bayou/Newboston.dmm
code/modules/jobs/job_types/oasis.dm
code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm

Its not fenny if its not map touching

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

The Den Revamp

---

_maps/map_files/coyote_bayou/Newboston.dmm
code/game/machinery/computer/communications.dm
code/modules/jobs/job_types/oasis.dm
code/modules/jobs/jobs.dm

- Librarian to Cataloger
- Medic to Healer
- Bartender to Kitcheneer
- Banker to Financier
Small map fixes as well
:cl:
/:cl:

Guild Flavor, First Pass

---

code/datums/mutable_appearance.dm
code/game/machinery/bloodbankgen.dm
code/game/machinery/iv_drip.dm
code/game/machinery/water_purifier.dm
code/game/objects/effects/effect_system/effects_foam.dm
code/game/objects/effects/effect_system/effects_smoke.dm
code/game/objects/items/tanks/watertank.dm
code/game/objects/structures/lavaland/geyser.dm
code/modules/food_and_drinks/drinks/drinks.dm
code/modules/food_and_drinks/drinks/drinks/drinkingglass.dm
code/modules/food_and_drinks/food/customizables.dm
code/modules/food_and_drinks/food/snacks_egg.dm
code/modules/pool/pool_controller.dm
code/modules/reagents/chemistry/colors.dm
code/modules/reagents/reagent_containers/chem_pack.dm
code/modules/reagents/reagent_containers/glass.dm
code/modules/reagents/reagent_containers/spray.dm

should be the last big update for custom blood color
:cl:
/:cl:

rainbow reagent in containers

---

code/datums/traits/good.dm
code/modules/mob/living/carbon/carbon_movement.dm
code/modules/mob/living/carbon/human/species.dm

it works! also it's 14 points (same as other semi-beneficial quirks used for flavor) because there's so much food everywhere why does it matter. the power gamers have better quirks to use their quirk slots and points on even if this IS cheap. also eating is literally good for you? so idk why The Gamers would want to avoid it too much
:cl: …

Fix Does Not Eat and reduces its cost

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm

Makes it so the lockdown button in science actually works.
Spoiler alert, it was the shutters, not the button.
:cl:
/:cl:

Fixes a Lockdown button

---

code/game/objects/items/plushes.dm
code/modules/WVM/wvm.dm
code/modules/cargo/export_scanner.dm
code/modules/cargo/exports/materials.dm
code/modules/fallout/obj/stack/f13Cash.dm

Removes union scrip

---

_maps/map_files/coyote_bayou/Newboston.dmm

Small map fix

---

code/modules/jobs/job_types/oasis.dm

It's like a gyser wtf
:cl:
/:cl:

Hopefully fixes Guild Knights shit overflow

---

code/game/objects/items/devices/megaphone.dm
code/modules/jobs/job_types/oasis.dm

Worked alongside fenny to get this working! Should be just right.

Utterly cleans up the guild loadouts

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm
code/game/objects/structures/ladders.dm
modular_coyote/code/game/objects/items/melee.dm
modular_coyote/code/objects.dm

• Additional New Boston housing + bugfixes.
• Rugs should stay below other stuff now.
• Something something axe should have melee swing.
• Fixing of Red Rocket.
• Introduction to new ladders... doors! That's right! You now have teleport doors that will throw you into a door far away. Enjoy being teleported on top of the door. That's right! Not in front of it, on top of it! They have cheeky names to mock a certain very very very trash developer.
:cl:
qol: More New Boston housing refurbishments. Embrace the tiny-homes!
/:cl:

Stuff no one cares about Pt. 7

---

code/modules/mob/living/simple_animal/hostile/f13/chinese.dm
code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
code/modules/mob/living/simple_animal/hostile/f13/insects.dm
code/modules/mob/living/simple_animal/hostile/f13/raider.dm
code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
code/modules/mob/living/simple_animal/hostile/pirate.dm
code/modules/mob/living/simple_animal/hostile/russian.dm
code/modules/mob/living/simple_animal/hostile/syndicate.dm
modular_sunset/code/mob/renegade.dm

Okay its a bit much

---

code/game/objects/items/devices/radio/encryptionkey.dm

Seems I did an oopsy and left the _town part

Fixes the Guild Radio

---

_maps/map_files/coyote_bayou/Dungeons.dmm

You see everyone as demons! Don't touch it..

Adds an interesting hazard into bubblegums room/hellzone

---

code/game/objects/effects/spawners/masterlootdrop.dm
code/modules/projectiles/guns/mods/mods.dm

Should make ballistics noticeably better.

Ballistic Equivalent for Giga Lens

---

code/modules/clothing/chameleon.dm
modular_citadel/code/modules/client/loadout/suit.dm

Drip Harness

---

code/modules/surgery/organs/autosurgeon.dm

It doesn't take 30 seconds for surgery in this codebase lol.

Lowers the Autosurgeon use from 30 to 20

---

code/controllers/subsystem/vore.dm

Mostly non game changers, unless you can weaponize dice. Which you totally can.

Adds more things you shouldnt eat but can

---

code/controllers/subsystem/artifacts.dm

also no more candles, cant see em

Adds more totally fine stuff that can be artifacts

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

Oddy made den boo boos

---

code/modules/jobs/job_types/oasis.dm

How did he say garnment instead of german.

Fixes the Guild Loadout Box

---

code/modules/projectiles/guns/ballistic/shotgun.dm

Fixes the shotgun class cause it smelly
:cl:
/:cl:

(MERGE SMELLEH) Shotgun class fix

---

_maps/map_files/coyote_bayou/Newboston.dmm

…an pass back and forth without going outside again
Fenny pr, womp womp
:cl:
/:cl:

Fixes guild door from library to kitchen so that all the guild jobs c

---

code/controllers/master.dm
code/game/world.dm

Add a couple logs

---

code/__DEFINES/is_helpers.dm
code/__DEFINES/misc.dm
code/__DEFINES/mobs.dm
code/__DEFINES/preferences.dm
code/__HELPERS/_lists.dm
code/controllers/subsystem/pornhud.dm
code/modules/arousal/arousal.dm
code/modules/arousal/genitals.dm
code/modules/arousal/organs/breasts.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/mob/dead/new_player/preferences_setup.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/mob/living/carbon/human/species.dm
modular_coyote/code/modules/say/soundbubbles.dm

You can pick where your undies layer over, including genitals
added wings and tails for real now to pornhud

Touches up undies

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

Just a few more touch ups near the den!

More mapping fixes!

---

code/modules/research/designs/misc_designs.dm
code/modules/research/techweb/all_nodes.dm

A bit costly to produce, but now you won't be limited to just salvage! Just your material numbers.

Adds crafting components to research list

---

modular_coyote/code/creature_species.dm

I tested this code, but it didnt work on my server because its outdated. There shouldnt be any issue with it though, I was very careful
:cl:
/:cl:

Adds new mechs and robots

---

code/__DEFINES/is_helpers.dm

I didnt know is helpers was even a thing, thanks Dan for telling me about it
:cl:
/:cl:

Defines new adapted mobs as robots correctly

---

code/modules/supplykit/supplykit_items/supplykit_energy.dm

tglasers arent self charging and also the covenant energy pistol is missing from the supplykit, so I added it. Also, I added the portable recharger for 40. Technically you can get one by buying coins up to 50, but I'm heavily biased, and its basically a self charging gun, but for energy weapons and cells
:cl:
server: something server ops …

Adding new stuff to energy supplykit

---

code/game/objects/items/stacks/supplytoken.dm
code/modules/supplykit/supplykit_items.dm
modular_citadel/code/modules/client/loadout/head.dm
modular_citadel/code/modules/client/loadout/suit.dm

smol edits

---

code/modules/projectiles/guns/ballistic/revolver.dm

fixes some incorrectly sized heavy revolvers
buffed their damage to compensate

balance PR #5 morbillion

---

code/modules/research/techweb/nodes/alien_nodes.dm
code/modules/research/techweb/nodes/engineering_nodes.dm

Fixes the crafting tools oopsy I did, and removes the need to go out and nab hard to find canisters. Made it  dredge to finish everything.

Removes Experimental Tools Pre-request, and Fixes Crafting Research

---

code/modules/supplykit/supplykit_items/supplykit_explosives.dm
code/modules/supplykit/supplykit_items/supplykit_misc.dm

fixes a few stuff

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm

Removed a small room to add it
:cl:
/:cl:

HN Bathroom Addition

---

modular_coyote/code/creature_species.dm

I forgorb to change le' id, leading to invisible mobs
:cl:
/:cl:

Fixes oties to work

---

code/modules/supplykit/supplykit_items/supplykit_materials.dm

Fuzz owes me 7 kisses now

---

code/modules/WVM/wvm.dm
code/modules/projectiles/guns/mods/mods.dm

butter and lollipops for Dan and me!

one for the money two for the better green

---

modular_coyote/code/creature_species.dm

Adds the fat oties and scroties
:cl:
/:cl:

asterisk inflates you big and round asterisk

---

modular_citadel/code/modules/client/loadout/__donator.dm

For some reason lux's armor choices wouldn't find the path even though I put it in correctly. I'll try again tomorrow.

Loadout kits Dark/lux

---

code/modules/WVM/wvm.dm

name fix for the new vendor stuff
:cl:
fix: ultrasteel name fixed
/:cl:

That's not black bronze, silly

---

modular_coyote/code/creature_species.dm

I forgot to make it pull from the MNA dmi instead of splurtbot
:cl:
/:cl:

Makes advanced cybernetics (MNA) not invisible

---

code/datums/components/crafting/recipes/recipes_assemblies.dm

maybe we'll have a real game one day

treasure hunter changes

---

code/modules/jobs/job_types/tribals.dm

Adds the scry orb to shamans backpack, they had it before
:cl:
/:cl:

Gives shamans their orb back so they can ponder

---

code/modules/mob/living/simple_animal/friendly/farm_animals.dm

Fixes motorbikes being milkable (They produce something other than milk now)
:cl:
/:cl:

Fixes motorbikes being milkable (They produce something other than milk now)

---

code/__HELPERS/unsorted.dm
code/datums/components/melee_special.dm
code/game/objects/items/validball.dm
code/modules/mob/living/carbon/human/human.dm
code/modules/projectiles/ammunition/_firing.dm
code/modules/projectiles/projectile.dm

you no longer melee special things youre riding (or anyone whos friendly on your tile)
you'll also not shoot anyone within a tile or so if they're friendly, and you dont have CI on

Lets you ride your wife into battle

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

Made the den hot spring a bit more romantic, and then made some QOL stuff. Did try some experimental stuff, stand by for addition bug fix prs

I like pretty things

---

modular_citadel/code/modules/client/loadout/__donator.dm

Adds in Sawyers red tennis ball and anothers riot helmet 
:cl:
/:cl:

Adds in two donator things

---

code/modules/mob/living/carbon/human/species.dm
code/modules/mob/living/carbon/monkey/life.dm

makes humans and monkeys take damage while on fire

---

modular_coyote/code/creature_species.dm

They have resting sprites, they dont need to do this
:cl:
/:cl:

Fixes MNA rotating when resting

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm

My experiments did not work

---

code/game/turfs/simulated/water.dm
code/modules/fallout/turf/ground.dm
code/modules/mob/living/carbon/human/update_icons.dm

Water should no longer leave your body sitting in the puddle until you turn back. Still dont know why it did that, but now it doesnt, so good.
Also vore shoud work when you're on water. It titally didnt btw. Couldnt test, so, maybe!

fixes TF on water?

---

modular_citadel/code/modules/client/loadout/__donator.dm

https://github.com/ARF-SS13/coyote-bayou/pull/4661
PR was reverted accidentally. This re-adds it.

Loadout Dark/Lux

---

code/game/objects/effects/spawners/masterlootdrop.dm
code/modules/cargo/packs/security.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/supplykit/supplykit_items/supplykit_energy.dm

sorry gamers
PR has effect on lootlist,won't break it but it'll be funky

lasers aks now not god tier

---

code/modules/jobs/job_types/tribals.dm

Apparently you cant spawn too many things in the bag at one time or it just doesnt appear
:cl:
/:cl:

Gives shamans back their pondering orb (For real this time) (((((((hopefully)))))))

---

code/modules/jobs/job_types/oasis.dm

Should fix the reclaimer double supply kits oops

---

code/controllers/subsystem/research.dm

Ups research blueprints to 5k, like their desc says

---

code/modules/research/designs/power_designs.dm

Fixes Hypercharged cells in Research

---

code/game/machinery/porta_turret/portable_turret.dm

ande probably shoot u in closets too

turrets shoot mechs now again

---

code/modules/fallout/turf/ground.dm

Adds the new berries to the random spawn list

---

code/game/mecha/combat/durand.dm
code/game/mecha/working/ripley.dm

yolo swagins 2013 we armor core now boys lets eat ass and chew taint
:cl:
/:cl:

Jacks mech speed up and makes em strafe

---

code/__DEFINES/mobs.dm
code/datums/wounds/bleed.dm
code/modules/mining/machine_vending.dm
modular_splurt/code/modules/research/xenoarch/artifact_list.dm
modular_splurt/code/modules/research/xenoarch/strange_rock.dm

potentially fixes massive client lag

---

code/game/objects/items/loadout_beacons.dm
code/game/objects/items/melee/energy.dm
code/modules/supplykit/supplykit_items/supplykit_meleesmall.dm

fixes 'typos'
spellcheck:changes all instances of the melee plasma weapon, outside of its atom path to prevent code issues
/:cl:

Fixes plasma 'slicers' fully

---

code/modules/mob/living/simple_animal/hostile/hostile.dm

Usually when you think something's been disabled for something like performance or balance reasons, like 90% of the time its just broken and im too embarassed to say anything.

Fixes mob infighting not working

---

code/modules/mob/living/carbon/human/human.dm

The rider no longer needs hands, for edge cases where it makes sense, like having a micro sniper on your shoulder
:cl:
/:cl:

Buffs carrying a little to encourage teamwork

---

tgui/packages/tgui-dev-server/reloader.js

Gets the TGUI dev server to work on BYOND 515
:cl:
/:cl:

Fix a little oopsie

---

_maps/map_files/coyote_bayou/Newboston.dmm

Imagine not having a wall there

---

code/modules/projectiles/boxes_magazines/ammo_boxes.dm

Doubles all ammo box capacity

---

_maps/map_files/coyote_bayou/Ashdown-Upper.dmm

removes ashdown spawns

---

code/datums/traits/good.dm

Blocks little leagues from bruiser, otherwise Big and Little leagues DO appear to work so
Fixes #4259
:cl:
/:cl:

Unlittleing Bruiser

---

tgui/packages/tgui/interfaces/Orbit.js

Fixes #4044
Though, I hate observer overall. it is a terrible concept for us and a remnant of normal ss13 that I firmly believe we do not need.
:cl:
/:cl:

Removes the dead list from orbit

---

arfsuits.dm

Fixes insect chitin armors wrong icon

---

modular_citadel/code/modules/client/loadout/__donator.dm

Adjusts my loadout to add a really cool armor.
Need to have this armor craftable. Somehow.
:cl:
tweak: Adjusts a loadout box.
/:cl:

Modifies a Loadout

---

code/datums/components/orbiter.dm
code/modules/projectiles/guns/magic/wand.dm
tgui/packages/tgui/interfaces/Orbit.js

Reverts ARF-SS13/coyote-bayou#4740

Revert "Removes the dead list from orbit"

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm

It's literally just dressers for Jess.
I am not "too much of a sub to wear underwear" :'(

Stuff no one cares about Pt. 9

---

code/modules/projectiles/guns/misc/medbeam.dm

Poor robots couldnt get healed by staves, but now they do
:cl:
/:cl:

Medbeam and healing staff heals robots

---

code/modules/vending/cigarette.dm

puts syndiecigs in the cig machine

---

code/modules/projectiles/guns/magic/staff.dm
code/modules/supplykit/supplykit_items/supplykit_magic.dm

adds more low power magic staffs for spawning in with
also fixes lesser fireball staff
:cl:
/:cl:

Magic Gear Expansion

---

code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm
code/modules/mob/living/simple_animal/hostile/f13/centaur.dm
code/modules/mob/living/simple_animal/hostile/f13/chinese.dm
code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
code/modules/mob/living/simple_animal/hostile/f13/insects.dm
code/modules/mob/living/simple_animal/hostile/f13/mirelurks.dm
code/modules/mob/living/simple_animal/hostile/f13/raider.dm
code/modules/mob/living/simple_animal/hostile/f13/rattler.dm
code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
code/modules/mob/living/simple_animal/hostile/f13/tunnelers.dm
code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
code/modules/mob/living/simple_animal/hostile/f13/wolf.dm
code/modules/mob/living/simple_animal/hostile/pirate.dm
code/modules/mob/living/simple_animal/hostile/russian.dm

Its a placeholder, but it'll have to do for now until we can dial them in better.
:cl:
/:cl:

Preliminary Mob Loot Rolls

---

code/__HELPERS/_string_lists.dm
code/__HELPERS/unsorted.dm

okay maybe like 2 people, but still
Anyone whose name is literally just their ckey (no idea why you'd do this but okay) will be replaced with a cow or fish.
Also included (not included) is a json where you can easily add in exceptions to the list, so if your character's name is just your name, you wont be a fish (sadly).

Fixes the orbit menu doxing literally everyone

---

modular_sunset/code/mob/renegade.dm

Renegade loot drops

---

code/__HELPERS/_string_lists.dm
code/__HELPERS/unsorted.dm

And lets it load things from other folders!

Fixes stringcache breaking down completely

---

code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm
code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm
code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
code/modules/mob/living/simple_animal/hostile/f13/insects.dm
code/modules/mob/living/simple_animal/hostile/f13/mirelurks.dm
code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
code/modules/mob/living/simple_animal/hostile/f13/tunnelers.dm
code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
modular_coyote/code/mob.dm
modular_sunset/code/mob/renegade.dm

adds loot to hellpigs

---

code/modules/projectiles/projectile/beams.dm
modular_coyote/eris/code/mods/mod_types.dm

So many changes, hard to descibe.
Paint is now more properly tiered and doesn't ramp up to insane numbers.  Black paint is the combination of all the previous paints, which means you may not always want it specifically.
:cl:
/:cl:

Mod & Paint Overhaul

---

modular_coyote/eris/code/mods/mod_types.dm

I forgot to put damage on black paint

---

code/modules/mob/living/simple_animal/hostile/megafauna/behemoth.dm
code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
code/modules/mob/living/simple_animal/hostile/megafauna/captainarlem.dm
code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm

- Loot for behemoth, arlem & drakes
- Blood drunk miners made raider faction
- Heiro set to a handful of factions, should stop it being infought to death
:cl:
/:cl:

More mob loot changes & some factions

---

_maps/map_files/coyote_bayou/Newboston.dmm

because they were not on this plane of reality
:cl:
/:cl:

makes the new boston fishing poles real

---

code/modules/holiday/holidays.dm
code/modules/reagents/chemistry/reagents/toxin_reagents.dm
code/modules/reagents/chemistry/recipes/toxins.dm
code/modules/surgery/advanced/necrotic_revival.dm

removes zombie powder, maybe lets us pass integ checks now

---

code/modules/research/designs/ammolathe_designs.dm

4.7 has a fucking crate now

---

code/datums/traits/negative.dm

see title
did I test this? no I just changed numbers

increases the amount of gain from hardcore

---

code/game/objects/items/stacks/sheets/sheet_types.dm
code/modules/food_and_drinks/kitchen_machinery/smartfridge.dm

15 metal for something that can barely store 20 items, its good if your putting a bunch of trashy guns on it, but it really needs help, this is that help
:cl:
/:cl:

buffs shop shelves

---

code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm

*centers ur molerats cutely

---

code/datums/traits/negative.dm

Just makes toxinlover a direct trait-applying quirk instead of not being obtainable after it was removed from xenobio hybrids. Same price as hardcore since the whole reason it was removed was due to slimes getting RR'ed by hunting horns that don't trueheal. Also specifically mentions mages and the non true-healing systems to prevent the apparent 'noob trap'. The wording could use some refinement but, those who pick this already know what it is in the first place. Also Jaeger helped with this in both pricing and philosophy.
🆑 
add:Toxinlover quirk
/🆑

Toxinlover quirk

---

_maps/map_files/coyote_bayou/Newboston.dmm

https://discord.com/channels/986779026205073408/991100197666967552/1220743932032319628
Literally this, just puts a grinder in the reclaimers chem room, because that is a basic chem device, especially for botanical use, not much else to say. Technically untested because it is a singular line of code about a new grinder QoL. big diff.
add: grinder
/:cl:

reclaimers grinder

---

code/modules/projectiles/guns/magic/wand.dm

After killing a hellpig by mag dumping it with 3 wands on headshots (Which took about 3 seconds to do), I feel like the spark wand might be slightly overtuned
:cl:
/:cl:

Nerfs the sparkwand a lil'

---

code/datums/components/crafting/recipes/recipes_clothing.dm
code/game/objects/items/holy_weapons.dm
code/game/objects/items/storage/belt.dm
code/modules/reagents/chemistry/reagents/medicine_reagents.dm
modular_citadel/code/modules/client/loadout/neck.dm

Renames shoulder holster to "standard holster" so that people know to use it, because its statistically the same as the ranger cape now. Also buffs the medbot chem, and adds it to the prayer beads
:cl:
/:cl:

Buffs medbot chem/prayer beads/shoulder holster

---

code/modules/projectiles/boxes_magazines/internal/misc.dm
code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/projectiles/guns/ballistic/rifle.dm
modular_citadel/code/modules/client/loadout/__donator.dm

ran the debug verb
they're fine

three loadouts

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Quick map fixes

---

code/modules/cargo/packs/security.dm

fixes exploit (lmao)

---

code/game/objects/items/storage/survivalkit.dm
code/game/objects/items/teleportation.dm
code/modules/research/designs/bluespace_designs.dm
code/modules/research/techweb/nodes/bluespace_nodes.dm

what this PR does
1. removes beacons from science printability
2. gives hand teles to the survival kit

fast travel

---

AAADevTool/AAA_DEVELOPMENT_CONFIG.dm
AAADevTool/AAA_DEVELOPMENT_CONFIG.json
code/__HELPERS/_lists.dm
code/controllers/subsystem/mapping.dm
code/modules/mapping/reader.dm
code/modules/mapping/space_management/space_transition.dm
fortune13.dme

Wleocme-to-the-ntfc-atlas

---

code/modules/shuttle/supply.dm

should help (but not eliminate) CI failures

Fixes shuttles runtiming at roundstart

---

modular_coyote/code/objects.dm

makes rugs and carpets render at a lower layer

---

code/modules/projectiles/boxes_magazines/internal/misc.dm
code/modules/projectiles/guns/ballistic/automatic.dm
modular_citadel/code/modules/client/loadout/__donator.dm

removes the LLX90

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm
code/game/objects/items/storage/survivalkit.dm

brim said tribe wants teleporters
I put the teleporters in their survival kit

map PR # 1 billion + tribal teleporter

---

code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm

lol tungsten cube

---

code/modules/mob/living/simple_animal/hostile/killertomato.dm

Buffs the lil guys uwu
:cl:
/:cl:

Killer-er Tomatos

---

code/modules/mob/living/simple_animal/hostile/netherworld.dm
code/modules/mob/living/simple_animal/hostile/sharks.dm

More mob buffs

---

code/_onclick/telekinesis.dm
code/datums/mutations/telekinesis.dm
code/datums/traits/good.dm
code/modules/clothing/chameleon.dm
code/modules/projectiles/guns/magic/staff.dm

Magehand is just telekinesis but nerfed. Show how friggin cool you are by slinging around and using objects from a distance, or making the environment sparkle. Goes great with the wisps I added a while ago.
:cl:
/:cl:

Tweaks Alchemy Staff, Nerfs Chameleon Cloths, Adds Magehand

---

_maps/map_files/coyote_bayou/Dungeons.dmm

Removes the funny arlem beacon

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

More Newbs Town Tweaks (ruins)

---

code/game/objects/hand_items.dm

to make the biggest ones slowest, like they should be.  Unrinification
:cl:
/:cl:

Updates the clawer/biter/tailer speeds

---

code/datums/traits/good.dm

Big Game Hunter oversight

---

code/modules/projectiles/guns/magic.dm

Removes the chat spammy magic weapon procs

---

code/controllers/subsystem/economy.dm
code/modules/client/preferences_savefile.dm

Chatspamn't

---

code/modules/antagonists/changeling/powers/mutations.dm

makes it small, to be used with weak of muscle
:cl:
/:cl:

Arm Tent shrink

---

modular_coyote/code/creature_species.dm

A completely biased salt PR because now I cant pretend to be a box in the corner of the room spilling drinks onto people with telekinesis because synthetics dont have DNA
:cl:
/:cl:

Makes mimics organic instead of synthetic

---

_maps/map_files/coyote_bayou/Ashdown.dmm
_maps/map_files/coyote_bayou/Garland-City.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Newboston.dmm
_maps/map_files/coyote_bayou/Redwater.dmm
code/game/objects/items/teleportation.dm
modular_coyote/code/modules/area_blurb.dm

1. Adds Reclaimer Portal Storm Shelters to the wastes. Features technology that exploits them to teleport to places.
2. Adds a tip to a failed teleport.

teleporter tweaks

---

code/__DEFINES/traits.dm
code/datums/traits/good.dm
code/modules/mob/living/simple_animal/hostile/bees.dm

A quirk to make radbees non-hostile to you.
:cl: Anonymous
add: Beefriend with the new quirk!
/:cl:

Added bee friend quirk

---

_maps/map_files/coyote_bayou/Ashdown-Upper.dmm
_maps/map_files/coyote_bayou/Ashdown.dmm
_maps/map_files/coyote_bayou/Backup Nash/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Backup Nash/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Backup Nash/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Backup Nash/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Backup Nash/Newboston.dmm
_maps/map_files/coyote_bayou/Dungeons.dmm
_maps/map_files/coyote_bayou/Garland-City.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm
_maps/map_files/coyote_bayou/Redwater-Upper.dmm
_maps/map_files/coyote_bayou/Redwater.dmm
_maps/map_files/coyote_bayou/Texarkana_underground.dmm
code/game/objects/structures/tables_racks.dm
code/modules/food_and_drinks/kitchen_machinery/microwave.dm
modular_coyote/code/objects.dm

Reverts ARF-SS13/coyote-bayou#4857

Actually Fixes White Stove and Counters [READY]

---

_maps/map_files/coyote_bayou/Dungeons.dmm
_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Merge my shit before I shin you with a bat
:cl:
/:cl:

New Boston Update

---

_maps/map_files/coyote_bayou/Newboston.dmm

I literally can not strop
:cl:
/:cl:

More map tweaks

---

code/datums/traits/good.dm

fixes beastcummer

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Fixes heavens nights doors

---

code/datums/components/mood.dm
code/modules/mob/living/carbon/life.dm

drunkenness works.
mood icon has colors to indicate sanity
mood event sound has an adjustable 5 second cooldown
:cl:
/:cl:

better mood events

---

code/game/objects/structures/flora.dm
code/modules/antagonists/changeling/powers/mutations.dm

Works, but likely needs adjusting 😆 
:cl:
/:cl:

Floral Size Variation

---

code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm

Culls doubled up protectron taunts

---

code/modules/mob/living/emote.dm

Adds a few smug versions of emotes, for the brats in the class.  Also a leer.
:cl:
/:cl:

Smug Update & Leer

---

code/modules/client/preferences.dm

Cactus Fixes Dans Integ fail while forgetting they're on my liveshare

---

modular_citadel/code/modules/client/loadout/__donator.dm

father alric

---

code/modules/mob/say_vr.dm

Enloudens Subtler sound effect

---

_maps/map_files/coyote_bayou/Dungeons.dmm
_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Makes the ladder to the 'upper' part of Heavens Night functional.
Adds Curtains to Heavens Night
Adds some carpet to Heavens Night.
:cl:
/:cl:

Small changes to Heavens Night

---

code/__DEFINES/traits.dm
code/datums/components/crafting/recipes/recipes_tools.dm
code/datums/traits/good.dm
code/game/machinery/doors/door.dm
code/game/objects/items/prize_loot.dm

lockpicks are more reliable but require the Security Expert trait to craft and use. there's also an improved lockpicking set that's better but more expensive to make.
:cl:
/:cl:

better lockpicks and security expert trait

---

code/datums/traits/negative.dm

Makes very flimsy not kill you instantly on spawn with no chance of revival

---

code/modules/client/verbs/looc.dm
code/modules/mining/equipment/lazarus_injector.dm
modular_citadel/code/modules/client/loadout/__donator.dm

LOOC sounds

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm

Small map fix - roofing new boston

---

_maps/map_files/coyote_bayou/Newboston.dmm

Adds
- seed vendor
- Biogen
- Seed extractor
- Nutrimax
- Bucket
:cl:
/:cl:

NB Farm Additions

---

code/datums/components/crafting/recipes/recipes_assemblies.dm
modular_sand/code/modules/crafting/recipes/recipes_misc.dm

Fixes the recipe where Amusing Ducks were made from not being makable.

Make ducks craftable, now

---

code/modules/hydroponics/grown/ambrosia.dm

Reduces the Weed Rate and Weed Chance on Ambrosia gaia
:cl:
/:cl:

Buffs Ambrosia Gaia by reducing its weeds.

---

code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm
code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
code/modules/projectiles/projectile/beams.dm

you know, so skill can actually be a thing
:cl:
/:cl:

Slows down some bot lasers

---

code/controllers/subsystem/monster_wave.dm
code/datums/components/spawner.dm

unbreaks Rifts

---

code/_onclick/hud/_defines.dm

I may be fucking with the UI soon.  We'll see.
:cl:
/:cl:

Slides the quest button over a few pixels

---

code/modules/jobs/job_types/oasis.dm

Knew I probably missed some of these
:cl:
/:cl:

Prospector PDA

---

code/controllers/subsystem/second_wind.dm

Second wind recycle to 1 hour 15 minutes

---

code/modules/projectiles/boxes_magazines/external/smg.dm
code/modules/research/designs/ammolathe_designs.dm

empty vss mag added to autolathe

---

code/modules/jobs/job_types/wasteland.dm

They have the supply kit now, don't need two
:cl:
/:cl:

Pulls one medkit from Tex-Ranger

---

code/modules/mob/dead/new_player/sprite_accessories/tails.dm

Fixes the raddog tail

---

code/__DEFINES/time.dm
code/controllers/subsystem/who.dm
code/datums/components/crafting/recipes/recipes_assemblies.dm

New (under 4 days of playtime) players show up as New! in who. Also makes ducks a biit less awful to play as (also you can play as em if you find one).

Ducks and Newbies

---

code/modules/instruments/instruments/item.dm
code/modules/instruments/instruments/stationary.dm

Not anchored so you can drag it around. Realstic? No. Do I care? Also no! Piano time
:cl:
/:cl:

Adds piano too the delivery becon

---

code/game/objects/items.dm

why was that even there. people don't want to know how much damage an old version of their weapon does. they want to know how much THEIRS will do if they swing it NOW.
:cl:
/:cl:

remove initial() from examine calculations

---

code/game/objects/items.dm

force bonus is already added to force
:cl:
/:cl:

stop double-counting force_bonus

---

code/modules/jobs/jobs.dm

Oops I forgot to add reclaimer healer

---

code/modules/hydroponics/hydroponics.dm

Removes weeds and makes nutriment drain slower

---

code/modules/hydroponics/hydroponics.dm

Lowers the drain further

---

code/controllers/subsystem/who.dm
code/modules/mob/living/simple_animal/hostile/duckbot.dm

Why didnt this fucking commit

---

_maps/map_files/coyote_bayou/Newboston.dmm

Re-adds new boston gate button

---

code/modules/fallout/obj/structures/mob_spawners.dm
code/modules/mob/living/simple_animal/hostile/f13/insects.dm
code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm

- moves broodmothers up
- turns micro rats back on
- pillbugs variants turned on oops
:cl:
/:cl:

Molerat & Radroach Fixes

---

code/game/turfs/simulated/floor/f13_floors.dm

fixes broken streets having a missing icon state

---

code/modules/mob/living/carbon/human/species_types/podpeople.dm
code/modules/mob/living/carbon/human/species_types/synthliz.dm

Apparently this was just in the greyscaled limb code, I added it to synths because golems are cool. 
Did you know
Golems have tits
On the female sprite?
:cl:
/:cl:

Makes golems "playable"

---

code/modules/admin/verbs/playsound.dm

Adds a single line of code to fix Play-Internet-Sound
:cl:
/:cl:

Tries to fix Play Internet Sound

---

code/game/objects/items/tools/crowbar.dm
code/game/objects/items/tools/screwdriver.dm
code/game/objects/items/tools/wirecutters.dm
code/game/objects/items/tools/wrench.dm

Basically just gives robots minor healing for free
:cl:
/:cl:

Adds robo heal functionality to wrench/crowbar/screwdriver

---

code/modules/jobs/job_types/oasis.dm

Removes extra librarian money stash

---

code/datums/components/crafting/crafting.dm
code/datums/components/crafting/recipes/recipes_explosives.dm
code/datums/components/crafting/recipes/recipes_misc.dm
code/modules/smithing/smithed_items.dm
tgui/packages/tgui/interfaces/PersonalCrafting.js

makes crafting menu more usable
:cl:
/:cl:

give ingots names, fixes crafting tabs, adds refresh button to craft menu

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm
code/modules/jobs/job_types/wasteland.dm

Its not a great spot, but it sure is a spot of all time.  Also gets their spawn and sets their faction to Oasis.
:cl:
/:cl:

Moves Radio Operator into New Boston

---

code/modules/jobs/job_types/oasis.dm

Barkeep PDA

---

code/modules/cargo/packs/secballistics.dm

these are basically worthless and craftable by everyone, no need to buy them

removes the combat knife pack

---

_maps/map_files/coyote_bayou/Newboston.dmm
code/modules/jobs/job_types/oasis.dm

Adds Science Access to Reclaimer Healer so they can actually do their job.
Fixes a small area bit around Heavens Night
:cl:
/:cl:

Fixes Reclaimer Healer Access

---

code/datums/components/crafting/recipes/recipes_bottling.dm
code/modules/cargo/bounties/kill_quests.dm
code/modules/research/designs/autobotter_designs.dm

4800 copper for 1000u of liquid (Literally 3 harvests) is a little rediculous. This should make it a little more difficult. This might still require more tuning.
(Easy: 240 copper for 200u)
(Medium: 750 copper for 500u. Requires one of 4 specific bottles)
(Hard 2000 copper for 1000u. Requires one of 3 specific bottles)
(CBT: 4000 copper for 2000u. Requires one of 2 specific bottles)
:cl:
config: changed some …

Makes export bottle quests a little less rediculously rewarding

---

code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
code/game/objects/effects/spawners/masterlootdrop.dm
code/game/objects/items/loadout_beacons.dm
code/game/objects/items/tools/crowbar.dm
code/game/objects/items/tools/screwdriver.dm
code/modules/cargo/bounties/kill_quests.dm
code/modules/cargo/exports/misc_export.dm
code/modules/cargo/packs/secenergy.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/energy/laser_crank.dm
code/modules/reagents/chemistry/reagents/medicine_reagents.dm
code/modules/supplykit/supplykit_items/supplykit_energy.dm

Also fixes a quest making people crash, everything else on the tin. Thanks to dan for making them auto-pump
:cl:
/:cl:

Makes tg lasers into crankguns, inverts medibot chem functions

---

code/modules/mob/dead/new_player/sprite_accessories/wings.dm

Cause angels can have more then white wings.
:cl:
/:cl:

Makes angel wings colorable

---

code/modules/cargo/bounties/kill_quests.dm
code/modules/projectiles/guns/energy/laser_crank.dm

Unsure how to fix it beyond this so uh 🤷 
:cl:
/:cl:

Possible fix for salvage quota quests.

---

_maps/map_files/coyote_bayou/Dungeons.dmm

Adds a Dare Dice room to Heavens Night.
:cl:
/:cl:

Adds a Dare Dice Room to Heavens Night

---

code/modules/cargo/bounties/item_quests.dm
code/modules/cargo/bounties/kill_boss_quests.dm
code/modules/cargo/bounties/kill_quests.dm
code/modules/cargo/bounty.dm

Makes CBT quests not overwrite other quests.

Expands cock and ball torture

---

code/game/objects/items/stacks/sheets/mineral.dm
modular_coyote/code/game/objects/structures/barricade.dm

See title.
maybe engineering job soon?

adds directional sandbag barricades

---

code/modules/cargo/bounties/kill_quests.dm
code/modules/projectiles/guns/energy/laser_crank.dm

Oops, I forgot to label a projectile correctly, everyone gets 60 damage laser carbines!
:cl:
/:cl:

Fixes tg laser stats + quests

---

code/modules/projectiles/guns/energy/laser_crank.dm

Reverts ARF-SS13/coyote-bayou#4965

Revert "Makes improv laser do music box noises"

---

code/modules/projectiles/guns/energy/laser_crank.dm

TG crank gun no longer kills the server ( And makes music box noises)

---

code/controllers/subsystem/economy.dm
code/game/machinery/autolathe.dm
code/game/objects/items/stacks/stack.dm
code/modules/WVM/wmv_buyer.dm
code/modules/WVM/wvm.dm
code/modules/paperwork/paper.dm
code/modules/vending/_vending.dm

Vendors now output exact change.
And you can gamble with lathe rerports.

Fixes vendors eating cash, and makes lathe reports worth something

---

code/modules/projectiles/guns/energy.dm

Self charger weapons now recharge by using them inhand instead of alt clicking them
:cl:
/:cl:

Self charger QOL

---

code/modules/clothing/spacesuits/hardsuit.dm
modular_citadel/code/modules/client/loadout/__donator.dm

Removes the unique Cydonian Powersuit item and from a ckey loadout. The character it was for no longer exists and I was unhappy with the item as it felt too strong.
:cl:
- Cydonian Powersuit unique removed
- Removed the Cydonian Powersuit from a Ckey loadout
:cl:

Edits Kelprunner's Loadout (Good to go if it passes checks)

---

modular_coyote/code/creature_species.dm

Adds playable german shepard

---

code/modules/projectiles/projectile.dm

pvp is now opt in

---

modular_sand/code/datums/interactions/interaction_datums/lewd/self/cb_does_it_better/coy_crotch.dm

sugma fixes

---

modular_coyote/code/modules/say/soundbubbles.dm

Reverts ARF-SS13/coyote-bayou#4990

Revert "makes radio sound only audible within your tile"

---

modular_coyote/code/modules/say/typing_sounds.dm

Reverts ARF-SS13/coyote-bayou#4991

Revert "Fixes Many Voices Repeatedly Overlapping When Spoken"

---

AAADevTool/AAA_DEVELOPMENT_CONFIG.json
code/controllers/subsystem/chat.dm
code/controllers/subsystem/who.dm
modular_splurt/code/datums/modules/client/verbs/character_directory.dm
tgui/packages/tgui/interfaces/CharacterDirectory.js
tgui/packages/tgui/interfaces/CharacterInspection.js

And makes the lag kinda sorta stop lagging

Fixes DMs maybe

---

code/__DEFINES/span.dm
code/controllers/subsystem/chat.dm
code/controllers/subsystem/monster_wave.dm
code/modules/mob/dead/new_player/new_player.dm
modular_splurt/code/datums/modules/client/verbs/character_directory.dm
tgui/packages/tgui-panel/styles/goon/chat-dark.scss
tgui/packages/tgui-panel/styles/goon/chat-light.scss

Fixes DMs AGAIN

---

_maps/map_files/coyote_bayou/Dungeons.dmm

Bos dungeon fix

---

modular_citadel/code/modules/client/loadout/__donator.dm

Adds a hat to a loadout.
:cl:
/:cl:

Updates a Loadout

---

code/__DEFINES/preferences.dm
code/controllers/subsystem/chat.dm
code/controllers/subsystem/gunreticle.dm
code/modules/client/preferences_savefile.dm
modular_splurt/code/datums/modules/client/verbs/character_directory.dm
tgui/packages/tgui/components/TogglePopup.js
tgui/packages/tgui/components/index.js
tgui/packages/tgui/interfaces/CargoBountyConsole.js
tgui/packages/tgui/interfaces/CharacterDirectory.js
tgui/packages/tgui/interfaces/PaperSheet.js

fuck you popper you laggy piece of shit, gimme one good reason I dont just gut you and replace you with tippy? aside from the fact i dont know how to

Fixes certain menus being laggy as all get out

---

code/game/objects/items/melee/huntinghorn.dm

you can pick between a few instruments (performance still only has one noise for now). swinging to play a note should actually have audio every time. add small clarification to description
:cl:
/:cl:

HH improvements

---

tgui/packages/tgui/interfaces/CharacterInspection.js

Fixes inspection DMs not working

---

code/datums/status_effects/huntinghorneffects.dm

changes proc used to heal robots and synths so it works on them
:cl:
/:cl:

HH instaheal for robots and synths

---

code/__DEFINES/preferences.dm
code/__HELPERS/_lists.dm
code/controllers/subsystem/economy.dm
code/controllers/subsystem/vore.dm
code/game/objects/items/grenades/grenade.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/vore/eating/belly_obj.dm
tgui/packages/tgui/interfaces/CargoBountyConsole.js

Fixes playing the game well making the game lag to hell

---

code/controllers/subsystem/vore.dm
code/modules/vore/eating/belly_obj.dm
code/modules/vore/eating/vore_core.dm

Vital Vore Vixes

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Some more updates for newbstown

---

_maps/map_files/coyote_bayou/Dungeons.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Guess who bitches

---

code/__HELPERS/_lists.dm
code/game/say.dm
code/modules/client/preferences.dm
code/modules/mob/living/carbon/human/say.dm
code/modules/mob/living/say.dm

replaces the pick-a-verb dropdown with my cool text input version
:cl:
/:cl:

Custom "say" verbs

---

code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm

Shotgunners are now greem

---

code/modules/projectiles/guns/magic.dm

Should stop the low power fireball from being a machinegun
:cl:
/:cl:

Fireballn't

---

_maps/map_files/coyote_bayou/Texarkana_underground.dmm
code/game/objects/structures/ladders.dm

Lets Ghosts Use Ladders & Fixes PDA server connection for nash underground

---

_maps/map_files/coyote_bayou/Newboston.dmm

emagged bar soda vend

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm

oops hard boards

---

modular_coyote/code/objects.dm

- [fuck no] You tested this on a local server.

makes cave deco not solid

---

code/modules/projectiles/guns/energy/laser_crank.dm

:cl:
- Makes the TG blaster pistol check the right projectile instead of the 60 damage template
- Makes the TG blaster pistol recharge twice as fast (10000 power in the battery to 5000, shot cost from 500 to 250)
:cl:

Fixes the TG Blaster Pistol. Again. For, like, the third time (Good to go if it passes checks)

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

new boston rooves

---

_maps/map_files/coyote_bayou/Newboston.dmm

unpisses your river cutely

---

code/datums/components/crafting/recipes/recipes_forge.dm
code/datums/materials/basemats.dm
code/game/objects/items/stacks/bscrystal.dm
code/modules/WVM/wvm.dm
code/modules/smithing/smithed_items.dm

forging hotfixes part 2

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm

house area fix nboston

---

code/game/objects/items/melee/misc.dm
code/modules/WVM/wvm.dm
code/modules/movespeed/modifiers/status_effects.dm

just takes an old one and reflavors it

adventuring supplies vendor

---

code/_globalvars/lists/mobs.dm
code/modules/mob/living/blood.dm
code/modules/reagents/chemistry/reagents/other_reagents.dm

fixes weird blood data issues
:cl:
/:cl:

blood type for blood tomatoes

---

code/controllers/subsystem/autotransfer.dm

Extends linting functionality

---

code/modules/projectiles/guns/energy.dm

Crank guns no longer cry about being self charging

---

code/controllers/subsystem/input.dm

Now you have to use ctrl-tab to make it happen.
PSA: input tab sucks

Makes the input bar harder to use

---

_maps/map_files/coyote_bayou/Newboston.dmm

Fixes a bush on a sneaky spot in NB

---

code/__DEFINES/economy.dm
code/controllers/subsystem/economy.dm
code/datums/components/artifacts.dm
code/game/machinery/autolathe.dm
code/game/objects/items/cards_ids.dm
code/modules/WVM/bountypuncher.dm
code/modules/WVM/wmv_buyer.dm
code/modules/cargo/bounties/item_quests.dm
code/modules/cargo/bounties/kill_boss_quests.dm
code/modules/cargo/bounties/kill_quests.dm
code/modules/cargo/bounty.dm
code/modules/cargo/order.dm
code/modules/keybindings/keybind/carbon.dm
code/modules/paperwork/paper.dm
strings/ion_laws.json

Lathe report cards and scanner hotkey

---

code/controllers/subsystem/input.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/keybindings/setup.dm

if you know a better place to actually set the button than `ensure_keys_set()` feel free to tell me lol
:cl:
/:cl:

toggleable button for input mode switching

---

code/datums/components/crafting/recipes/recipes_forge.dm

reduces cost of whetstone

---

_maps/map_files/coyote_bayou/Dungeons.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Garden in Heaven's Night updated
Garden Completely redone
-Added new apartment
-Moved Dare Dice tent
-Increased amount of green space
-Added bush snuggling spot
-Improved upstairs bar
:cl:
/:cl:

Heaven's Night Map Changes

---

code/game/objects/items/melee/coyotemelee.dm

screaming at melee

---

code/game/objects/items/devices/scanners.dm

I DON'T CARE HOW BIG YOUR E-PEEN IS

makes medscanners not print traits

---

code/game/area/areas.dm
code/modules/fallout/areas/area.dm
code/modules/fallout/turf/ground.dm
modular_coyote/code/modules/mapping/areas.dm
modular_coyote/code/modules/turf_changes/PlantGrass.dm

WAR WITHOUT REASON pt 2

---

code/modules/fallout/obj/structures/mob_spawners.dm

Especially since we're adding a billion more of the spawners, like, wow.

Reduces the amount of shaman spam

---

code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm
code/modules/mob/living/carbon/human/human_defines.dm
code/modules/mob/living/carbon/human/species.dm

Its an option to make your tiny head dot eyes go over the scraggly mass of pixels you call hair (use a comb, dummy)

Adds eyes that go over ur hair

---

code/modules/mob/living/carbon/human/species.dm

eye live on an eyeland eating out furreyes

---

code/modules/cargo/packs/misc.dm
code/modules/research/designs/nanite_designs.dm
code/modules/research/techweb/nodes/nanites_nodes.dm

removes coin conversion, grief nanites, healing nanites

---

config/dbconfig.txt

doing what i was told to do

---

code/modules/projectiles/projectile/special/ion.dm
modular_sunset/code/mob/renegade.dm

emp renegades now no longer kill you

---

_maps/map_files/coyote_bayou/Newboston.dmm

colormate fix

---

_maps/map_files/coyote_bayou/Newboston.dmm

Let there be loight

---

_maps/map_files/coyote_bayou/Newboston.dmm

fucking bus i swear to god

---

code/game/objects/items/melee/f13powerfist.dm
code/game/objects/items/melee/f13twohanded.dm

Rebalances and touches on some melee loot weapons, as requested by the bnuuy, namely buffing some older legendaries that were really bad / underpowered for what they were meant to be, as well as introducing armor piercing elements to some of them, as again requested by them.
(all damage values are considered wielded)
AUTO AXE - 35 + 0.3 AP
STEEL SAW 30 + 0.2 AP
ATOM'S 60 + 0.4 (but increase CD slightly) (removed the useless radiation effect for increased AP)
Court martial 60 1 CD (weaker but faster sledge with knockback is my intention)
ROCKET SLEDGE 55 1 CD 
PROTON AXE 55 - EMP (0.2 AP)
THERMIC 45 (0.2 AP) 0.6 CD, turned it into a spear
DEATHCLAW SPEAR AXE 45 damage (legendary drop) (0.2 AP)
deathclaw spear (0.1 AP)
HEAVY AXE (0.3 AP)
RIPPER / PRE WAR RIPPER (0.2 / 0.3 AP)
super sledge …

revamps a few legendary / rare melee weapons under Jæger's request (part 1)

---

code/datums/components/caltrop.dm
code/game/machinery/obstacles_barricades.dm

Barbed Wire hard stun removal, but add a sound when you walk into it 

---

code/datums/traits/good.dm

fix Security Expert recipes missing

---

code/modules/mob/living/simple_animal/hostile/f13/insects.dm

ant de-assification

---

code/game/sound.dm

Mainly that they are no longer blocked by walls.

Experimental sweeping changes to sound

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

Removes an extra ladder from Texarkana

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Moves ranger station nearer to new boston

---

code/game/objects/effects/spawners/masterlootdrop.dm
code/modules/cargo/exports/misc_export.dm
code/modules/cargo/packs/secballistics.dm
code/modules/cargo/packs/secenergy.dm
code/modules/projectiles/boxes_magazines/external/pistol.dm
code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/projectiles/guns/ballistic/pistol.dm
code/modules/projectiles/guns/ballistic/revolver.dm
code/modules/projectiles/guns/energy/laser_crank.dm
code/modules/projectiles/guns/magic/staff.dm
code/modules/projectiles/guns/magic/wand.dm

Started out just adding stuff to the train but ended up being one part balance patch, one part bug fixing, and one part typo fixing.
:cl:
- Adds just so much shit to the train. Honestly I don't have it in me to list it all, so just check files changed
- Fixes a few typos and formatting issues
- Fixes some masterloot issues
- Fixes(?) the magic missile staff and adds it, tentatively, to the shop. I'll add it back to the loot lists if it isn't too OP and doesn't have the infinite ammo bug again
- Some adjustments to magic weapon stats, but honestly looking at it we'll probably need to go in at some point and seriously overhaul them
:cl:

Mostly train touches (Good to go if it passes checks)

---

code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm

The town needs thiccer walls, too

Mutated deathclaw spawners no longer spawn like 40 of them

---

code/modules/cargo/packs/secballistics.dm

Fixes the saiga12k in the shop (good to go checks yada yada)

---

code/modules/client/preferences.dm

remove extra char setup buttons

---

code/modules/mob/living/carbon/human/species.dm

Fire does 25% damage if you're in crit

---

code/modules/supplykit/supplykit_items/supplykit_magic.dm

I accidently left it as carp, 4 AM coding.
:cl:
/:cl:

fixes the wrong path for rising bass in the supply kit.

---

code/__DEFINES/dcs/signals.dm
code/__DEFINES/preferences.dm
code/datums/components/reskin.dm
code/game/objects/items/devices/PDA/PDA.dm
code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm

You can now set your PDA's default skin and beep-boop message in the Underlying Appearances. Might want to do this, cus its set to random, lol.
Also makes it so DataPals always look like they're on your glove, even if its just in the ID slot.

PDA Personalization

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm
code/modules/fallout/turf/ground.dm
modular_coyote/code/modules/turf_changes/PlantGrass.dm

Pulls back the ruins, lowers mob spawn rate on roads.  And car spawn rate.  Also fixes nests not spawning on grass.
:cl:
/:cl:

New Boston Ruins Overhaul

---

code/game/objects/effects/spawners/masterlootdrop.dm

whoops accidentally'd 10x the loot value of the stun tribeam
:cl:
/:cl:

aghsdaghdsg fixes for the TG blaster fixes??? (good to go if it passes checks)

---

code/modules/client/preferences.dm
code/modules/keybindings/setup.dm

input toggle key set in different proc

---

code/modules/mob/living/simple_animal/hostile/bear.dm

wrong sprite but at least you can see them
:cl:
/:cl:

fixes invisible butter bears

---

code/modules/client/preferences.dm

move hair options to appearance tab

---

code/__DEFINES/traits.dm
code/datums/traits/neutral.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/carbon/human/species.dm

Co-authored-by: Superlagg <Superlagg@users.noreply.github.com>
:cl:
/:cl:

oral fixation

---

_maps/map_files/coyote_bayou/Dungeons.dmm
_maps/map_files/coyote_bayou/Newboston.dmm
_maps/map_files/generic/CentCom.dmm
code/game/objects/items/teleportation.dm
code/modules/mining/fulton.dm

no just kidding moves admin sex dungeons

extends linters 2.0

---

code/modules/cargo/packs/misc.dm
code/modules/cargo/packs/service.dm
code/modules/projectiles/guns/ballistic/automatic.dm
code/modules/projectiles/guns/ballistic/flintlock.dm
code/modules/projectiles/guns/energy/laser.dm
code/modules/projectiles/guns/energy/laser_crank.dm
code/modules/projectiles/guns/energy/special.dm

removes whetstone crafting bypass from cargo/
removes endless lootbox generating from cargo

fully standardizes the amount of mods from guns/

---

code/game/objects/effects/portals.dm

put pulled mobs into portals

---

code/game/objects/items/tools/crowbar.dm
code/game/objects/items/tools/screwdriver.dm
code/game/objects/items/tools/wrench.dm
code/modules/reagents/chemistry/reagents/medicine_reagents.dm

By improvements I mean nerfs and QOL improvements to compensate for them

Wrench Healing Improvements

---

code/modules/mob/living/simple_animal/hostile/f13/geckotribe.dm

We'll just uh.  Go with this now.
:cl:
/:cl:

Lowers chieftain health

---

code/__DEFINES/inventory.dm
code/game/objects/items/melee/weaponry.dm
code/game/objects/items/storage/bags.dm

snee snitle
- [SURE] This code did not runtime during testing.

quiver size now 50 - 100 respectfully

---

code/datums/components/storage/ui.dm
code/game/machinery/autolathe.dm
code/modules/projectiles/boxes_magazines/_box_magazine.dm

draws an ammo counter on top of ammo boxes & magazines that aren't on a turf

magazine ammo counter

---

COOLBOOK_books/chief_guide/Our History.txt
COOLBOOK_books/chief_guide/index.json
COOLBOOK_books/shaman_guide3/index.json
COOLBOOK_books/villager_guide/index.json
arfsuits.dm
code/datums/traits/neutral.dm
code/modules/clothing/suits/arfsuits.dm
code/modules/jobs/job_types/tribals.dm
code/modules/jobs/job_types/wasteland.dm

This is the first part in the tribe rename. I have left the books untouched as it does go into their history, pending the lore rewrite.
:cl:
/:cl:

Renames the Tribe into the Mountain River tribe

---

code/modules/supplykit/supplykit_items/supplykit_improvised.dm

Ghlorp hlrop rglorlp glorp!!1!!!
Longbow 
:cl:
/:cl:

Longow fixed

---

code/controllers/subsystem/flirt/flirts.dm

Fixing the heaving

---

code/datums/components/storage/concrete/bags.dm

You know, because they're fucking salvage?  Amazing.
:cl:
/:cl:

Stockparts into salvage bags

---

code/game/objects/hand_items.dm

To match better with the new melee weapon damage amounts.
Also so you can't accidently murder a fucker by wielding and unwielding your beans lmao
:cl:
/:cl:

Biter, Clawer, Tailer, & Bean Update

---

code/modules/fallout/reagents/teas.dm

so that they default to just 'tea'
:cl:
/:cl:

Corrects some of the teas icons

---

tgui/packages/tgui/interfaces/PersonalCrafting.js

disable crafting buttons when busy

---

code/controllers/subsystem/monster_wave.dm
code/modules/WVM/wvm.dm

name clarifications

---

_maps/map_files/coyote_bayou/Newboston.dmm

Adds the lobby vending machine back to the clinic

---

code/modules/mob/living/emote.dm

Also you can now choose if you want a message when you sparkle by inputting a message
:cl:
/:cl:

Adds magic sparks and makes sparks better

---

code/datums/traits/good.dm

makes them both read the same way
:cl:
/:cl:

Clarifies rad resist quirks

---

code/modules/mob/living/simple_animal/hostile/f13/deathclaw.dm

Fixes aethergiest sprites

---

code/game/objects/items/handcuffs.dm
code/modules/jobs/job_types/oasis.dm

Adds a missing PDA to farmers loadout
Shrinks Bolas to fit into combat belts.
:cl:
/:cl:

Gives Farmers a PDA and Shrinks Bolas to small.

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm

Adds some torches to a tunnel
:cl:
/:cl:

Adds some torches to a tunnel

---

code/controllers/subsystem/monster_wave.dm

Respawn blockers are tiny items

---

code/modules/fallout/turf/ground.dm

Lowers Medicinal plants by half.
:cl:
/:cl:

Lowers the weights of medicinal plants

---

code/modules/client/preferences.dm

extra column in char info

---

code/game/objects/items/devices/multitool.dm
code/game/objects/items/tools/crowbar.dm
code/game/objects/items/tools/screwdriver.dm
code/game/objects/items/tools/weldingtool.dm
code/game/objects/items/tools/wirecutters.dm
code/game/objects/items/tools/wrench.dm

Just like the sledgehammer owo

Makes tools able to parry

---

code/modules/fallout/obj/explosives.dm

Especially in the dark
:cl:
/:cl:

Should make mines glow and be more visible

---

code/game/mecha/mecha.dm

Should make them all a hair more survivable
:cl:
/:cl:

buffs mech rear armor multiplier

---

code/modules/fallout/turf/ground.dm

Makes the correct dirt appear everywhere

---

code/game/objects/items/fishingrod.dm

Fishing bad.  Return to hunter gatherer (Fishing Fixed, in theory)

---

tgui/packages/tgui/interfaces/CargoBountyConsole.js

Yeah, we uh.  Didn't.  Actually tell yall how to do that.
:cl:
/:cl:

Tooltip for banking

---

code/modules/WVM/wmv_buyer.dm

Fixes the scrapper saying wierd shit

---

code/__DEFINES/traits.dm
code/controllers/configuration/entries/game_options.dm
code/datums/traits/good.dm
code/datums/traits/neutral.dm
code/modules/mob/living/carbon/human/human_movement.dm
config/game_options.txt

removed quick step, made sprinting faster in return

---

_maps/map_files/coyote_bayou/Ashdown-Upper.dmm
_maps/map_files/coyote_bayou/Ashdown.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Redwater.dmm
code/modules/mob/living/simple_animal/hostile/f13/insects.dm

Makes Pillbug leaders a little smaller

---

code/modules/mob/mob.dm

This pull request refactors the `mob.dm` file to improve message handling. It includes changes to the `visible_message` and `audible_message` functions to handle self messages correctly. Additionally, it removes unnecessary code related to self messages in these functions.

Refactor mob.dm for improved message handling

---

_maps/map_files/coyote_bayou/Ashdown.dmm
_maps/map_files/coyote_bayou/Garland-City.dmm
_maps/map_files/coyote_bayou/Legacy Storage/Castle Nash.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm
_maps/map_files/coyote_bayou/Redwater.dmm

More map fixes from the wallening

---

code/game/objects/items/stacks/medical.dm

to stand around edging in your boy jorts for 10 minutes to lick the oofies out of your soul
:cl:
/:cl:

Buffs Triage healing so you don't have

---

code/__DEFINES/dcs/signals.dm
code/datums/traits/neutral.dm

clothing adjust renamed to "fix fit"

---

_maps/map_files/coyote_bayou/Newboston.dmm

More small map fixes

---

_maps/map_files/coyote_bayou/Dungeons.dmm

because its unreal high, and that matters now
:cl:
/:cl:

Lowers artifact amount in Bhood dungeon

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
code/modules/supplykit/supplykit_items/supplykit_medical.dm

More small fen shaped fixes

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

all around me are familiar faces
worn out places
worn out faceess
bright and early for all the daily races
going nowhere, going nowwhheeerree

Fixes some mapper heckery with walls.

---

_maps/map_files/generic/CentCom.dmm
code/game/turfs/closed.dm
code/modules/fallout/turf/walls.dm

i want to cry and comfort-eat cookies

mad world (wallening fixes)

---

_maps/map_files/coyote_bayou/Newboston.dmm

Removes the duplicate augment machine and vending machines from previous reclaimer PR, also swaps out tables for glass that I just forgot
:cl:
/:cl:

Small reclaimer forgor's 

---

code/datums/traits/neutral.dm

Its visible up to 3 tiles out, presumably. I didnt test it extensively after adding the range in
:cl:
/:cl:

Fix fit now plays a message to people around you

---

code/modules/jobs/job_types/jobs_we_use.dm
code/modules/jobs/job_types/wasteland.dm

Also cleans up preacher some
:cl:
/:cl:

Removes unneeded old loadout from town jobs

---

code/controllers/subsystem/economy.dm

This pull request fixes a bug in the quest loading process where an invalid save chunk was causing quests to fail to load. Additionally, it optimizes the folder marking/unmarking functionality by sending only one request instead of multiple requests for each file.

Fix issues with quest loading and active quests

---

code/controllers/subsystem/economy.dm
code/modules/mob/dead/new_player/new_player.dm
code/modules/mob/living/login.dm

The pull request fixes an issue where the game was not loading the questbook properly. The problem was resolved by adding a function to load the saved data for the questbook when a player spawns.

Fix questbook loading issue

---

code/__DEFINES/traits.dm
code/controllers/configuration/entries/game_options.dm
code/datums/traits/good.dm
code/datums/traits/neutral.dm
code/modules/mob/living/carbon/human/human_movement.dm
code/modules/projectiles/guns/mods/mods.dm
config/game_options.txt

see title
keeps all of the bonuses of my revert PR, but without the removal of quick step
quick step returns 
black paint is made to have no weaknesses

quick step return, black paint buffed

---

code/game/objects/items/melee/weaponry.dm

I WAS SUPPOSED TO DO THIS
increases parry windows by 1.5x
i was supposed to

increased parry window by 1.5x

---

code/modules/mob/mob.dm

get self_message outta here

---

code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
code/modules/mob/living/simple_animal/hostile/f13/raider.dm
code/modules/mob/living/simple_animal/simple_animal.dm
modular_sunset/code/mob/renegade.dm

immobilized ranged hostile mobs

---

code/_onclick/hud/_defines.dm

Slight Adjustments based off feedback

---

code/_onclick/hud/_defines.dm

More slight adjustments

---

code/game/objects/structures/guncase.dm

see title
increased max cap of gunlockers from 8 to 500

gunlocker 8 -> 500

---

code/game/objects/items/storage/toolbox.dm
code/modules/hydroponics/hydroponics.dm
modular_coyote/code/mailbird.dm

colfer PR (buffed delivery and gaia)

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Redwater.dmm
_maps/map_files/coyote_bayou/Texarkana_underground.dmm
code/game/objects/effects/landmarks.dm
code/modules/jobs/job_types/sewer_rats_jobs_we_use.dm
code/modules/jobs/jobs.dm
modular_coyote/code/modules/area_blurb.dm
strings/insult.json

and other bullshit from fenny
:cl:
/:cl:

Fucking oops - tunnel rats

---

_maps/map_files/coyote_bayou/Ashdown-Upper.dmm
code/game/objects/effects/landmarks.dm
code/modules/jobs/job_types/ashdown_jobs_we_use.dm
code/modules/jobs/job_types/outfits_we_use.dm
code/modules/jobs/jobs.dm

Ashdown Jobs

---

_maps/map_files/coyote_bayou/Ashdown-Upper.dmm
_maps/map_files/coyote_bayou/Ashdown.dmm
code/game/objects/items/holy_weapons.dm
code/game/objects/items/storage/book.dm
modular_citadel/code/modules/client/loadout/__donator.dm

ashdown nonsense

---

_maps/map_files/coyote_bayou/Ashdown-Upper.dmm
_maps/map_files/coyote_bayou/Ashdown.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
code/game/objects/effects/landmarks.dm

smoll chonges

---

code/modules/mob/living/carbon/human/species_types/lizardpeople.dm

Removes grain and dairy allergy from liznerds

---

code/modules/mob/living/simple_animal/hostile/hostile.dm

Okay, lets see what happens

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper-2.dmm
_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm

table fixes in the Den

---

code/datums/traits/negative.dm

You know what?  No. I'm good homie.

---

code/controllers/subsystem/nightcycle.dm
code/game/objects/items/devices/flashlight.dm
code/modules/fallout/turf/ground.dm

This makes the slowdown on water/rough terrain less.  Meaning players need Trekking less.
It also makes night time not quite as dark and buffs flashlights heavily, making night vision quirks less of a requirement.
God speed, you wonderful code.

Some damn near final touch ups

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm

grrr kitten get out of the corner

Made Everything in Den Clinic accessible

---

code/_onclick/hud/_defines.dm
code/_onclick/hud/human.dm

Reverts the UI change
Adjusts a few positions of the UI to look more uniform
:cl:
tweak: Reverted UI change
/:cl:

Reverts UI Change

---

code/datums/components/crafting/recipes/recipes_tribal.dm

See title. Now requires material sheets of titanium, rather than the metaphysical concept of titanium
:cl:
/:cl:

Fixes grav gloves recipe

---

code/modules/client/preferences.dm
code/modules/client/preferences_savefile.dm

makes tab easier to use

---

_maps/map_files/coyote_bayou/Newboston.dmm
_maps/map_files/coyote_bayou/Texarkana_underground.dmm
_maps/pahrump-everything.json

Reeling it back in due to no pop.
- New Boston Upper
- New Boston Streets
- Texarkana Sewers below
:cl:
/:cl:

Z level recompression

---

code/datums/traits/negative.dm

how dare you comment this out. Also reworded and made to make newbies fuck off with an EXPLICIT wording towards synths. New positive quirk systems should also make them not choose this
I refuse to test this, it has been done already, it does build fine tho
:cl:
/:cl:

Toxinlover boogaloo

---

_maps/map_files/coyote_bayou/Newboston.dmm
_maps/pahrump-everything.json

thinking emoji

---

_maps/pahrump-everything.json
code/modules/mapping/map_config.dm

Update map config

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm
_maps/map_files/coyote_bayou/Texarkana_underground.dmm

Slice this shit in half for now.

---

code/controllers/subsystem/autotransfer.dm

round time: 4.25 hours -> 4.25 weeks.
just be sure to restart it occasionally

Makes rounds last like 4 friggin weeks.

---

code/_onclick/hud/screen_objects/character_actions.dm
code/game/objects/grope_kiss.dm
code/game/objects/hand_items.dm
code/modules/admin/admin_verbs.dm
code/modules/fallout/obj/trash/electronics.dm
code/modules/mob/living/carbon/emote.dm
fortune13.dme
modular_coyote/code/hairbrush.dm

Now you can touch your friends ~anywhere~

Ports the grope kiss MERP

---

modular_coyote/code/mam_tails_coyote.dm

makes downward fox tail not disappear

---

code/datums/components/crafting/crafting.dm
tgui/packages/tgui/interfaces/PersonalCrafting.js

THANKS POPPER YOU LAGGY PIECE OF SHIT

Removes compact mode from crafting

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm

Adds the online jukebox (to the map)

---

_maps/map_files/coyote_bayou/Newboston.dmm

salt for the salt gods

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm
code/controllers/subsystem/npcpool.dm
code/modules/fallout/obj/structures/wasteplants.dm
code/world.dm

and seeds the tribal camp with 2 of each waste medical plant (for now)
:cl:
/:cl:

Re-opens the south side of the map

---

code/__DEFINES/traits.dm
code/datums/traits/good.dm
code/game/machinery/doors/door.dm
code/game/objects/effects/spawners/lootdrop.dm
code/game/objects/items/prize_loot.dm
code/game/objects/items/storage/firstaid.dm
code/modules/reagents/chemistry/reagents/medicine_reagents.dm
code/modules/reagents/chemistry/recipes/medicine.dm
code/modules/reagents/reagent_containers/pill.dm
code/modules/vending/medical.dm
modular_citadel/code/modules/reagents/chemistry/recipes/fermi.dm

does the mood removal proper (throwing shade at fenny)

---

code/modules/mob/living/life.dm

SOUP META
R   E   A   L
:cl:
/:cl:

Culls passive triage healing

---

code/datums/components/supplykit.dm

supplykits no longer give you extra points for waiting

---

code/controllers/subsystem/monster_wave.dm
code/modules/projectiles/projectile/special/rocket.dm

reenables spawn waves!

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

readds the katiamallplaza

---

code/datums/components/supplykit.dm

Reverts ARF-SS13/coyote-bayou#5381

Revert "supplykits no longer give you extra points for waiting"

---

code/datums/components/supplykit.dm

Doing something

---

code/__DEFINES/loadout.dm
code/controllers/subsystem/job.dm
code/modules/client/preferences.dm
modular_citadel/code/modules/client/loadout/_loadout.dm

Add support for custom color in loadout items
:cl:
/:cl:

ports the bar's color PR thing

---

_maps/map_files/coyote_bayou/Newboston.dmm

dice cups to the bar

---

code/modules/mob/living/life.dm

Use it or lose it.  Don't whorf food down to heal 30 minutes from now with.
:cl:
/:cl:

Adds a slight drain to the triage reservoir.

---

code/modules/mob/living/living_active_parry.dm

Decouples combat intent from parrying.

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm

Fixes upper new boston areas

---

code/controllers/subsystem/validball_spawner.dm

Turn this wacky thing off.
:cl:
/:cl:

Validball shutdown

---

AAADevTool/AAA_DEVELOPMENT_CONFIG.json
code/datums/looping_sounds/item_sounds.dm
code/modules/mob/living/living_active_block.dm

Also lowers hairbrush brushing volume.
We can add mouse look to it later.
:cl:
/:cl:

Uncouples Blocking from CI.

---

code/game/objects/hand_items.dm
code/modules/mob/living/life.dm

Yeah, it was too slow
:cl:
/:cl:

Increases triage drain

---

code/controllers/subsystem/itemspawners.dm
code/controllers/subsystem/nightcycle.dm
code/controllers/subsystem/ticker.dm
code/datums/explosion.dm
code/modules/mob/living/simple_animal/hostile/f13/centaur.dm
code/modules/mob/living/simple_animal/hostile/f13/chinese.dm
code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
code/modules/mob/living/simple_animal/hostile/f13/geckotribe.dm
code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
code/modules/mob/living/simple_animal/hostile/f13/insects.dm
code/modules/mob/living/simple_animal/hostile/f13/mirelurks.dm
code/modules/mob/living/simple_animal/hostile/f13/raider.dm
code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
code/modules/mob/living/simple_animal/hostile/f13/tunnelers.dm
code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
config/motd.txt

This is partially in preperation of culling fallout mobs as well.  Culling or redesigning anyway.
:cl:
/:cl:

Culling of chat spam.

---

code/controllers/subsystem/chat.dm
code/controllers/subsystem/who.dm
code/modules/mob/living/living.dm
code/modules/mob/living/skillcheck.dm
code/modules/mob/mob_movement.dm
modular_sand/code/datums/components/interaction_menu_granter.dm
modular_sand/code/modules/mob/living/living_movement.dm

and puts them in the roleplay tab
:cl:
/:cl:

Pulls roleplay focused actions from the IC tab

---

code/controllers/subsystem/statpanel.dm

Map, server time, and station time.
Round time needs to be adjusted to be real world time.
:cl:
/:cl:

Culls useless info from status tab.

---

code/modules/client/preferences.dm
code/modules/mob/living/skillcheck.dm

All of them work EXCEPT for Moxie, once that one is fixed it will be ready to merge.
Brawn 
Awareness
Toughness
Moxie
Smarts
Deftness
Fate
:cl:
/:cl:

Shifts Special to a unique system

---

_maps/map_files/coyote_bayou/Newboston.dmm
_maps/map_files/coyote_bayou/Texarkana_underground.dmm

Removes validball spawners

---

code/modules/mob/living/life.dm

it wasn't draining, should be now
:cl:
/:cl:

Triage tweaks

---

modular_sunset/code/mob/renegade.dm

So they can, in theory, still retreat if you get them low enough but they're basically on the cusp of death anyway.
:cl:
/:cl:

Massively lowers retreat health percent on mobs

---

code/controllers/subsystem/monster_wave.dm

Makes nests respawn in 3 hours

---

_maps/map_files/coyote_bayou/Newboston.dmm
code/modules/projectiles/guns/mods/mods.dm
modular_coyote/code/modules/znuguns/code/_defines.dm
modular_coyote/code/modules/znuguns/code/ammo/3006.dm
modular_coyote/eris/code/gun_firemode.dm

pretty princess snanch

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm
code/__DEFINES/random_mob_spawner.dm
code/_onclick/hud/ghost.dm
code/_onclick/hud/screen_objects/character_actions.dm
code/controllers/subsystem/chat.dm
code/controllers/subsystem/monster_wave.dm
code/game/objects/items/storage/survivalkit.dm
code/game/objects/structures/window.dm
code/game/turfs/closed.dm
code/modules/admin/admin_verbs.dm
code/modules/events/carp_migration.dm
code/modules/fallout/obj/structures/mob_spawners.dm
code/modules/fallout/obj/structures/simple_door.dm
code/modules/mob/dead/new_player/new_player.dm
code/modules/mob/dead/observer/observer.dm
code/modules/mob/living/living_defense.dm
code/modules/mob/living/silicon/robot/robot.dm
code/modules/mob/living/silicon/silicon.dm
code/modules/mob/living/simple_animal/hostile/f13/raider.dm
code/modules/mob/living/simple_animal/hostile/giant_spider.dm
code/modules/mob/living/simple_animal/hostile/hostile.dm
code/modules/modular_computers/file_system/programs/crewmanifest.dm
modular_splurt/code/datums/modules/client/verbs/character_directory.dm

- removed sojurn big spiders
- fully removed character directory for non admins 
- crew manifest removed (unneeded and technically lies like crazy with super long rounds)
- more randomization for walls and windows.  Radvines and cracks mostly.
- Some doors randomized open at round start
- Survival pouch matches removed, replaced with water bottle
- lobby screen simplified a bit
- lowered mob chat spam via attack phrases
- makes mobs decompose in about 3 minutes
:cl:
spellcheck: fixed a few …

Dan and fenny get up to no good

---

code/game/objects/items/cosmetics.dm

nailpolish is now tiny so you can store it in special places

---

code/__DEFINES/artifacts.dm
code/controllers/subsystem/artifacts.dm
code/datums/components/artifacts.dm
code/game/objects/effects/spawners/masterlootdrop.dm
code/game/objects/items/cards_ids.dm
modular_citadel/code/modules/client/loadout/__donator.dm

dan lickings

---

code/modules/mob/living/simple_animal/hostile/f13/raider.dm
code/modules/mob/living/simple_animal/hostile/f13/rattler.dm

Raiders no longer do interpretive dance for 30 minutes before hitting you one time, they now just walk up to you and hit you until you fall
:cl:
/:cl:

Makes melee raiders more deadly

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Can you believe fenny is making a mapping branch wowie

---

modular_coyote/code/modules/znuguns/code/guns/zloadout.dm

lkynx to lynx

---

modular_coyote/code/modules/znuguns/code/guns/tier1.dm

Fixes broomie to 9mm

---

code/_globalvars/lists/maintenance_loot.dm
modular_coyote/code/modules/znuguns/code/_defines.dm

attachment fix

---

code/_globalvars/lists/maintenance_loot.dm
code/game/objects/items/granters.dm
code/modules/WVM/wvm.dm
code/modules/cargo/exports/misc_export.dm
code/modules/cargo/packs/skillbooks.dm

removes traitbooks from being able to be gotten as well as blueprints

---

_maps/map_files/coyote_bayou/Dungeons.dmm

validball spawner purge

---

code/modules/supplykit/supplykit_items/supplykit_ammo.dm

Readds quiver to supply kit

---

code/datums/components/crafting/recipes/recipes_misc.dm
code/datums/weather/weather_types/acid_rain.dm
code/datums/weather/weather_types/ash_storm.dm
code/datums/weather/weather_types/radiation_storm.dm
code/datums/weather/weather_types/rain.dm
modular_coyote/code/creature_species.dm

The recipe result for cheap and regular ranged hivebots is no longer identical
:cl:
/:cl:

Craftable hivebot fix

---

code/modules/mob/living/simple_animal/hostile/f13/insects.dm

stops bloaties from running you over

---

code/modules/fallout/obj/structures/mob_spawners.dm

so they have some vague ranged capability
:cl:
/:cl:

Lets bloatflies spawn with pillbugs

---

code/controllers/subsystem/nightcycle.dm

Make outside a fair deal darker, but not like.  Ultradark

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

fixes  to the map, i know, impossible

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm
modular_roguetown/todo/trees/treestuff.dm

Domeification 2.9

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Fixes stairs up to mining in reclaimers

---

_maps/map_files/coyote_bayou/Newboston.dmm
code/controllers/subsystem/datumrentals.dm
code/modules/jobs/jobs.dm

shut up, super mutants

---

_maps/map_files/coyote_bayou/Newboston.dmm

Some street light changes

---

code/game/objects/effects/landmarks.dm
code/modules/jobs/job_types/jobs_we_use.dm
code/modules/jobs/job_types/oasis.dm
code/modules/jobs/jobs.dm

Reclaimer Guard to Praetorian

---

code/modules/research/designs/autolathe_desings/autolathe_designs_construction.dm

Fixes an infinite metal exploit

---

code/modules/admin/admin.dm
code/modules/mob/dead/observer/observer.dm
code/modules/research/designs/autolathe_desings/autolathe_designs_construction.dm

Grip them logs

---

code/modules/mob/living/carbon/human/examine.dm
code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
code/modules/mob/living/simple_animal/hostile/f13/raider.dm
code/modules/mob/living/simple_animal/hostile/nanotrasen.dm
code/modules/mob/living/simple_animal/hostile/retaliate/spaceman.dm
code/modules/mob/living/simple_animal/hostile/russian.dm
code/modules/mob/living/simple_animal/hostile/syndicate.dm
modular_sunset/code/mob/renegade.dm

Removes summon backup spam.

---

code/datums/components/pellet_cloud.dm
code/datums/martial/sleeping_carp.dm
code/game/objects/obj_defense.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/mob/living/emote.dm
code/modules/mob/living/living_defense.dm
code/modules/mob/living/simple_animal/hostile/f13/insects.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/projectile.dm

Murdering chat spam in droves.

---

code/game/objects/items/stacks/sheets/sheet_types.dm

Prefall alloy fix

---

code/modules/mob/living/simple_animal/bot/medbot.dm

Hate medibot chatter, needless shit

---

code/modules/supplykit/supplykit_items/supplykit_ammo.dm

Quiver stink

---

code/__DEFINES/weather.dm

Jacks up weather amount

---

code/game/objects/items/cigs_lighters.dm

Stops Cigarettes from burning out.

---

_maps/map_files/coyote_bayou/Newboston.dmm
code/datums/weather/weather_types/acid_rain.dm
code/datums/weather/weather_types/rain.dm

Chester and his stairs

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm
code/__HELPERS/names.dm
code/game/objects/structures/mirror.dm
modular_coyote/code/hairbrush.dm
modular_coyote/code/hairdye.dm

Biodome Alert System report, Botique, and Gym

---

_maps/map_files/coyote_bayou/Ashdown.dmm
_maps/map_files/coyote_bayou/Dungeons.dmm
code/datums/components/spawner.dm
code/game/machinery/wishgranter.dm
code/game/objects/items/shrapnel.dm
code/modules/events/spacevine.dm
code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
fortune13.dme

Fuckin ell

---

code/game/objects/items/cigs_lighters.dm

Since we really don't plan on keeping chemistry anyway
:cl:
/:cl:

Stops cigs from being dippable into chems

---

arfsuits.dm
code/__DEFINES/armor.dm
code/modules/fallout/obj/trash_stack.dm

Adjusting Bio hazard suits & Unrandomizing trashpiles

---

code/datums/traits/good.dm

bruh soup is a vegetable
:cl:
/:cl:

Makes Nuka Lover Not Ass

---

code/modules/mob/living/simple_animal/hostile/f13/Securitron.dm
code/modules/mob/living/simple_animal/hostile/f13/eyebot.dm
code/modules/mob/living/simple_animal/hostile/f13/fallout_NPC.dm
code/modules/mob/living/simple_animal/hostile/f13/ghoul.dm
code/modules/mob/living/simple_animal/hostile/f13/insects.dm
code/modules/mob/living/simple_animal/hostile/f13/mirelurks.dm
code/modules/mob/living/simple_animal/hostile/f13/raider.dm
code/modules/mob/living/simple_animal/hostile/f13/rattler.dm
code/modules/mob/living/simple_animal/hostile/f13/supermutant.dm
code/modules/mob/living/simple_animal/hostile/f13/tunnelers.dm
code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm
code/modules/mob/living/simple_animal/hostile/f13/wastebots.dm
code/modules/mob/living/simple_animal/hostile/f13/wolf.dm
code/modules/mob/living/simple_animal/hostile/megafauna/behemoth.dm
code/modules/mob/living/simple_animal/hostile/megafauna/blood_drunk_miner.dm
code/modules/mob/living/simple_animal/hostile/nanotrasen.dm
code/modules/mob/living/simple_animal/hostile/russian.dm

Yeah, I know I'm working after myself.  I aught to bite the fucker who did this.
:cl:
/:cl:

Reduces junk spam from combat

---

code/modules/ruins/lavalandruin_code/syndicate_base.dm
code/modules/vending/autodrobe.dm
code/modules/vending/bigredvendor.dm
code/modules/vending/boozeomat.dm
code/modules/vending/brahminvendordm.dm
code/modules/vending/cartridge.dm
code/modules/vending/cigarette.dm
code/modules/vending/clothesmate.dm
code/modules/vending/cola.dm
code/modules/vending/f13nukacola.dm
code/modules/vending/liberation.dm
code/modules/vending/liberation_toy.dm
code/modules/vending/magivend.dm
code/modules/vending/medical.dm
code/modules/vending/megaseed.dm
code/modules/vending/nutrimax.dm
code/modules/vending/snack.dm
code/modules/vending/sovietvend.dm
code/modules/vending/sustenance.dm
code/modules/vending/toys.dm

Silence, thot-vendors

---

modular_coyote/code/modules/znuguns/code/guns/zloadout.dm

So you know what you're buying.
:cl:
/:cl:

Gun names adjustment in loadout

---

_maps/map_files/coyote_bayou/Newboston.dmm

trail fluff

---

arfsuits.dm
code/game/objects/effects/spawners/masterlootdrop.dm
code/modules/clothing/head/f13factionhead.dm
code/modules/clothing/head/f13head.dm
code/modules/clothing/head/helmet.dm
code/modules/clothing/suits/arfsuits.dm
code/modules/clothing/suits/miscellaneous.dm
code/modules/supplykit/supplykit_items/supplykit_magic.dm
modular_citadel/code/modules/client/loadout/__donator.dm
modular_citadel/code/modules/client/loadout/head.dm
modular_citadel/code/modules/client/loadout/suit.dm
modular_sand/code/modules/client/loadout/head.dm

Loadout overhaul - Armor & Martial Arts

---

code/game/objects/items.dm

my name is shadow the hedgehog and I HATE lag

---

code/__DEFINES/mobs.dm
code/controllers/subsystem/second_wind.dm
code/modules/mob/living/blood.dm
code/modules/mob/living/carbon/carbon_defense.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/mob/living/living.dm
code/modules/reagents/reagent_containers/blood_pack.dm

but mainly only while youre in town.
see, the goal is to make getting critted make you go back to town. just gotta make it not suck the doc's dick when you get there.

Makes crit less ultra CBT

---

_maps/map_files/coyote_bayou/Newboston-Upper.dmm
_maps/map_files/coyote_bayou/Newboston.dmm

Upstairs Overhaul

---

_maps/map_files/coyote_bayou/Newboston.dmm

Adds piano to the bar by request

---

code/game/objects/items/stacks/sheets/leather.dm

TYPO OBLITERATION

---

code/modules/fallout/obj/food_and_drinks/food.dm
code/modules/fallout/obj/structures/mob_spawners.dm
code/modules/food_and_drinks/recipes/tablecraft/recipes_wastefood.dm
code/modules/mob/living/simple_animal/hostile/f13/wasteanimals.dm

Hellhounds instead of nightstalkers

---

code/modules/fallout/turf/walls.dm

matrix tile info

---

code/modules/fallout/turf/walls.dm

Dumbass moment.

---

code/controllers/subsystem/monster_wave.dm

turns off nests getting harder?
:cl:
/:cl:

Nutate deez

---

_maps/map_files/coyote_bayou/Newboston.dmm
_maps/templates/splurt_templates/hilbertshotel_templates/apartment_4.dmm
code/__DEFINES/mobs.dm
code/_onclick/item_attack.dm
code/modules/projectiles/ammunition/_firing.dm
code/modules/projectiles/projectile.dm

Feralboykissingvorebots

---

code/modules/mob/living/carbon/human/examine.dm

Quick examine bug fix

---

_maps/map_files/coyote_bayou/Newboston.dmm

Modifies house on tribe road

---

code/controllers/subsystem/nightcycle.dm
code/game/turfs/closed.dm

Makes all light levels higher outside & Massively lowers vine chance

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana-Upper.dmm
_maps/map_files/coyote_bayou/Texarkana_underground.dmm
code/controllers/subsystem/recoil.dm

Shopkeep door fix

---

code/modules/WVM/wvm.dm

Removes unworking damage buff mods

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm
modular_coyote/code/modules/znuguns/code/ammo/9mm.dm

Just some small mapping updates

---

code/modules/fallout/obj/structures/mob_spawners.dm

Removes every nests custom spawn timer

---

_maps/map_files/coyote_bayou/Texarkana_underground.dmm

Removes dirt, gives science a more clean and unified look (also fixes the missing middle, seen on the rightmost pens)
**This doesnt touch top-z dust, only bottom, if ya want that you gotta bug me for it**
:cl:
add: added grinder to botany, other logical changes
del: All dust (on lower Z)
/:cl:

skoiyence change and no more dirt enfuckening

---

_maps/map_files/coyote_bayou/Nash_and_Texarkana.dmm

Matrix tiles near secondary spawn

---

code/game/objects/hand_items.dm
code/modules/jobs/job_types/jobs_we_use.dm
code/modules/mob/living/carbon/emote.dm

Job stuff and generic tail

---

code/game/objects/effects/spawners/masterlootdrop.dm
code/modules/fallout/obj/trash_stack.dm

trash pile name and descriptions changed to be less unappealing. search time changed to one second. toasters added to drops for common piles
:cl:
/:cl:

trash pile adjustments

---

code/modules/client/preferences.dm

admins can export characters into images

---

code/controllers/subsystem/lootmanager.dm
code/modules/fallout/obj/trash_stack.dm
code/modules/mob/login.dm
fortune13.dme

The pile's icon is removed from clients after they search through it. Also, when the pile inits it checks the location for other piles, and if it finds any it deletes itself and calls a `CRASH` for tracing.
:cl:
/:cl:

more trash pile updates

---

.github/workflows/autobuild_tgui.yml
.github/workflows/ci_suite.yml
.github/workflows/compile_changelogs.yml
.github/workflows/conflicts.yml
.github/workflows/docker_publish.yml
.github/workflows/pr_emoji.yml
.github/workflows/show_screenshot_test_results.yml
.github/workflows/stale.yml
.github/workflows/update_tgs_dmapi.yml
dependencies.sh
tools/ci/check_changelogs.sh
tools/requirements.txt

`<Insert screaming here>`
Updates all the GitHub Actions to their latest supported versions
Updates the runner to Ubuntu 22.04 due to 20.04 EoL in April
Updates RUST_G to 2.0.2 because of outdated dependencies no longer present in Ubuntu 22.04
Updates Python to 3.9
Updates Python dependencies to versions compatible with Ubuntu 22.04
Adds missing software packages required for running on Ubuntu 22.04
This is ready to merge
:cl:
refactor: …

Update workflows take 3

---

code/modules/WVM/wvm.dm

Fixes Vendors
